import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { Image } from 'expo-image';
import * as ImagePicker from 'expo-image-picker';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { AppText } from '@/components/warsha/Typography';
import { colors, radii, spacing, typography } from '@/constants/theme';
import { useLocalization } from '@/src/i18n/localization';
import { useReviews } from '@/src/reviews/review-context';
import type { BookingReview, ReviewAttachment } from '@/src/reviews/review-types';
import { realtimeService } from '@/src/realtime/realtime-service';

const MAX_IMAGES=4;const MAX_BYTES=5*1024*1024;const MIME=new Set(['image/jpeg','image/png','image/webp']);
export function BookingReviewCard({bookingId,providerId,completed}:{bookingId:string;providerId:string;completed:boolean}){
  const{language,isRTL}=useLocalization();const reviews=useReviews();const{getBookingReview,revision}=reviews;const[review,setReview]=useState<BookingReview>();const[open,setOpen]=useState(false);const[rating,setRating]=useState(0);const[comment,setComment]=useState('');const[attachments,setAttachments]=useState<ReviewAttachment[]>([]);const[error,setError]=useState('');const[loading,setLoading]=useState(true);const request=useRef(0);const scope=useRef(revision);scope.current=revision;const ar=language==='ar';
  const load=useCallback(()=>{const current=++request.current;const targetRevision=revision;setLoading(true);setReview(undefined);void getBookingReview(bookingId).then(item=>{if(request.current===current&&scope.current===targetRevision){setReview(item);setError('')}}).catch(()=>{if(request.current===current&&scope.current===targetRevision)setError(ar?'تعذر تحميل التقييم.':'Could not load review.')}).finally(()=>{if(request.current===current&&scope.current===targetRevision)setLoading(false)})},[ar,bookingId,getBookingReview,revision]);
  useEffect(()=>{load();return()=>{request.current+=1}},[load]);
  useEffect(()=>{let first=true;const reconcile=()=>load();const connection=(status:'connected'|'reconnecting'|'error')=>{if(status==='connected'){if(first)first=false;else reconcile()}};return review?.id?realtimeService.reviewDetail(review.id,reconcile,connection):realtimeService.bookingReview(bookingId,reconcile,connection)},[bookingId,load,review?.id]);
  if(!completed)return null;
  const pick=async()=>{setError('');const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsMultipleSelection:true,selectionLimit:MAX_IMAGES-attachments.length,quality:.85});if(result.canceled)return;const next:ReviewAttachment[]=[];for(const asset of result.assets){if(!asset.mimeType||!MIME.has(asset.mimeType)||!asset.fileSize||asset.fileSize>MAX_BYTES){setError(ar?'الصورة لازم تكون JPG أو PNG أو WebP وأقل من ٥ ميجابايت.':'Images must be JPG, PNG, or WebP and under 5 MB.');continue}next.push({id:asset.assetId?.replace(/[^A-Za-z0-9_-]/g,'')||`${Date.now()}-${next.length}`,url:asset.uri,mimeType:asset.mimeType,size:asset.fileSize})}setAttachments(current=>[...current,...next].slice(0,MAX_IMAGES))};
  const submit=async()=>{if(!rating){setError(ar?'اختار تقييم من ١ إلى ٥ نجوم.':'Choose a rating from 1 to 5 stars.');return}setError('');try{await reviews.submit({bookingId,providerId,rating,comment,attachments});setOpen(false);load()}catch(reason){setError(reason instanceof Error?reason.message:(ar?'تعذر إرسال التقييم.':'Could not submit your review.'))}};
  return <View style={styles.card}><AppText style={styles.title}>{ar?'تقييم الخدمة':'Rate this service'}</AppText>{loading?<ActivityIndicator color={colors.white}/>:review?<View style={styles.form}><View style={styles.done}><MaterialIcons name="verified" size={18} color={colors.success}/><AppText>{ar?'تم إرسال تقييمك':'Your review was submitted'}</AppText></View>{review.comment?<AppText>{review.comment}</AppText>:null}<ScrollView horizontal contentContainerStyle={styles.images}>{review.attachments.map(item=>item.url?<Image key={item.id} source={{uri:item.url}} style={styles.image}/>:<AppText key={item.id}>{ar?'الصورة غير متاحة':'Image unavailable'}</AppText>)}</ScrollView></View>:!open?<Pressable accessibilityRole="button" onPress={()=>setOpen(true)} style={styles.button}><AppText style={styles.buttonText}>{ar?'قيّم الخدمة':'Rate this service'}</AppText></Pressable>:<View style={styles.form}><AppText>{ar?'التقييم مطلوب':'Rating required'}</AppText><View style={[styles.stars,isRTL&&styles.rtl]}>{[1,2,3,4,5].map(value=><Pressable key={value} accessibilityRole="button" accessibilityLabel={ar?`${value} نجوم`:`${value} stars`} onPress={()=>setRating(value)} style={styles.star}><MaterialIcons name={value<=rating?'star':'star-border'} size={32} color={colors.white}/></Pressable>)}</View><TextInput value={comment} onChangeText={setComment} maxLength={2000} multiline placeholder={ar?'اكتب رأيك (اختياري)':'Write a review (optional)'} placeholderTextColor={colors.textMuted} style={[styles.input,{textAlign:isRTL?'right':'left'}]}/><Pressable disabled={attachments.length>=MAX_IMAGES||reviews.busy} onPress={()=>void pick()} style={styles.outline}><AppText>{ar?'إضافة صور':'Add photos'} ({attachments.length}/{MAX_IMAGES})</AppText></Pressable><View style={styles.images}>{attachments.map(item=><View key={item.id}><Image source={{uri:item.url}} style={styles.image}/><Pressable accessibilityLabel={ar?'حذف الصورة':'Remove photo'} onPress={()=>setAttachments(current=>current.filter(value=>value.id!==item.id))} style={styles.remove}><MaterialIcons name="close" size={18} color={colors.background}/></Pressable></View>)}</View><AppText style={styles.count}>{comment.length}/2000</AppText>{error?<AppText style={styles.error}>{error}</AppText>:null}<Pressable disabled={reviews.busy} onPress={()=>void submit()} style={[styles.button,reviews.busy&&styles.disabled]}>{reviews.busy?<ActivityIndicator color={colors.background}/>:<AppText style={styles.buttonText}>{ar?'إرسال التقييم':'Submit review'}</AppText>}</Pressable></View>}</View>
}
const styles=StyleSheet.create({card:{gap:spacing.md,padding:spacing.lg,borderWidth:1,borderColor:colors.borderSoft,borderRadius:radii.lg,backgroundColor:colors.surface},title:{fontSize:18,fontWeight:typography.semibold},form:{gap:spacing.sm},stars:{flexDirection:'row',gap:6},rtl:{flexDirection:'row-reverse'},star:{minWidth:44,minHeight:44,alignItems:'center',justifyContent:'center'},input:{minHeight:100,borderWidth:1,borderColor:colors.border,borderRadius:radii.md,color:colors.white,padding:spacing.md,textAlignVertical:'top'},count:{fontSize:11,color:colors.textMuted,alignSelf:'flex-end'},button:{minHeight:48,borderRadius:radii.md,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},outline:{minHeight:44,borderWidth:1,borderColor:colors.border,borderRadius:radii.md,alignItems:'center',justifyContent:'center'},buttonText:{color:colors.background,fontWeight:typography.bold},done:{flexDirection:'row',gap:spacing.sm,alignItems:'center'},error:{color:colors.error,fontSize:12},disabled:{opacity:.5},images:{flexDirection:'row',gap:spacing.sm,flexWrap:'wrap'},image:{width:88,height:88,borderRadius:radii.md},remove:{position:'absolute',right:-4,top:-4,width:28,height:28,borderRadius:14,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'}});
