import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { router } from 'expo-router';
import { Pressable,StyleSheet,View } from 'react-native';
import { colors,radii,spacing,typography } from '@/constants/theme';
import { useLocalization } from '@/src/i18n/localization';
import { useNotifications } from '@/src/notifications/notification-context';
import { useEngagementText } from '@/src/notifications/notification-engagement-translations';
import { AppText } from './Typography';
import { BrandLockup } from './BrandMark';
export function Header(){const{t,toggleLanguage,isRTL}=useLocalization();const nt=useEngagementText();const{unreadCount,chatUnreadCount}=useNotifications();return <View style={[styles.row,isRTL&&styles.reverse]}><BrandLockup size={38}/><View style={[styles.actions,isRTL&&styles.reverse]}><Pressable accessibilityRole="button" accessibilityLabel={t('language')} onPress={toggleLanguage} style={styles.control}><AppText style={styles.language}>{t('language')}</AppText></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`${t('chat')}${chatUnreadCount?`. ${chatUnreadCount} ${nt.text('unread')}`:''}`} onPress={()=>router.push('/chat')} style={styles.control}><MaterialIcons name="chat-bubble-outline" size={21} color={colors.textPrimary}/>{chatUnreadCount?<Count value={chatUnreadCount} isRTL={isRTL}/>:null}</Pressable><Pressable accessibilityRole="button" accessibilityLabel={nt.text('notificationBell')} onPress={()=>router.push('/notifications')} style={styles.control}><MaterialIcons name="notifications-none" size={22} color={colors.textPrimary}/>{unreadCount?<Count value={unreadCount} isRTL={isRTL}/>:null}</Pressable></View></View>}
function Count({value,isRTL}:{value:number;isRTL:boolean}){return <View accessibilityLabel={`${value}`} style={[styles.badge,isRTL?styles.badgeLeft:styles.badgeRight]}><AppText style={styles.badgeText}>{value>99?'99+':value}</AppText></View>}
const styles=StyleSheet.create({row:{minHeight:58,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},reverse:{flexDirection:'row-reverse'},actions:{flexDirection:'row',gap:spacing.sm},control:{height:44,minWidth:44,paddingHorizontal:10,borderRadius:radii.md,borderWidth:1,borderColor:colors.borderSoft,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},language:{fontWeight:typography.semibold,fontSize:12},badge:{position:'absolute',top:-5,minWidth:19,height:19,paddingHorizontal:4,borderRadius:10,backgroundColor:colors.white,alignItems:'center',justifyContent:'center',borderWidth:2,borderColor:colors.background},badgeRight:{right:-5},badgeLeft:{left:-5},badgeText:{fontSize:9,lineHeight:11,color:colors.background,fontWeight:typography.bold}});
