import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { colors, radii, spacing, typography } from '@/constants/theme';
import { defaultProviderFilters, type ProviderFilters as Filters, type ProviderSort } from '@/src/data/marketplace-types';
import { AppText } from './Typography';

const ratings=[0,4,4.5]; const prices=[[0,2000],[0,250],[250,500],[500,2000]]; const distances=[50,2,5,10];
export function ProviderFilters({filters,onChange,sort,onSort}:{filters:Filters;onChange:(value:Filters)=>void;sort:ProviderSort;onSort:(value:ProviderSort)=>void}){return <View style={styles.panel}><Row title="Sort by">{(['recommended','nearest','topRated','lowestPrice'] as ProviderSort[]).map((value)=><Chip key={value} label={{recommended:'Recommended',nearest:'Nearest',topRated:'Highest rated',lowestPrice:'Lowest price'}[value]} selected={sort===value} onPress={()=>onSort(value)}/>)}</Row><Row title="Minimum rating">{ratings.map((value)=><Chip key={value} label={value?`${value}+ ★`:'Any'} selected={filters.minimumRating===value} onPress={()=>onChange({...filters,minimumRating:value})}/>)}</Row><Row title="Price range">{prices.map(([minimumPrice,maximumPrice])=><Chip key={`${minimumPrice}-${maximumPrice}`} label={maximumPrice===2000&&minimumPrice===0?'Any':maximumPrice===2000?`${minimumPrice}+ EGP`:`${minimumPrice}–${maximumPrice} EGP`} selected={filters.minimumPrice===minimumPrice&&filters.maximumPrice===maximumPrice} onPress={()=>onChange({...filters,minimumPrice,maximumPrice})}/>)}</Row><Row title="Maximum distance">{distances.map((value)=><Chip key={value} label={value===50?'Any':`${value} km`} selected={filters.maximumDistance===value} onPress={()=>onChange({...filters,maximumDistance:value})}/>)}</Row><View style={styles.toggles}><Chip label="Available now" selected={filters.availableNow} onPress={()=>onChange({...filters,availableNow:!filters.availableNow})}/><Chip label="Verified only" selected={filters.verifiedOnly} onPress={()=>onChange({...filters,verifiedOnly:!filters.verifiedOnly})}/><Pressable onPress={()=>onChange(defaultProviderFilters)}><AppText style={styles.clear}>Clear filters</AppText></Pressable></View></View>}
function Row({title,children}:{title:string;children:React.ReactNode}){return <View style={styles.row}><AppText style={styles.title}>{title}</AppText><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{children}</ScrollView></View>}
function Chip({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.chip,selected&&styles.selected]}><AppText style={[styles.chipText,selected&&styles.selectedText]}>{label}</AppText></Pressable>}
export function applyProviderFilters<T extends {rating:number;price:number;distance:number;available:boolean;verified:boolean}>(items:T[],filters:Filters,sort:ProviderSort){return items.filter((item)=>item.rating>=filters.minimumRating&&item.price>=filters.minimumPrice&&item.price<=filters.maximumPrice&&item.distance<=filters.maximumDistance&&(!filters.availableNow||item.available)&&(!filters.verifiedOnly||item.verified)).sort((a,b)=>sort==='nearest'?a.distance-b.distance:sort==='topRated'?b.rating-a.rating:sort==='lowestPrice'?a.price-b.price:b.rating*10-a.rating*10+Number(b.verified)-Number(a.verified))}
const styles=StyleSheet.create({panel:{gap:spacing.md,padding:spacing.md,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,backgroundColor:colors.surface},row:{gap:spacing.sm},title:{fontSize:12,color:colors.textSecondary,fontWeight:typography.medium},chips:{gap:spacing.sm},chip:{minHeight:34,paddingHorizontal:12,borderRadius:radii.pill,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},selected:{backgroundColor:colors.white,borderColor:colors.white},chipText:{fontSize:11,color:colors.textSecondary},selectedText:{color:colors.background,fontWeight:typography.semibold},toggles:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:spacing.sm},clear:{fontSize:12,textDecorationLine:'underline',color:colors.textSecondary,padding:spacing.sm}});
