import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';

import { bookingStatusTranslationKeys, type Booking, type BookingStatus } from '@/src/bookings/booking-types';
import { useProviderJobs } from '@/src/provider-jobs/provider-job-context';
import { useMarketplaceData } from '@/src/data/marketplace-context';
import { useLocalization } from '@/src/i18n/localization';
import { useProviderJobText, type ProviderJobCopyKey } from '@/src/i18n/provider-job-translations';
import { formatBookingDateTime, formatNumber, localeFor } from '@/src/utils/date-format';
import { radii, spacing, typography, type ThemeColors } from '@/constants/theme';
import { useThemeColors, useThemedStyles } from '@/src/appearance/appearance-context';
import { AppText } from './Typography';
import { BrandLoadingMark as ActivityIndicator } from './BrandMark';
import { cataloguedServiceReferenceLabel } from '@/src/services/specific-services';

type JobSection='new'|'active'|'done';
const sections:{id:JobSection;label:ProviderJobCopyKey;statuses:BookingStatus[]}[]=[{id:'new',label:'newRequests',statuses:['pending_provider_approval']},{id:'active',label:'inProgressJobs',statuses:['accepted','rescheduling_requested','confirmed','provider_on_the_way','provider_arrived','job_started','work_in_progress','disputed']},{id:'done',label:'completedJobs',statuses:['completed','rejected','cancelled','refunded','no_show']}];
export function ProviderJobsContent(){
  const colors = useThemeColors();
  const styles = useThemedStyles(makeStyles);const jobsState=useProviderJobs();const{isRTL}=useLocalization();const jt=useProviderJobText();const[section,setSection]=useState<JobSection>('new');const selected=sections.find(item=>item.id===section)!;const jobs=useMemo(()=>jobsState.jobs.filter(job=>selected.statuses.includes(job.status)).sort((a,b)=>section==='new'?Date.parse(a.createdAt)-Date.parse(b.createdAt):`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)),[jobsState.jobs,section,selected.statuses]);if(jobsState.loading)return <View style={styles.state}><ActivityIndicator color={colors.white}/></View>;if(jobsState.error)return <View style={styles.state}><MaterialIcons name="error-outline" size={36} color={colors.textMuted}/><AppText style={styles.muted}>{jt('jobsLoadError')}</AppText><Pressable onPress={()=>void jobsState.reload()} style={styles.retry}><AppText>{jt('retry')}</AppText></Pressable></View>;return <View style={styles.wrapper}><View style={[styles.tabs,isRTL&&styles.reverse]}>{sections.map(item=><Pressable accessibilityRole="tab" accessibilityState={{selected:section===item.id}} key={item.id} onPress={()=>setSection(item.id)} style={[styles.tab,section===item.id&&styles.activeTab]}><AppText style={[styles.tabText,section===item.id&&styles.activeText]} numberOfLines={1}>{jt(item.label)}</AppText></Pressable>)}</View>{jobs.length?jobs.map(job=><JobCard key={job.id} job={job}/>):<View style={styles.state}><MaterialIcons name="work-outline" size={38} color={colors.textMuted}/><AppText style={styles.muted}>{jt('noJobs')}</AppText></View>}</View>;
function JobCard({job}:{job:Booking}){
  const styles = useThemedStyles(makeStyles);const{t,isRTL,language}=useLocalization();const{services}=useMarketplaceData();const jt=useProviderJobText();const serviceLabel=cataloguedServiceReferenceLabel(job,services,language);const elapsed=Math.max(0,Date.now()-Date.parse(job.createdAt));const relative=new Intl.RelativeTimeFormat(localeFor(language),{numeric:'auto'}).format(-Math.max(1,Math.round(elapsed/3600000)),'hour');return <Pressable accessibilityRole="button" accessibilityLabel={`${job.customerName}, ${serviceLabel}`} onPress={()=>router.push({pathname:'/worker/jobs/[id]',params:{id:job.id}})} style={styles.card}><View style={[styles.row,isRTL&&styles.reverse]}><View style={styles.grow}><AppText style={styles.name}>{job.customerName}</AppText><AppText style={styles.service}>{serviceLabel}</AppText></View><View style={styles.badge}><AppText style={styles.badgeText}>{t(bookingStatusTranslationKeys[job.status])}</AppText></View></View><AppText style={styles.detail}>{formatBookingDateTime(job.date,job.time,localeFor(language))}</AppText><AppText numberOfLines={2} style={styles.detail}>{typeof job.address==='string'?job.address:job.address.district}</AppText><View style={[styles.row,isRTL&&styles.reverse]}><AppText style={styles.detail}>{job.bookingType==='emergency'?jt('emergencyBooking'):jt('scheduledBooking')}</AppText><AppText style={styles.price}>{formatNumber(job.price,language)} {t('currency')}</AppText></View>{job.status==='pending_provider_approval'?<AppText style={styles.age}>{jt('requested')}: {relative}</AppText>:null}</Pressable>}
}
const makeStyles = (colors: ThemeColors) => StyleSheet.create({wrapper:{gap:spacing.md},tabs:{flexDirection:'row',gap:spacing.sm},reverse:{flexDirection:'row-reverse'},tab:{flex:1,minHeight:52,paddingHorizontal:spacing.md,borderRadius:radii.lg,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},activeTab:{backgroundColor:colors.white,borderColor:colors.white},tabText:{fontSize:13,color:colors.textSecondary},activeText:{color:colors.background,fontWeight:typography.bold},card:{padding:spacing.lg,gap:spacing.sm,borderRadius:radii.xl,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.md},grow:{flex:1},name:{fontSize:17,fontWeight:typography.bold},service:{fontSize:14,fontWeight:typography.semibold},detail:{color:colors.textSecondary,fontSize:13,lineHeight:19},price:{fontWeight:typography.bold},badge:{maxWidth:'48%',paddingHorizontal:spacing.sm,paddingVertical:5,borderRadius:radii.pill,backgroundColor:colors.surfaceElevated},badgeText:{fontSize:10,textAlign:'center'},age:{fontSize:12,color:colors.textMuted},state:{minHeight:240,alignItems:'center',justifyContent:'center',gap:spacing.md},muted:{color:colors.textMuted,textAlign:'center'},retry:{minHeight:48,paddingHorizontal:spacing.lg,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,justifyContent:'center'}});
