import { router,useLocalSearchParams } from 'expo-router';
import { Pressable,StyleSheet,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppText } from '@/components/warsha/Typography'; import { WarshaLogo } from '@/components/warsha/WarshaLogo';
import { colors,radii,spacing,typography } from '@/constants/theme';
import { useBookings } from '@/src/bookings/booking-context';
import { useLocalization } from '@/src/i18n/localization';
export default function BookingSuccess(){const{id}=useLocalSearchParams<{id:string}>();const{getBooking}=useBookings();const{t}=useLocalization();const booking=getBooking(id);return <SafeAreaView style={s.safe}><View style={s.content}><View style={s.icon}><WarshaLogo size={46} variant="dark"/></View><AppText style={s.title}>{t('bookingSubmitted')}</AppText><AppText style={s.body}>{t('bookingSubmittedBody')}</AppText><AppText style={s.id}>{booking?.id??id}</AppText><Pressable accessibilityLabel={t('viewBookingDetails')} onPress={()=>router.replace({pathname:'/booking/[id]',params:{id}})} style={s.primary}><AppText style={s.primaryText}>{t('viewBookingDetails')}</AppText></Pressable><Pressable accessibilityLabel={t('goToOrders')} onPress={()=>router.replace('/(tabs)/orders')} style={s.secondary}><AppText style={s.secondaryText}>{t('goToOrders')}</AppText></Pressable></View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{flex:1,alignItems:'center',justifyContent:'center',padding:spacing.xl,gap:spacing.lg,maxWidth:520,width:'100%',alignSelf:'center'},icon:{width:72,height:72,borderRadius:24,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},title:{fontSize:27,fontWeight:typography.bold},body:{fontSize:14,lineHeight:21,color:colors.textSecondary,textAlign:'center'},id:{fontSize:13,color:colors.textMuted,writingDirection:'ltr'},primary:{height:54,width:'100%',borderRadius:radii.lg,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},primaryText:{color:colors.background,fontWeight:typography.bold},secondary:{height:50,width:'100%',borderRadius:radii.lg,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},secondaryText:{fontWeight:typography.semibold}});

