import type { Locale } from './preferences.ts';

/**
 * Every word the authenticated application says, in both languages.
 *
 * Same rule as the public site: no component holds a bare string, because the
 * failure nobody reports and everybody sees is one English word left in the
 * middle of an Arabic page.
 */
export const appCopy = {
  en: {
    home: 'Warsha home',
    navPrimary: 'Primary',
    signOut: 'Sign out',

    signInTitle: 'Sign in to Warsha',
    signInLead: 'Use the email address or the phone number you registered with. Warsha works out the rest.',
    identityLabel: 'Email or phone number',
    passwordLabel: 'Password',
    signInAction: 'Sign in',
    signingIn: 'Signing in…',
    noAccount: 'Do not have an account yet?',
    createOne: 'Create one on warsha',

    errInvalidIdentifier: 'Enter the email address or phone number you registered with.',
    errInvalidCredentials: 'Those details did not match an account. Check them and try again.',
    errRateLimited: 'Too many attempts. Wait a little, then try again.',
    errOutdatedClient: 'Reload the page to get the latest version, then sign in.',
    errNetwork: 'Warsha could not be reached. Check your connection and try again.',
    errServer: 'Something went wrong on our side. Please try again shortly.',

    chooseModeTitle: 'How do you want to use Warsha today?',
    chooseModeLead: 'Your account can do both. Pick one — you can switch whenever you like.',
    chooseCustomer: 'Book work',
    chooseCustomerBody: 'Describe a job, receive quotes, and track it to completion.',
    chooseWorker: 'Do work',
    chooseWorkerBody: 'See requests that match your trades and quote the ones you want.',

    modeCustomer: 'Customer',
    modeWorker: 'Worker',

    navHome: 'Home',
    navJobs: 'My jobs',
    navNotifications: 'Notifications',
    navSupport: 'Support',
    navAccount: 'Account',
    navRequests: 'Requests',
    navEarnings: 'Earnings',
    navVerification: 'Verification',
    navProfile: 'Profile',

    dashboardGreeting: 'Your Warsha',
    activeJobs: 'Active jobs',
    noActiveJobs: 'Nothing in progress right now.',
    notifications: 'Notifications',
    noNotifications: 'Nothing new.',
    unreadCount: 'unread',
    supportCases: 'Support',
    noSupportCases: 'No open support cases.',
    legalCentre: 'Legal',
    privacyCentre: 'Privacy',
    viewAll: 'View all',
    loading: 'Loading…',
    loadFailed: 'That could not be loaded. Try again.',
    retry: 'Try again',

    workerNextStep: 'What to do next',
    workerVerificationPending: 'Your application is with a reviewer. You will be told the outcome and the reason.',
    workerOnboardingIncomplete: 'Finish your application to start receiving work.',
    workerActive: 'You are set up. New requests that match your trades appear here.',
    accountUnavailableTitle: 'This account is not available',
    accountUnavailableBody: 'Contact Warsha support if you believe this is a mistake.',
    developmentBanner: 'Development environment — this is not real customer data',

    consoleTitle: 'Warsha Console',
    consoleLead: 'Signed in as staff. Every action below is authorised by the server on each request; this page reflects that authority, it does not grant it.',
    consoleSignInRequired: 'Sign in required',
    consoleSignInBody: 'Sign in with your Warsha staff account to continue.',
    consoleGoToSignIn: 'Go to sign in',
    consoleRefusedTitle: 'This console is not available to you',
    consoleRefusedBody: 'Your account is authenticated but has no active staff role. If that is wrong, ask a Security Administrator to review your grants.',
    consoleYourAccess: 'Your staff access',
    consoleNoRoles: 'No active staff roles.',
    consoleCapabilities: 'Capabilities',
    consoleNoCapabilities: 'No capabilities are granted to this account.',
    consoleSession: 'Session',
    consoleEnvironment: 'Environment',
    consoleUnbound: 'unbound',
    consoleReauth: 'Recent reauthentication',
    consoleReauthValid: 'valid',
    consoleReauthRequired: 'required for sensitive actions',
    consoleMfa: 'MFA required',
    consoleYes: 'yes',
    consoleNo: 'no',
    consoleTimezone: 'Timezone',
    consoleNotProduction: 'this is not production data',
    console_dashboard: 'Dashboard',
    console_users: 'Users',
    console_verification: 'Verification',
    console_staff: 'Staff',
    console_audit: 'Audit',
    usersTitle: 'Record lookup',
    usersLead: 'Look up one record by its exact identifier. Results are redacted to what your role may see, and the lookup itself is recorded.',
    usersSearchLabel: 'Identifier',
    usersSearchAction: 'Look up',
    usersNoQuery: 'Paste an exact record ID to begin.',
    usersNoResults: 'Nothing matched that identifier.',
    usersRefused: 'Your role cannot use this lookup.',
    usersNotDirectory: 'This is a lookup, not a directory. There is no way to browse or export accounts, wildcards are rejected, and only an exact identifier returns anything. That is deliberate.',
    usersContactHint: 'Your role may also look up an exact verified email address or phone number.',
    usersNoContactHint: 'Only a record ID works for your role. Looking up an email address or phone number needs the contact-details capability.',
    usersKindLabel: 'Kind',
    usersKindAll: 'Any kind',
    usersTooShort: 'That identifier is too short.',
    usersWildcard: 'Wildcards are not permitted. Enter an exact identifier.',
    usersRateLimited: 'Too many lookups in the last minute. Wait a moment.',
    usersExactOnly: 'Enter an exact identifier. Partial and name searches are not available.',
    colKind: 'Kind',
    colStatus: 'Status',
    colCreated: 'Created',
    colIdentifier: 'Identifier',
    colOpen: 'Open',

    verificationTitle: 'Verification queue',
    verificationLead: 'Worker applications awaiting a decision, oldest first. Every decision is recorded with its reason.',
    verificationEmpty: 'Nothing is waiting for review.',
    verificationPseudonymous: 'The queue shows an opaque reference rather than a name. Who a case belongs to is revealed only when it is opened under a capability that logs the access.',
    verificationRefused: 'Your role cannot review worker vetting.',
    colSubject: 'Case',
    colWorkerState: 'State',
    colWaiting: 'Waiting',
    colCertificate: 'Certificate',
    colPriority: 'Priority',
    certificateOnFile: 'On file',
    certificateMissing: 'Not yet',
    priorityHigh: 'Needs a person',
    priorityNormal: 'Normal',
    state_identity_submitted: 'Identity submitted',
    state_identity_under_review: 'Identity under review',
    state_criminal_record_submitted: 'Certificate submitted',
    state_criminal_record_under_review: 'Certificate under review',
    state_manual_review: 'Manual review',
    state_appeal_pending: 'Appeal pending',

    staffTitle: 'Staff access',
    staffLead: 'Roles, the capabilities they carry, and who holds them. Granting or revoking is governed: it requires capability, fresh authentication, and it is audited.',
    staffRefused: 'Your role cannot manage staff access.',
    staffRolesHeading: 'Roles',
    staffGrantsHeading: 'Who holds a role',
    staffCapabilitiesHeading: 'Capabilities',
    colRole: 'Role',
    colRiskTier: 'Risk',
    colCapabilityCount: 'Capabilities',
    colHolder: 'Holder',
    colGranted: 'Granted',
    colExpires: 'Expires',
    colCapability: 'Capability',
    colDomain: 'Domain',
    grantNoExpiry: 'No expiry',
    grantExpired: 'Expired',
    grantActive: 'Active',
    flagHighRisk: 'High risk',
    flagDualControl: 'Second person',
    flagReauth: 'Fresh sign-in',

    auditTitle: 'Audit',
    auditLead: 'Append-only record of what was done, by whom, and to what. This view cannot change it.',
    auditFrom: 'From',
    auditTo: 'To',
    auditSource: 'Source',
    auditEmpty: 'No entries for that range.',
    auditRefused: 'Your role cannot read the audit log.',
    auditNoOutcome: 'Every row is an action that happened; there is no separate success or failure column. What each source additionally recorded appears under Detail.',
    auditRangeTooWide: 'The range must be within 366 days.',
    colTime: 'Time',
    colActor: 'Actor',
    colAction: 'Action',
    colTarget: 'Target',
    colDetail: 'Detail',
    source_audit_logs: 'General',
    source_staff_audit: 'Staff actions',
    source_trust_moderation: 'Trust & moderation',
    source_payment_audit: 'Payments',
    source_dispute_events: 'Disputes',
    source_configuration_history: 'Configuration',
    source_staff_role_history: 'Role changes',
    source_support_events: 'Support',
    source_operational_events: 'Operations',

    pagerPrevious: 'Previous',
    pagerNext: 'Next',
    pagerShowing: 'Showing {from}–{to}',
    pagerPage: 'Page {page}',

    reauthTitle: 'Confirm it is you',
    reauthBodyPassword: 'This action needs a recent sign-in. Enter your password to continue.',
    reauthBodyCode: 'This action needs a recent sign-in. Enter the code from your authenticator app.',
    reauthPasswordLabel: 'Your password',
    reauthCodeLabel: 'Authentication code',
    reauthConfirm: 'Confirm',
    reauthPasswordRejected: 'That password was not accepted.',
    reauthCodeRejected: 'That code was not accepted.',
    reauthStillStale: 'The sign-in did not refresh. Sign out and in again.',
    reauthUnavailable: 'Re-authentication is unavailable right now.',
    reauthDeniedTitle: 'Your role cannot do this',
    reauthDeniedBody: 'Confirming who you are will not change this. The capability is not held by any of your roles.',
    reauthRevokedTitle: 'This session was ended',
    reauthRevokedBody: 'Your session was revoked. Sign out and sign in again to continue.',
    reauthRequired: 'Needs a fresh sign-in',
    reauthFreshFor: 'Confirmed for another {minutes} min',
    reauthConfirmNow: 'Confirm now',

    notificationCategory: 'Category',
    notificationAllCategories: 'All categories',
    category_marketplace: 'Marketplace',
    category_bookings: 'Bookings',
    category_messages: 'Messages',
    category_payments: 'Payments',
    category_worker_account: 'Worker account',
    category_reviews: 'Reviews',
    category_disputes: 'Disputes',
    category_security: 'Security',
    category_system: 'System',

    supportTitle: 'Support',
    supportLead: 'Open a case and the support team will reply. Everything you send is kept with the case.',
    supportOpenCase: 'Open a case',
    supportYourCases: 'Your cases',
    supportNoCases: 'You have not opened a case yet.',
    supportCategory: 'What is this about?',
    supportSubject: 'Subject',
    supportBody: 'What happened?',
    supportSend: 'Send',
    supportRateLimited: 'You have opened several cases just now. Wait a moment before opening another.',
    supportOpenFailed: 'That case could not be opened. Try again.',
    supportNoMessages: 'Nothing has been added to this case yet.',
    supportReplyByEmail: 'Replies to this case arrive by email and in the Warsha app.',
    supportCategory_account_access: 'Getting into my account',
    supportCategory_booking_help: 'A booking',
    supportCategory_worker_onboarding: 'Signing up as a worker',
    supportCategory_verification_help: 'Verification',
    supportCategory_payment_question: 'A payment',
    supportCategory_withdrawal_question: 'Withdrawing money',
    supportCategory_technical_issue: 'Something is broken',
    supportCategory_app_feedback: 'Feedback',
    supportCategory_other: 'Something else',
    supportStatus_open: 'Open',
    supportStatus_in_progress: 'Being looked at',
    supportStatus_waiting_participant: 'Waiting for you',
    supportStatus_escalated: 'Escalated',
    supportStatus_resolved: 'Resolved',
    supportStatus_closed: 'Closed',

    workerVerificationTitle: 'Verification',
    workerActiveBody: 'Your account is verified and you can take work.',
    workerNeedsAction: 'Something needs your attention',
    workerRemainingSteps: 'What is left',
    gateProgress: '{done} of {total} steps done',
    gateNext: 'Next',
    verificationUseApp: 'Photographs of your ID and your certificate are taken in the Warsha app, using your phone camera.',
    verificationNothingToDo: 'Nothing is needed from you. A reviewer is looking at your application.',
    verificationSubmit: 'Send for review',
    verificationSubmitted: 'Sent. A reviewer will look at your application.',
    verificationSubmitFailed: 'That could not be sent. Try again.',
    verificationAppealTitle: 'Appeal',
    verificationAppealBody: 'You can ask a different reviewer to look at the decision again. Appeals are made in the Warsha app.',
    gate_worker_role_selected: 'Choose the worker account',
    gate_phone_number_provided: 'Add your phone number',
    gate_worker_agreement_accepted: 'Accept the worker agreement',
    gate_document_processing_accepted: 'Agree to document review',
    gate_legal_name_complete: 'Add your full legal name',
    gate_profile_photo: 'Add a profile photo',
    gate_professions_configured: 'Choose your trades',
    gate_services_configured: 'Choose the services you offer',
    gate_service_area_configured: 'Set the areas you work in',
    gate_current_address_provided: 'Confirm your address',
    gate_national_id_front_uploaded: 'Photograph the front of your ID',
    gate_national_id_back_uploaded: 'Photograph the back of your ID',
    gate_identity_fields_confirmed: 'Confirm the details on your ID',
    gate_criminal_record_uploaded: 'Upload your certificate',

    cancel: 'Cancel',
    close: 'Close',
    resultKind: 'Kind',
    resultLabel: 'Result',
    tableEmpty: 'Nothing to show.',
  },

  ar: {
    home: 'الصفحة الرئيسية لورشة',
    navPrimary: 'التنقل الرئيسي',
    signOut: 'تسجيل الخروج',

    signInTitle: 'ادخل على ورشة',
    signInLead: 'استخدم البريد الإلكتروني أو رقم التليفون اللي سجّلت بيه. ورشة هتعرف الباقي.',
    identityLabel: 'البريد الإلكتروني أو رقم التليفون',
    passwordLabel: 'كلمة السر',
    signInAction: 'تسجيل الدخول',
    signingIn: 'بيتم الدخول…',
    noAccount: 'لسه ما عندكش حساب؟',
    createOne: 'اعمل واحد على ورشة',

    errInvalidIdentifier: 'اكتب البريد الإلكتروني أو رقم التليفون اللي سجّلت بيه.',
    errInvalidCredentials: 'البيانات دي ما طابقتش أي حساب. راجعها وحاول تاني.',
    errRateLimited: 'محاولات كتير. استنى شوية وحاول تاني.',
    errOutdatedClient: 'حدّث الصفحة عشان تجيب آخر إصدار، وبعدين ادخل.',
    errNetwork: 'ما قدرناش نوصل لورشة. راجع الاتصال وحاول تاني.',
    errServer: 'حصلت مشكلة عندنا. حاول تاني بعد شوية.',

    chooseModeTitle: 'عايز تستخدم ورشة إزاي النهاردة؟',
    chooseModeLead: 'حسابك يقدر يعمل الاتنين. اختار واحد — وتقدر تبدّل في أي وقت.',
    chooseCustomer: 'اطلب شغل',
    chooseCustomerBody: 'اوصف الشغل، استنى العروض، وتابع لحد ما يخلص.',
    chooseWorker: 'اشتغل',
    chooseWorkerBody: 'شوف الطلبات اللي تناسب مهنتك وقدّم سعر على اللي يعجبك.',

    modeCustomer: 'عميل',
    modeWorker: 'صنايعي',

    navHome: 'الرئيسية',
    navJobs: 'شغلاناتي',
    navNotifications: 'الإشعارات',
    navSupport: 'الدعم',
    navAccount: 'الحساب',
    navRequests: 'الطلبات',
    navEarnings: 'الأرباح',
    navVerification: 'التوثيق',
    navProfile: 'الملف الشخصي',

    dashboardGreeting: 'ورشة بتاعتك',
    activeJobs: 'الشغلانات الجارية',
    noActiveJobs: 'مفيش حاجة شغالة دلوقتي.',
    notifications: 'الإشعارات',
    noNotifications: 'مفيش جديد.',
    unreadCount: 'غير مقروء',
    supportCases: 'الدعم',
    noSupportCases: 'مفيش حالات دعم مفتوحة.',
    legalCentre: 'القانوني',
    privacyCentre: 'الخصوصية',
    viewAll: 'اعرض الكل',
    loading: 'بيحمّل…',
    loadFailed: 'ما قدرناش نحمّل ده. حاول تاني.',
    retry: 'حاول تاني',

    workerNextStep: 'الخطوة الجاية',
    workerVerificationPending: 'طلبك مع حد بيراجعه. هتعرف النتيجة والسبب.',
    workerOnboardingIncomplete: 'كمّل طلبك عشان تبدأ تستقبل شغل.',
    workerActive: 'إنت جاهز. الطلبات الجديدة اللي تناسب مهنتك بتظهر هنا.',
    accountUnavailableTitle: 'الحساب ده مش متاح',
    accountUnavailableBody: 'تواصل مع دعم ورشة لو شايف إن ده خطأ.',
    developmentBanner: 'بيئة تطوير — دي مش بيانات عملاء حقيقية',

    consoleTitle: 'كونسول ورشة',
    consoleLead: 'داخل كموظف. كل إجراء تحت بيتصرّح من السيرفر مع كل طلب؛ الصفحة دي بتعكس الصلاحية مش بتمنحها.',
    consoleSignInRequired: 'مطلوب تسجيل الدخول',
    consoleSignInBody: 'ادخل بحساب موظفي ورشة عشان تكمّل.',
    consoleGoToSignIn: 'روح لتسجيل الدخول',
    consoleRefusedTitle: 'الكونسول ده مش متاح ليك',
    consoleRefusedBody: 'حسابك متحقق منه بس مالوش دور موظف فعّال. لو ده غلط، اطلب من مسؤول الأمان يراجع صلاحياتك.',
    consoleYourAccess: 'صلاحياتك كموظف',
    consoleNoRoles: 'مفيش أدوار موظفين فعّالة.',
    consoleCapabilities: 'الصلاحيات',
    consoleNoCapabilities: 'مفيش صلاحيات ممنوحة للحساب ده.',
    consoleSession: 'الجلسة',
    consoleEnvironment: 'البيئة',
    consoleUnbound: 'غير مرتبطة',
    consoleReauth: 'إعادة تحقق حديثة',
    consoleReauthValid: 'سارية',
    consoleReauthRequired: 'مطلوبة للإجراءات الحساسة',
    consoleMfa: 'المصادقة الثنائية مطلوبة',
    consoleYes: 'أيوه',
    consoleNo: 'لأ',
    consoleTimezone: 'المنطقة الزمنية',
    consoleNotProduction: 'دي مش بيانات إنتاج',
    console_dashboard: 'لوحة التحكم',
    console_users: 'المستخدمين',
    console_verification: 'التوثيق',
    console_staff: 'الموظفين',
    console_audit: 'السجل',
    usersTitle: 'البحث عن سجل',
    usersLead: 'دوّر على سجل واحد برقمه بالظبط. النتايج بتتعرض حسب صلاحيتك، والبحث نفسه بيتسجّل.',
    usersSearchLabel: 'المُعرّف',
    usersSearchAction: 'دوّر',
    usersNoQuery: 'الصق رقم السجل بالظبط عشان تبدأ.',
    usersNoResults: 'مفيش نتايج للمُعرّف ده.',
    usersRefused: 'دورك ما يسمحش باستخدام البحث ده.',
    usersNotDirectory: 'ده بحث عن سجل واحد، مش دليل. مفيش طريقة تتصفّح بيها الحسابات أو تصدّرها، والبحث بعلامات عامة مرفوض، ومحدش بيرجّع حاجة غير المُعرّف الكامل. ده مقصود.',
    usersContactHint: 'دورك كمان يسمح بالبحث بإيميل أو رقم تليفون موثّق بالظبط.',
    usersNoContactHint: 'رقم السجل بس هو اللي شغّال مع دورك. البحث بالإيميل أو التليفون محتاج صلاحية بيانات التواصل.',
    usersKindLabel: 'النوع',
    usersKindAll: 'أي نوع',
    usersTooShort: 'المُعرّف ده قصير أوي.',
    usersWildcard: 'العلامات العامة ممنوعة. اكتب المُعرّف بالظبط.',
    usersRateLimited: 'عمليات بحث كتير في الدقيقة اللي فاتت. استنى شوية.',
    usersExactOnly: 'اكتب المُعرّف بالظبط. البحث الجزئي أو بالاسم مش متاح.',
    colKind: 'النوع',
    colStatus: 'الحالة',
    colCreated: 'اتعمل في',
    colIdentifier: 'المُعرّف',
    colOpen: 'افتح',

    verificationTitle: 'طابور التوثيق',
    verificationLead: 'طلبات الصنايعية اللي مستنية قرار، الأقدم الأول. كل قرار بيتسجّل بسببه.',
    verificationEmpty: 'مفيش حاجة مستنية مراجعة.',
    verificationPseudonymous: 'الطابور بيعرض إشارة مبهمة مش اسم. صاحب الحالة ما بيظهرش غير لما تتفتح بصلاحية بتسجّل الوصول.',
    verificationRefused: 'دورك ما يسمحش بمراجعة توثيق الصنايعية.',
    colSubject: 'الحالة',
    colWorkerState: 'الوضع',
    colWaiting: 'مستنية من',
    colCertificate: 'الفيش',
    colPriority: 'الأولوية',
    certificateOnFile: 'موجود',
    certificateMissing: 'لسه',
    priorityHigh: 'محتاجة حد',
    priorityNormal: 'عادية',
    state_identity_submitted: 'الإثبات اتبعت',
    state_identity_under_review: 'الإثبات تحت المراجعة',
    state_criminal_record_submitted: 'الفيش اتبعت',
    state_criminal_record_under_review: 'الفيش تحت المراجعة',
    state_manual_review: 'مراجعة يدوية',
    state_appeal_pending: 'تظلّم مستني',

    staffTitle: 'صلاحيات الموظفين',
    staffLead: 'الأدوار، والصلاحيات اللي بتحملها، ومين شايلها. المنح أو السحب متحكوم فيه: بيحتاج صلاحية وتسجيل دخول حديث، وبيتسجّل.',
    staffRefused: 'دورك ما يسمحش بإدارة صلاحيات الموظفين.',
    staffRolesHeading: 'الأدوار',
    staffGrantsHeading: 'مين شايل دور',
    staffCapabilitiesHeading: 'الصلاحيات',
    colRole: 'الدور',
    colRiskTier: 'الخطورة',
    colCapabilityCount: 'الصلاحيات',
    colHolder: 'الشخص',
    colGranted: 'اتمنح في',
    colExpires: 'بينتهي في',
    colCapability: 'الصلاحية',
    colDomain: 'المجال',
    grantNoExpiry: 'من غير نهاية',
    grantExpired: 'منتهي',
    grantActive: 'ساري',
    flagHighRisk: 'خطورة عالية',
    flagDualControl: 'محتاج شخص تاني',
    flagReauth: 'دخول حديث',

    auditTitle: 'السجل',
    auditLead: 'سجل بيتضاف عليه بس: اتعمل إيه، ومين عمله، وعلى مين. الشاشة دي ما بتغيّرهوش.',
    auditFrom: 'من',
    auditTo: 'إلى',
    auditSource: 'المصدر',
    auditEmpty: 'مفيش سجلات في المدى ده.',
    auditRefused: 'دورك ما يسمحش بقراءة السجل.',
    auditNoOutcome: 'كل سطر هنا إجراء حصل فعلاً؛ مفيش عمود منفصل للنجاح أو الفشل. اللي كل مصدر سجّله زيادة بيظهر تحت التفاصيل.',
    auditRangeTooWide: 'المدى لازم يكون في حدود ٣٦٦ يوم.',
    colTime: 'الوقت',
    colActor: 'مين',
    colAction: 'الإجراء',
    colTarget: 'على إيه',
    colDetail: 'التفاصيل',
    source_audit_logs: 'عام',
    source_staff_audit: 'إجراءات الموظفين',
    source_trust_moderation: 'الثقة والإشراف',
    source_payment_audit: 'المدفوعات',
    source_dispute_events: 'الخلافات',
    source_configuration_history: 'الإعدادات',
    source_staff_role_history: 'تغييرات الأدوار',
    source_support_events: 'الدعم',
    source_operational_events: 'التشغيل',

    pagerPrevious: 'السابق',
    pagerNext: 'التالي',
    pagerShowing: 'بيعرض {from}–{to}',
    pagerPage: 'صفحة {page}',

    reauthTitle: 'أكّد إنك إنت',
    reauthBodyPassword: 'الإجراء ده محتاج تسجيل دخول حديث. اكتب كلمة السر عشان تكمّل.',
    reauthBodyCode: 'الإجراء ده محتاج تسجيل دخول حديث. اكتب الكود من تطبيق المصادقة.',
    reauthPasswordLabel: 'كلمة السر بتاعتك',
    reauthCodeLabel: 'كود المصادقة',
    reauthConfirm: 'أكّد',
    reauthPasswordRejected: 'كلمة السر دي مش مقبولة.',
    reauthCodeRejected: 'الكود ده مش مقبول.',
    reauthStillStale: 'تسجيل الدخول ما اتجدّدش. اخرج وادخل تاني.',
    reauthUnavailable: 'إعادة التحقق مش متاحة دلوقتي.',
    reauthDeniedTitle: 'دورك ما يسمحش بده',
    reauthDeniedBody: 'تأكيد شخصيتك مش هيغيّر ده. الصلاحية دي مش موجودة في أي دور من أدوارك.',
    reauthRevokedTitle: 'الجلسة دي اتقفلت',
    reauthRevokedBody: 'جلستك اتسحبت. اخرج وادخل تاني عشان تكمّل.',
    reauthRequired: 'محتاج تسجيل دخول حديث',
    reauthFreshFor: 'مؤكّد لمدة {minutes} دقيقة كمان',
    reauthConfirmNow: 'أكّد دلوقتي',

    notificationCategory: 'النوع',
    notificationAllCategories: 'كل الأنواع',
    category_marketplace: 'السوق',
    category_bookings: 'الحجوزات',
    category_messages: 'الرسايل',
    category_payments: 'المدفوعات',
    category_worker_account: 'حساب الصنايعي',
    category_reviews: 'التقييمات',
    category_disputes: 'الخلافات',
    category_security: 'الأمان',
    category_system: 'النظام',

    supportTitle: 'الدعم',
    supportLead: 'افتح حالة وفريق الدعم هيرد عليك. كل اللي بتبعته بيتحفظ مع الحالة.',
    supportOpenCase: 'افتح حالة',
    supportYourCases: 'حالاتك',
    supportNoCases: 'لسه مفتحتش أي حالة.',
    supportCategory: 'الموضوع بخصوص إيه؟',
    supportSubject: 'العنوان',
    supportBody: 'حصل إيه؟',
    supportSend: 'ابعت',
    supportRateLimited: 'فتحت حالات كتير دلوقتي. استنى شوية قبل ما تفتح واحدة تانية.',
    supportOpenFailed: 'مقدرناش نفتح الحالة دي. جرّب تاني.',
    supportNoMessages: 'لسه مفيش حاجة اتضافت للحالة دي.',
    supportReplyByEmail: 'الردود على الحالة دي بتوصل على الإيميل وفي تطبيق ورشة.',
    supportCategory_account_access: 'الدخول على حسابي',
    supportCategory_booking_help: 'حجز',
    supportCategory_worker_onboarding: 'التسجيل كصنايعي',
    supportCategory_verification_help: 'التوثيق',
    supportCategory_payment_question: 'دفع',
    supportCategory_withdrawal_question: 'سحب فلوس',
    supportCategory_technical_issue: 'في حاجة مش شغالة',
    supportCategory_app_feedback: 'رأيك',
    supportCategory_other: 'حاجة تانية',
    supportStatus_open: 'مفتوحة',
    supportStatus_in_progress: 'بيتشاف فيها',
    supportStatus_waiting_participant: 'مستنية منك',
    supportStatus_escalated: 'اتصعّدت',
    supportStatus_resolved: 'اتحلّت',
    supportStatus_closed: 'اتقفلت',

    workerVerificationTitle: 'التوثيق',
    workerActiveBody: 'حسابك موثّق وتقدر تستلم شغل.',
    workerNeedsAction: 'في حاجة محتاجة انتباهك',
    workerRemainingSteps: 'الباقي إيه',
    gateProgress: 'خلّصت {done} من {total} خطوات',
    gateNext: 'التالي',
    verificationUseApp: 'صور البطاقة والفيش بتتاخد من تطبيق ورشة بكاميرا الموبايل.',
    verificationNothingToDo: 'مش محتاجين حاجة منك. في حد بيراجع طلبك.',
    verificationSubmit: 'ابعت للمراجعة',
    verificationSubmitted: 'اتبعت. هيتراجع طلبك.',
    verificationSubmitFailed: 'مقدرناش نبعت. جرّب تاني.',
    verificationAppealTitle: 'تظلّم',
    verificationAppealBody: 'تقدر تطلب إن حد تاني يراجع القرار. التظلّم بيتعمل من تطبيق ورشة.',
    gate_worker_role_selected: 'اختار حساب الصنايعي',
    gate_phone_number_provided: 'ضيف رقم تليفونك',
    gate_worker_agreement_accepted: 'وافق على اتفاقية الصنايعي',
    gate_document_processing_accepted: 'وافق على مراجعة المستندات',
    gate_legal_name_complete: 'اكتب اسمك الرباعي',
    gate_profile_photo: 'ضيف صورة شخصية',
    gate_professions_configured: 'اختار حرفتك',
    gate_services_configured: 'اختار الخدمات اللي بتقدمها',
    gate_service_area_configured: 'حدّد المناطق اللي بتشتغل فيها',
    gate_current_address_provided: 'أكّد عنوانك',
    gate_national_id_front_uploaded: 'صوّر وش البطاقة',
    gate_national_id_back_uploaded: 'صوّر ضهر البطاقة',
    gate_identity_fields_confirmed: 'أكّد بيانات البطاقة',
    gate_criminal_record_uploaded: 'ارفع الفيش والتشبيه',

    cancel: 'إلغاء',
    close: 'إقفال',
    resultKind: 'النوع',
    resultLabel: 'النتيجة',
    tableEmpty: 'مفيش حاجة تتعرض.',
  },
} as const;

export type AppCopyKey = keyof typeof appCopy.en;

/**
 * One locale's copy, widened from its literal types.
 *
 * `appCopy` is `as const`, so `appCopy.en` and `appCopy.ar` have different
 * literal types and neither is assignable to the other. Anything that accepts
 * "the words for whichever locale is active" wants this, not `typeof
 * appCopy.en`.
 */
export type AppWords = Record<AppCopyKey, string>;

export function appText(locale: Locale, key: AppCopyKey): string {
  return appCopy[locale][key];
}
