import type { Locale } from './preferences.ts';

/**
 * Every word the authenticated application says, in both languages.
 *
 * Same rule as the public site: no component holds a bare string, because the
 * failure nobody reports and everybody sees is one English word left in the
 * middle of an Arabic page.
 */
export const appCopy = {
  en: {
    home: 'Warsha home',
    navPrimary: 'Primary',
    signOut: 'Sign out',

    signInTitle: 'Sign in to Warsha',
    signInLead: 'Use the email address or the phone number you registered with. Warsha works out the rest.',
    identityLabel: 'Email or phone number',
    passwordLabel: 'Password',
    signInAction: 'Sign in',
    signingIn: 'Signing in…',
    noAccount: 'Do not have an account yet?',
    createOne: 'Create one on warsha',

    errInvalidIdentifier: 'Enter the email address or phone number you registered with.',
    errInvalidCredentials: 'Those details did not match an account. Check them and try again.',
    errRateLimited: 'Too many attempts. Wait a little, then try again.',
    errOutdatedClient: 'Reload the page to get the latest version, then sign in.',
    errNetwork: 'Warsha could not be reached. Check your connection and try again.',
    errServer: 'Something went wrong on our side. Please try again shortly.',

    chooseModeTitle: 'How do you want to use Warsha today?',
    chooseModeLead: 'Your account can do both. Pick one — you can switch whenever you like.',
    chooseCustomer: 'Book work',
    chooseCustomerBody: 'Describe a job, receive quotes, and track it to completion.',
    chooseWorker: 'Do work',
    chooseWorkerBody: 'See requests that match your trades and quote the ones you want.',

    modeCustomer: 'Customer',
    modeWorker: 'Worker',

    navHome: 'Home',
    navJobs: 'My jobs',
    navNotifications: 'Notifications',
    navSupport: 'Support',
    navAccount: 'Account',
    navRequests: 'Requests',
    navEarnings: 'Earnings',
    navVerification: 'Verification',
    navProfile: 'Profile',

    dashboardGreeting: 'Your Warsha',
    activeJobs: 'Active jobs',
    noActiveJobs: 'Nothing in progress right now.',
    notifications: 'Notifications',
    noNotifications: 'Nothing new.',
    unreadCount: 'unread',
    supportCases: 'Support',
    noSupportCases: 'No open support cases.',
    legalCentre: 'Legal',
    privacyCentre: 'Privacy',
    viewAll: 'View all',
    loading: 'Loading…',
    loadFailed: 'That could not be loaded. Try again.',
    retry: 'Try again',

    workerNextStep: 'What to do next',
    workerVerificationPending: 'Your application is with a reviewer. You will be told the outcome and the reason.',
    workerOnboardingIncomplete: 'Finish your application to start receiving work.',
    workerActive: 'You are set up. New requests that match your trades appear here.',
    accountUnavailableTitle: 'This account is not available',
    accountUnavailableBody: 'Contact Warsha support if you believe this is a mistake.',
    developmentBanner: 'Development environment — this is not real customer data',

    consoleTitle: 'Warsha Console',
    consoleLead: 'Signed in as staff. Every action below is authorised by the server on each request; this page reflects that authority, it does not grant it.',
    consoleSignInRequired: 'Sign in required',
    consoleSignInBody: 'Sign in with your Warsha staff account to continue.',
    consoleGoToSignIn: 'Go to sign in',
    consoleRefusedTitle: 'This console is not available to you',
    consoleRefusedBody: 'Your account is authenticated but has no active staff role. If that is wrong, ask a Security Administrator to review your grants.',
    consoleYourAccess: 'Your staff access',
    consoleNoRoles: 'No active staff roles.',
    consoleCapabilities: 'Capabilities',
    consoleNoCapabilities: 'No capabilities are granted to this account.',
    consoleSession: 'Session',
    consoleEnvironment: 'Environment',
    consoleUnbound: 'unbound',
    consoleReauth: 'Recent reauthentication',
    consoleReauthValid: 'valid',
    consoleReauthRequired: 'required for sensitive actions',
    consoleMfa: 'MFA required',
    consoleYes: 'yes',
    consoleNo: 'no',
    consoleTimezone: 'Timezone',
    consoleNotProduction: 'this is not production data',
  },

  ar: {
    home: 'الصفحة الرئيسية لورشة',
    navPrimary: 'التنقل الرئيسي',
    signOut: 'تسجيل الخروج',

    signInTitle: 'ادخل على ورشة',
    signInLead: 'استخدم البريد الإلكتروني أو رقم التليفون اللي سجّلت بيه. ورشة هتعرف الباقي.',
    identityLabel: 'البريد الإلكتروني أو رقم التليفون',
    passwordLabel: 'كلمة السر',
    signInAction: 'تسجيل الدخول',
    signingIn: 'بيتم الدخول…',
    noAccount: 'لسه ما عندكش حساب؟',
    createOne: 'اعمل واحد على ورشة',

    errInvalidIdentifier: 'اكتب البريد الإلكتروني أو رقم التليفون اللي سجّلت بيه.',
    errInvalidCredentials: 'البيانات دي ما طابقتش أي حساب. راجعها وحاول تاني.',
    errRateLimited: 'محاولات كتير. استنى شوية وحاول تاني.',
    errOutdatedClient: 'حدّث الصفحة عشان تجيب آخر إصدار، وبعدين ادخل.',
    errNetwork: 'ما قدرناش نوصل لورشة. راجع الاتصال وحاول تاني.',
    errServer: 'حصلت مشكلة عندنا. حاول تاني بعد شوية.',

    chooseModeTitle: 'عايز تستخدم ورشة إزاي النهاردة؟',
    chooseModeLead: 'حسابك يقدر يعمل الاتنين. اختار واحد — وتقدر تبدّل في أي وقت.',
    chooseCustomer: 'اطلب شغل',
    chooseCustomerBody: 'اوصف الشغل، استنى العروض، وتابع لحد ما يخلص.',
    chooseWorker: 'اشتغل',
    chooseWorkerBody: 'شوف الطلبات اللي تناسب مهنتك وقدّم سعر على اللي يعجبك.',

    modeCustomer: 'عميل',
    modeWorker: 'صنايعي',

    navHome: 'الرئيسية',
    navJobs: 'شغلاناتي',
    navNotifications: 'الإشعارات',
    navSupport: 'الدعم',
    navAccount: 'الحساب',
    navRequests: 'الطلبات',
    navEarnings: 'الأرباح',
    navVerification: 'التوثيق',
    navProfile: 'الملف الشخصي',

    dashboardGreeting: 'ورشة بتاعتك',
    activeJobs: 'الشغلانات الجارية',
    noActiveJobs: 'مفيش حاجة شغالة دلوقتي.',
    notifications: 'الإشعارات',
    noNotifications: 'مفيش جديد.',
    unreadCount: 'غير مقروء',
    supportCases: 'الدعم',
    noSupportCases: 'مفيش حالات دعم مفتوحة.',
    legalCentre: 'القانوني',
    privacyCentre: 'الخصوصية',
    viewAll: 'اعرض الكل',
    loading: 'بيحمّل…',
    loadFailed: 'ما قدرناش نحمّل ده. حاول تاني.',
    retry: 'حاول تاني',

    workerNextStep: 'الخطوة الجاية',
    workerVerificationPending: 'طلبك مع حد بيراجعه. هتعرف النتيجة والسبب.',
    workerOnboardingIncomplete: 'كمّل طلبك عشان تبدأ تستقبل شغل.',
    workerActive: 'إنت جاهز. الطلبات الجديدة اللي تناسب مهنتك بتظهر هنا.',
    accountUnavailableTitle: 'الحساب ده مش متاح',
    accountUnavailableBody: 'تواصل مع دعم ورشة لو شايف إن ده خطأ.',
    developmentBanner: 'بيئة تطوير — دي مش بيانات عملاء حقيقية',

    consoleTitle: 'كونسول ورشة',
    consoleLead: 'داخل كموظف. كل إجراء تحت بيتصرّح من السيرفر مع كل طلب؛ الصفحة دي بتعكس الصلاحية مش بتمنحها.',
    consoleSignInRequired: 'مطلوب تسجيل الدخول',
    consoleSignInBody: 'ادخل بحساب موظفي ورشة عشان تكمّل.',
    consoleGoToSignIn: 'روح لتسجيل الدخول',
    consoleRefusedTitle: 'الكونسول ده مش متاح ليك',
    consoleRefusedBody: 'حسابك متحقق منه بس مالوش دور موظف فعّال. لو ده غلط، اطلب من مسؤول الأمان يراجع صلاحياتك.',
    consoleYourAccess: 'صلاحياتك كموظف',
    consoleNoRoles: 'مفيش أدوار موظفين فعّالة.',
    consoleCapabilities: 'الصلاحيات',
    consoleNoCapabilities: 'مفيش صلاحيات ممنوحة للحساب ده.',
    consoleSession: 'الجلسة',
    consoleEnvironment: 'البيئة',
    consoleUnbound: 'غير مرتبطة',
    consoleReauth: 'إعادة تحقق حديثة',
    consoleReauthValid: 'سارية',
    consoleReauthRequired: 'مطلوبة للإجراءات الحساسة',
    consoleMfa: 'المصادقة الثنائية مطلوبة',
    consoleYes: 'أيوه',
    consoleNo: 'لأ',
    consoleTimezone: 'المنطقة الزمنية',
    consoleNotProduction: 'دي مش بيانات إنتاج',
  },
} as const;

export type AppCopyKey = keyof typeof appCopy.en;

export function appText(locale: Locale, key: AppCopyKey): string {
  return appCopy[locale][key];
}
