/**
 * French copy for the authenticated customer, worker, and staff web surfaces.
 *
 * Kept separate from the EN/AR authority so reviews can detect accidental
 * English fallback without making the already-large shared catalogue harder
 * to audit. Product identifiers and interpolation tokens stay unchanged.
 */
export const frenchAppCopyOverrides = {
  home: 'Accueil Warsha',
  identityLabel: 'Adresse e-mail ou numéro de téléphone',
  passwordLabel: 'Mot de passe',
  noAccount: 'Vous n’avez pas encore de compte ?',
  errInvalidIdentifier: 'Saisissez l’adresse e-mail ou le numéro de téléphone utilisé lors de votre inscription.',
  errInvalidCredentials: 'Ces informations ne correspondent à aucun compte. Vérifiez-les et réessayez.',
  errRateLimited: 'Trop de tentatives. Patientez un instant, puis réessayez.',
  errOutdatedClient: 'Actualisez la page pour obtenir la dernière version, puis reconnectez-vous.',
  errNetwork: 'Warsha est inaccessible. Vérifiez votre connexion et réessayez.',
  errServer: 'Un problème est survenu de notre côté. Réessayez dans quelques instants.',
  chooseModeTitle: 'Comment souhaitez-vous utiliser Warsha aujourd’hui ?',
  chooseModeLead: 'Votre compte permet les deux usages. Choisissez-en un ; vous pourrez changer à tout moment.',
  chooseCustomer: 'Demander un service',
  chooseCustomerBody: 'Décrivez le travail, recevez des devis et suivez sa réalisation.',
  chooseWorker: 'Proposer mes services',
  chooseWorkerBody: 'Consultez les demandes correspondant à vos métiers et envoyez les devis qui vous intéressent.',
  modeCustomer: 'Client',
  modeWorker: 'Professionnel',
  dashboardGreeting: 'Votre espace Warsha',
  activeJobs: 'Travaux en cours',
  noActiveJobs: 'Aucun travail en cours pour le moment.',
  noNotifications: 'Aucune nouveauté.',
  unreadCount: 'non lues',
  noSupportCases: 'Aucune demande d’assistance ouverte.',
  legalCentre: 'Informations juridiques',
  privacyCentre: 'Confidentialité',
  viewAll: 'Tout afficher',
  loadFailed: 'Impossible de charger ces informations. Réessayez.',
  workerNextStep: 'Prochaine étape',
  workerVerificationPending: 'Votre dossier est en cours d’examen. Vous recevrez la décision et son motif.',
  workerOnboardingIncomplete: 'Terminez votre dossier pour commencer à recevoir des demandes.',
  workerActive: 'Votre compte est prêt. Les nouvelles demandes correspondant à vos métiers apparaîtront ici.',
  developmentBanner: 'Environnement de développement — ces données ne sont pas celles de vrais clients',

  consoleTitle: 'Console Warsha',
  consoleLead: 'Vous êtes connecté comme membre du personnel. Chaque action ci-dessous est autorisée par le serveur au moment de la demande ; cette page reflète vos droits, elle ne les accorde pas.',
  consoleSignInRequired: 'Connexion requise',
  consoleSignInBody: 'Connectez-vous avec votre compte Warsha du personnel pour continuer.',
  consoleGoToSignIn: 'Se connecter',
  consoleRefusedTitle: 'Vous n’avez pas accès à cette console',
  consoleRefusedBody: 'Votre compte est authentifié, mais ne possède aucun rôle actif du personnel. Si cela semble incorrect, demandez à un administrateur de la sécurité de vérifier vos attributions.',
  consoleYourAccess: 'Vos accès en tant que membre du personnel',
  consoleNoRoles: 'Aucun rôle actif du personnel.',
  consoleCapabilities: 'Autorisations',
  consoleNoCapabilities: 'Aucune autorisation n’est accordée à ce compte.',
  consoleSession: 'Session',
  consoleEnvironment: 'Environnement',
  consoleUnbound: 'non associé',
  consoleReauth: 'Réauthentification récente',
  consoleReauthValid: 'valide',
  consoleReauthRequired: 'requise pour les actions sensibles',
  consoleMfa: 'Authentification multifacteur requise',
  consoleYes: 'oui',
  consoleNo: 'non',
  consoleTimezone: 'Fuseau horaire',
  consoleNotProduction: 'il ne s’agit pas de données de production',
  console_providers: 'Prestataires',
  providersTitle: 'Prestataires externes',
  providersLead: 'Les services externes que Warsha peut appeler, et les étapes encadrées qui en activent un. Aucune information d’identification n’est affichée ici.',
  providersNoCapability: 'Vous ne disposez pas de la permission nécessaire pour consulter les prestataires externes.',
  providerMapsName: 'Google Maps Platform',
  providerMapsPurpose: 'Fournit la recherche et la reconnaissance d’adresses pour les fonctions de localisation de Warsha. Les clients l’utilisent lorsqu’ils recherchent une adresse ou utilisent leur position actuelle.',
  providerEnvironment: 'Environnement',
  providerCredential: 'Identifiant',
  providerCredentialSet: 'Configuré',
  providerCredentialMissing: 'Non configuré',
  providerStatus: 'État du prestataire',
  providerStatusActive: 'Actif',
  providerStatusAwaiting: 'En attente d’activation',
  providerFeature: 'Fonctionnalité',
  providerFeatureOn: 'Activée',
  providerFeatureOff: 'Désactivée',
  providerKillSwitch: 'Coupe-circuit',
  providerKillSwitchReady: 'Prêt',
  providerSequenceTitle: 'Comment se déroule l’activation',
  providerSequenceLead: 'Ces étapes suivent cet ordre parce que Warsha l’impose. Activer la fonctionnalité trop tôt ne fait pas gagner d’étape : l’activation est refusée tant qu’elle est déjà active.',
  providerStepDone: 'Fait',
  providerStepReady: 'Vous pouvez le faire maintenant',
  providerStepWaiting: 'En attente de quelqu’un d’autre',
  providerStepBlocked: 'Étape précédente d’abord',
  providerStep_environment: 'Confirmer qu’il s’agit de Warsha Développement',
  providerStepWhy_environment: 'Un prestataire est approuvé pour un environnement à la fois : Warsha vérifie donc d’abord sur quel backend vous êtes.',
  providerStep_credential: 'Confirmer que l’identifiant cartographique est configuré',
  providerStepWhy_credential: 'Warsha demande au service de localisation s’il dispose d’un identifiant utilisable. Elle ne lit ni n’affiche jamais l’identifiant lui-même.',
  providerStep_prerequisites: 'Vérifier que le prestataire est prêt',
  providerStepWhy_prerequisites: 'Le prestataire doit être enregistré pour cet environnement et disposer de sa propre bascule de fonctionnalité et de son propre coupe-circuit.',
  providerStep_approvalRequested: 'Demander l’accord d’un second collègue',
  providerStepWhy_approvalRequested: 'Vous consignez la raison de l’activation. La demande expire après 24 heures si personne n’y donne suite.',
  providerStep_approvalGranted: 'Un second collègue approuve',
  providerStepWhy_approvalGranted: 'Ce doit être une personne différente. Warsha refuse que quiconque approuve sa propre demande, quelles que soient ses permissions.',
  providerStep_activate: 'Activer le prestataire',
  providerStepWhy_activate: 'Cela consomme l’accord une seule fois et rend le prestataire actif. L’accord ne peut plus être réutilisé ensuite.',
  providerStep_activated: 'Confirmer la réussite de l’activation',
  providerStepWhy_activated: 'Warsha relit le registre des prestataires plutôt que de supposer que l’activation a fonctionné.',
  providerStep_feature: 'Activer la recherche d’adresses',
  providerStepWhy_feature: 'L’activation autorise le prestataire ; ceci expose réellement la recherche aux clients. Cette étape vient en dernier car l’activation est refusée tant qu’elle est déjà active.',
  providerStep_health: 'Vérifier qu’il fonctionne vraiment',
  providerStepWhy_health: 'Une recherche sûre et une reconnaissance d’adresse sûre, pour prouver que le service répond au lieu de le supposer.',
  providerStep_operational: 'La recherche d’adresses est active',
  providerStepWhy_operational: 'Les clients peuvent désormais rechercher une adresse et utiliser leur position actuelle.',
  providerApprovalTitle: 'Second accord',
  providerApprovalWhy: 'Activer un service externe lui transmet les adresses des clients : Warsha exige donc deux personnes différentes, l’une qui demande et l’autre qui accepte. Ce n’est pas une formalité — la base de données refuse l’activation sans cela.',
  providerApprovalRequestedBy: 'Demandé par',
  providerApprovalRequestedAt: 'Demandé le',
  providerApprovalExpires: 'Expire le',
  providerApprovalState: 'Statut',
  providerApprovalApproved: 'Approuvé',
  providerApprovalPending: 'En attente d’une seconde personne',
  providerApprovalApprovedBy: 'Approuvé par',
  providerApprovalReason: 'Motif indiqué',
  providerApprovalNotYours: 'Vous êtes à l’origine de cette demande, vous ne pouvez donc pas l’approuver. Un collègue disposant de la même permission doit ouvrir cette page et l’approuver.',
  providerApprovalNote: 'Note d’approbation',
  providerApprovalNoteHint: 'Enregistrée sous votre compte dans la piste d’audit. Au moins 3 caractères.',
  providerApproveAction: 'Approuver cette demande',
  providerApprovalUnavailable: 'Aucune demande d’accord n’est ouverte et les étapes précédentes ne sont pas terminées.',
  providerReason: 'Motif',
  providerReasonHint: 'Pourquoi ce service doit être activé. Enregistré dans la piste d’audit. Au moins 10 caractères.',
  providerRequestAction: 'Demander l’accord',
  providerActionsTitle: 'Actions',
  providerActivateTitle: 'Activer le prestataire',
  providerActivateBody: 'Rend Google Maps Platform actif pour cet environnement et consomme le second accord.',
  providerActivateAction: 'Activer le prestataire',
  providerActivateDefaultReason: 'Activation du prestataire de localisation pour le développement hébergé.',
  providerFeatureTitle: 'Activer la recherche d’adresses',
  providerFeatureBody: 'Rend la recherche et la reconnaissance d’adresses disponibles pour les clients dans cet environnement.',
  providerFeatureAction: 'Activer la recherche d’adresses',
  providerFeatureDefaultReason: 'Activation du prestataire de localisation après activation.',
  providerHealthTitle: 'Tester le prestataire',
  providerHealthBody: 'Lance une recherche d’adresse sûre et une reconnaissance d’adresse sûre. Ne modifie rien et ne révèle aucun identifiant.',
  providerHealthAction: 'Lancer le test',
  providerHealthResult: 'Résultat du test',
  providerHealthSearch: 'La recherche d’adresses a répondu',
  providerHealthReverse: 'La reconnaissance d’adresse a répondu',
  providerHealthFailed: 'Le service de localisation n’a pas répondu. Vérifiez l’état du prestataire et réessayez.',
  providerFactPermission: 'Permission requise',
  providerFactMutates: 'Modifie l’état hébergé',
  providerFactFreshAuth: 'Nécessite une connexion récente',
  providerFactSecondPerson: 'Nécessite une seconde personne',
  providerFactReversible: 'Réversible',
  providerFactAudit: 'Enregistré comme',
  providerTechnical: 'Détails techniques',
  providerActionFailed: 'Cette action a été refusée. Rien n’a été modifié.',
  capability_manage_subprocessors: 'Gérer les sous-traitants',
  capability_manage_feature_flags: 'Gérer les indicateurs de fonctionnalité',
  capability_review_legal_governance: 'Examiner la gouvernance juridique',
  addressGovernorateChoose: 'Choisissez un gouvernorat',
  addressDistrictChoose: 'Choisissez une zone',
  addressDistrictPickGovernorate: 'Choisissez d’abord un gouvernorat pour voir ses zones.',
  addressLocationSection: 'Emplacement',
  addressLocationWhy: 'Warsha a besoin de l’emplacement exact pour que le professionnel vous trouve. Recherchez l’adresse ou utilisez votre position actuelle.',
  addressLocationMissing: 'Confirmez l’emplacement ci-dessus avant d’enregistrer cette adresse.',
  addressLocationDenied: 'L’autorisation de localisation est bloquée pour ce site. Autorisez-la dans les réglages de votre navigateur puis réessayez, ou recherchez l’adresse à la place.',
  console_platform: 'Plateforme',
  platformTitle: 'Environnement de la plateforme',
  platformLead: 'Identifiez ce backend Warsha et vérifiez que ses garanties de publication tiennent toujours. Aucun de ces outils ne déploie de code, et aucun ne peut affecter la Production.',
  platformEnvHeading: 'Environnement de la plateforme',
  platformEnvExplain: 'Chaque backend Warsha démarre sans identification, car la même installation tourne sur une machine de développement et sur un projet hébergé. L’identifier permet aux outils du personnel et aux contrôles propres à chaque environnement de décrire correctement les données que vous consultez.',
  platformEnvCurrent: 'Statut actuel',
  platformEnvProject: 'Projet Warsha',
  platformEnvUnconfigured: 'Non configuré',
  platformEnvDevelopment: 'Warsha Développement',
  platformEnvStaging: 'Warsha Préproduction',
  platformEnvProduction: 'Warsha Production',
  platformEnvTarget: 'Identifier ce backend comme',
  platformEnvTargetHint: 'La Production ne peut pas être choisie ici. Elle se configure par sa propre procédure approuvée.',
  platformEnvReason: 'Motif',
  platformEnvReasonPlaceholder: 'Pourquoi ce backend est identifié maintenant',
  platformEnvReasonHint: 'Enregistré dans la piste d’audit sous votre compte. Au moins 10 caractères.',
  platformEnvReview: 'Examiner ce changement',
  platformEnvConfirmTitle: 'Confirmer ce changement',
  platformEnvConfirmFrom: 'Actuellement identifié comme :',
  platformEnvConfirmTo: 'Sera identifié comme :',
  platformEnvConfirmProject: 'Projet Warsha concerné :',
  platformEnvConfirmNoDeploy: 'Cela ne déploie aucun code et ne touche pas la Production.',
  platformEnvConfirmOneWay: 'C’est délibérément à sens unique. Une fois identifié, ce backend ne peut plus être renommé ici.',
  platformEnvConfirmAction: 'Confirmer et identifier',
  platformEnvBound: 'Ce backend est maintenant identifié. Sa bannière d’environnement se mettra à jour au prochain chargement.',
  platformEnvAlreadyBound: 'Ce backend est déjà identifié. Le changement est à sens unique et ne peut pas être répété ici.',
  platformEnvBlocked: 'Ce backend ne peut pas être identifié ici pour le moment, car son état actuel ne correspond pas au changement que cet outil est autorisé à faire. Rien n’a été modifié.',
  platformEnvNoCapability: 'Vous ne disposez pas de la permission nécessaire pour identifier ce backend.',
  platformVerifyHeading: 'Vérification de publication',
  platformVerifyExplain: 'Un contrôle structurel en lecture seule qui vérifie que les garanties de sécurité annoncées par Warsha sont réellement en place : sécurité au niveau des lignes, données privées jamais exposées aux clients, aucune fonctionnalité activée par accident, et règles propres à la Production. Il ne modifie rien.',
  platformVerifyRun: 'Lancer la vérification',
  platformVerifyIdle: 'Pas encore lancée.',
  platformVerifyOutcome: 'Résultat',
  platformVerifyClear: 'Aucun problème inattendu',
  platformVerifyBlocked: 'Problèmes inattendus détectés',
  platformVerifyWhen: 'Vérifié à',
  platformVerifyPassedCount: 'Contrôles réussis',
  platformVerifyUnexpected: 'Problèmes inattendus',
  platformVerifyUnexpectedAction: 'Considérez ceci comme un arrêt. Ne poursuivez pas une publication ; signalez-les à l’ingénierie avec cette page ouverte.',
  platformVerifyExpected: 'Connu et attendu',
  platformVerifyExpectedNote: 'Enregistré comme lacune ouverte dans le registre de préparation au lancement. C’est attendu tant que cette lacune est ouverte et cela ne bloque pas une publication à soi seul.',
  platformVerifyTechnical: 'Détails techniques',
  platformVerifyNoCapability: 'Vous ne disposez pas de la permission nécessaire pour lancer la vérification.',
  consoleEnvironmentFault: 'Environnement non configuré.',
  consoleEnvironmentUnbound: 'Cette console hébergée n’est liée à aucun environnement ; elle ne peut donc pas indiquer s’il s’agit de données de développement ou de production. Un opérateur doit lier l’environnement de la plateforme avant que cette console soit fiable.',
  consoleEnvironmentUnknown: 'Cette console a signalé un environnement qu’elle ne reconnaît pas ; elle ne peut donc pas indiquer s’il s’agit de données de développement ou de production.',
  console_dashboard: 'Tableau de bord',
  console_users: 'Utilisateurs',
  console_verification: 'Vérifications',
  console_analytics: 'Analyses',
  console_staff: 'Personnel',
  console_audit: 'Journal d’audit',
  console_help: 'Aide',

  usersTitle: 'Recherche d’un dossier',
  usersLead: 'Recherchez un dossier par son identifiant exact. Les résultats sont masqués selon les droits de votre rôle et la recherche elle-même est enregistrée.',
  usersSearchLabel: 'Identifiant',
  usersSearchAction: 'Rechercher',
  usersNoQuery: 'Collez un identifiant de dossier exact pour commencer.',
  usersNoResults: 'Aucun dossier ne correspond à cet identifiant.',
  usersRefused: 'Votre rôle ne permet pas cette recherche.',
  usersNotDirectory: 'Il s’agit d’une recherche ciblée, pas d’un annuaire. Les comptes ne peuvent être ni parcourus ni exportés, les caractères génériques sont refusés et seul un identifiant exact renvoie un résultat. Ce comportement est volontaire.',
  usersContactHint: 'Votre rôle permet aussi de rechercher une adresse e-mail vérifiée ou un numéro de téléphone exact.',
  usersNoContactHint: 'Votre rôle peut uniquement utiliser un identifiant de dossier. La recherche par e-mail ou téléphone nécessite l’autorisation d’accéder aux coordonnées.',
  usersKindLabel: 'Type',
  usersKindAll: 'Tous les types',
  usersTooShort: 'Cet identifiant est trop court.',
  usersWildcard: 'Les caractères génériques ne sont pas autorisés. Saisissez un identifiant exact.',
  usersRateLimited: 'Trop de recherches au cours de la dernière minute. Patientez un instant.',
  usersExactOnly: 'Saisissez un identifiant exact. La recherche partielle ou par nom n’est pas disponible.',
  colKind: 'Type', colStatus: 'Statut', colCreated: 'Création', colIdentifier: 'Identifiant', colOpen: 'Ouvrir',

  verificationTitle: 'File des vérifications',
  verificationLead: 'Dossiers professionnels en attente d’une décision, du plus ancien au plus récent. Chaque décision et son motif sont enregistrés.',
  verificationEmpty: 'Aucun dossier en attente d’examen.',
  verificationPseudonymous: 'La file affiche une référence opaque plutôt qu’un nom. L’identité liée au dossier est révélée uniquement à son ouverture avec une autorisation qui journalise cet accès.',
  verificationRefused: 'Votre rôle ne permet pas d’examiner les dossiers professionnels.',
  colSubject: 'Dossier', colWorkerState: 'État', colWaiting: 'Attente', colCertificate: 'Certificat', colPriority: 'Priorité',
  certificateOnFile: 'Disponible', certificateMissing: 'Pas encore fourni', priorityHigh: 'Intervention humaine requise', priorityNormal: 'Normale',
  state_identity_submitted: 'Identité envoyée', state_identity_under_review: 'Identité en cours d’examen',
  state_criminal_record_submitted: 'Certificat envoyé', state_criminal_record_under_review: 'Certificat en cours d’examen',
  state_manual_review: 'Examen manuel', state_appeal_pending: 'Recours en attente',

  staffTitle: 'Accès du personnel',
  staffLead: 'Consultez les rôles, leurs autorisations et leurs titulaires. Toute attribution ou révocation est encadrée : elle exige l’autorisation requise, une authentification récente et laisse une trace d’audit.',
  staffRefused: 'Votre rôle ne permet pas de gérer les accès du personnel.',
  staffRolesHeading: 'Rôles', staffGrantsHeading: 'Titulaires des rôles', staffCapabilitiesHeading: 'Autorisations',
  colRole: 'Rôle', colRiskTier: 'Risque', colCapabilityCount: 'Autorisations', colHolder: 'Titulaire', colGranted: 'Attribué le', colExpires: 'Expiration', colCapability: 'Autorisation', colDomain: 'Domaine',
  grantNoExpiry: 'Sans expiration', grantExpired: 'Expiré', grantActive: 'Actif', flagHighRisk: 'Risque élevé', flagDualControl: 'Deuxième personne', flagReauth: 'Connexion récente',

  auditTitle: 'Journal d’audit',
  auditLead: 'Historique non modifiable de ce qui a été fait, par qui et sur quel objet. Cette page ne permet pas de le modifier.',
  auditFrom: 'Du', auditTo: 'Au', auditSource: 'Source', auditEmpty: 'Aucune entrée pour cette période.', auditRefused: 'Votre rôle ne permet pas de consulter le journal d’audit.',
  auditNoOutcome: 'Chaque ligne représente une action effectuée ; il n’existe pas de colonne distincte de réussite ou d’échec. Les informations supplémentaires enregistrées par chaque source figurent dans Détail.',
  auditRangeTooWide: 'La période doit être limitée à 366 jours.',
  colTime: 'Date et heure', colActor: 'Auteur', colAction: 'Action', colTarget: 'Cible', colDetail: 'Détail',
  source_audit_logs: 'Général', source_staff_audit: 'Actions du personnel', source_trust_moderation: 'Confiance et modération', source_payment_audit: 'Paiements', source_dispute_events: 'Litiges', source_configuration_history: 'Configuration', source_staff_role_history: 'Modifications de rôles', source_support_events: 'Assistance', source_operational_events: 'Opérations',
  pagerPrevious: 'Précédent', pagerNext: 'Suivant', pagerShowing: 'Affichage de {from} à {to}', pagerPage: 'Page {page}',

  reauthTitle: 'Confirmez votre identité',
  reauthBodyPassword: 'Cette action exige une connexion récente. Saisissez votre mot de passe pour continuer.',
  reauthBodyCode: 'Cette action exige une connexion récente. Saisissez le code de votre application d’authentification.',
  reauthPasswordLabel: 'Votre mot de passe', reauthCodeLabel: 'Code d’authentification', reauthConfirm: 'Confirmer',
  reauthPasswordRejected: 'Ce mot de passe n’a pas été accepté.', reauthCodeRejected: 'Ce code n’a pas été accepté.',
  reauthStillStale: 'La connexion n’a pas été actualisée. Déconnectez-vous, puis reconnectez-vous.',
  reauthUnavailable: 'La réauthentification est indisponible pour le moment.',
  reauthDeniedTitle: 'Votre rôle ne permet pas cette action',
  reauthDeniedBody: 'Confirmer votre identité n’y changera rien : aucun de vos rôles ne possède l’autorisation requise.',
  reauthRevokedTitle: 'Cette session a été fermée',
  reauthRevokedBody: 'Votre session a été révoquée. Déconnectez-vous, puis reconnectez-vous pour continuer.',
  reauthRequired: 'Connexion récente requise', reauthFreshFor: 'Identité confirmée pour encore {minutes} min', reauthConfirmNow: 'Confirmer maintenant',

  notificationCategory: 'Catégorie', notificationAllCategories: 'Toutes les catégories',
  category_marketplace: 'Demandes et devis', category_bookings: 'Travaux', category_messages: 'Messages', category_payments: 'Paiements', category_worker_account: 'Compte professionnel', category_reviews: 'Avis', category_disputes: 'Litiges', category_security: 'Sécurité', category_system: 'Système',
  supportRateLimited: 'Vous venez d’ouvrir plusieurs demandes. Patientez avant d’en ouvrir une autre.',
  supportByYou: 'par vous', supportByWarsha: 'par Warsha', supportMessageCount: 'messages', supportReopenedTimes: 'Réouvertures',
  supportReopenNote: 'Cette demande a été résolue. Si le problème persiste, indiquez ce qui ne va toujours pas pour la rouvrir.',
  supportReopenLabel: 'Quel problème persiste ?', supportRateLabel: 'Comment s’est passée cette assistance ?', supportRateComment: 'Souhaitez-vous ajouter quelque chose ? (facultatif)', supportRateSend: 'Envoyer l’évaluation', supportRated: 'Vous avez évalué cette demande',
  supportCaseClosed: 'Cette demande est fermée et ne peut plus recevoir de réponse. Ouvrez-en une nouvelle.', supportNotFound: 'Cette demande est introuvable.', supportTooLong: 'Ce message est trop long. Raccourcissez-le et réessayez.',
  supportReopenExhausted: 'Cette demande a atteint le nombre maximal de réouvertures. Ouvrez-en une nouvelle en mentionnant celle-ci.', supportReopenWindowPassed: 'Le délai de réouverture est dépassé. Ouvrez une nouvelle demande en mentionnant celle-ci.',
  supportAction_opened: 'Ouverture', supportAction_replied: 'Réponse ajoutée', supportAction_status_changed: 'Statut modifié', supportAction_escalated: 'Transmission', supportAction_resolved: 'Résolution', supportAction_closed: 'Fermeture', supportAction_noted: 'Note ajoutée',
  supportCategory_account_access: 'Accès à mon compte', supportCategory_booking_help: 'Un travail', supportCategory_worker_onboarding: 'Inscription comme professionnel', supportCategory_verification_help: 'Vérification', supportCategory_payment_question: 'Un paiement', supportCategory_withdrawal_question: 'Retrait d’argent', supportCategory_technical_issue: 'Problème technique', supportCategory_app_feedback: 'Avis sur l’application', supportCategory_other: 'Autre sujet',
  supportStatus_open: 'Ouverte', supportStatus_in_progress: 'En cours d’examen', supportStatus_waiting_participant: 'En attente de votre réponse', supportStatus_escalated: 'Transmise', supportStatus_resolved: 'Résolue', supportStatus_closed: 'Fermée',

  workerVerificationTitle: 'Vérification', workerActiveBody: 'Votre compte est vérifié et vous pouvez accepter des travaux.', workerNeedsAction: 'Une action est requise', workerRemainingSteps: 'Étapes restantes',
  gateProgress: '{done} étape(s) sur {total} terminée(s)', gateNext: 'Suivant',
  verificationUseApp: 'Les photos de votre pièce d’identité et de votre certificat sont prises dans l’application Warsha avec l’appareil photo du téléphone.',
  verificationNothingToDo: 'Aucune action n’est requise de votre part. Votre dossier est en cours d’examen.', verificationSubmit: 'Envoyer pour examen', verificationSubmitted: 'Dossier envoyé. Il va être examiné.', verificationSubmitFailed: 'Impossible d’envoyer le dossier. Réessayez.',
  verificationAppealTitle: 'Recours', verificationAppealBody: 'Vous pouvez demander à une autre personne d’examiner à nouveau la décision. Les recours se font dans l’application Warsha.',
  gate_worker_role_selected: 'Choisir le compte professionnel', gate_phone_number_provided: 'Ajouter votre numéro de téléphone', gate_worker_agreement_accepted: 'Accepter l’accord professionnel', gate_document_processing_accepted: 'Accepter l’examen des documents', gate_legal_name_complete: 'Ajouter votre nom légal complet', gate_profile_photo: 'Ajouter une photo de profil', gate_professions_configured: 'Choisir vos métiers', gate_services_configured: 'Choisir les services proposés', gate_service_area_configured: 'Définir vos zones d’intervention', gate_current_address_provided: 'Confirmer votre adresse', gate_national_id_front_uploaded: 'Photographier le recto de votre pièce d’identité', gate_national_id_back_uploaded: 'Photographier le verso de votre pièce d’identité', gate_identity_fields_confirmed: 'Confirmer les informations de votre pièce d’identité', gate_criminal_record_uploaded: 'Ajouter votre extrait de casier judiciaire',

  grantTitle: 'Attribuer un rôle',
  grantNotice: 'Vous ne pouvez pas attribuer un rôle à votre propre compte. Chaque attribution et révocation est enregistrée avec son motif, le rôle et le compte concernés.',
  grantSubject: 'Identifiant du compte', grantExpiry: 'Expiration (facultatif)', grantAction: 'Attribuer le rôle', grantDone: 'Rôle attribué.',
  grantDuplicate: 'Cette attribution existait déjà. Aucune modification n’a été apportée.', grantSelfRefused: 'Vous ne pouvez pas attribuer un rôle à votre propre compte.', grantAlreadyActive: 'Ce compte possède déjà ce rôle.', grantUnknownRole: 'Ce rôle n’existe pas.', grantUnknownAccount: 'Aucun compte ne correspond à cet identifiant.', grantReasonRequired: 'Un motif est obligatoire.', grantFailed: 'Impossible de terminer cette opération.',
  reasonLabel: 'Motif', revokeAction: 'Révoquer', revokeConfirm: 'Révoquer le rôle',

  consoleSignInTitle: 'Console Warsha', consoleSignInLead: 'Connectez-vous avec votre compte Warsha. L’accès à la console dépend du rôle attribué à votre compte.', consoleSignInNote: 'L’accès à la console est accordé par un administrateur de la sécurité. Il ne peut pas être demandé ici.',
  forgotPassword: 'Mot de passe oublié ?', forgotTitle: 'Réinitialiser votre mot de passe', forgotLead: 'Saisissez l’adresse e-mail de votre compte. Si un compte lui est associé, nous enverrons un lien permettant de choisir un nouveau mot de passe.', forgotAction: 'M’envoyer un lien',
  forgotSentTitle: 'Consultez votre e-mail', forgotSentBody: 'Si cette adresse correspond à un compte Warsha, un lien de réinitialisation a été envoyé. Il ne fonctionne qu’une fois et expire après une heure.', forgotSentAgain: 'Vous n’avez rien reçu ? Vérifiez les courriers indésirables, puis demandez un nouveau lien.', forgotWorkerNote: 'Les professionnels se connectent avec leur numéro de téléphone. Si c’est votre cas, utilisez l’application Warsha pour réinitialiser le mot de passe.', backToSignIn: 'Retour à la connexion',
  resetTitle: 'Créer un nouveau mot de passe', resetLead: 'Choisissez un mot de passe que vous n’avez encore jamais utilisé sur Warsha.', newPassword: 'Nouveau mot de passe', confirmPassword: 'Confirmer le mot de passe', showPassword: 'Afficher le mot de passe', hidePassword: 'Masquer le mot de passe', revealShow: 'Afficher', revealHide: 'Masquer',
  passwordRequirements: 'Utilisez au moins 8 caractères, dont une majuscule, une minuscule et un chiffre.', passwordLengthRequirement: 'Au moins 8 caractères', passwordUppercaseRequirement: 'Une lettre majuscule', passwordLowercaseRequirement: 'Une lettre minuscule', passwordNumberRequirement: 'Un chiffre', passwordMismatch: 'Les deux mots de passe ne correspondent pas.', updatePassword: 'Mettre à jour le mot de passe', updatingPassword: 'Mise à jour du mot de passe…',
  passwordUpdatedTitle: 'Mot de passe mis à jour', passwordUpdatedBody: 'Toutes les autres sessions ont été fermées. Connectez-vous avec votre nouveau mot de passe.', returnToSignIn: 'Se connecter',
  resetLinkInvalidTitle: 'Ce lien ne peut pas être utilisé', resetLinkInvalidBody: 'Un lien de réinitialisation ne fonctionne qu’une fois et expire après une heure. Celui-ci a expiré, a déjà été utilisé ou a été ouvert dans un autre navigateur que celui ayant fait la demande.', requestNewReset: 'Demander un nouveau lien', errSamePassword: 'Ce mot de passe est déjà le vôtre. Choisissez-en un autre.', errSessionExpired: 'Ce lien de réinitialisation a expiré. Demandez-en un nouveau et réessayez.',
  confirmCheckingTitle: 'Confirmation de votre adresse e-mail', confirmCheckingBody: 'Un instant.', confirmedTitle: 'Adresse e-mail confirmée', confirmedBody: 'Votre compte est prêt. Vous pouvez maintenant décrire le travail dont vous avez besoin.', confirmFailedTitle: 'Ce lien ne peut pas être utilisé', confirmFailedBody: 'Un lien de confirmation ne fonctionne qu’une fois et expire. Connectez-vous pour en recevoir un nouveau ou recréez votre compte.', continueAction: 'Continuer',

  detailCustomer: 'Client', detailWorker: 'Professionnel', detailNoName: 'Aucun nom enregistré', detailAccount: 'Compte', detailCreated: 'Inscription', detailLanguage: 'Langue', detailProductAccess: 'Accès au produit', detailCustomerAccess: 'Client', detailContact: 'Coordonnées', detailEmail: 'Adresse e-mail', detailPhone: 'Numéro de téléphone',
  detailContactWithheld: 'L’accès aux coordonnées exige l’autorisation correspondante. Votre rôle ne la possède pas : ces informations sont donc masquées, et non absentes. Le compte peut avoir un numéro de téléphone et une adresse enregistrés.',
  detailFinancialWithheld: 'L’accès aux revenus exige l’autorisation de consulter le registre financier. Votre rôle ne la possède pas : les montants sont masqués, et non nuls.',
  detailEnforcement: 'Restrictions', detailNoRestrictions: 'Aucune restriction en vigueur.', detailActivity: 'Activité', detailBookings: 'Travaux', detailCompleted: 'Terminés', detailActive: 'En cours', detailCancelled: 'Annulés', detailDisputes: 'Litiges ouverts', detailReportsFiled: 'Signalements déposés', detailReportsAgainst: 'Signalements reçus', detailSupportCases: 'Demandes d’assistance', detailCompletedJobs: 'Travaux terminés', detailTrade: 'Métier', detailOnboarding: 'Intégration', detailPublished: 'Publié', detailAvailable: 'Disponible pour travailler', detailRating: 'Note', detailUserId: 'Compte', detailVerification: 'Vérification', detailSubmitted: 'Envoi', detailReviewed: 'Examen', detailExpires: 'Expiration', detailNotSubmitted: 'Non envoyé', detailCertificateType: 'Certificat', detailNoCertificates: 'Aucun certificat enregistré.', detailEarnings: 'Revenus', detailAvailable2: 'Disponible', detailPending: 'En attente', detailHeld: 'Retenu', detailPaidOut: 'Versé', detailOpenWithdrawals: 'Retraits en cours', detailActiveHolds: 'Retenues actives', detailOpenAudit: 'Afficher ce dossier dans le journal d’audit', detailRefused: 'Votre rôle ne permet pas d’ouvrir ce dossier.', detailNotFound: 'Aucun dossier ne correspond à cet identifiant.', detailFailed: 'Impossible de charger ce dossier.',
  accountStatus_active: 'Actif', accountStatus_deleted: 'Supprimé', trust_good_standing: 'En règle', trust_watch: 'Sous surveillance', trust_restricted: 'Restreint', trust_suspended: 'Suspendu', trust_banned: 'Banni',
  restriction_marketplaceRemoved: 'Retiré de la place de marché', restriction_communicationRestricted: 'Messagerie restreinte', restriction_reviewRestricted: 'Avis restreints', restriction_paymentHold: 'Paiements retenus',
  languageEnglish: 'Anglais', languageArabic: 'Arabe',
  auditSubject: 'Dossier concerné', auditActor: 'Auteur de l’action', auditAnySubject: 'Tous les dossiers', auditAnyActor: 'Tous les auteurs', auditIdentifierIgnored: 'Seul un identifiant de dossier exact filtre le journal. Le texte saisi ci-dessus n’en est pas un ; il est ignoré plutôt qu’interprété.',

  decisionTitle: 'Décision de vérification',
  decisionLead: 'Seules les décisions légalement possibles pour ce dossier sont affichées. Chacune exige sa propre autorisation et est enregistrée avec son motif.',
  decisionNoneAvailable: 'Aucune décision de vérification n’est possible dans l’état actuel du dossier. La prochaine action revient au professionnel ou le dossier est déjà terminé.',
  decisionNeedsCapability: 'Cette décision exige l’autorisation suivante', decisionImpact: 'Conséquence de la décision', decisionMovesTo: 'Nouvel état du dossier',
  decisionLocksRole: 'Empêche le compte de basculer entre les modes client et professionnel, car une décision existe désormais.',
  decisionPublishes: 'Rend le professionnel visible dans la recherche ; l’action est refusée si toutes les conditions d’activation ne sont pas réunies.',
  decisionUnpublishes: 'Retire immédiatement le professionnel des résultats de recherche.', decisionAudited: 'Enregistrée dans le journal d’audit sous',
  decisionWillAskReauth: 'Cette autorisation exige une connexion récente. Vous devrez confirmer votre identité avant l’enregistrement.',
  decisionReasonCode: 'Code du motif', decisionReasonCodeHint: 'Minuscules et traits de soulignement, entre 3 et 61 caractères. Choisissez dans la liste lorsqu’un motif convient afin que les examinateurs décrivent une même situation de façon cohérente.',
  decisionSafeReason: 'Motif affiché au professionnel', decisionSafeReasonHint: 'Le professionnel lira ce texte. Expliquez ce qui s’est passé et ce qu’il peut faire.',
  decisionEvidenceRequired: 'Éléments justificatifs (obligatoires)', decisionEvidenceOptional: 'Éléments justificatifs (facultatifs)', decisionEvidenceHint: 'Le professionnel ne voit jamais ce texte. Une décision défavorable exige au moins ce nombre de caractères :', decisionEvidenceNever: 'Le professionnel ne voit jamais ce texte. Il est conservé avec la décision pour tout examen ultérieur.',
  decisionRecord: 'Enregistrer la décision', decisionRecorded: 'Décision enregistrée :',
  decisionReauth: 'Votre connexion n’est plus assez récente. Confirmez votre identité et réessayez.', decisionDualControl: 'Cette action doit être approuvée par une deuxième personne avant d’être enregistrée.', decisionCapability: 'Votre rôle ne possède pas l’autorisation nécessaire à cette décision.', decisionGates: 'L’activation a été refusée, car toutes les conditions ne sont pas remplies. Les conditions ci-dessus indiquent lesquelles.', decisionInvalidTransition: 'Cette décision n’est pas possible dans l’état actuel du dossier. Actualisez la page et vérifiez son état.', decisionReasonRequired: 'Un motif de 3 à 400 caractères est obligatoire.', decisionEvidenceRequired2: 'Une décision défavorable exige au moins 10 caractères de justification enregistrée.', decisionReportRequired: 'Cette action doit mentionner un signalement ayant fait l’objet d’une enquête.', decisionDuplicate: 'Cette action a déjà été enregistrée. Elle n’a pas été exécutée deux fois.', decisionNotFound: 'Aucun dossier n’existe pour ce compte.', decisionFailed: 'Impossible d’enregistrer cette décision. Aucune modification n’a été apportée.',
  decision_start_identity_review: 'Commencer l’examen de l’identité', decision_start_certificate_review: 'Commencer l’examen du certificat', decision_request_correction: 'Demander des informations supplémentaires', decision_escalate_manual_review: 'Transmettre pour examen manuel', decision_approve: 'Approuver', decision_activate: 'Activer', decision_reject: 'Refuser', decision_suspend: 'Suspendre', decision_reinstate: 'Rétablir',
  state_account_created: 'Compte créé', state_onboarding_incomplete: 'Intégration incomplète', state_identity_required: 'Identité requise', state_correction_required: 'Correction requise', state_criminal_record_required: 'Certificat requis', state_approved: 'Approuvé', state_active: 'Actif', state_rejected: 'Refusé', state_suspended: 'Suspendu',
  tier_full: 'Entièrement activé', tier_provisional: 'Activé provisoirement', tier_none: 'Non autorisé',
  caseTitle: 'Dossier de vérification', caseRefused: 'L’examen d’un dossier professionnel exige l’autorisation correspondante. Votre rôle ne la possède pas.', caseNone: 'Ce compte n’a aucun dossier de vérification professionnelle.', caseActivationGates: 'Conditions d’activation complète', caseProvisionalGates: 'Conditions d’activation provisoire', caseNoGates: 'Aucune condition enregistrée.', caseFieldsConfirmed: 'Informations confirmées par le professionnel', caseCertificate: 'Extrait de casier judiciaire', caseDocument: 'Document', caseCapture: 'Capture', caseSide: 'Côté', caseNoDocuments: 'Aucun document envoyé.', caseOcrNote: 'L’extraction automatisée est exécutée. Warsha enregistre qu’elle a eu lieu et son résultat, jamais un score de confiance ni une valeur extraite : le document lui-même constitue la preuve et sa lecture relève de l’examinateur.', caseOutcome: 'Résultat', caseFields: 'Champs',

  enforcementTitle: 'Mesures de restriction', enforcementLead: 'L’historique des mesures est immuable : aucun élément ne peut être modifié ni retiré. Une annulation par le serveur prend la forme d’une nouvelle action de type Rétablissement.', enforcementRecord: 'Enregistrer la mesure', enforcementRecorded: 'Mesure enregistrée :', enforcementImmutable: 'Cette mesure est permanente. L’historique ne peut être ni modifié ni supprimé, seulement complété.', enforcementPublicSeen: 'Le motif public est affiché à la personne concernée. Les éléments justificatifs ne le sont pas.', enforcementDualControl: 'Une deuxième personne doit l’approuver avant son entrée en vigueur.', enforcementNoExpiry: 'Cette mesure n’expire jamais et doit citer un signalement examiné.', enforcementRestorationNote: 'Le rétablissement annule les effets d’une mesure antérieure, mais celle-ci reste dans l’historique.', enforcementChooseReason: 'Choisir un motif', enforcementReasonHint: 'Liste fermée : la base de données accepte uniquement ces motifs et refuse les autres.', enforcementPublicReason: 'Motif affiché à la personne', enforcementPublicReasonHint: 'Entre 3 et 300 caractères. Ce texte sera communiqué à la personne.', enforcementEvidence: 'Résumé des éléments justificatifs', enforcementEvidenceHint: 'Entre 3 et 2 000 caractères, jamais affiché à la personne. Chaque mesure exige une justification : c’est le contrat d’audit.', enforcementReport: 'Signalement examiné', enforcementReportHint: 'Un bannissement permanent doit citer le signalement qui a été examiné. La base de données refuse l’action sans cette référence.', enforcementReportRequired: 'Un bannissement permanent doit citer un signalement examiné. Ajoutez son identifiant et réessayez.', enforcementExpires: 'Expiration (facultatif)', enforcementExpiresHint: 'Laissez vide pour une mesure sans date de fin. Un bannissement permanent ne peut jamais en avoir.',
  enforcement_warning: 'Avertissement', enforcement_temporary_restriction: 'Restriction temporaire', enforcement_investigation: 'Enquête', enforcement_suspension: 'Suspension', enforcement_permanent_ban: 'Bannissement permanent', enforcement_marketplace_removal: 'Retirer de la place de marché', enforcement_profile_hidden: 'Masquer le profil', enforcement_payment_hold: 'Retenir les paiements', enforcement_withdrawal_hold: 'Bloquer les retraits', enforcement_communication_restriction: 'Restreindre la messagerie', enforcement_review_restriction: 'Restreindre les avis', enforcement_restoration: 'Rétablir',
  reason_fraud: 'Fraude', reason_impersonation: 'Usurpation d’identité', reason_abusive_language: 'Propos injurieux', reason_harassment: 'Harcèlement', reason_discrimination: 'Discrimination', reason_fake_profile: 'Faux profil', reason_fake_documents: 'Faux documents', reason_fake_certificates: 'Faux certificats', reason_spam: 'Contenu indésirable', reason_scam: 'Escroquerie', reason_dangerous_behavior: 'Comportement dangereux', reason_off_platform_payment: 'Paiement effectué hors de Warsha', reason_off_platform_contact: 'Prise de contact hors de Warsha', reason_illegal_activity: 'Activité illégale', reason_inappropriate_content: 'Contenu inapproprié', reason_copyright: 'Droits d’auteur', reason_privacy: 'Confidentialité', reason_repeated_violations: 'Infractions répétées', reason_appeal_upheld: 'Recours confirmé', reason_appeal_overturned: 'Décision annulée après recours', reason_investigation_closed: 'Enquête clôturée',
  saveChanges: 'Enregistrer les modifications', editAction: 'Modifier', deleteAction: 'Supprimer',

  discoverTitle: 'Trouver un professionnel', discoverLead: 'Choisissez le type de travail et décrivez votre besoin. Les professionnels couvrant votre zone vous envoient leur prix, puis vous choisissez.', discoverCategories: 'Quel travail faut-il réaliser ?', discoverSearch: 'Rechercher', discoverSearchHint: 'Électricité, plomberie, climatisation…', discoverSearchAction: 'Rechercher des professionnels', discoverNoWorkersMatch: 'Aucun professionnel ne correspond à cette recherche.', discoverAskWorker: 'Demander à ce professionnel', discoverNoCategories: 'Aucun résultat.', discoverAvailable: 'Disponibles maintenant', discoverNoneAvailable: 'Aucun professionnel n’est indiqué comme disponible pour le moment.', discoverTrusted: 'Expérience confirmée', discoverNoneTrusted: 'Aucun professionnel n’a encore de travail terminé.', discoverSaved: 'Enregistrés', discoverNoneSaved: 'Vous n’avez encore enregistré aucun professionnel.', discoverRecent: 'Consultés récemment', discoverNoneRecent: 'Aucune consultation récente.', discoverReviews: 'avis', discoverNoRating: 'Pas encore noté', discoverJobsDone: 'travaux terminés', discoverIdentityVerified: 'Identité vérifiée', discoverSkillVerified: 'Compétence certifiée', discoverCertificateVerified: 'Certificat professionnel', discoverEmergency: 'Urgences', discoverAvailableNow: 'Disponible', discoverNoMapNote: 'Warsha n’affiche pas la position d’un professionnel sur une carte. Les professionnels indiquent leurs zones d’intervention ; l’adresse exacte est communiquée uniquement lorsqu’un travail est convenu.',

  requestsTitle: 'Vos demandes', requestsLead: 'Une demande sollicite les professionnels couvrant votre zone pour connaître leur prix. Aucun travail n’est réservé avant votre choix.', requestsNew: 'Demander des devis', requestsYours: 'Demandes', requestsNone: 'Vous n’avez encore envoyé aucune demande.', requestsSeeAll: 'Voir vos demandes', requestDetail: 'Demande', requestQuoteCount: 'devis', requestArea: 'Zone', requestExpires: 'Fin des devis', requestConfirmBy: 'À confirmer avant', requestRecovery: 'Vous pouvez maintenant :', requestSortBy: 'Trier les devis par', requestNoQuotes: 'Aucun devis pour le moment. Les professionnels couvrant votre zone sont en train d’être sollicités.', requestCancel: 'Annuler cette demande',
  requestNewTitle: 'Décrivez le travail', requestNewLead: 'Plus votre description est précise, plus les devis seront proches du prix réel.', requestCategory: 'Type de travail', requestChooseCategory: 'Choisissez une option', requestService: 'Service précis (facultatif)', requestAnyService: 'Tout service de cette catégorie', requestTargetedWorker: 'Cette demande sera envoyée au professionnel choisi. Les mêmes règles de marché et de confidentialité continuent de s’appliquer.', requestIssue: 'Que faut-il faire ?', requestIssueHint: 'Au moins 8 caractères. Expliquez le problème, son emplacement et ce qu’un professionnel doit savoir avant d’établir son devis.', requestNotes: 'Autres informations (facultatif)', requestNotesHint: 'Accès, stationnement, code de portail ou horaires de présence.', requestAddress: 'Lieu', requestAddressHint: 'Pendant la phase de devis, les professionnels voient uniquement votre gouvernorat et votre quartier. L’adresse exacte est communiquée après votre choix.', requestChooseAddress: 'Choisissez une adresse vérifiée', requestAddVerifiedAddress: 'Ajoutez d’abord une adresse vérifiée', requestWhen: 'Quand ?', requestStart: 'À partir de', requestEnd: 'Jusqu’à', requestFutureTime: 'Choisissez une heure à venir.', requestEndAfterStart: 'L’heure de fin doit être postérieure à l’heure de début.', requestSend: 'Demander des devis',
  requestSentTitle: 'Votre demande a été envoyée', requestSentBody: 'Les professionnels couvrant votre zone sont sollicités. Les devis apparaîtront dans la demande à mesure qu’ils arrivent.', requestRateLimited: 'Vous avez envoyé plusieurs demandes au cours de la dernière heure. Patientez avant d’en envoyer une autre.', requestUnavailable: 'Ce type de travail n’est pas encore disponible dans votre zone.', requestInvalid: 'Certaines informations de cette demande n’ont pas été acceptées. Vérifiez la description et les horaires.', requestStale: 'Cette demande a changé pendant votre consultation. Elle a été actualisée ; vérifiez-la avant de choisir à nouveau.', requestExpired: 'Cette demande a expiré.', requestNotFound: 'Cette demande est introuvable.', requestFailed: 'Impossible d’envoyer cette demande. Aucune modification n’a été apportée.',
  requestStatus_collecting_quotes: 'Réception des devis', requestStatus_matching: 'Recherche de professionnels', requestStatus_quoted: 'Devis reçus', requestStatus_selected: 'Professionnel choisi', requestStatus_converted_to_booking: 'Travail réservé', requestStatus_cancelled: 'Annulée', requestStatus_expired: 'Expirée', requestStatus_closed: 'Fermée',
  schedule_asap: 'Dès que possible', schedule_today: 'Aujourd’hui', schedule_scheduled: 'À une heure précise', schedule_flexible: 'À tout moment dans une plage horaire',
  sort_best_value: 'Meilleur rapport qualité-prix', sort_lowest_price: 'Prix le plus bas', sort_highest_rated: 'Mieux notés', sort_closest: 'Plus proches', sort_fastest_arrival: 'Arrivée la plus rapide', sort_most_experienced: 'Plus expérimentés',
  recovery_retry: 'envoyer une nouvelle demande', recovery_expand: 'élargir la zone', recovery_schedule: 'choisir un autre horaire', recovery_browse_workers: 'choisir vous-même un professionnel',
  quoteMaterials: 'Matériaux', quoteLabour: 'Main-d’œuvre comprise', quoteWarranty: 'Garantie', quoteEta: 'Peut arriver dans', quoteDays: 'jours', quoteMinutes: 'minutes', quoteAccept: 'Accepter ce devis', quoteChosen: 'Vous avez choisi ce devis.', quoteWaitingForWorker: 'Vous avez choisi ce devis. Le professionnel doit maintenant le confirmer avant qu’il ne devienne un travail réservé.',
  materials_included: 'Inclus dans le prix', materials_excluded: 'Non inclus', materials_estimated: 'Estimation séparée', payment_cash: 'Espèces', payment_online: 'Carte bancaire',

  jobsTitle: 'Vos travaux', jobsLead: 'Les travaux en cours et ceux qui sont terminés.', jobsActive: 'En cours', jobsNoneActive: 'Aucun travail en cours.', jobsPast: 'Terminés', jobsNonePast: 'Aucun travail terminé pour le moment.', jobsAddress: 'Lieu', jobsEstimate: 'Estimation', jobsFinalPrice: 'Prix final', jobsDetail: 'Détails du travail', jobsProposedTime: 'Le professionnel a proposé un autre horaire', jobsAcceptTime: 'Accepter cet horaire', jobsRejectTime: 'Refuser cet horaire', jobsReschedule: 'Modifier la date ou l’heure', jobsNewDate: 'Nouvelle date', jobsNewTime: 'Nouvelle heure', jobsSaveTime: 'Enregistrer le nouvel horaire', jobsCancelReason: 'Pourquoi annulez-vous ?', jobsCancel: 'Annuler ce travail', jobsTimeline: 'Historique', jobsNoTimeline: 'Aucun événement dans l’historique.', jobsActionFailed: 'Impossible de mettre ce travail à jour. Son état actuel n’a été ni deviné ni remplacé.',
  cancelReason_plans_changed: 'Mes projets ont changé', cancelReason_booked_by_mistake: 'Réservé par erreur', cancelReason_provider_delay: 'Retard du professionnel', cancelReason_price_concern: 'Problème de prix', cancelReason_other: 'Autre motif',
  bookingStatus_draft: 'Brouillon', bookingStatus_pending_provider_approval: 'En attente du professionnel', bookingStatus_accepted: 'Accepté', bookingStatus_rejected: 'Refusé', bookingStatus_rescheduling_requested: 'Modification d’horaire demandée', bookingStatus_confirmed: 'Confirmé', bookingStatus_provider_on_the_way: 'En route', bookingStatus_provider_arrived: 'Arrivé', bookingStatus_job_started: 'Commencé', bookingStatus_awaiting_quote_approval: 'En attente de votre accord', bookingStatus_work_in_progress: 'En cours', bookingStatus_awaiting_customer_confirmation: 'En attente de votre confirmation', bookingStatus_completed: 'Terminé', bookingStatus_cancelled: 'Annulé', bookingStatus_disputed: 'En litige', bookingStatus_refunded: 'Remboursé', bookingStatus_no_show: 'Absence constatée',
  cancel: 'Annuler', close: 'Fermer', resultKind: 'Type', resultLabel: 'Résultat', tableEmpty: 'Aucun élément à afficher.',
} as const;
