import type { AppWords } from './app-copy.ts';

/**
 * The rules around enrolling a staff authenticator, kept out of the component.
 *
 * Warsha owns none of the cryptography here and must not. The secret is
 * generated by Supabase Auth, inside the staff member's own authenticated
 * browser session, and this module never sees it except to format it for
 * someone typing it by hand. There is no Warsha TOTP implementation, no seed in
 * a database column, and no server round trip that could carry one.
 *
 * The important consequence of using `supabase.auth.mfa.enroll` is one it is
 * easy to miss: IT TAKES NO ACCOUNT PARAMETER. It enrols a factor on the
 * session that calls it and there is no shape of argument that points it at
 * somebody else. That is why "one administrator cannot enrol MFA for another"
 * is a property of the API rather than a check this file performs — a check
 * could be removed, and this cannot be expressed at all.
 */

export const STAFF_FACTOR_NAME = 'Warsha staff authenticator';

/**
 * What the account is allowed to do right now.
 *
 * `email-unconfirmed` is a refusal, not a warning. A factor enrolled against an
 * address nobody has proved they hold turns a possible email compromise into a
 * permanent second factor, and recovery from that needs the database owner.
 */
export type EnrolmentGate =
  | 'ready'
  | 'no-account'
  | 'email-unconfirmed'
  | 'already-enrolled';

export type AccountFacts = {
  email: string | null;
  emailConfirmedAt: string | null;
};

export function enrolmentGate(
  account: AccountFacts | null,
  verifiedFactorCount: number,
): EnrolmentGate {
  if (!account || !account.email) return 'no-account';
  if (!account.emailConfirmedAt) return 'email-unconfirmed';
  if (verifiedFactorCount > 0) return 'already-enrolled';
  return 'ready';
}

/**
 * The manual key in groups of four.
 *
 * The QR code is the easy path and the fallback is the one that has to work:
 * somebody using a screen reader, a desktop authenticator with no camera, or a
 * phone that cannot photograph its own screen. Base32 read as one 32-character
 * run is unusable by voice and error-prone by hand; in fours it is neither.
 */
export function manualKeyGroups(secret: string): readonly string[] {
  const cleaned = secret.replace(/\s+/g, '').toUpperCase();
  const groups: string[] = [];
  for (let index = 0; index < cleaned.length; index += 4) {
    groups.push(cleaned.slice(index, index + 4));
  }
  return groups;
}

/** A six-digit code, whatever spacing the authenticator app displayed. */
export function codeLooksComplete(code: string): boolean {
  return /^\d{6}$/.test(code.replace(/\s+/g, ''));
}

export function normalizeCode(code: string): string {
  return code.replace(/\s+/g, '');
}

/**
 * Enrolment is only finished when the session it produced is actually `aal2`.
 *
 * Verifying a factor and HOLDING a second-factor session are different claims,
 * and the second is the one every staff gate reads. Asking the identity
 * provider closes the gap between "the code was accepted" and "this session now
 * satisfies `private.staff_mfa_satisfied()`".
 */
export function reachedAal2(level: string | null | undefined): boolean {
  return level === 'aal2';
}

/**
 * Every failure the screen can show, as a fixed message.
 *
 * Provider error text is deliberately NOT rendered anywhere in this flow. It
 * can quote the request that produced it, and the request during enrolment
 * carries the seed. A fixed set of sentences cannot leak something it never
 * interpolates.
 */
export type EnrolmentFailure =
  | 'start'
  | 'code-rejected'
  | 'not-aal2'
  | 'unavailable';

export function failureMessage(failure: EnrolmentFailure, words: AppWords): string {
  switch (failure) {
    case 'start': return words.mfaEnrolFailed;
    case 'code-rejected': return words.mfaCodeRejected;
    case 'not-aal2': return words.mfaNotElevated;
    default: return words.mfaUnavailable;
  }
}
