/** Worker product presentation for the unprefixed EN/AR application. */
const baseWorkerCopy = {
  en: {
    onboardingTitle: 'Set up your work account',
    onboardingLead: 'Finish one clear step at a time. Warsha will tell you when the next step belongs to a reviewer.',
    onboardingStep: 'Step {current} of {total}',
    onboardingAgreementTitle: 'Start your application',
    onboardingAgreementBody: 'Accept the worker agreement and allow Warsha to process the identity documents you submit for verification.',
    onboardingAccept: 'Accept and continue',
    onboardingProfileTitle: 'Tell customers about you',
    onboardingProfileBody: 'Your name and photo are public on your worker profile. An introduction and experience are optional.',
    onboardingPhotoRequired: 'Choose a clear profile photo. Warsha stores it in the same protected worker bucket used by the app.',
    onboardingTradesTitle: 'Select your profession',
    onboardingTradesBody: 'Choose the kind of work you do, then the specific jobs you can take.',
    onboardingAreaTitle: 'Where can you work?',
    onboardingAreaBody: 'Choose your governorate and area. Your exact work location stays private and is used only for matching.',
    onboardingLocationRequired: 'Confirm your private work location after saving this area.',
    onboardingIdentityTitle: 'Verify your identity',
    onboardingIdentityBody: 'ID, selfie and criminal-record evidence use the guided capture flow in the Warsha app. Sensitive evidence is not accepted through this browser form.',
    onboardingReviewTitle: 'Your application is being reviewed',
    onboardingReviewBody: 'There is nothing to guess or resubmit unless Warsha asks you for a correction.',
    workerName: 'Public name',
    workerAbout: 'Short introduction (optional)',
    workerExperience: 'Years of experience (optional)',
    workerProfession: 'Your profession',
    workerProfessionBody: 'Choose the kind of work you do.',
    workerServices: 'Services you offer',
    workerServicesBody: 'Choose the specific jobs you can take.',
    workerChooseProfessionFirst: 'Choose your profession first, then pick the jobs you can take.',
    workerSelectAllServices: 'Select every job in this trade',
    workerNoServicesChosen: 'No jobs chosen yet',
    workerServicesSelected: '{count} jobs selected',
    workerOneServiceSelected: '1 job selected',
    workerNoServicesAvailable: 'Warsha has no jobs listed for this trade yet.',
    workerProfessionRequired: 'Select at least one profession.',
    workerServiceRequired: 'Choose at least one job you can take.',
    workerProfessionWithdrawn: 'Warsha no longer offers this trade. Choose the one that matches your work.',
    workerServiceOutsideProfession: 'Some chosen jobs do not belong to your professions. Open each trade and check the list.',
    workerProfileIncomplete: 'Some profile details are missing. Check your name, photo and years of experience.',
    workerAreaInvalid: 'Check the governorate and area you chose.',
    workerWithdrawnProfessionNotice: 'Your account still records a trade Warsha no longer offers. Choose the concrete trade that matches your work.',
    workerHistoricalServicesTitle: 'Previously offered services',
    workerHistoricalServicesBody: 'These saved services remain on your profile. Choose a current profession to review which jobs you can still offer.',
    workerGovernorate: 'Governorate',
    workerArea: 'Area',
    workerSaveDraft: 'Save and continue',
    workerProfileTitle: 'Your worker profile',
    workerProfileLead: 'The information customers see and the work Warsha can match to you.',
    workerProfileSaved: 'Your worker profile was saved.',
    workerPhotoSaved: 'Photo saved',
    workerProfileFailed: 'Your worker profile could not be saved. Nothing was changed locally.',
    loading: 'Loading…',
    retry: 'Try again',
    workerAvailability: 'Availability',
    workerAvailable: 'Available for new work',
    workerUnavailable: 'Not taking new work',
    workerAvailabilityHelp: 'Only an active, approved worker can become publicly discoverable. The server enforces that rule.',
    workerGoAvailable: 'Go available',
    workerGoUnavailable: 'Pause new work',
    workerPortfolioMobile: 'Portfolio media and professional certificates continue in the Warsha app. Existing protected-upload rules remain in force.',
    workLocationUseCurrent: 'Use my current location',
    workLocationSearch: 'Search for an address',
    workLocationSearchPlaceholder: 'Type a street, building, or place',
    workLocationSearchAction: 'Search',
    workLocationSearchUnavailable: 'Address search is unavailable right now. You can still use your current location.',
    workLocationSearchNone: 'No matching address was found. Try a more specific search.',
    workLocationSearchFailed: 'Address search could not be reached. Try again or use your current location.',
    workLocationSearching: 'Searching…',
    workLocationLocating: 'Locating…',
    workLocationResolving: 'Resolving address…',
    workLocationSaved: 'Address found',
    workLocationPartial: 'Location found. Review the address before continuing.',
    workLocationLookupFailed: 'Location obtained, but the address could not be looked up. You can still continue with your selected work area.',
    workLocationPermissionDenied: 'Location permission was denied. Allow it in your browser, or search for the address.',
    workLocationUnavailable: 'Your browser could not provide a location. Search for the address or try again.',
    workLocationTimeout: 'Getting your location took too long. Try again or search for the address.',
    workLocationFailed: 'We could not get that location. Try another option.',
    workLocationContinue: 'Continue',
    workLocationAreaFailed: 'Unable to load the saved work area.',

    opportunitiesTitle: 'Opportunities',
    opportunitiesLead: 'Requests matched to your approved services and work areas. Exact customer addresses stay hidden until a job is agreed.',
    opportunitiesNone: 'No matched requests right now.',
    opportunitiesActive: 'Active opportunities',
    opportunitiesHistory: 'Opportunity history',
    opportunitiesCount: '{count} opportunities available',
    opportunityDetail: 'Request details',
    opportunityExpires: 'Respond by',
    opportunityArea: 'Approximate area',
    opportunityPayment: 'Customer payment preference',
    opportunityQuote: 'Send a quote',
    opportunityRevise: 'Revise quote',
    opportunityWithdraw: 'Withdraw quote',
    opportunityDecline: 'Decline request',
    opportunityConfirm: 'Confirm selected quote',
    opportunityEmergencyAccept: 'Accept emergency request',
    opportunityPrice: 'Your price (EGP)',
    opportunityDuration: 'Estimated job time (minutes)',
    opportunityEta: 'Arrival estimate (minutes, optional)',
    opportunityMessage: 'Message to the customer (optional)',
    opportunityMaterials: 'Materials',
    opportunityMaterialsIncluded: 'Included',
    opportunityMaterialsExcluded: 'Not included',
    opportunityMaterialsPartial: 'Partly included',
    opportunityMaterialsUnknown: 'To be agreed',
    opportunityMaterialsExplanation: 'Materials detail (optional)',
    opportunityLabour: 'Labour is included',
    opportunityCash: 'Cash',
    opportunityOnline: 'Online payment',
    opportunityPaymentEither: 'Cash or online payment',
    opportunityRevisionReason: 'Why the quote changed',
    opportunityReason: 'Reason',
    opportunityActionFailed: 'That action is no longer available or could not be completed. Reload the request before trying again.',
    opportunityActionDone: 'The request was updated.',
    opportunityQuoteHistory: 'Quote history',
    invitationStatus_invited: 'New',
    invitationStatus_viewed: 'Viewed',
    invitationStatus_quoted: 'Quoted',
    invitationStatus_declined: 'Declined',
    invitationStatus_withdrawn: 'Withdrawn',
    invitationStatus_expired: 'Expired',
    invitationStatus_request_closed: 'Closed',
    invitationStatus_accepted: 'Accepted',
    quoteStatus_submitted: 'Submitted',
    quoteStatus_revised: 'Revised',
    quoteStatus_selected: 'Selected',
    quoteStatus_rejected: 'Not selected',
    quoteStatus_withdrawn: 'Withdrawn',
    quoteStatus_expired: 'Expired',
    quoteStatus_invalidated_by_request_change: 'Request changed',

    workerJobsTitle: 'My jobs',
    workerJobsLead: 'Accept new bookings, follow the required sequence, and keep the customer informed.',
    workerJobsActive: 'Current work',
    workerJobsPast: 'History',
    workerJobsNoneActive: 'No current jobs.',
    workerJobsNonePast: 'No finished jobs yet.',
    workerJobsCount: '{count} active jobs',
    workerJobCustomer: 'Customer',
    workerJobAddress: 'Job address',
    workerJobPrice: 'Price',
    workerJobAccept: 'Accept job',
    workerJobReject: 'Decline job',
    workerJobRejectReason: 'Why you cannot take it',
    workerJobReschedule: 'Propose another time',
    workerJobDate: 'New date',
    workerJobTime: 'New time',
    workerJobNote: 'Explain the change',
    workerJobNext: 'Move to: {status}',
    workerJobCompleteNote: 'Completion note (optional)',
    workerJobDispute: 'Report a problem',
    workerJobNoShow: 'Report customer no-show',
    workerJobTimeline: 'Timeline',
    workerJobActionFailed: 'The job could not be updated. Its current server state is unchanged.',

    earningsTitle: 'Earnings',
    earningsLead: 'Balances and transactions come directly from Warsha’s financial ledger.',
    earningsAvailable: 'Available',
    earningsPending: 'Pending',
    earningsPaid: 'Paid out',
    earningsHeld: 'Held',
    earningsCashDebt: 'Cash commission due',
    earningsRecovery: 'Adjustments due',
    earningsTransactions: 'Transactions',
    earningsNone: 'No earnings transactions yet.',
    earningsWithdrawals: 'Withdraw earnings',
    earningsWithdrawalUnavailable: 'Withdrawals are not enabled in this environment. Your ledger remains visible.',
    earningsMinimum: 'Minimum',
    earningsDestination: 'Payout destination',
    earningsNoDestination: 'Add a payout destination before requesting a withdrawal.',
    earningsAddDestination: 'Add payout destination',
    earningsDestinationType: 'Destination type',
    earningsMobileWallet: 'Mobile wallet',
    earningsBankAccount: 'Bank account',
    earningsDestinationLabel: 'Destination name',
    earningsDestinationValue: 'Account or wallet value',
    earningsOwnership: 'I confirm this destination belongs to me',
    earningsAmount: 'Amount (EGP)',
    earningsRequestWithdrawal: 'Request withdrawal',
    earningsWithdrawalsHistory: 'Withdrawal history',
    earningsActionFailed: 'That payout action could not be completed.',
    earningsActionDone: 'Your payout request was recorded.',
    earningStatus_pending_job_completion: 'Waiting for job completion',
    earningStatus_pending_release: 'Pending release',
    earningStatus_available: 'Available',
    earningStatus_withdrawal_requested: 'Withdrawal requested',
    earningStatus_paid_out: 'Paid out',
    earningStatus_reversed: 'Reversed',
    earningStatus_held_for_dispute: 'Held for review',
    withdrawalStatus_requested: 'Requested',
    withdrawalStatus_under_review: 'Under review',
    withdrawalStatus_processing: 'Processing',
    withdrawalStatus_paid: 'Paid',
    withdrawalStatus_failed: 'Failed',
    withdrawalStatus_cancelled: 'Cancelled',
    withdrawalStatus_reversed: 'Reversed',
  },
  ar: {
    onboardingTitle: 'جهّز حساب شغلك',
    onboardingLead: 'خلّص خطوة واضحة كل مرة. ورشة هتقولك لما الخطوة الجاية تكون عند المراجع.',
    onboardingStep: 'الخطوة {current} من {total}',
    onboardingAgreementTitle: 'ابدأ طلبك',
    onboardingAgreementBody: 'وافق على اتفاق الصنايعي واسمح لورشة بمعالجة مستندات الهوية اللي هتقدمها للتحقق.',
    onboardingAccept: 'وافق وكمّل',
    onboardingProfileTitle: 'عرّف العملاء بيك',
    onboardingProfileBody: 'اسمك وصورتك بيظهروا في ملف الصنايعي. النبذة وسنين الخبرة اختياريين.',
    onboardingPhotoRequired: 'اختار صورة واضحة لملفك. ورشة بتحفظها في نفس مساحة الصنايعي المحمية اللي بيستخدمها التطبيق.',
    onboardingTradesTitle: 'اختار مهنتك',
    onboardingTradesBody: 'اختار نوع الشغل اللي بتعمله، وبعدها الشغلانات اللي تقدر تستلمها.',
    onboardingAreaTitle: 'بتشتغل فين؟',
    onboardingAreaBody: 'اختار المحافظة والمنطقة. مكان شغلك بالتفصيل يفضل خاص وبيستخدم بس للمطابقة.',
    onboardingLocationRequired: 'أكد مكان شغلك الخاص بعد حفظ المنطقة دي.',
    onboardingIdentityTitle: 'اتحقق من هويتك',
    onboardingIdentityBody: 'صور البطاقة والسيلفي والفيش بتستخدم مسار التصوير الموجّه في تطبيق ورشة. المستندات الحساسة مش بتترفع من نموذج المتصفح ده.',
    onboardingReviewTitle: 'طلبك بيتراجع',
    onboardingReviewBody: 'مش مطلوب منك تخمّن أو تعيد حاجة إلا لو ورشة طلبت تصحيح.',
    workerName: 'الاسم الظاهر للعملاء',
    workerAbout: 'نبذة قصيرة (اختياري)',
    workerExperience: 'سنين الخبرة (اختياري)',
    workerProfession: 'مهنتك',
    workerProfessionBody: 'اختار نوع الشغل اللي بتعمله.',
    workerServices: 'الخدمات اللي بتقدمها',
    workerServicesBody: 'اختار الشغلانات اللي تقدر تستلمها.',
    workerChooseProfessionFirst: 'اختار مهنتك الأول، وبعدها اختار الشغلانات اللي تقدر تستلمها.',
    workerSelectAllServices: 'اختار كل شغلانات المهنة دي',
    workerNoServicesChosen: 'لسه ما اخترتش شغلانات',
    workerServicesSelected: '{count} شغلانات مختارة',
    workerOneServiceSelected: 'شغلانة واحدة مختارة',
    workerNoServicesAvailable: 'ورشة لسه ما عندهاش شغلانات للمهنة دي.',
    workerProfessionRequired: 'اختار مهنة واحدة على الأقل.',
    workerServiceRequired: 'اختار شغلانة واحدة على الأقل تقدر تستلمها.',
    workerProfessionWithdrawn: 'ورشة ما بقتش بتقدم المهنة دي. اختار المهنة اللي بتوصف شغلك.',
    workerServiceOutsideProfession: 'في شغلانات مختارة مش تابعة لمهنك. افتح كل مهنة وراجع القايمة.',
    workerProfileIncomplete: 'في بيانات ناقصة في ملفك. راجع اسمك وصورتك وسنين الخبرة.',
    workerAreaInvalid: 'راجع المحافظة والمنطقة اللي اخترتهم.',
    workerWithdrawnProfessionNotice: 'حسابك لسه مسجّل عليه مهنة ورشة ما بقتش بتقدمها. اختار المهنة المحددة اللي بتوصف شغلك.',
    workerHistoricalServicesTitle: 'خدمات كنت بتقدمها قبل كده',
    workerHistoricalServicesBody: 'الخدمات المحفوظة دي لسه في ملفك. اختار مهنة حالية علشان تراجع الشغلانات اللي تقدر تفضل تقدمها.',
    workerGovernorate: 'المحافظة',
    workerArea: 'المنطقة',
    workerSaveDraft: 'احفظ وكمّل',
    workerProfileTitle: 'ملفك كصنايعي',
    workerProfileLead: 'المعلومات اللي بيشوفها العملاء والشغل اللي ورشة تقدر تطابقه معاك.',
    workerProfileSaved: 'ملف الصنايعي اتحفظ.',
    workerPhotoSaved: 'الصورة اتحفظت',
    workerProfileFailed: 'ما قدرناش نحفظ ملف الصنايعي. مفيش حاجة اتغيرت محليًا.',
    loading: 'بيحمّل…',
    retry: 'جرّب تاني',
    workerAvailability: 'التوفر',
    workerAvailable: 'متاح لشغل جديد',
    workerUnavailable: 'مش بستقبل شغل جديد',
    workerAvailabilityHelp: 'بس الصنايعي النشط والمقبول يقدر يظهر للعملاء. السيرفر هو اللي بيفرض القاعدة دي.',
    workerGoAvailable: 'خلّيني متاح',
    workerGoUnavailable: 'وقف الشغل الجديد',
    workerPortfolioMobile: 'صور أعمالك وشهاداتك المهنية بتكمل من تطبيق ورشة. قواعد الرفع المحمي الحالية لسه سارية.',
    workLocationUseCurrent: 'استخدم موقعي الحالي',
    workLocationSearch: 'دور على عنوان',
    workLocationSearchPlaceholder: 'اكتب شارع أو مبنى أو مكان',
    workLocationSearchAction: 'دور',
    workLocationSearchUnavailable: 'بحث العناوين مش متاح دلوقتي. تقدر تستخدم موقعك الحالي.',
    workLocationSearchNone: 'مالقيناش عنوان مطابق. جرّب تكتب تفاصيل أكتر.',
    workLocationSearchFailed: 'ما قدرناش نوصل لبحث العناوين. حاول تاني أو استخدم موقعك الحالي.',
    workLocationSearching: 'بندور…',
    workLocationLocating: 'بنحدد موقعك…',
    workLocationResolving: 'بنجيب العنوان…',
    workLocationSaved: 'لقينا العنوان',
    workLocationPartial: 'لقينا الموقع. راجع العنوان قبل ما تكمّل.',
    workLocationLookupFailed: 'حددنا الموقع، لكن ما قدرناش نجيب العنوان. تقدر تكمّل بمنطقة الشغل اللي اخترتها.',
    workLocationPermissionDenied: 'إذن الموقع اترفض. اسمح بيه من المتصفح، أو دوّر على العنوان.',
    workLocationUnavailable: 'المتصفح ما قدرش يحدد موقعك. دوّر على العنوان أو حاول تاني.',
    workLocationTimeout: 'تحديد موقعك أخد وقت طويل. حاول تاني أو دوّر على العنوان.',
    workLocationFailed: 'ما قدرناش نجيب الموقع ده. جرّب طريقة تانية.',
    workLocationContinue: 'كمّل',
    workLocationAreaFailed: 'ما قدرناش نحمّل منطقة الشغل المحفوظة.',

    opportunitiesTitle: 'الفرص',
    opportunitiesLead: 'طلبات مناسبة لخدماتك ومناطق شغلك المقبولة. عنوان العميل بالتفصيل يفضل مخفي لحد ما تتفقوا على الشغل.',
    opportunitiesNone: 'مفيش طلبات مناسبة دلوقتي.',
    opportunitiesActive: 'الفرص المتاحة',
    opportunitiesHistory: 'سجل الفرص',
    opportunitiesCount: '{count} فرص متاحة',
    opportunityDetail: 'تفاصيل الطلب',
    opportunityExpires: 'رد قبل',
    opportunityArea: 'المنطقة التقريبية',
    opportunityPayment: 'طريقة الدفع المفضلة للعميل',
    opportunityQuote: 'ابعت عرض',
    opportunityRevise: 'عدّل العرض',
    opportunityWithdraw: 'اسحب العرض',
    opportunityDecline: 'ارفض الطلب',
    opportunityConfirm: 'أكد العرض المختار',
    opportunityEmergencyAccept: 'اقبل طلب الطوارئ',
    opportunityPrice: 'سعرك (جنيه)',
    opportunityDuration: 'مدة الشغل المتوقعة (دقيقة)',
    opportunityEta: 'وقت الوصول المتوقع (دقيقة، اختياري)',
    opportunityMessage: 'رسالة للعميل (اختياري)',
    opportunityMaterials: 'الخامات',
    opportunityMaterialsIncluded: 'داخلة',
    opportunityMaterialsExcluded: 'مش داخلة',
    opportunityMaterialsPartial: 'جزء منها داخل',
    opportunityMaterialsUnknown: 'هنتفق عليها',
    opportunityMaterialsExplanation: 'تفاصيل الخامات (اختياري)',
    opportunityLabour: 'المصنعية داخلة',
    opportunityCash: 'كاش',
    opportunityOnline: 'دفع أونلاين',
    opportunityPaymentEither: 'كاش أو دفع أونلاين',
    opportunityRevisionReason: 'سبب تغيير العرض',
    opportunityReason: 'السبب',
    opportunityActionFailed: 'الإجراء ده مبقاش متاح أو ما اكتملش. حدّث الطلب قبل ما تحاول تاني.',
    opportunityActionDone: 'الطلب اتحدّث.',
    opportunityQuoteHistory: 'سجل العرض',
    invitationStatus_invited: 'جديد',
    invitationStatus_viewed: 'اتشاف',
    invitationStatus_quoted: 'اتبعت عرض',
    invitationStatus_declined: 'اترفض',
    invitationStatus_withdrawn: 'اتسحب',
    invitationStatus_expired: 'انتهى',
    invitationStatus_request_closed: 'اتقفل',
    invitationStatus_accepted: 'اتقبل',
    quoteStatus_submitted: 'اتبعت',
    quoteStatus_revised: 'اتعدّل',
    quoteStatus_selected: 'اتختار',
    quoteStatus_rejected: 'ما اتختارش',
    quoteStatus_withdrawn: 'اتسحب',
    quoteStatus_expired: 'انتهى',
    quoteStatus_invalidated_by_request_change: 'الطلب اتغيّر',

    workerJobsTitle: 'شغلاناتي',
    workerJobsLead: 'اقبل الحجز الجديد، امشِ بالترتيب المطلوب، وخلي العميل عارف آخر تطور.',
    workerJobsActive: 'الشغل الحالي',
    workerJobsPast: 'السجل',
    workerJobsNoneActive: 'مفيش شغل حالي.',
    workerJobsNonePast: 'لسه مفيش شغل خلص.',
    workerJobsCount: '{count} شغلانات حالية',
    workerJobCustomer: 'العميل',
    workerJobAddress: 'عنوان الشغل',
    workerJobPrice: 'السعر',
    workerJobAccept: 'اقبل الشغل',
    workerJobReject: 'ارفض الشغل',
    workerJobRejectReason: 'ليه مش هتقدر تاخده',
    workerJobReschedule: 'اقترح ميعاد تاني',
    workerJobDate: 'التاريخ الجديد',
    workerJobTime: 'الوقت الجديد',
    workerJobNote: 'وضح سبب التغيير',
    workerJobNext: 'انقل للحالة: {status}',
    workerJobCompleteNote: 'ملاحظة الإكمال (اختياري)',
    workerJobDispute: 'بلّغ عن مشكلة',
    workerJobNoShow: 'بلّغ إن العميل ما حضرش',
    workerJobTimeline: 'المراحل',
    workerJobActionFailed: 'ما قدرناش نحدّث الشغل. حالته الحالية على السيرفر ما اتغيرتش.',

    earningsTitle: 'الأرباح',
    earningsLead: 'الأرصدة والحركات جاية مباشرة من دفتر ورشة المالي.',
    earningsAvailable: 'متاح',
    earningsPending: 'معلّق',
    earningsPaid: 'اتصرف',
    earningsHeld: 'محجوز',
    earningsCashDebt: 'عمولة الكاش المستحقة',
    earningsRecovery: 'تسويات مستحقة',
    earningsTransactions: 'الحركات',
    earningsNone: 'لسه مفيش حركات أرباح.',
    earningsWithdrawals: 'اسحب أرباحك',
    earningsWithdrawalUnavailable: 'السحب مش متاح في البيئة دي. دفتر أرباحك يفضل ظاهر.',
    earningsMinimum: 'الحد الأدنى',
    earningsDestination: 'جهة التحويل',
    earningsNoDestination: 'ضيف جهة تحويل قبل ما تطلب سحب.',
    earningsAddDestination: 'ضيف جهة تحويل',
    earningsDestinationType: 'نوع جهة التحويل',
    earningsMobileWallet: 'محفظة موبايل',
    earningsBankAccount: 'حساب بنكي',
    earningsDestinationLabel: 'الاسم',
    earningsDestinationValue: 'رقم الحساب أو المحفظة',
    earningsOwnership: 'بأكد إن جهة التحويل دي ملكي',
    earningsAmount: 'المبلغ (جنيه)',
    earningsRequestWithdrawal: 'اطلب السحب',
    earningsWithdrawalsHistory: 'سجل السحب',
    earningsActionFailed: 'إجراء التحويل ده ما اكتملش.',
    earningsActionDone: 'طلب التحويل اتسجل.',
    earningStatus_pending_job_completion: 'مستني اكتمال الشغل',
    earningStatus_pending_release: 'معلّق للصرف',
    earningStatus_available: 'متاح',
    earningStatus_withdrawal_requested: 'اتطلب سحبه',
    earningStatus_paid_out: 'اتصرف',
    earningStatus_reversed: 'اتعكس',
    earningStatus_held_for_dispute: 'محجوز للمراجعة',
    withdrawalStatus_requested: 'اتطلب',
    withdrawalStatus_under_review: 'تحت المراجعة',
    withdrawalStatus_processing: 'بيتحوّل',
    withdrawalStatus_paid: 'اتصرف',
    withdrawalStatus_failed: 'ما اكتملش',
    withdrawalStatus_cancelled: 'اتلغى',
    withdrawalStatus_reversed: 'اتعكس',
  },
} as const;

export const workerCopy = {
  ...baseWorkerCopy,
  fr: {
    ...baseWorkerCopy.en,
    onboardingTitle: 'Préparez votre activité', onboardingLead: 'Terminez une étape claire à la fois. Warsha vous indiquera quand une vérification est nécessaire.', onboardingStep: 'Étape {current} sur {total}', onboardingAgreementTitle: 'Commencez votre candidature', onboardingAgreementBody: 'Acceptez l’accord professionnel et autorisez Warsha à traiter les documents fournis pour la vérification.', onboardingAccept: 'Accepter et continuer', onboardingProfileTitle: 'Présentez-vous aux clients', onboardingProfileBody: 'Votre nom et votre photo apparaissent sur votre profil. La présentation et l’expérience sont facultatives.', onboardingPhotoRequired: 'Choisissez une photo de profil claire.', onboardingTradesTitle: 'Choisissez votre métier', onboardingTradesBody: 'Choisissez le type de travail que vous faites, puis les interventions précises que vous pouvez accepter.', onboardingAreaTitle: 'Où intervenez-vous ?', onboardingAreaBody: 'Choisissez le gouvernorat et la zone. Votre lieu de travail exact reste privé et sert uniquement à la mise en relation.', onboardingLocationRequired: 'Confirmez votre lieu de travail après avoir enregistré cette zone.', onboardingIdentityTitle: 'Vérifiez votre identité', onboardingIdentityBody: 'Utilisez l’application Warsha pour photographier les documents d’identité requis.', onboardingReviewTitle: 'Votre dossier est en cours d’examen', onboardingReviewBody: 'Ne renvoyez des informations que si Warsha vous demande une correction.',
    workerName: 'Nom affiché aux clients', workerAbout: 'Courte présentation (facultatif)', workerExperience: "Années d'expérience (facultatif)", workerProfession: 'Votre métier', workerProfessionBody: 'Choisissez le type de travail que vous faites.', workerServices: 'Les services que vous proposez', workerServicesBody: 'Choisissez les interventions précises que vous pouvez accepter.', workerChooseProfessionFirst: 'Choisissez d’abord votre métier, puis les interventions que vous pouvez accepter.', workerSelectAllServices: 'Sélectionner toutes les interventions de ce métier', workerNoServicesChosen: 'Aucune intervention choisie', workerServicesSelected: '{count} interventions sélectionnées', workerOneServiceSelected: '1 intervention sélectionnée', workerNoServicesAvailable: 'Warsha ne propose pas encore d’intervention pour ce métier.', workerProfessionRequired: 'Choisissez au moins un métier.', workerServiceRequired: 'Choisissez au moins une intervention que vous pouvez accepter.', workerProfessionWithdrawn: 'Warsha ne propose plus ce métier. Choisissez celui qui correspond à votre travail.', workerServiceOutsideProfession: 'Certaines interventions choisies n’appartiennent pas à vos métiers. Ouvrez chaque métier et vérifiez la liste.', workerProfileIncomplete: 'Des informations manquent dans votre profil. Vérifiez votre nom, votre photo et vos années d’expérience.', workerAreaInvalid: 'Vérifiez le gouvernorat et la zone que vous avez choisis.', workerWithdrawnProfessionNotice: 'Votre compte enregistre encore un métier que Warsha ne propose plus. Choisissez le métier précis qui correspond à votre travail.', workerHistoricalServicesTitle: 'Services proposés auparavant', workerHistoricalServicesBody: 'Ces services enregistrés restent dans votre profil. Choisissez un métier actuel pour vérifier les interventions que vous pouvez encore proposer.', workerGovernorate: 'Gouvernorat', workerArea: 'Zone', workerSaveDraft: 'Enregistrer et continuer', workerProfileTitle: 'Votre profil professionnel', workerProfileLead: 'Les informations visibles par les clients et utilisées pour vous proposer des travaux.', workerProfileSaved: 'Profil enregistré.', workerPhotoSaved: 'Photo enregistrée', workerProfileFailed: "Le profil n'a pas pu être enregistré. Aucune modification locale n'a été appliquée.", loading: 'Chargement…', retry: 'Réessayer',
    workerAvailability: 'Disponibilité', workerAvailable: 'Disponible pour de nouveaux travaux', workerUnavailable: 'Indisponible pour de nouveaux travaux', workerAvailabilityHelp: 'Seuls les professionnels actifs et approuvés peuvent apparaître aux clients.', workerGoAvailable: 'Me rendre disponible', workerGoUnavailable: 'Suspendre les nouvelles demandes', workerPortfolioMobile: 'Ajoutez vos réalisations et certificats depuis l’application mobile Warsha.',
    workLocationUseCurrent: 'Utiliser ma position actuelle', workLocationSearch: 'Rechercher une adresse', workLocationSearchPlaceholder: 'Rue, bâtiment ou lieu', workLocationSearchAction: 'Rechercher', workLocationSearchUnavailable: "La recherche d'adresse est indisponible. Vous pouvez utiliser votre position actuelle.", workLocationSearchNone: 'Aucune adresse correspondante. Ajoutez plus de détails.', workLocationSearchFailed: "La recherche n'a pas abouti. Réessayez ou utilisez votre position.", workLocationSearching: 'Recherche…', workLocationLocating: 'Localisation…', workLocationResolving: "Recherche de l'adresse…", workLocationSaved: 'Adresse trouvée', workLocationPartial: "Position trouvée. Vérifiez l'adresse avant de continuer.", workLocationLookupFailed: "Position trouvée, mais l'adresse n'a pas pu être récupérée. Vous pouvez continuer avec la zone sélectionnée.", workLocationPermissionDenied: "L'accès à la position a été refusé. Autorisez-le dans le navigateur ou recherchez une adresse.", workLocationUnavailable: "Votre position n'est pas disponible. Recherchez une adresse ou réessayez.", workLocationTimeout: 'La localisation a pris trop de temps. Réessayez ou recherchez une adresse.', workLocationFailed: "Nous n'avons pas pu obtenir cette position. Essayez une autre méthode.", workLocationContinue: 'Continuer', workLocationAreaFailed: "La zone de travail enregistrée n'a pas pu être chargée.",
    opportunitiesTitle: 'Opportunités', opportunitiesLead: 'Demandes adaptées à vos services et à vos zones approuvées. L’adresse exacte du client reste masquée jusqu’à l’accord.', opportunitiesNone: 'Aucune demande correspondante pour le moment.', opportunitiesActive: 'Opportunités actives', opportunitiesHistory: 'Historique des opportunités', opportunitiesCount: '{count} opportunités disponibles', opportunityDetail: 'Détails de la demande', opportunityExpires: 'Répondre avant', opportunityArea: 'Zone approximative', opportunityPayment: 'Mode de paiement préféré du client', opportunityQuote: 'Envoyer un devis', opportunityRevise: 'Modifier le devis', opportunityWithdraw: 'Retirer le devis', opportunityDecline: 'Refuser la demande', opportunityConfirm: 'Confirmer le devis sélectionné', opportunityEmergencyAccept: "Accepter la demande urgente", opportunityPrice: 'Votre prix (EGP)', opportunityDuration: 'Durée estimée (minutes)', opportunityEta: "Délai d'arrivée (minutes, facultatif)", opportunityMessage: 'Message au client (facultatif)', opportunityMaterials: 'Matériaux', opportunityMaterialsIncluded: 'Inclus', opportunityMaterialsExcluded: 'Non inclus', opportunityMaterialsPartial: 'Partiellement inclus', opportunityMaterialsUnknown: 'À convenir', opportunityMaterialsExplanation: 'Détails sur les matériaux (facultatif)', opportunityLabour: "Main-d'œuvre incluse", opportunityCash: 'Espèces', opportunityOnline: 'Paiement en ligne', opportunityPaymentEither: 'Espèces ou en ligne', opportunityRevisionReason: 'Motif de la modification', opportunityReason: 'Motif', opportunityActionFailed: "Cette action n'est plus disponible ou n'a pas abouti. Actualisez avant de réessayer.", opportunityActionDone: 'Demande mise à jour.', opportunityQuoteHistory: 'Historique du devis',
    invitationStatus_invited: 'Nouvelle', invitationStatus_viewed: 'Consultée', invitationStatus_quoted: 'Devis envoyé', invitationStatus_declined: 'Refusée', invitationStatus_withdrawn: 'Retirée', invitationStatus_expired: 'Expirée', invitationStatus_request_closed: 'Fermée', invitationStatus_accepted: 'Acceptée', quoteStatus_submitted: 'Envoyé', quoteStatus_revised: 'Modifié', quoteStatus_selected: 'Sélectionné', quoteStatus_rejected: 'Non sélectionné', quoteStatus_withdrawn: 'Retiré', quoteStatus_expired: 'Expiré', quoteStatus_invalidated_by_request_change: 'Demande modifiée',
    workerJobsTitle: 'Mes travaux', workerJobsLead: 'Acceptez les nouvelles réservations, suivez les étapes et tenez le client informé.', workerJobsActive: 'Travaux en cours', workerJobsPast: 'Historique', workerJobsNoneActive: 'Aucun travail en cours.', workerJobsNonePast: 'Aucun travail terminé.', workerJobsCount: '{count} travaux en cours', workerJobCustomer: 'Client', workerJobAddress: "Adresse d'intervention", workerJobPrice: 'Prix', workerJobAccept: 'Accepter le travail', workerJobReject: 'Refuser le travail', workerJobRejectReason: 'Pourquoi ne pouvez-vous pas le prendre ?', workerJobReschedule: 'Proposer un autre créneau', workerJobDate: 'Nouvelle date', workerJobTime: 'Nouvelle heure', workerJobNote: 'Expliquez le changement', workerJobNext: 'Passer au statut : {status}', workerJobCompleteNote: 'Note de fin (facultatif)', workerJobDispute: 'Signaler un problème', workerJobNoShow: "Signaler l'absence du client", workerJobTimeline: 'Étapes', workerJobActionFailed: "Le travail n'a pas pu être mis à jour. Son état officiel n'a pas changé.",
    earningsTitle: 'Revenus', earningsLead: 'Soldes et mouvements provenant du registre financier officiel de Warsha.', earningsAvailable: 'Disponible', earningsPending: 'En attente', earningsPaid: 'Versé', earningsHeld: 'Bloqué', earningsCashDebt: 'Commission espèces due', earningsRecovery: 'Régularisations dues', earningsTransactions: 'Mouvements', earningsNone: 'Aucun mouvement de revenu.', earningsWithdrawals: 'Retirer vos revenus', earningsWithdrawalUnavailable: "Les retraits ne sont pas disponibles dans cet environnement. Votre registre reste visible.", earningsMinimum: 'Minimum', earningsDestination: 'Destination du versement', earningsNoDestination: 'Ajoutez une destination avant de demander un retrait.', earningsAddDestination: 'Ajouter une destination', earningsDestinationType: 'Type de destination', earningsMobileWallet: 'Portefeuille mobile', earningsBankAccount: 'Compte bancaire', earningsDestinationLabel: 'Nom de la destination', earningsDestinationValue: 'Numéro du compte ou du portefeuille', earningsOwnership: "Je confirme que cette destination m'appartient", earningsAmount: 'Montant (EGP)', earningsRequestWithdrawal: 'Demander le retrait', earningsWithdrawalsHistory: 'Historique des retraits', earningsActionFailed: "L'action de versement n'a pas abouti.", earningsActionDone: 'Votre demande de versement a été enregistrée.',
    earningStatus_pending_job_completion: 'En attente de la fin du travail', earningStatus_pending_release: 'En attente du déblocage', earningStatus_available: 'Disponible', earningStatus_withdrawal_requested: 'Retrait demandé', earningStatus_paid_out: 'Versé', earningStatus_reversed: 'Annulé', earningStatus_held_for_dispute: 'Bloqué pour examen', withdrawalStatus_requested: 'Demandé', withdrawalStatus_under_review: 'En cours d’examen', withdrawalStatus_processing: 'En traitement', withdrawalStatus_paid: 'Versé', withdrawalStatus_failed: 'Échoué', withdrawalStatus_cancelled: 'Annulé', withdrawalStatus_reversed: 'Annulé',
  },
} as const;

export type WorkerWords = Record<keyof typeof workerCopy.en, string>;
