/** Worker product presentation for the unprefixed EN/AR application. */
export const workerCopy = {
  en: {
    onboardingTitle: 'Set up your work account',
    onboardingLead: 'Finish one clear step at a time. Warsha will tell you when the next step belongs to a reviewer.',
    onboardingStep: 'Step {current} of {total}',
    onboardingAgreementTitle: 'Start your application',
    onboardingAgreementBody: 'Accept the worker agreement and allow Warsha to process the identity documents you submit for verification.',
    onboardingAccept: 'Accept and continue',
    onboardingProfileTitle: 'Tell customers about you',
    onboardingProfileBody: 'Your name and photo are public on your worker profile. An introduction and experience are optional.',
    onboardingPhotoRequired: 'Choose a clear profile photo. Warsha stores it in the same protected worker bucket used by the app.',
    onboardingTradesTitle: 'Choose your work',
    onboardingTradesBody: 'Pick at least one profession and one service. Warsha uses them to match relevant opportunities.',
    onboardingAreaTitle: 'Where can you work?',
    onboardingAreaBody: 'Choose your governorate and area. Your exact work location stays private and is used only for matching.',
    onboardingLocationRequired: 'Confirm your private work location after saving this area.',
    onboardingIdentityTitle: 'Verify your identity',
    onboardingIdentityBody: 'ID, selfie and criminal-record evidence use the guided capture flow in the Warsha app. Sensitive evidence is not accepted through this browser form.',
    onboardingReviewTitle: 'Your application is being reviewed',
    onboardingReviewBody: 'There is nothing to guess or resubmit unless Warsha asks you for a correction.',
    workerName: 'Public name',
    workerAbout: 'Short introduction (optional)',
    workerExperience: 'Years of experience (optional)',
    workerProfession: 'Profession(s)',
    workerServices: 'Services',
    workerGovernorate: 'Governorate',
    workerArea: 'Area',
    workerSaveDraft: 'Save and continue',
    workerProfileTitle: 'Your worker profile',
    workerProfileLead: 'The information customers see and the work Warsha can match to you.',
    workerProfileSaved: 'Your worker profile was saved.',
    workerPhotoSaved: 'Photo saved',
    workerProfileFailed: 'Your worker profile could not be saved. Nothing was changed locally.',
    loading: 'Loading…',
    retry: 'Try again',
    workerAvailability: 'Availability',
    workerAvailable: 'Available for new work',
    workerUnavailable: 'Not taking new work',
    workerAvailabilityHelp: 'Only an active, approved worker can become publicly discoverable. The server enforces that rule.',
    workerGoAvailable: 'Go available',
    workerGoUnavailable: 'Pause new work',
    workerPortfolioMobile: 'Portfolio media and professional certificates continue in the Warsha app. Existing protected-upload rules remain in force.',
    workLocationUseCurrent: 'Use my current location',
    workLocationSearch: 'Search for an address',
    workLocationSearchAction: 'Search',
    workLocationSearchUnavailable: 'Address search is unavailable right now. You can still use your current location.',
    workLocationSaved: 'Location saved',
    workLocationFailed: 'We could not get that location. Try another option.',
    workLocationContinue: 'Continue',
    workLocationAreaFailed: 'Unable to load the saved work area.',

    opportunitiesTitle: 'Opportunities',
    opportunitiesLead: 'Requests matched to your approved services and work areas. Exact customer addresses stay hidden until a job is agreed.',
    opportunitiesNone: 'No matched requests right now.',
    opportunitiesCount: '{count} opportunities available',
    opportunityDetail: 'Request details',
    opportunityExpires: 'Respond by',
    opportunityArea: 'Approximate area',
    opportunityPayment: 'Customer payment preference',
    opportunityQuote: 'Send a quote',
    opportunityRevise: 'Revise quote',
    opportunityWithdraw: 'Withdraw quote',
    opportunityDecline: 'Decline request',
    opportunityConfirm: 'Confirm selected quote',
    opportunityEmergencyAccept: 'Accept emergency request',
    opportunityPrice: 'Your price (EGP)',
    opportunityDuration: 'Estimated job time (minutes)',
    opportunityEta: 'Arrival estimate (minutes, optional)',
    opportunityMessage: 'Message to the customer (optional)',
    opportunityMaterials: 'Materials',
    opportunityMaterialsIncluded: 'Included',
    opportunityMaterialsExcluded: 'Not included',
    opportunityMaterialsPartial: 'Partly included',
    opportunityMaterialsUnknown: 'To be agreed',
    opportunityMaterialsExplanation: 'Materials detail (optional)',
    opportunityLabour: 'Labour is included',
    opportunityCash: 'Cash',
    opportunityOnline: 'Online payment',
    opportunityPaymentEither: 'Cash or online payment',
    opportunityRevisionReason: 'Why the quote changed',
    opportunityReason: 'Reason',
    opportunityActionFailed: 'That action is no longer available or could not be completed. Reload the request before trying again.',
    opportunityActionDone: 'The request was updated.',
    opportunityQuoteHistory: 'Quote history',
    invitationStatus_invited: 'New',
    invitationStatus_viewed: 'Viewed',
    invitationStatus_quoted: 'Quoted',
    invitationStatus_declined: 'Declined',
    invitationStatus_withdrawn: 'Withdrawn',
    invitationStatus_expired: 'Expired',
    invitationStatus_request_closed: 'Closed',
    invitationStatus_accepted: 'Accepted',
    quoteStatus_submitted: 'Submitted',
    quoteStatus_revised: 'Revised',
    quoteStatus_selected: 'Selected',
    quoteStatus_rejected: 'Not selected',
    quoteStatus_withdrawn: 'Withdrawn',
    quoteStatus_expired: 'Expired',
    quoteStatus_invalidated_by_request_change: 'Request changed',

    workerJobsTitle: 'My jobs',
    workerJobsLead: 'Accept new bookings, follow the required sequence, and keep the customer informed.',
    workerJobsActive: 'Current work',
    workerJobsPast: 'History',
    workerJobsNoneActive: 'No current jobs.',
    workerJobsNonePast: 'No finished jobs yet.',
    workerJobsCount: '{count} active jobs',
    workerJobCustomer: 'Customer',
    workerJobAddress: 'Job address',
    workerJobPrice: 'Price',
    workerJobAccept: 'Accept job',
    workerJobReject: 'Decline job',
    workerJobRejectReason: 'Why you cannot take it',
    workerJobReschedule: 'Propose another time',
    workerJobDate: 'New date',
    workerJobTime: 'New time',
    workerJobNote: 'Explain the change',
    workerJobNext: 'Move to: {status}',
    workerJobCompleteNote: 'Completion note (optional)',
    workerJobDispute: 'Report a problem',
    workerJobNoShow: 'Report customer no-show',
    workerJobTimeline: 'Timeline',
    workerJobActionFailed: 'The job could not be updated. Its current server state is unchanged.',

    earningsTitle: 'Earnings',
    earningsLead: 'Balances and transactions come directly from Warsha’s financial ledger.',
    earningsAvailable: 'Available',
    earningsPending: 'Pending',
    earningsPaid: 'Paid out',
    earningsHeld: 'Held',
    earningsCashDebt: 'Cash commission due',
    earningsRecovery: 'Adjustments due',
    earningsTransactions: 'Transactions',
    earningsNone: 'No earnings transactions yet.',
    earningsWithdrawals: 'Withdraw earnings',
    earningsWithdrawalUnavailable: 'Withdrawals are not enabled in this environment. Your ledger remains visible.',
    earningsMinimum: 'Minimum',
    earningsDestination: 'Payout destination',
    earningsNoDestination: 'Add a payout destination before requesting a withdrawal.',
    earningsAddDestination: 'Add payout destination',
    earningsDestinationType: 'Destination type',
    earningsMobileWallet: 'Mobile wallet',
    earningsBankAccount: 'Bank account',
    earningsDestinationLabel: 'Label',
    earningsDestinationValue: 'Account or wallet value',
    earningsOwnership: 'I confirm this destination belongs to me',
    earningsAmount: 'Amount (EGP)',
    earningsRequestWithdrawal: 'Request withdrawal',
    earningsWithdrawalsHistory: 'Withdrawal history',
    earningsActionFailed: 'That payout action could not be completed.',
    earningsActionDone: 'Your payout request was recorded.',
    earningStatus_pending_job_completion: 'Waiting for job completion',
    earningStatus_pending_release: 'Pending release',
    earningStatus_available: 'Available',
    earningStatus_withdrawal_requested: 'Withdrawal requested',
    earningStatus_paid_out: 'Paid out',
    earningStatus_reversed: 'Reversed',
    earningStatus_held_for_dispute: 'Held for review',
    withdrawalStatus_requested: 'Requested',
    withdrawalStatus_under_review: 'Under review',
    withdrawalStatus_processing: 'Processing',
    withdrawalStatus_paid: 'Paid',
    withdrawalStatus_failed: 'Failed',
    withdrawalStatus_cancelled: 'Cancelled',
    withdrawalStatus_reversed: 'Reversed',
  },
  ar: {
    onboardingTitle: 'جهّز حساب شغلك',
    onboardingLead: 'خلّص خطوة واضحة كل مرة. ورشة هتقولك لما الخطوة الجاية تكون عند المراجع.',
    onboardingStep: 'الخطوة {current} من {total}',
    onboardingAgreementTitle: 'ابدأ طلبك',
    onboardingAgreementBody: 'وافق على اتفاق الصنايعي واسمح لورشة بمعالجة مستندات الهوية اللي هتقدمها للتحقق.',
    onboardingAccept: 'وافق وكمّل',
    onboardingProfileTitle: 'عرّف العملاء بيك',
    onboardingProfileBody: 'اسمك وصورتك بيظهروا في ملف الصنايعي. النبذة وسنين الخبرة اختياريين.',
    onboardingPhotoRequired: 'اختار صورة واضحة لملفك. ورشة بتحفظها في نفس مساحة الصنايعي المحمية اللي بيستخدمها التطبيق.',
    onboardingTradesTitle: 'اختار شغلك',
    onboardingTradesBody: 'اختار مهنة وخدمة واحدة على الأقل. ورشة بتستخدمهم عشان تبعتلك فرص مناسبة.',
    onboardingAreaTitle: 'بتشتغل فين؟',
    onboardingAreaBody: 'اختار المحافظة والمنطقة. مكان شغلك بالتفصيل يفضل خاص وبيستخدم بس للمطابقة.',
    onboardingLocationRequired: 'أكد مكان شغلك الخاص بعد حفظ المنطقة دي.',
    onboardingIdentityTitle: 'اتحقق من هويتك',
    onboardingIdentityBody: 'صور البطاقة والسيلفي والفيش بتستخدم مسار التصوير الموجّه في تطبيق ورشة. المستندات الحساسة مش بتترفع من نموذج المتصفح ده.',
    onboardingReviewTitle: 'طلبك بيتراجع',
    onboardingReviewBody: 'مش مطلوب منك تخمّن أو تعيد حاجة إلا لو ورشة طلبت تصحيح.',
    workerName: 'الاسم الظاهر للعملاء',
    workerAbout: 'نبذة قصيرة (اختياري)',
    workerExperience: 'سنين الخبرة (اختياري)',
    workerProfession: 'المهنة أو المهن',
    workerServices: 'الخدمات',
    workerGovernorate: 'المحافظة',
    workerArea: 'المنطقة',
    workerSaveDraft: 'احفظ وكمّل',
    workerProfileTitle: 'ملفك كصنايعي',
    workerProfileLead: 'المعلومات اللي بيشوفها العملاء والشغل اللي ورشة تقدر تطابقه معاك.',
    workerProfileSaved: 'ملف الصنايعي اتحفظ.',
    workerPhotoSaved: 'الصورة اتحفظت',
    workerProfileFailed: 'ما قدرناش نحفظ ملف الصنايعي. مفيش حاجة اتغيرت محليًا.',
    loading: 'بيحمّل…',
    retry: 'جرّب تاني',
    workerAvailability: 'التوفر',
    workerAvailable: 'متاح لشغل جديد',
    workerUnavailable: 'مش بستقبل شغل جديد',
    workerAvailabilityHelp: 'بس الصنايعي النشط والمقبول يقدر يظهر للعملاء. السيرفر هو اللي بيفرض القاعدة دي.',
    workerGoAvailable: 'خلّيني متاح',
    workerGoUnavailable: 'وقف الشغل الجديد',
    workerPortfolioMobile: 'صور أعمالك وشهاداتك المهنية بتكمل من تطبيق ورشة. قواعد الرفع المحمي الحالية لسه سارية.',
    workLocationUseCurrent: 'استخدم موقعي الحالي',
    workLocationSearch: 'دور على عنوان',
    workLocationSearchAction: 'دور',
    workLocationSearchUnavailable: 'بحث العناوين مش متاح دلوقتي. تقدر تستخدم موقعك الحالي.',
    workLocationSaved: 'الموقع اتحفظ',
    workLocationFailed: 'ما قدرناش نجيب الموقع ده. جرّب طريقة تانية.',
    workLocationContinue: 'كمّل',
    workLocationAreaFailed: 'ما قدرناش نحمّل منطقة الشغل المحفوظة.',

    opportunitiesTitle: 'الفرص',
    opportunitiesLead: 'طلبات مناسبة لخدماتك ومناطق شغلك المقبولة. عنوان العميل بالتفصيل يفضل مخفي لحد ما تتفقوا على الشغل.',
    opportunitiesNone: 'مفيش طلبات مناسبة دلوقتي.',
    opportunitiesCount: '{count} فرص متاحة',
    opportunityDetail: 'تفاصيل الطلب',
    opportunityExpires: 'رد قبل',
    opportunityArea: 'المنطقة التقريبية',
    opportunityPayment: 'طريقة الدفع المفضلة للعميل',
    opportunityQuote: 'ابعت عرض',
    opportunityRevise: 'عدّل العرض',
    opportunityWithdraw: 'اسحب العرض',
    opportunityDecline: 'ارفض الطلب',
    opportunityConfirm: 'أكد العرض المختار',
    opportunityEmergencyAccept: 'اقبل طلب الطوارئ',
    opportunityPrice: 'سعرك (جنيه)',
    opportunityDuration: 'مدة الشغل المتوقعة (دقيقة)',
    opportunityEta: 'وقت الوصول المتوقع (دقيقة، اختياري)',
    opportunityMessage: 'رسالة للعميل (اختياري)',
    opportunityMaterials: 'الخامات',
    opportunityMaterialsIncluded: 'داخلة',
    opportunityMaterialsExcluded: 'مش داخلة',
    opportunityMaterialsPartial: 'جزء منها داخل',
    opportunityMaterialsUnknown: 'هنتفق عليها',
    opportunityMaterialsExplanation: 'تفاصيل الخامات (اختياري)',
    opportunityLabour: 'المصنعية داخلة',
    opportunityCash: 'كاش',
    opportunityOnline: 'دفع أونلاين',
    opportunityPaymentEither: 'كاش أو دفع أونلاين',
    opportunityRevisionReason: 'سبب تغيير العرض',
    opportunityReason: 'السبب',
    opportunityActionFailed: 'الإجراء ده مبقاش متاح أو ما اكتملش. حدّث الطلب قبل ما تحاول تاني.',
    opportunityActionDone: 'الطلب اتحدّث.',
    opportunityQuoteHistory: 'سجل العرض',
    invitationStatus_invited: 'جديد',
    invitationStatus_viewed: 'اتشاف',
    invitationStatus_quoted: 'اتبعت عرض',
    invitationStatus_declined: 'اترفض',
    invitationStatus_withdrawn: 'اتسحب',
    invitationStatus_expired: 'انتهى',
    invitationStatus_request_closed: 'اتقفل',
    invitationStatus_accepted: 'اتقبل',
    quoteStatus_submitted: 'اتبعت',
    quoteStatus_revised: 'اتعدّل',
    quoteStatus_selected: 'اتختار',
    quoteStatus_rejected: 'ما اتختارش',
    quoteStatus_withdrawn: 'اتسحب',
    quoteStatus_expired: 'انتهى',
    quoteStatus_invalidated_by_request_change: 'الطلب اتغيّر',

    workerJobsTitle: 'شغلاناتي',
    workerJobsLead: 'اقبل الحجز الجديد، امشِ بالترتيب المطلوب، وخلي العميل عارف آخر تطور.',
    workerJobsActive: 'الشغل الحالي',
    workerJobsPast: 'السجل',
    workerJobsNoneActive: 'مفيش شغل حالي.',
    workerJobsNonePast: 'لسه مفيش شغل خلص.',
    workerJobsCount: '{count} شغلانات حالية',
    workerJobCustomer: 'العميل',
    workerJobAddress: 'عنوان الشغل',
    workerJobPrice: 'السعر',
    workerJobAccept: 'اقبل الشغل',
    workerJobReject: 'ارفض الشغل',
    workerJobRejectReason: 'ليه مش هتقدر تاخده',
    workerJobReschedule: 'اقترح ميعاد تاني',
    workerJobDate: 'التاريخ الجديد',
    workerJobTime: 'الوقت الجديد',
    workerJobNote: 'وضح سبب التغيير',
    workerJobNext: 'انقل للحالة: {status}',
    workerJobCompleteNote: 'ملاحظة الإكمال (اختياري)',
    workerJobDispute: 'بلّغ عن مشكلة',
    workerJobNoShow: 'بلّغ إن العميل ما حضرش',
    workerJobTimeline: 'المراحل',
    workerJobActionFailed: 'ما قدرناش نحدّث الشغل. حالته الحالية على السيرفر ما اتغيرتش.',

    earningsTitle: 'الأرباح',
    earningsLead: 'الأرصدة والحركات جاية مباشرة من دفتر ورشة المالي.',
    earningsAvailable: 'متاح',
    earningsPending: 'معلّق',
    earningsPaid: 'اتصرف',
    earningsHeld: 'محجوز',
    earningsCashDebt: 'عمولة الكاش المستحقة',
    earningsRecovery: 'تسويات مستحقة',
    earningsTransactions: 'الحركات',
    earningsNone: 'لسه مفيش حركات أرباح.',
    earningsWithdrawals: 'اسحب أرباحك',
    earningsWithdrawalUnavailable: 'السحب مش متاح في البيئة دي. دفتر أرباحك يفضل ظاهر.',
    earningsMinimum: 'الحد الأدنى',
    earningsDestination: 'جهة التحويل',
    earningsNoDestination: 'ضيف جهة تحويل قبل ما تطلب سحب.',
    earningsAddDestination: 'ضيف جهة تحويل',
    earningsDestinationType: 'نوع جهة التحويل',
    earningsMobileWallet: 'محفظة موبايل',
    earningsBankAccount: 'حساب بنكي',
    earningsDestinationLabel: 'الاسم',
    earningsDestinationValue: 'رقم الحساب أو المحفظة',
    earningsOwnership: 'بأكد إن جهة التحويل دي ملكي',
    earningsAmount: 'المبلغ (جنيه)',
    earningsRequestWithdrawal: 'اطلب السحب',
    earningsWithdrawalsHistory: 'سجل السحب',
    earningsActionFailed: 'إجراء التحويل ده ما اكتملش.',
    earningsActionDone: 'طلب التحويل اتسجل.',
    earningStatus_pending_job_completion: 'مستني اكتمال الشغل',
    earningStatus_pending_release: 'معلّق للصرف',
    earningStatus_available: 'متاح',
    earningStatus_withdrawal_requested: 'اتطلب سحبه',
    earningStatus_paid_out: 'اتصرف',
    earningStatus_reversed: 'اتعكس',
    earningStatus_held_for_dispute: 'محجوز للمراجعة',
    withdrawalStatus_requested: 'اتطلب',
    withdrawalStatus_under_review: 'تحت المراجعة',
    withdrawalStatus_processing: 'بيتحوّل',
    withdrawalStatus_paid: 'اتصرف',
    withdrawalStatus_failed: 'ما اكتملش',
    withdrawalStatus_cancelled: 'اتلغى',
    withdrawalStatus_reversed: 'اتعكس',
  },
} as const;

export type WorkerWords = Record<keyof typeof workerCopy.en, string>;
