project_id = "warsha"
[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
[db]
major_version = 15
[db.seed]
enabled = true
sql_paths = ["./seed.sql"]
[auth]
enabled = true
site_url = "http://localhost:8081"
[auth.sms]
enable_signup = true
enable_confirmations = true
max_frequency = "2s"
[auth.sms.test_otp]
"+201000000008" = "123456"
"+201099221106" = "123456"
[auth.sms.textlocal]
enabled = true
api_key = "local-test-only-no-real-sms"
sender = "WarshaLocal"
[storage]
enabled = true
