import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { Image } from 'expo-image';
import * as ImagePicker from 'expo-image-picker';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useRef, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ScreenHeader } from '@/components/warsha/ScreenHeader';
import { BrandLoadingMark as ActivityIndicator } from '@/components/warsha/BrandMark';
import { ProviderReviewReply } from '@/components/warsha/ProviderReviewReply';
import { ProviderCashPaymentCard } from '@/components/warsha/ProviderCashPaymentCard';
import { BookingPriceAdjustmentCard } from '@/components/warsha/BookingPriceAdjustmentCard';
import { BookingDisputePanel } from '@/components/warsha/BookingDisputePanel';
import { JobOperationsPanel } from '@/components/warsha/JobOperationsPanel';
import { AppText } from '@/components/warsha/Typography';
import { StateBadge } from '@/components/warsha/BrandUI';
import { radii, spacing, typography, type ThemeColors } from '@/constants/theme';
import { useThemeColors, useThemedStyles } from '@/src/appearance/appearance-context';
import { persistAttachment, removePersistedAttachment } from '@/src/bookings/attachment-storage';
import { bookingStatusTranslationKeys, formatAddress, type BookingAttachment, type BookingStatus } from '@/src/bookings/booking-types';
import { isBookingChatActivated } from '@/src/chat/chat-lifecycle';
import { useLocalization } from '@/src/i18n/localization';
import { useProviderJobText } from '@/src/i18n/provider-job-translations';
import { useProviderJobs } from '@/src/provider-jobs/provider-job-context';
import { useMarketplaceData } from '@/src/data/marketplace-context';
import { marketplaceRepository } from '@/src/marketplace-intelligence/marketplace-repository';
import { marketplaceIdempotency } from '@/src/marketplace-intelligence/marketplace-types';
import { formatBookingDateTime, formatNumber, formatTimestamp, localeFor } from '@/src/utils/date-format';
import { cataloguedServiceReferenceLabel } from '@/src/services/specific-services';
import { bookingLifecycleSemantic, lifecycleBadgeTone } from '@/src/lifecycle/lifecycle-presentation';

type Panel='reject'|'propose'|'no_show'|'late'|'disputed'|'complete'|null;
export default function ProviderJobDetails(){
  const colors = useThemeColors();
  const styles = useThemedStyles(makeStyles);const{id}=useLocalSearchParams<{id:string}>();const jobs=useProviderJobs();const{services}=useMarketplaceData();const{t,isRTL,language}=useLocalization();const jt=useProviderJobText();const job=jobs.getJob(id);const[panel,setPanel]=useState<Panel>(null);const[note,setNote]=useState('');const[date,setDate]=useState('');const[time,setTime]=useState('');const[images,setImages]=useState<BookingAttachment[]>([]);const imagesRef=useRef(images);imagesRef.current=images;useEffect(()=>()=>{imagesRef.current.forEach(removePersistedAttachment)},[]);if(jobs.loading)return <State><ActivityIndicator color={colors.white}/></State>;if(!job)return <State><AppText>{jt('jobsLoadError')}</AppText><Pressable style={styles.outline} onPress={()=>router.back()}><AppText>{t('back')}</AppText></Pressable></State>;const serviceLabel=cataloguedServiceReferenceLabel(job,services,language);
  const run=async(operation:()=>Promise<void>)=>{try{await operation();setPanel(null);setNote('');setDate('');setTime('');setImages([])}catch{Alert.alert(jt('jobDetails'),jt('actionFailed'))}};
  const pick=async()=>{if(images.length>=4)return;const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsMultipleSelection:true,selectionLimit:4-images.length,quality:.75});if(result.canceled)return;const added:BookingAttachment[]=[];try{for(const asset of result.assets.slice(0,4-images.length))added.push(persistAttachment(asset));setImages(current=>[...current,...added])}catch{added.forEach(removePersistedAttachment);Alert.alert(jt('completionImages'),jt('actionFailed'))}};
  const advance=(status:BookingStatus,label:string)=>Button(label,()=>void run(()=>jobs.advance(job.id,status)),jobs.actionInFlight===job.id);
  return <SafeAreaView style={styles.safe}><ScreenHeader title={jt('jobDetails')}/><ScrollView contentContainerStyle={styles.page}><Card><View style={[styles.row,isRTL&&styles.reverse]}><View style={styles.grow}><AppText style={styles.title}>{job.customerName}</AppText><AppText style={styles.muted}>{jt('customer')}</AppText></View><StateBadge label={t(bookingStatusTranslationKeys[job.status])} tone={lifecycleBadgeTone(bookingLifecycleSemantic(job.status))} compact /></View><Line label={jt('dateTime')} value={formatBookingDateTime(job.date,job.time,localeFor(language),t('asap'))}/><Line label={jt('address')} value={formatAddress(job.address)}/><Line label={jt('scheduledBooking')} value={job.bookingType==='emergency'?jt('emergencyBooking'):jt('scheduledBooking')}/></Card>
    <Card><Heading>{serviceLabel}</Heading><Line label={jt('issueDescription')} value={job.issueDescription}/>{job.notes?<Line label={jt('notes')} value={job.notes}/>:null}</Card>
    {job.status==='rescheduling_requested'?<Card><Heading>{jt('awaitingCustomer')}</Heading><Line label={jt('originalSchedule')} value={formatBookingDateTime(job.date,job.time,localeFor(language),t('asap'))}/><Line label={jt('proposedSchedule')} value={job.proposedDate&&job.proposedTime?formatBookingDateTime(job.proposedDate,job.proposedTime,localeFor(language),t('asap')):'—'}/><Line label={jt('reason')} value={job.providerRescheduleNote??'—'}/></Card>:null}
    {job.attachments.filter(item=>item.kind!=='completion_evidence').length?<Card><Heading>{jt('customerAttachments')}</Heading><View style={styles.images}>{job.attachments.filter(item=>item.kind!=='completion_evidence').map(item=>item.uri?<Image key={item.id} source={{uri:item.uri}} style={styles.image}/>:null)}</View></Card>:null}
    <Card><Heading>{jt('priceBreakdown')}</Heading><Price label={jt('servicePrice')} value={job.priceBreakdown?.servicePrice??job.price}/><Price label={jt('transportation')} value={job.priceBreakdown?.transportationFee??0}/><Price label={jt('emergencyFee')} value={job.priceBreakdown?.emergencySurcharge??0}/><Price label={jt('discount')} value={-(job.priceBreakdown?.discount??0)}/><View style={styles.divider}/><Price label={jt('total')} value={job.price} strong/></Card>
    <BookingPriceAdjustmentCard booking={job} role="provider"/>
    <JobOperationsPanel booking={job} role="worker" onBookingChanged={()=>jobs.reload(true)}/>
    <BookingDisputePanel booking={job} role="worker"/>
    <ProviderCashPaymentCard bookingId={job.id} completed={job.status==='completed'}/>
    <Card><Heading>{jt('timeline')}</Heading>{job.history.map((event,index)=><View key={`${event.status}-${event.at}-${index}`} style={[styles.timeline,isRTL&&styles.reverse]}><View style={styles.dot}/><View style={styles.grow}><AppText style={styles.lineLabel}>{t(bookingStatusTranslationKeys[event.status])}</AppText><AppText style={styles.muted}>{formatTimestamp(event.at,localeFor(language))}</AppText>{event.note?<AppText style={styles.note}>{event.note}</AppText>:null}</View></View>)}</Card>
    {job.completionNotes||job.attachments.some(item=>item.kind==='completion_evidence')?<Card><Heading>{jt('completionImages')}</Heading>{job.completionNotes?<AppText style={styles.note}>{job.completionNotes}</AppText>:null}<View style={styles.images}>{job.attachments.filter(item=>item.kind==='completion_evidence').map(item=>item.uri?<Image key={item.id} source={{uri:item.uri}} style={styles.image}/>:null)}</View></Card>:null}
    {isBookingChatActivated(job)?<Card><Heading>{t('chat')}</Heading>{Button(t('chat'),()=>router.push({pathname:'/conversation/[bookingId]',params:{bookingId:job.id}}))}</Card>:null}
    {job.status==='completed'?<Card><Heading>{t('customerReview')}</Heading><ProviderReviewReply bookingId={job.id}/></Card>:null}
    {actions(job.status).length?<Card><Heading>{jt('actions')}</Heading>{job.status==='pending_provider_approval'?Button(jt('accept'),()=>void run(()=>jobs.accept(job.id)),jobs.actionInFlight===job.id):null}{job.status==='pending_provider_approval'?Button(jt('reject'),()=>setPanel('reject')):null}{['pending_provider_approval','accepted','confirmed'].includes(job.status)?Button(jt('proposeTime'),()=>setPanel('propose')):null}{job.status==='accepted'?advance('confirmed',jt('confirm')):null}{['confirmed','provider_on_the_way'].includes(job.status)?Button(jt('runningLate'),()=>setPanel('late')):null}{job.status==='confirmed'?advance('provider_on_the_way',jt('onWay')):null}{job.status==='provider_on_the_way'?advance('provider_arrived',jt('arrived')):null}{job.status==='provider_arrived'?<>{advance('job_started',jt('startWork'))}{Button(jt('noShow'),()=>setPanel('no_show'))}</>:null}{job.status==='job_started'?advance('work_in_progress',jt('workProgress')):null}{['job_started','work_in_progress'].includes(job.status)?<>{Button(jt('complete'),()=>setPanel('complete'))}{Button(jt('flagProblem'),()=>setPanel('disputed'))}</>:null}</Card>:null}
    {panel?<Card><Heading>{panel==='propose'?jt('proposeTime'):panel==='complete'?jt('complete'):panel==='late'?jt('updateArrival'):jt('reason')}</Heading>{panel==='propose'?<><Field label={jt('proposedDate')} value={date} onChangeText={setDate}/><Field label={jt('proposedTime')} value={time} onChangeText={setTime}/></>:null}{panel==='late'?<Field label={jt('delayMinutes')} value={time} onChangeText={setTime} keyboardType="number-pad"/>:null}<Field label={panel==='complete'?jt('completionNotes'):jt('reason')} value={note} onChangeText={setNote} multiline/>{panel==='complete'?<><Pressable accessibilityLabel={jt('addImages')} onPress={()=>void pick()} style={styles.outline}><AppText>{jt('addImages')} ({images.length}/4)</AppText></Pressable><View style={styles.images}>{images.map(item=><View key={item.id}><Image source={{uri:item.uri}} style={styles.image}/><Pressable accessibilityLabel={jt('removeImage')} onPress={()=>{removePersistedAttachment(item);setImages(current=>current.filter(image=>image.id!==item.id))}} style={styles.remove}><MaterialIcons name="close" size={18} color={colors.background}/></Pressable></View>)}</View></>:null}{Button(jt('confirmAction'),()=>void run(()=>panel==='reject'?jobs.reject(job.id,note):panel==='propose'?jobs.propose(job.id,date,time,note):panel==='late'?marketplaceRepository.reportRunningLate(job.id,Number(time),'traffic',note,marketplaceIdempotency('running-late')).then(()=>jobs.reload()):panel==='no_show'?marketplaceRepository.reportCustomerNoShow(job.id,{note},marketplaceIdempotency('customer-no-show')).then(()=>jobs.reload()):panel==='disputed'?jobs.advance(job.id,'disputed',note):jobs.complete(job.id,note,images)),jobs.actionInFlight===job.id,!valid(panel,note,date,time))}{Button(jt('close'),()=>setPanel(null))}</Card>:null}
  </ScrollView></SafeAreaView>;
  function Price({label,value,strong}:{label:string;value:number;strong?:boolean}){return <View style={[styles.row,isRTL&&styles.reverse]}><AppText style={strong&&styles.lineLabel}>{label}</AppText><AppText style={strong&&styles.lineLabel}>{formatNumber(value,language)} {t('currency')}</AppText></View>}
}
function actions(status:BookingStatus){return['pending_provider_approval','accepted','confirmed','provider_on_the_way','provider_arrived','job_started','work_in_progress'].filter(item=>item===status)}
function valid(panel:Panel,note:string,date:string,time:string){if(panel==='complete')return true;if(panel==='late')return Number(time)>=1&&Number(time)<=240;if(panel==='propose')return /^\d{4}-\d{2}-\d{2}$/.test(date)&&/^\d{2}:\d{2}$/.test(time)&&note.trim().length>=3;return note.trim().length>=3}
function Button(label:string,onPress:()=>void,busy=false,disabled=false){
  const colors = useThemeColors();
  const styles = useThemedStyles(makeStyles);return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={busy||disabled} onPress={onPress} style={[styles.button,(busy||disabled)&&styles.disabled]}>{busy?<ActivityIndicator color={colors.white}/>:<AppText style={styles.buttonText}>{label}</AppText>}</Pressable>}
function State({children}:{children:React.ReactNode}){
  const styles = useThemedStyles(makeStyles);return <SafeAreaView style={styles.safe}><View style={styles.state}>{children}</View></SafeAreaView>}
function Card({children}:{children:React.ReactNode}){
  const styles = useThemedStyles(makeStyles);return <View style={styles.card}>{children}</View>}
function Heading({children}:{children:React.ReactNode}){
  const styles = useThemedStyles(makeStyles);return <AppText style={styles.heading}>{children}</AppText>}
function Line({label,value}:{label:string;value:string}){
  const styles = useThemedStyles(makeStyles);return <View style={styles.line}><AppText style={styles.lineLabel}>{label}</AppText><AppText style={styles.note}>{value}</AppText></View>}
function Field({label,...props}:{label:string}&React.ComponentProps<typeof TextInput>){
  const colors = useThemeColors();
  const styles = useThemedStyles(makeStyles);const{isRTL}=useLocalization();return <View><AppText style={styles.lineLabel}>{label}</AppText><TextInput accessibilityLabel={label} placeholder={label} placeholderTextColor={colors.textMuted} {...props} style={[styles.input,props.multiline&&styles.multiline,{textAlign:isRTL?'right':'left'}]}/></View>}
const makeStyles = (colors: ThemeColors) => StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},page:{padding:spacing.lg,paddingBottom:spacing.xxxl,gap:spacing.md,maxWidth:720,width:'100%',alignSelf:'center'},card:{padding:spacing.lg,gap:spacing.md,borderWidth:1,borderColor:colors.border,borderRadius:radii.xl,backgroundColor:colors.surface},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:spacing.md},reverse:{flexDirection:'row-reverse'},grow:{flex:1},title:{fontSize:22,fontWeight:typography.bold},heading:{fontSize:17,fontWeight:typography.bold},muted:{fontSize:12,color:colors.textMuted},line:{gap:4},lineLabel:{fontWeight:typography.semibold},note:{color:colors.textSecondary,lineHeight:21},images:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},image:{width:92,height:92,borderRadius:radii.md,backgroundColor:colors.surfaceElevated},remove:{position:'absolute',right:-4,top:-4,width:28,height:28,borderRadius:14,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},divider:{height:1,backgroundColor:colors.border},timeline:{flexDirection:'row',gap:spacing.md},dot:{width:9,height:9,borderRadius:5,backgroundColor:colors.white,marginTop:5},button:{minHeight:50,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,alignItems:'center',justifyContent:'center',paddingHorizontal:spacing.md},buttonText:{fontWeight:typography.semibold,textAlign:'center'},outline:{minHeight:48,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,alignItems:'center',justifyContent:'center'},disabled:{opacity:.4},input:{minHeight:50,borderWidth:1,borderColor:colors.border,borderRadius:radii.md,backgroundColor:colors.surfaceElevated,color:colors.white,padding:spacing.md},multiline:{height:100,textAlignVertical:'top'},state:{flex:1,alignItems:'center',justifyContent:'center',gap:spacing.md,padding:spacing.xl}});
