begin;
select plan(63);
select has_table('public','profiles','profiles exists');
select has_table('public','bookings','bookings exists');
select has_table('public','provider_verification_documents','verification documents exist');
select has_table('public','audit_logs','audit log exists');
select is((select relrowsecurity from pg_class where oid='public.bookings'::regclass),true,'bookings RLS enabled');
select is((select relrowsecurity from pg_class where oid='public.provider_verification_documents'::regclass),true,'verification RLS enabled');
select is((select relrowsecurity from pg_class where oid='public.messages'::regclass),true,'messages RLS enabled');
select has_function('public','cancel_own_booking',array['uuid'],'controlled booking cancellation function exists');
select has_function('public','ensure_customer_profile',array[]::text[],'customer bootstrap recovery exists');
select has_function('public','set_default_address',array['uuid'],'default address function exists');
select has_function('public','cancel_customer_booking',array['uuid','text'],'secure customer cancellation exists');
select has_function('public','reschedule_customer_booking',array['uuid','date','time without time zone'],'secure rescheduling exists');
select has_function('public','activate_provider_role',array['text'],'provider activation is server controlled');
select has_function('public','save_provider_foundation',array['jsonb','boolean'],'provider foundation save is transactional');
select has_column('public','provider_profiles','onboarding_status','provider onboarding status exists');
select has_column('public','provider_services','pricing_type','provider pricing model exists');
select has_function('public','accept_provider_booking',array['uuid'],'provider acceptance RPC exists');
select has_function('public','reject_provider_booking',array['uuid','text'],'provider rejection RPC exists');
select has_function('public','propose_provider_reschedule',array['uuid','date','time without time zone','text'],'provider proposal RPC exists');
select has_function('public','advance_provider_booking_status',array['uuid','text','text'],'provider progression RPC exists');
select has_function('public','report_provider_no_show',array['uuid','text'],'provider no-show RPC exists');
select has_function('public','accept_provider_reschedule',array['uuid'],'customer proposal acceptance RPC exists');
select has_function('public','reject_provider_reschedule',array['uuid'],'customer proposal rejection RPC exists');
select has_column('public','bookings','proposed_scheduled_date','provider proposal date exists');
select has_column('public','booking_attachments','attachment_kind','attachment purpose exists');
select is(has_function_privilege('anon','public.accept_provider_booking(uuid)','EXECUTE'),false,'anon cannot accept provider bookings');
select is(has_function_privilege('authenticated','public.accept_provider_booking(uuid)','EXECUTE'),true,'authenticated can invoke provider acceptance subject to ownership');
select is((select not exists(select 1 from pg_catalog.aclexplode(coalesce(p.proacl,pg_catalog.acldefault('f',p.proowner))) a where a.grantee=0 and a.privilege_type='EXECUTE') from pg_catalog.pg_proc p where p.oid='public.accept_provider_booking(uuid)'::regprocedure),true,'PUBLIC cannot accept provider bookings');
select is(has_function_privilege('anon','public.reject_provider_booking(uuid,text)','EXECUTE'),false,'anon cannot reject provider bookings');
select is(has_function_privilege('authenticated','public.reject_provider_booking(uuid,text)','EXECUTE'),true,'authenticated can invoke provider rejection subject to ownership');
select is((select not exists(select 1 from pg_catalog.aclexplode(coalesce(p.proacl,pg_catalog.acldefault('f',p.proowner))) a where a.grantee=0 and a.privilege_type='EXECUTE') from pg_catalog.pg_proc p where p.oid='public.reject_provider_booking(uuid,text)'::regprocedure),true,'PUBLIC cannot reject provider bookings');
select is(has_function_privilege('anon','public.propose_provider_reschedule(uuid,date,time without time zone,text)','EXECUTE'),false,'anon cannot propose provider reschedules');
select is(has_function_privilege('authenticated','public.propose_provider_reschedule(uuid,date,time without time zone,text)','EXECUTE'),true,'authenticated can invoke provider proposals subject to ownership');
select is((select not exists(select 1 from pg_catalog.aclexplode(coalesce(p.proacl,pg_catalog.acldefault('f',p.proowner))) a where a.grantee=0 and a.privilege_type='EXECUTE') from pg_catalog.pg_proc p where p.oid='public.propose_provider_reschedule(uuid,date,time without time zone,text)'::regprocedure),true,'PUBLIC cannot propose provider reschedules');
select is(has_function_privilege('anon','public.advance_provider_booking_status(uuid,text,text)','EXECUTE'),false,'anon cannot advance provider bookings');
select is(has_function_privilege('authenticated','public.advance_provider_booking_status(uuid,text,text)','EXECUTE'),true,'authenticated can invoke provider progression subject to ownership');
select is((select not exists(select 1 from pg_catalog.aclexplode(coalesce(p.proacl,pg_catalog.acldefault('f',p.proowner))) a where a.grantee=0 and a.privilege_type='EXECUTE') from pg_catalog.pg_proc p where p.oid='public.advance_provider_booking_status(uuid,text,text)'::regprocedure),true,'PUBLIC cannot advance provider bookings');
select is(has_function_privilege('anon','public.report_provider_no_show(uuid,text)','EXECUTE'),false,'anon cannot report provider no-shows');
select is(has_function_privilege('authenticated','public.report_provider_no_show(uuid,text)','EXECUTE'),true,'authenticated can invoke no-show reporting subject to ownership');
select is((select not exists(select 1 from pg_catalog.aclexplode(coalesce(p.proacl,pg_catalog.acldefault('f',p.proowner))) a where a.grantee=0 and a.privilege_type='EXECUTE') from pg_catalog.pg_proc p where p.oid='public.report_provider_no_show(uuid,text)'::regprocedure),true,'PUBLIC cannot report provider no-shows');
select is(has_function_privilege('anon','public.accept_provider_reschedule(uuid)','EXECUTE'),false,'anon cannot accept reschedule proposals');
select is(has_function_privilege('authenticated','public.accept_provider_reschedule(uuid)','EXECUTE'),true,'authenticated can invoke proposal acceptance subject to customer ownership');
select is((select not exists(select 1 from pg_catalog.aclexplode(coalesce(p.proacl,pg_catalog.acldefault('f',p.proowner))) a where a.grantee=0 and a.privilege_type='EXECUTE') from pg_catalog.pg_proc p where p.oid='public.accept_provider_reschedule(uuid)'::regprocedure),true,'PUBLIC cannot accept reschedule proposals');
select is(has_function_privilege('anon','public.reject_provider_reschedule(uuid)','EXECUTE'),false,'anon cannot reject reschedule proposals');
select is(has_function_privilege('authenticated','public.reject_provider_reschedule(uuid)','EXECUTE'),true,'authenticated can invoke proposal rejection subject to customer ownership');
select is((select not exists(select 1 from pg_catalog.aclexplode(coalesce(p.proacl,pg_catalog.acldefault('f',p.proowner))) a where a.grantee=0 and a.privilege_type='EXECUTE') from pg_catalog.pg_proc p where p.oid='public.reject_provider_reschedule(uuid)'::regprocedure),true,'PUBLIC cannot reject reschedule proposals');
select is(has_function_privilege('anon','public.cancel_customer_booking(uuid,text)','EXECUTE'),false,'anon cannot cancel customer bookings');
select is(has_function_privilege('authenticated','public.cancel_customer_booking(uuid,text)','EXECUTE'),true,'authenticated can invoke customer cancellation subject to ownership');
select is((select not exists(select 1 from pg_catalog.aclexplode(coalesce(p.proacl,pg_catalog.acldefault('f',p.proowner))) a where a.grantee=0 and a.privilege_type='EXECUTE') from pg_catalog.pg_proc p where p.oid='public.cancel_customer_booking(uuid,text)'::regprocedure),true,'PUBLIC cannot cancel customer bookings');
select is((select count(*)::integer from pg_policies where schemaname='storage' and tablename='objects' and policyname='booking_attachment_participant_upload'),1,'scoped booking upload policy exists');
select is((select count(*)::integer from pg_policies where schemaname='public' and tablename='bookings' and policyname='bookings_participant_read'),1,'booking participant read remains singular');
select has_function('public','mark_notification_read',array['uuid'],'single notification read RPC exists');
select has_function('public','mark_all_notifications_read',array[]::text[],'mark-all notification RPC exists');
select has_function('public','dismiss_notification',array['uuid'],'notification dismissal RPC exists');
select is(has_function_privilege('anon','public.mark_notification_read(uuid)','EXECUTE'),false,'anon cannot mark notifications read');
select is(has_function_privilege('anon','public.mark_all_notifications_read()','EXECUTE'),false,'anon cannot mark all notifications read');
select is(has_function_privilege('anon','public.dismiss_notification(uuid)','EXECUTE'),false,'anon cannot dismiss notifications');
select is(has_function_privilege('authenticated','public.mark_notification_read(uuid)','EXECUTE'),true,'authenticated can invoke owned notification read mutation');
select is(has_function_privilege('authenticated','public.mark_all_notifications_read()','EXECUTE'),true,'authenticated can invoke owned mark-all mutation');
select is(has_function_privilege('authenticated','public.dismiss_notification(uuid)','EXECUTE'),true,'authenticated can invoke owned notification dismissal');
select is((select not exists(select 1 from pg_catalog.aclexplode(coalesce(p.proacl,pg_catalog.acldefault('f',p.proowner))) a where a.grantee=0 and a.privilege_type='EXECUTE') from pg_catalog.pg_proc p where p.oid='public.mark_notification_read(uuid)'::regprocedure),true,'PUBLIC cannot mark notifications read');
select is((select not exists(select 1 from pg_catalog.aclexplode(coalesce(p.proacl,pg_catalog.acldefault('f',p.proowner))) a where a.grantee=0 and a.privilege_type='EXECUTE') from pg_catalog.pg_proc p where p.oid='public.mark_all_notifications_read()'::regprocedure),true,'PUBLIC cannot mark all notifications read');
select is((select not exists(select 1 from pg_catalog.aclexplode(coalesce(p.proacl,pg_catalog.acldefault('f',p.proowner))) a where a.grantee=0 and a.privilege_type='EXECUTE') from pg_catalog.pg_proc p where p.oid='public.dismiss_notification(uuid)'::regprocedure),true,'PUBLIC cannot dismiss notifications');
select * from finish();
rollback;
