import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { Image } from 'expo-image';
import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ScreenHeader } from '@/components/warsha/ScreenHeader';
import { BrandLoadingMark as ActivityIndicator } from '@/components/warsha/BrandMark';
import { BookingReviewCard } from '@/components/warsha/BookingReviewCard';
import { BookingPaymentCard } from '@/components/warsha/BookingPaymentCard';
import { BookingPriceAdjustmentCard } from '@/components/warsha/BookingPriceAdjustmentCard';
import { EligiblePromotionBanner } from '@/components/warsha/EligiblePromotionBanner';
import { BookingDisputePanel } from '@/components/warsha/BookingDisputePanel';
import { JobOperationsPanel } from '@/components/warsha/JobOperationsPanel';
import { CallCounterpartyButton } from '@/components/warsha/CallCounterpartyButton';
import { AppText } from '@/components/warsha/Typography';
import { StateBadge } from '@/components/warsha/BrandUI';
import { radii, spacing, typography, type ThemeColors } from '@/constants/theme';
import { useThemeColors, useThemedStyles } from '@/src/appearance/appearance-context';
import { useAuth } from '@/src/auth/auth-context';
import { useBookings } from '@/src/bookings/booking-context';
import { bookingStatusTranslationKeys, cancellableStatuses, formatAddress, getAllowedTransitions, reschedulableStatuses, type BookingStatus, type CancellationReason } from '@/src/bookings/booking-types';
import { isBookingChatActivated } from '@/src/chat/chat-lifecycle';
import { useMarketplaceData } from '@/src/data/marketplace-context';
import { useLocalization } from '@/src/i18n/localization';
import { useProviderJobText } from '@/src/i18n/provider-job-translations';
import type { TranslationKey } from '@/src/i18n/translations';
import { getSupabaseClient } from '@/src/lib/supabase';
import { marketplaceRepository } from '@/src/marketplace-intelligence/marketplace-repository';
import { marketplaceIdempotency } from '@/src/marketplace-intelligence/marketplace-types';
import { cataloguedServiceReferenceLabel } from '@/src/services/specific-services';
import { formatBookingDateTime, formatNumber, formatTimestamp, localeFor, toLocalISODate } from '@/src/utils/date-format';
import { bookingLifecycleSemantic, lifecycleBadgeTone } from '@/src/lifecycle/lifecycle-presentation';

const reasons:{value:CancellationReason;label:TranslationKey}[]=[{value:'plans_changed',label:'plansChanged'},{value:'booked_by_mistake',label:'bookedMistake'},{value:'provider_delay',label:'providerDelay'},{value:'price_concern',label:'priceConcern'},{value:'other',label:'other'}];
export default function BookingDetails(){
  const colors = useThemeColors();
  const styles = useThemedStyles(makeStyles);const{id}=useLocalSearchParams<{id:string}>();const{t,language,isRTL}=useLocalization();const jt=useProviderJobText();const auth=useAuth();const bookings=useBookings();const{getProvider,services}=useMarketplaceData();const booking=bookings.getBooking(id);const provider=booking?getProvider(booking.providerId):undefined;const[cancelOpen,setCancelOpen]=useState(false);const[reason,setReason]=useState<CancellationReason>();const[reschedule,setReschedule]=useState(false);const[newDate,setNewDate]=useState('');const[newTime,setNewTime]=useState('');const[proposalBusy,setProposalBusy]=useState(false);const[marketBusy,setMarketBusy]=useState(false);const dates=useMemo(()=>Array.from({length:5},(_,index)=>{const day=new Date();day.setDate(day.getDate()+index+1);return toLocalISODate(day)}),[]);if(!booking||!provider)return <SafeAreaView style={styles.safe}><ScreenHeader title={t('bookingDetails')}/><AppText style={styles.empty}>{t('bookingNotFound')}</AppText></SafeAreaView>;const serviceLabel=cataloguedServiceReferenceLabel(booking,services,language);const eligible=cancellableStatuses.includes(booking.status);const nextStatuses=getAllowedTransitions(booking.status).filter(status=>status!=='cancelled'&&status!=='rescheduling_requested');const price=booking.priceBreakdown;
  const respondProposal=async(accept:boolean)=>{if(proposalBusy)return;setProposalBusy(true);try{if(auth.mode==='supabase'){const{error}=await getSupabaseClient().rpc(accept?'accept_provider_reschedule':'reject_provider_reschedule',{p_booking_id:booking.id});if(error)throw error}else await bookings.simulateStatus(booking.id,'confirmed');await bookings.reload()}catch{Alert.alert(t('bookingDetails'),t('genericTryAgain'))}finally{setProposalBusy(false)}};
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><ScreenHeader title={t('bookingDetails')} subtitle={booking.id}/><View style={[styles.provider,isRTL&&styles.reverse]}><Image source={{uri:provider.image}} style={styles.avatar}/><View style={styles.grow}><AppText style={styles.name}>{provider.name}</AppText><AppText style={styles.muted}>{serviceLabel}</AppText></View><Badge status={booking.status}/></View>
    <Section title={t('bookingInformation')}><Row label={t('status')} value={t(bookingStatusTranslationKeys[booking.status])}/><Row label={t('dateAndTime')} value={formatBookingDateTime(booking.date,booking.time,localeFor(language),t('asap'))}/><Row label={t('bookingType')} value={booking.bookingType==='emergency'?t('emergency'):t('scheduled')}/><Row label={t('problem')} value={booking.issueDescription}/>{booking.notes?<Row label={t('notes')} value={booking.notes}/>:null}<Row label={t('addressStep')} value={formatAddress(booking.address)}/>{booking.rejectionReason?<Row label={jt('reason')} value={booking.rejectionReason}/>:null}</Section>
    {booking.status==='rescheduling_requested'?<Section title={jt('awaitingCustomer')}><Row label={jt('originalSchedule')} value={formatBookingDateTime(booking.date,booking.time,localeFor(language),t('asap'))}/><Row label={jt('proposedSchedule')} value={booking.proposedDate&&booking.proposedTime?formatBookingDateTime(booking.proposedDate,booking.proposedTime,localeFor(language),t('asap')):'—'}/>{booking.providerRescheduleNote?<Row label={jt('reason')} value={booking.providerRescheduleNote}/>:null}<Pressable disabled={proposalBusy} onPress={()=>void respondProposal(true)} style={styles.primary}>{proposalBusy?<ActivityIndicator color={colors.background}/>:<AppText style={styles.primaryText}>{jt('accept')}</AppText>}</Pressable><Pressable disabled={proposalBusy} onPress={()=>void respondProposal(false)} style={styles.outline}><AppText>{jt('reject')}</AppText></Pressable></Section>:null}
    {booking.attachments.length?<Section title={t('attachments')}><ScrollView horizontal contentContainerStyle={styles.gallery}>{booking.attachments.map(item=>item.uri?<Image key={item.id} source={{uri:item.uri}} style={styles.attachment}/>:null)}</ScrollView></Section>:null}
    <Section title={t('priceSummary')}><Price label={t('servicePrice')} value={price?.servicePrice||price?.inspectionFee||booking.price}/><Price label={t('transportationFee')} value={price?.transportationFee??0}/><Price label={t('emergencySurcharge')} value={price?.emergencySurcharge??0}/><Price label={t('discount')} value={-(price?.discount??0)}/><Price label={t('estimatedTotal')} value={price?.estimatedTotal??booking.price}/><AppText style={styles.warning}>{t('estimateNotice')}</AppText></Section>
    <EligiblePromotionBanner bookingId={booking.id} baseMinor={Math.round((price?.estimatedTotal??booking.price)*100)} onApplied={()=>bookings.reload()}/>
    <BookingPriceAdjustmentCard booking={booking} role="customer"/>
    <JobOperationsPanel booking={booking} role="customer" onBookingChanged={()=>bookings.reload()}/>
    <BookingDisputePanel booking={booking} role="customer"/>
    <BookingPaymentCard booking={booking}/>
    <Section title={t('bookingTimeline')}>{booking.history.map((event,index)=><View key={`${event.at}-${event.status}-${index}`} style={[styles.event,isRTL&&styles.reverse]}><View style={styles.marker}><View style={[styles.dot,['cancelled','rejected'].includes(event.status)&&styles.red]}/>{index<booking.history.length-1?<View style={styles.line}/>:null}</View><View style={styles.grow}><AppText style={styles.name}>{t(bookingStatusTranslationKeys[event.status])}</AppText>{event.note?<AppText style={styles.muted}>{event.note}</AppText>:null}<AppText style={styles.muted}>{formatTimestamp(event.at,localeFor(language))}</AppText></View></View>)}</Section>
    <BookingReviewCard bookingId={booking.id} providerId={booking.providerId} completed={booking.status==='completed'}/>
    <View style={styles.actions}>{isBookingChatActivated(booking)?<Pressable onPress={()=>router.push({pathname:'/conversation/[bookingId]',params:{bookingId:booking.id}})} style={styles.outline}><MaterialIcons name="chat-bubble-outline" size={18} color={colors.white}/><AppText style={styles.name}>{t('chat')}</AppText></Pressable>:null}{/* The Call action decides for itself whether to exist: it asks the server
       whether this booking is in a state where a call is appropriate, and
       renders nothing when it is not. Nothing on this screen ever holds a
       telephone number. */}<CallCounterpartyButton bookingId={booking.id} counterpartyRole="worker" counterpartyName={provider?.name} bookingStatus={booking.status}/>{reschedulableStatuses.includes(booking.status)?<Pressable onPress={()=>setReschedule(current=>!current)} style={styles.outline}><AppText style={styles.name}>{t('reschedule')}</AppText></Pressable>:null}{['confirmed','provider_on_the_way'].includes(booking.status)?<Pressable disabled={marketBusy} onPress={()=>Alert.alert(language==='ar'?'الصنايعي مجاش؟':'Worker did not arrive?',language==='ar'?'تقدر تبلغ بعد ١٥ دقيقة من آخر ميعاد وصول مؤكد.':'You can report this 15 minutes after the latest confirmed ETA.',[{text:t('back'),style:'cancel'},{text:language==='ar'?'إرسال البلاغ':'Report no-show',style:'destructive',onPress:async()=>{setMarketBusy(true);try{await marketplaceRepository.reportWorkerNoShow(booking.id,{customerConfirmedWait:true},marketplaceIdempotency('worker-no-show'));await bookings.reload()}catch{Alert.alert(t('bookingDetails'),t('genericTryAgain'))}finally{setMarketBusy(false)}}}])} style={styles.danger}><AppText style={styles.dangerText}>{language==='ar'?'بلاغ عدم حضور':'Report worker no-show'}</AppText></Pressable>:null}{booking.status==='completed'?<Pressable disabled={marketBusy} onPress={async()=>{setMarketBusy(true);try{const requestId=await marketplaceRepository.createComeback(booking.id,{issueDescription:booking.issueDescription,notes:'Comeback request'},marketplaceIdempotency('comeback'));router.push({pathname:'/marketplace-request/[id]',params:{id:requestId}})}catch{Alert.alert(language==='ar'?'الضمان غير متاح':'Warranty unavailable',language==='ar'?'الضمان لازم يكون مفعّل للفئة ولسه في مدته.':'This category must have an active, unexpired warranty policy.')}finally{setMarketBusy(false)}}} style={styles.outline}><AppText style={styles.name}>{language==='ar'?'طلب رجوع':'Request a comeback'}</AppText></Pressable>:null}{eligible?<Pressable onPress={()=>setCancelOpen(current=>!current)} style={styles.danger}><AppText style={styles.dangerText}>{t('cancelBooking')}</AppText></Pressable>:null}</View>
    {reschedule?<Section title={t('chooseNewSlot')}><View style={styles.wrap}>{dates.map(item=><Choice key={item} label={item} selected={newDate===item} onPress={()=>setNewDate(item)}/>)}</View><View style={styles.wrap}>{['09:00','11:00','13:00','15:00'].map(item=><Choice key={item} label={item} selected={newTime===item} onPress={()=>setNewTime(item)}/>)}</View><Pressable disabled={!newDate||!newTime} onPress={()=>{void bookings.rescheduleBooking(booking.id,newDate,newTime);setReschedule(false)}} style={styles.primary}><AppText style={styles.primaryText}>{t('saveNewSchedule')}</AppText></Pressable></Section>:null}
    {cancelOpen?<Section title={t('cancellationReason')}><View style={styles.wrap}>{reasons.map(item=><Choice key={item.value} label={t(item.label)} selected={reason===item.value} onPress={()=>setReason(item.value)}/>)}</View><AppText style={styles.warning}>{t('historyRetention')}</AppText><Pressable disabled={!reason} onPress={()=>{if(reason)void bookings.cancelBooking(booking.id,reason);setCancelOpen(false)}} style={styles.danger}><AppText style={styles.dangerText}>{t('confirmCancellation')}</AppText></Pressable></Section>:null}
    {__DEV__&&nextStatuses.length?<Section title={t('devControls')}><AppText style={styles.muted}>{t('devControlsHint')}</AppText><View style={styles.wrap}>{nextStatuses.map(status=><Pressable key={status} disabled={bookings.actionInFlight!==null} onPress={()=>void bookings.simulateStatus(booking.id,status)} style={[styles.dev,bookings.actionInFlight!==null&&styles.disabled]}><AppText style={styles.devText}>{t(bookingStatusTranslationKeys[status])}</AppText></Pressable>)}</View></Section>:null}
  </ScrollView></SafeAreaView>;
  function Price({label,value}:{label:string;value:number}){return <Row label={label} value={`${formatNumber(value,language)} ${t('currency')}`}/>}
}
function Section({title,children}:{title:string;children:React.ReactNode}){
  const styles = useThemedStyles(makeStyles);return <View style={styles.section}><AppText style={styles.sectionTitle}>{title}</AppText>{children}</View>}
function Row({label,value}:{label:string;value:string}){
  const styles = useThemedStyles(makeStyles);const{isRTL}=useLocalization();return <View style={[styles.row,isRTL&&styles.reverse]}><AppText style={styles.muted}>{label}</AppText><AppText style={styles.value}>{value}</AppText></View>}
function Choice({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){
  const styles = useThemedStyles(makeStyles);return <Pressable onPress={onPress} style={[styles.choice,selected&&styles.selected]}><AppText style={styles.devText}>{label}</AppText></Pressable>}
function Badge({status}:{status:BookingStatus}){
  const{t}=useLocalization();return <StateBadge label={t(bookingStatusTranslationKeys[status])} tone={lifecycleBadgeTone(bookingLifecycleSemantic(status))} compact />}
const makeStyles = (colors: ThemeColors) => StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,paddingBottom:spacing.xxxl,gap:spacing.xl,maxWidth:720,width:'100%',alignSelf:'center'},empty:{padding:spacing.xxxl},provider:{flexDirection:'row',alignItems:'center',gap:spacing.md,padding:spacing.md,borderWidth:1,borderColor:colors.borderSoft,borderRadius:radii.lg,backgroundColor:colors.surface},reverse:{flexDirection:'row-reverse'},avatar:{width:62,height:70,borderRadius:radii.md},grow:{flex:1,gap:4},name:{fontSize:14,fontWeight:typography.semibold},muted:{fontSize:11,lineHeight:16,color:colors.textMuted},section:{gap:spacing.lg,padding:spacing.lg,borderWidth:1,borderColor:colors.borderSoft,borderRadius:radii.lg,backgroundColor:colors.surface},sectionTitle:{fontSize:18,fontWeight:typography.semibold},row:{flexDirection:'row',justifyContent:'space-between',gap:spacing.lg},value:{fontSize:13,fontWeight:typography.semibold,flex:1.5},warning:{fontSize:11,lineHeight:17,color:colors.warning},gallery:{gap:spacing.sm},attachment:{width:120,height:100,borderRadius:radii.md},event:{flexDirection:'row',gap:spacing.md,minHeight:50},marker:{width:14,alignItems:'center'},dot:{width:10,height:10,borderRadius:5,backgroundColor:colors.success,marginTop:3},red:{backgroundColor:colors.error},line:{width:1,flex:1,backgroundColor:colors.border,marginTop:4},actions:{gap:spacing.sm},outline:{minHeight:50,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,flexDirection:'row',gap:spacing.sm,alignItems:'center',justifyContent:'center'},danger:{minHeight:50,borderWidth:1,borderColor:colors.actionDangerBorder,borderRadius:radii.lg,alignItems:'center',justifyContent:'center',padding:spacing.sm},dangerText:{fontSize:13,color:colors.error,fontWeight:typography.semibold},wrap:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},choice:{minHeight:40,paddingHorizontal:spacing.md,borderWidth:1,borderColor:colors.border,borderRadius:radii.md,alignItems:'center',justifyContent:'center'},selected:{borderColor:colors.white,backgroundColor:colors.surfaceElevated},primary:{minHeight:50,borderRadius:radii.md,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},primaryText:{color:colors.background,fontWeight:typography.bold},dev:{padding:spacing.sm,borderWidth:1,borderColor:colors.border,borderRadius:radii.md},devText:{fontSize:11,fontWeight:typography.medium},disabled:{opacity:.45}});
