import { useLocalization } from './localization';

const copy = {
  en: {
    required: 'Required', optional: 'Optional', addressName: 'Address name', addressNameHelp: 'Give this address a name, such as Home or Work.', address: 'Address', addressHelp: 'Street name and number.', governorate: 'Governorate', governorateHelp: 'The governorate where this address is located.', area: 'Area', areaHelp: 'Neighborhood, district, or local area.', building: 'Building', buildingHelp: 'Building name or number.', floor: 'Floor', floorHelp: 'Floor number, if applicable.', apartment: 'Apartment', apartmentHelp: 'Apartment or unit number, if applicable.', landmark: 'Nearby landmark', landmarkHelp: 'An easy-to-recognize place near this address, if helpful.', workerNotes: 'Notes for the worker', workerNotesHelp: 'Add directions or access details the worker should know.', useCurrentLocation: 'Use my current location', chooseOnMap: 'Choose location on map', searchAddress: 'Search for an address', searchPlaceholder: 'Start typing a street or place', locationSaved: 'Address found', locationPartial: 'Location found. Check the address details below.', lookupFailed: 'Location obtained, but address lookup failed. Complete the address below.', locating: 'Finding your location…', resolving: 'Finding the address…', locationFailed: 'We could not get that location. Try search or current location again.', permissionDenied: 'Location permission was denied. Allow it in device settings or search for the address.', servicesDisabled: 'Location services are off. Turn them on or search for the address.', deviceUnavailable: 'Your device could not provide a location. Search for the address or try again.', noResults: 'No matching addresses found.', providerUnavailable: 'Map and address search are unavailable right now. You can still enter the address and try current location.', permissionOptional: 'Location access is used once to place this address. Warsha does not request background location.', mapUnavailable: 'The map is unavailable right now.', mapHint: 'Move the pin to the exact service location.', loading: 'Loading location options…',
  },
  ar: {
    required: 'مطلوب', optional: 'اختياري', addressName: 'اسم العنوان', addressNameHelp: 'سمّي العنوان باسم واضح، زي البيت أو الشغل.', address: 'العنوان', addressHelp: 'اسم الشارع ورقم المبنى.', governorate: 'المحافظة', governorateHelp: 'المحافظة اللي العنوان موجود فيها.', area: 'المنطقة', areaHelp: 'الحي أو المنطقة المحلية.', building: 'المبنى', buildingHelp: 'اسم المبنى أو رقمه.', floor: 'الدور', floorHelp: 'رقم الدور لو ينطبق.', apartment: 'الشقة', apartmentHelp: 'رقم الشقة أو الوحدة لو ينطبق.', landmark: 'علامة مميزة قريبة', landmarkHelp: 'مكان معروف قريب من العنوان لو هيساعد في الوصول.', workerNotes: 'تعليمات للفني', workerNotesHelp: 'اكتب تعليمات الوصول أو الدخول اللي الفني محتاج يعرفها.', useCurrentLocation: 'استخدم موقعي الحالي', chooseOnMap: 'اختار الموقع على الخريطة', searchAddress: 'دور على عنوان', searchPlaceholder: 'اكتب اسم شارع أو مكان', locationSaved: 'لقينا العنوان', locationPartial: 'لقينا الموقع. راجع بيانات العنوان تحت.', lookupFailed: 'وصلنا للموقع لكن ماقدرناش نجيب العنوان. كمّل بياناته تحت.', locating: 'بندور على موقعك…', resolving: 'بندور على العنوان…', locationFailed: 'ماقدرناش نجيب الموقع. جرّب البحث أو الموقع الحالي تاني.', permissionDenied: 'إذن الموقع مرفوض. اسمح به من إعدادات الجهاز أو دور على العنوان.', servicesDisabled: 'خدمة الموقع مقفولة. شغّلها أو دور على العنوان.', deviceUnavailable: 'الجهاز ماقدرش يحدد موقع. دور على العنوان أو جرّب تاني.', noResults: 'مالقيناش عناوين مطابقة.', providerUnavailable: 'الخريطة والبحث عن عنوان مش متاحين دلوقتي. تقدر تكتب العنوان وتجرب موقعك الحالي.', permissionOptional: 'بنستخدم إذن الموقع مرة واحدة لتحديد العنوان. ورشة ما بتطلبش الموقع في الخلفية.', mapUnavailable: 'الخريطة مش متاحة دلوقتي.', mapHint: 'حرّك الدبوس لمكان الخدمة بالضبط.', loading: 'بنحمّل اختيارات الموقع…',
  },
  fr: {
    required: 'Obligatoire', optional: 'Facultatif', addressName: 'Nom de l’adresse', addressNameHelp: 'Donnez un nom à cette adresse, par exemple Maison ou Travail.', address: 'Adresse', addressHelp: 'Nom et numéro de rue.', governorate: 'Gouvernorat', governorateHelp: 'Le gouvernorat où se trouve cette adresse.', area: 'Quartier ou zone', areaHelp: 'Quartier, district ou zone locale.', building: 'Bâtiment', buildingHelp: 'Nom ou numéro du bâtiment.', floor: 'Étage', floorHelp: 'Numéro d’étage, si nécessaire.', apartment: 'Appartement', apartmentHelp: 'Numéro d’appartement ou d’unité, si nécessaire.', landmark: 'Point de repère', landmarkHelp: 'Un lieu facile à reconnaître à proximité, si utile.', workerNotes: 'Indications pour le professionnel', workerNotesHelp: 'Ajoutez les indications d’accès que le professionnel doit connaître.', useCurrentLocation: 'Utiliser ma position actuelle', chooseOnMap: 'Choisir sur la carte', searchAddress: 'Rechercher une adresse', searchPlaceholder: 'Commencez par une rue ou un lieu', locationSaved: 'Adresse trouvée', locationPartial: 'Position trouvée. Vérifiez les informations ci-dessous.', lookupFailed: 'Position obtenue, mais adresse introuvable. Complétez les informations ci-dessous.', locating: 'Recherche de votre position…', resolving: 'Recherche de l’adresse…', locationFailed: 'Impossible d’obtenir cette position. Réessayez ou recherchez une adresse.', permissionDenied: 'L’accès à la position a été refusé. Autorisez-le dans les réglages ou recherchez l’adresse.', servicesDisabled: 'Les services de localisation sont désactivés. Activez-les ou recherchez l’adresse.', deviceUnavailable: 'Votre appareil ne peut pas fournir de position. Recherchez l’adresse ou réessayez.', noResults: 'Aucune adresse correspondante.', providerUnavailable: 'La carte et la recherche sont indisponibles. Vous pouvez saisir l’adresse et essayer votre position actuelle.', permissionOptional: 'La position sert une seule fois à placer cette adresse. Warsha ne demande pas la localisation en arrière-plan.', mapUnavailable: 'La carte est indisponible pour le moment.', mapHint: 'Placez le repère exactement au lieu de l’intervention.', loading: 'Chargement des options de localisation…',
  },
} as const;

export type AddressFormCopyKey = keyof typeof copy.en;
export function useAddressFormText() { const { language } = useLocalization(); return (key: AddressFormCopyKey) => copy[language][key]; }
