import type { AddressLocationPickerCopy } from '@/components/warsha/AddressLocationPicker';
import { useLocalization } from './localization';

const copy = {
  en: {
    required: 'Required', optional: 'Optional', addressName: 'Address name', addressNameHelp: "Give this address a name, such as Home, Work, or Parents' house.", address: 'Address', addressHelp: 'Street name and number.', governorate: 'Governorate', governorateHelp: 'The governorate where this address is located.', area: 'Area', areaHelp: 'Neighborhood, district, or local area.', building: 'Building', buildingHelp: 'Building name or number.', floor: 'Floor', floorHelp: 'Floor number, if applicable.', apartment: 'Apartment', apartmentHelp: 'Apartment or unit number, if applicable.', landmark: 'Nearby landmark', landmarkHelp: 'An easy-to-recognize place near this address, if helpful.', workerNotes: 'Notes for the professional', workerNotesHelp: 'Add directions or access details the professional should know.', useCurrentLocation: 'Use my current location', chooseOnMap: 'Choose location on map', searchAddress: 'Search for an address', searchPlaceholder: 'Start typing a street or place', locationSaved: 'Address found', changeAddress: 'Change address', locationPartial: 'Location found. Check the address details below.', lookupFailed: 'Location obtained, but address lookup failed. Complete the address below.', locating: 'Finding your location…', resolving: 'Finding the address…', locationFailed: 'We could not get that location. Try search or current location again.', permissionDenied: 'Location permission was denied. Allow it in device settings or search for the address.', servicesDisabled: 'Location services are off. Turn them on or search for the address.', deviceUnavailable: 'Your device could not provide a location. Search for the address or try again.', noResults: 'No matching addresses found.', providerUnavailable: 'Map and address search are unavailable right now. You can still enter the address and try current location.', permissionOptional: 'Location access is used once to place this address. Warsha does not request background location.', mapUnavailable: 'The map is unavailable right now.', mapLoading: 'Loading the map…', mapHint: 'Move the pin to the exact service location.', loading: 'Loading location options…',
    confirmLocationTitle: 'Confirm where this address is', confirmLocationBody: 'Warsha only sends a request to a location you have confirmed. What you have written in this request stays here while you do it.', confirmLocationAction: 'Confirm this location', confirmLocationFailed: 'We could not confirm this location. Try again, or choose it another way.', locationNotConfirmed: 'Location not confirmed', confirmLocationPickerUnavailable: 'Map and address search are unavailable right now. You can still use your current location.', requestLocationRequired: 'Confirm the location of this address before sending the request.',
  },
  ar: {
    required: 'مطلوب', optional: 'اختياري', addressName: 'اسم العنوان', addressNameHelp: 'سمِّ هذا العنوان باسم يسهل تمييزه، مثل المنزل أو العمل.', address: 'العنوان', addressHelp: 'اسم الشارع ورقم المبنى.', governorate: 'المحافظة', governorateHelp: 'المحافظة اللي العنوان موجود فيها.', area: 'المنطقة', areaHelp: 'الحي أو المنطقة المحلية.', building: 'المبنى', buildingHelp: 'اسم المبنى أو رقمه.', floor: 'الدور', floorHelp: 'رقم الدور لو ينطبق.', apartment: 'الشقة', apartmentHelp: 'رقم الشقة أو الوحدة لو ينطبق.', landmark: 'علامة مميزة قريبة', landmarkHelp: 'مكان معروف قريب من العنوان لو هيساعد في الوصول.', workerNotes: 'تعليمات للصنايعي', workerNotesHelp: 'اكتب تعليمات الوصول أو الدخول اللي الصنايعي محتاج يعرفها.', useCurrentLocation: 'استخدم موقعي الحالي', chooseOnMap: 'اختار الموقع على الخريطة', searchAddress: 'دور على عنوان', searchPlaceholder: 'اكتب اسم شارع أو مكان', locationSaved: 'لقينا العنوان', changeAddress: 'غيّر العنوان', locationPartial: 'لقينا الموقع. راجع بيانات العنوان تحت.', lookupFailed: 'وصلنا للموقع لكن ماقدرناش نجيب العنوان. كمّل بياناته تحت.', locating: 'بندور على موقعك…', resolving: 'بندور على العنوان…', locationFailed: 'ماقدرناش نجيب الموقع. جرّب البحث أو الموقع الحالي تاني.', permissionDenied: 'إذن الموقع مرفوض. اسمح به من إعدادات الجهاز أو دور على العنوان.', servicesDisabled: 'خدمة الموقع مقفولة. شغّلها أو دور على العنوان.', deviceUnavailable: 'الجهاز ماقدرش يحدد موقع. دور على العنوان أو جرّب تاني.', noResults: 'مالقيناش عناوين مطابقة.', providerUnavailable: 'الخريطة والبحث عن عنوان مش متاحين دلوقتي. تقدر تكتب العنوان وتجرب موقعك الحالي.', permissionOptional: 'بنستخدم إذن الموقع مرة واحدة لتحديد العنوان. ورشة ما بتطلبش الموقع في الخلفية.', mapUnavailable: 'الخريطة مش متاحة دلوقتي.', mapLoading: 'بنحمّل الخريطة…', mapHint: 'حرّك الدبوس لمكان الخدمة بالضبط.', loading: 'بنحمّل اختيارات الموقع…',
    confirmLocationTitle: 'أكّد موقع العنوان ده', confirmLocationBody: 'ورشة بتبعت الطلب بس لموقع إنت أكّدته. اللي كتبته في الطلب ده بيفضل محفوظ وانت بتأكّد.', confirmLocationAction: 'أكّد الموقع ده', confirmLocationFailed: 'مقدرناش نأكّد الموقع ده. جرّب تاني أو اختاره بطريقة تانية.', locationNotConfirmed: 'الموقع مش متأكد', confirmLocationPickerUnavailable: 'الخريطة والبحث عن العناوين مش متاحين دلوقتي. لسه تقدر تستخدم موقعك الحالي.', requestLocationRequired: 'أكّد موقع العنوان ده قبل ما تبعت الطلب.',
  },
  fr: {
    required: 'Obligatoire', optional: 'Facultatif', addressName: 'Nom de l’adresse', addressNameHelp: 'Donnez un nom à cette adresse, par exemple Domicile ou Travail.', address: 'Adresse', addressHelp: 'Nom et numéro de rue.', governorate: 'Gouvernorat', governorateHelp: 'Le gouvernorat où se trouve cette adresse.', area: 'Quartier ou zone', areaHelp: 'Quartier, district ou zone locale.', building: 'Bâtiment', buildingHelp: 'Nom ou numéro du bâtiment.', floor: 'Étage', floorHelp: 'Numéro d’étage, si nécessaire.', apartment: 'Appartement', apartmentHelp: 'Numéro d’appartement ou d’unité, si nécessaire.', landmark: 'Point de repère', landmarkHelp: 'Un lieu facile à reconnaître à proximité, si utile.', workerNotes: 'Indications pour le professionnel', workerNotesHelp: 'Ajoutez les indications d’accès que le professionnel doit connaître.', useCurrentLocation: 'Utiliser ma position actuelle', chooseOnMap: 'Choisir sur la carte', searchAddress: 'Rechercher une adresse', searchPlaceholder: 'Commencez par une rue ou un lieu', locationSaved: 'Adresse trouvée', changeAddress: 'Changer d’adresse', locationPartial: 'Position trouvée. Vérifiez les informations ci-dessous.', lookupFailed: 'Position obtenue, mais adresse introuvable. Complétez les informations ci-dessous.', locating: 'Recherche de votre position…', resolving: 'Recherche de l’adresse…', locationFailed: 'Impossible d’obtenir cette position. Réessayez ou recherchez une adresse.', permissionDenied: 'L’accès à la position a été refusé. Autorisez-le dans les réglages ou recherchez l’adresse.', servicesDisabled: 'Les services de localisation sont désactivés. Activez-les ou recherchez l’adresse.', deviceUnavailable: 'Votre appareil ne peut pas fournir de position. Recherchez l’adresse ou réessayez.', noResults: 'Aucune adresse correspondante.', providerUnavailable: 'La carte et la recherche sont indisponibles. Vous pouvez saisir l’adresse et essayer votre position actuelle.', permissionOptional: 'La position sert une seule fois à placer cette adresse. Warsha ne demande pas la localisation en arrière-plan.', mapUnavailable: 'La carte est indisponible pour le moment.', mapLoading: 'Chargement de la carte…', mapHint: 'Placez le repère exactement au lieu de l’intervention.', loading: 'Chargement des options de localisation…',
    confirmLocationTitle: 'Confirmez l’emplacement de cette adresse', confirmLocationBody: 'Warsha n’envoie une demande qu’à un emplacement que vous avez confirmé. Ce que vous avez écrit dans cette demande est conservé pendant ce temps.', confirmLocationAction: 'Confirmer cet emplacement', confirmLocationFailed: 'Impossible de confirmer cet emplacement. Réessayez ou choisissez-le autrement.', locationNotConfirmed: 'Emplacement non confirmé', confirmLocationPickerUnavailable: 'La carte et la recherche d’adresse sont indisponibles pour le moment. Vous pouvez toujours utiliser votre position actuelle.', requestLocationRequired: 'Confirmez l’emplacement de cette adresse avant d’envoyer la demande.',
  },
} as const;

export type AddressFormCopyKey = keyof typeof copy.en;
export function useAddressFormText() { const { language } = useLocalization(); return (key: AddressFormCopyKey) => copy[language][key]; }

/**
 * The location picker's words, from this file. The booking form and the
 * request form's location confirmation both show the picker, and both used to
 * need the same twenty-one lookups written out.
 */
export function useAddressLocationPickerCopy(): AddressLocationPickerCopy {
  const addressText = useAddressFormText();
  return {
    useCurrentLocation: addressText('useCurrentLocation'), chooseOnMap: addressText('chooseOnMap'),
    searchAddress: addressText('searchAddress'), searchPlaceholder: addressText('searchPlaceholder'),
    locationSaved: addressText('locationSaved'), locationPartial: addressText('locationPartial'),
    addressLookupFailed: addressText('lookupFailed'), locating: addressText('locating'),
    resolvingAddress: addressText('resolving'), locationFailed: addressText('locationFailed'),
    locationPermissionDenied: addressText('permissionDenied'), locationServicesDisabled: addressText('servicesDisabled'),
    locationDeviceUnavailable: addressText('deviceUnavailable'), noSearchResults: addressText('noResults'),
    providerUnavailable: addressText('providerUnavailable'), permissionOptional: addressText('permissionOptional'),
    mapUnavailable: addressText('mapUnavailable'), changeAddress: addressText('changeAddress'),
    mapLoading: addressText('mapLoading'), mapDragHint: addressText('mapHint'), loading: addressText('loading'),
  };
}
