export const translations = {
  en: {
    home: 'Home', orders: 'Orders', chat: 'Chat', profile: 'Profile', currentLocation: 'Current location',
    address: '21 El Tahrir St, Zamalek', searchPlaceholder: 'Search for services…', categories: 'Services',
    featuredProviders: 'Featured providers', viewAll: 'View all', specialOffers: 'Special offers',
    recentBookings: 'Recent bookings', startsAt: 'Starts at', reviews: 'reviews', available: 'Available now',
    bookAgain: 'Book again', confirmed: 'Confirmed', offerTitle: 'A fresher home, for less',
    offerBody: 'Get 20% off your first deep cleaning this week.', claimOffer: 'Claim offer',
    plumbing: 'Plumbing', electrical: 'Electrical', carpentry: 'Carpentry', acRepair: 'AC repair', cleaning: 'Cleaning', painting: 'Painting',
    ordersEmpty: 'Your bookings will appear here.', chatEmpty: 'Your conversations will appear here.', profileEmpty: 'Your Warsha profile is coming next.', language: 'AR',
    browseServices:'Browse services',searchProviders:'Find a professional',searchHint:'Service, provider, area, or problem',allProviders:'All providers',providersFound:'professionals found',noProviders:'No professionals match your search.',filters:'Filters',recommended:'Recommended',nearest:'Nearest',topRated:'Top rated',lowestPrice:'Lowest price',availableOnly:'Available now',verifiedOnly:'Verified only',clearFilters:'Clear filters',about:'About',servicesAndPrices:'Services & prices',portfolio:'Recent work',reviewsTitle:'Customer reviews',experience:'Experience',completedJobs:'Jobs completed',responseTime:'Response time',serviceArea:'Service area',languages:'Languages',skills:'Skills',certifications:'Certifications',guarantee:'Warsha guarantee',cancellation:'Cancellation policy',chatNow:'Chat',bookNow:'Book now',years:'years',kmRadius:'km radius',fixed:'Fixed',starting:'Starting from',inspection:'Inspection fee',notFound:'Provider not found',back:'Back',
    plumbingDescription:'Leaks, fittings, heaters, and urgent plumbing repairs',electricalDescription:'Wiring, lighting, switches, and electrical faults',carpentryDescription:'Furniture, doors, shelving, and custom woodwork',acDescription:'Cleaning, maintenance, installation, and cooling faults',cleaningDescription:'Regular, deep, and move-in home cleaning',paintingDescription:'Interior painting, preparation, and decorative finishes',
    newBooking:'New booking',selectService:'Select a service',describeIssue:'Describe the issue',issueHint:'Tell the professional what needs to be fixed…',chooseSchedule:'Choose date and time',selectDate:'Select date',selectTime:'Select time',selectAddress:'Service address',addressHint:'Apartment, floor, and helpful directions',reviewBooking:'Review booking',continue:'Continue',confirmBooking:'Confirm booking',bookingConfirmed:'Booking confirmed',bookingConfirmedMessage:'Your professional has received the booking details.',bookingDetails:'Booking details',bookingNumber:'Booking number',provider:'Professional',service:'Service',dateAndTime:'Date & time',estimatedPrice:'Estimated price',status:'Status',cancelBooking:'Cancel booking',cancelQuestion:'Cancel this booking?',cancelWarning:'This action cannot be undone.',keepBooking:'Keep booking',yesCancel:'Yes, cancel',cancelled:'Cancelled',activeOrders:'Active',pastOrders:'Past',noActiveOrders:'No active bookings yet.',viewDetails:'View details',requiredField:'Please complete this step before continuing.',priceNotice:'Starting and inspection prices are not guaranteed final prices.',localDataNotice:'Saved locally for this app session.',
    signIn:'Sign in',signUp:'Create account',signOut:'Sign out',fullName:'Full name',email:'Email address',password:'Password',authWelcome:'Sign in to sync bookings securely.',createAccountHint:'Create a customer account to book professionals.',checkEmail:'Check your email to confirm your account.',authRequired:'Sign in before creating a booking.',authError:'Authentication error',
  },
  ar: {
    home: 'الرئيسية', orders: 'الطلبات', chat: 'المحادثات', profile: 'الحساب', currentLocation: 'الموقع الحالي',
    address: '٢١ شارع التحرير، الزمالك', searchPlaceholder: 'ابحث عن خدمة أو صنايعي…', categories: 'الخدمات',
    featuredProviders: 'صنايعية مميزون', viewAll: 'عرض الكل', specialOffers: 'عروض خاصة',
    recentBookings: 'آخر الحجوزات', startsAt: 'يبدأ من', reviews: 'تقييم', available: 'متاح الآن',
    bookAgain: 'احجز مجدداً', confirmed: 'مؤكد', offerTitle: 'بيت أنضف بسعر أقل',
    offerBody: 'خصم ٢٠٪ على أول حجز تنظيف عميق هذا الأسبوع.', claimOffer: 'استفد بالعرض',
    plumbing: 'سباكة', electrical: 'كهرباء', carpentry: 'نجارة', acRepair: 'صيانة تكييف', cleaning: 'تنظيف', painting: 'نقاشة',
    ordersEmpty: 'ستظهر حجوزاتك هنا.', chatEmpty: 'ستظهر محادثاتك هنا.', profileEmpty: 'حساب ورشة قادم في المرحلة التالية.', language: 'EN',
    browseServices:'تصفح الخدمات',searchProviders:'ابحث عن صنايعي',searchHint:'خدمة أو صنايعي أو منطقة أو مشكلة',allProviders:'كل الصنايعية',providersFound:'صنايعي متاح',noProviders:'لا يوجد صنايعية مطابقون لبحثك.',filters:'التصفية',recommended:'مقترح',nearest:'الأقرب',topRated:'الأعلى تقييماً',lowestPrice:'الأقل سعراً',availableOnly:'متاح الآن',verifiedOnly:'موثق فقط',clearFilters:'مسح التصفية',about:'نبذة',servicesAndPrices:'الخدمات والأسعار',portfolio:'أعمال سابقة',reviewsTitle:'آراء العملاء',experience:'الخبرة',completedJobs:'طلبات مكتملة',responseTime:'سرعة الرد',serviceArea:'نطاق الخدمة',languages:'اللغات',skills:'المهارات',certifications:'الشهادات',guarantee:'ضمان ورشة',cancellation:'سياسة الإلغاء',chatNow:'محادثة',bookNow:'احجز الآن',years:'سنوات',kmRadius:'كم نطاق الخدمة',fixed:'سعر ثابت',starting:'يبدأ من',inspection:'رسوم معاينة',notFound:'مقدم الخدمة غير موجود',back:'رجوع',
    plumbingDescription:'تسريب وتركيبات وسخانات وإصلاحات سباكة عاجلة',electricalDescription:'أسلاك وإضاءة ومفاتيح وأعطال كهربائية',carpentryDescription:'أثاث وأبواب وأرفف وأعمال خشب حسب الطلب',acDescription:'تنظيف وصيانة وتركيب وإصلاح أعطال التبريد',cleaningDescription:'تنظيف منزلي دوري وعميق وتنظيف قبل السكن',paintingDescription:'نقاشة داخلية وتجهيز حوائط وتشطيبات ديكورية',
    newBooking:'حجز جديد',selectService:'اختر الخدمة',describeIssue:'اوصف المشكلة',issueHint:'اشرح للصنايعي ما الذي يحتاج إصلاحاً…',chooseSchedule:'اختر الموعد',selectDate:'اختر اليوم',selectTime:'اختر الوقت',selectAddress:'عنوان الخدمة',addressHint:'الشقة والطابق وتعليمات الوصول',reviewBooking:'راجع الحجز',continue:'متابعة',confirmBooking:'تأكيد الحجز',bookingConfirmed:'تم تأكيد الحجز',bookingConfirmedMessage:'تم إرسال تفاصيل الحجز لمقدم الخدمة.',bookingDetails:'تفاصيل الحجز',bookingNumber:'رقم الحجز',provider:'مقدم الخدمة',service:'الخدمة',dateAndTime:'التاريخ والوقت',estimatedPrice:'السعر التقديري',status:'الحالة',cancelBooking:'إلغاء الحجز',cancelQuestion:'هل تريد إلغاء الحجز؟',cancelWarning:'لا يمكن التراجع عن هذا الإجراء.',keepBooking:'الاحتفاظ بالحجز',yesCancel:'نعم، إلغاء',cancelled:'ملغى',activeOrders:'الحالية',pastOrders:'السابقة',noActiveOrders:'لا توجد حجوزات حالية.',viewDetails:'عرض التفاصيل',requiredField:'أكمل هذه الخطوة قبل المتابعة.',priceNotice:'الأسعار المبدئية ورسوم المعاينة ليست سعراً نهائياً مضموناً.',localDataNotice:'محفوظ محلياً خلال جلسة التطبيق.',
    signIn:'تسجيل الدخول',signUp:'إنشاء حساب',signOut:'تسجيل الخروج',fullName:'الاسم الكامل',email:'البريد الإلكتروني',password:'كلمة المرور',authWelcome:'سجل الدخول لمزامنة حجوزاتك بأمان.',createAccountHint:'أنشئ حساب عميل لحجز الصنايعية.',checkEmail:'راجع بريدك لتأكيد حسابك.',authRequired:'سجل الدخول قبل إنشاء الحجز.',authError:'خطأ في تسجيل الدخول',
  },
} as const;

export type Language = keyof typeof translations;
export type TranslationKey = keyof typeof translations.en;




