import type { TranslationKey } from '@/src/i18n/translations';
import type { PinSource } from '@/src/onboarding/onboarding-types';

export type BookingStatus='draft'|'pending_provider_approval'|'accepted'|'rejected'|'rescheduling_requested'|'confirmed'|'provider_on_the_way'|'provider_arrived'|'job_started'|'awaiting_quote_approval'|'work_in_progress'|'awaiting_customer_confirmation'|'completed'|'disputed'|'cancelled'|'refunded'|'no_show';
export type BookingType='scheduled'|'emergency';
export type BookingStatusHistory={status:BookingStatus;at:string;note?:string};
export type BookingAttachment={id:string;uri:string;fileName?:string;mimeType?:string;kind?:'customer_issue'|'completion_evidence'};
export type Address={id:string;label:string;governorate:string;district:string;street:string;building:string;floor:string;apartment:string;landmark:string;instructions:string;isDefault?:boolean;latitude?:number;longitude?:number;pinSource?:PinSource};
export type TimeSlot={value:string;available:boolean;reason?:string};
export type PriceBreakdown={servicePrice:number;inspectionFee:number;transportationFee:number;emergencySurcharge:number;discount:number;estimatedTotal:number;pricingType:'fixed'|'starting'|'hourly'|'inspection'|'quote'};
export type CancellationReason='plans_changed'|'booked_by_mistake'|'provider_delay'|'price_concern'|'other';
export type Booking={id:string;providerId:string;serviceId:string;serviceTranslationKey?:string|null;serviceName:string;customerName?:string;issueDescription:string;notes:string;attachments:BookingAttachment[];address:Address|string;date:string;time:string;bookingType:BookingType;priceBreakdown?:PriceBreakdown;price:number;pricingType:'fixed'|'starting'|'hourly'|'inspection'|'quote';status:BookingStatus;history:BookingStatusHistory[];cancellationReason?:CancellationReason;rejectionReason?:string;proposedDate?:string;proposedTime?:string;providerRescheduleNote?:string;completionNotes?:string;createdAt:string;updatedAt?:string};
export type NewBooking=Omit<Booking,'id'|'status'|'history'|'createdAt'|'updatedAt'|'cancellationReason'|'customerName'|'rejectionReason'|'proposedDate'|'proposedTime'|'providerRescheduleNote'|'completionNotes'>;

export const bookingTransitions:Readonly<Record<BookingStatus,readonly BookingStatus[]>>={draft:[],pending_provider_approval:['accepted','rejected','rescheduling_requested','cancelled'],accepted:['confirmed','rescheduling_requested','cancelled'],rescheduling_requested:['pending_provider_approval','accepted','confirmed','cancelled'],confirmed:['provider_on_the_way','rescheduling_requested','cancelled'],provider_on_the_way:['provider_arrived','cancelled'],provider_arrived:['job_started','no_show','cancelled'],job_started:['work_in_progress','completed','disputed'],awaiting_quote_approval:[],work_in_progress:['completed','disputed'],awaiting_customer_confirmation:[],completed:['disputed'],disputed:['refunded'],rejected:[],cancelled:[],refunded:[],no_show:[]};
export const terminalStatuses:BookingStatus[]=['rejected','cancelled','refunded','no_show'];
export const cancellableStatuses:BookingStatus[]=['pending_provider_approval','accepted','rescheduling_requested','confirmed','provider_on_the_way','provider_arrived'];
/** The database reschedule RPC accepts exactly these customer-side states. */
export const reschedulableStatuses:BookingStatus[]=['pending_provider_approval','accepted','confirmed'];
export const timelineLabels:Record<BookingStatus,string>={draft:'Draft',pending_provider_approval:'Booking submitted — waiting for provider',accepted:'Provider accepted',rejected:'Provider rejected',rescheduling_requested:'Provider proposed another time',confirmed:'Booking confirmed',provider_on_the_way:'Provider on the way',provider_arrived:'Provider arrived',job_started:'Work started',awaiting_quote_approval:'Waiting for quote approval',work_in_progress:'Work in progress',awaiting_customer_confirmation:'Waiting for customer confirmation',completed:'Job completed',disputed:'Dispute opened',cancelled:'Booking cancelled',refunded:'Booking refunded',no_show:'No show'};
export const bookingStatusTranslationKeys:Record<BookingStatus,TranslationKey>={draft:'bookingDraftStatus',pending_provider_approval:'bookingSubmittedStatus',accepted:'providerAccepted',rejected:'providerRejected',rescheduling_requested:'providerRescheduleProposed',confirmed:'confirmBookingStatus',provider_on_the_way:'providerOnWay',provider_arrived:'providerArrived',job_started:'workStarted',awaiting_quote_approval:'awaitingQuoteApproval',work_in_progress:'workInProgress',awaiting_customer_confirmation:'awaitingCustomerConfirmation',completed:'jobCompleted',disputed:'disputeOpened',cancelled:'bookingCancelled',refunded:'bookingRefunded',no_show:'noShow'};
export function canTransition(from:BookingStatus,to:BookingStatus){return from!==to&&bookingTransitions[from].includes(to)}
export function getAllowedTransitions(status:BookingStatus){return bookingTransitions[status]}
export function normalizeHistory(history:BookingStatusHistory[]){const seen=new Set<string>();return [...history].filter((event)=>{const key=`${event.status}|${event.at}|${event.note??''}`;if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at))}
export function formatAddress(address:Address|string){return typeof address==='string'?address:[address.label,`${address.building} ${address.street}`,address.district,address.governorate,address.floor&&`Floor ${address.floor}`,address.apartment&&`Apt ${address.apartment}`,address.landmark].filter(Boolean).join(', ')}
