import { useLocalization } from '@/src/i18n/localization';

const copy = {
  en: {
    title: 'Messages', empty: 'No messages yet.', emptyBody: 'Send a message to coordinate this booking.', loadError: 'Could not load this conversation.', retry: 'Try again', offline: 'Message not sent. Check your connection and try again.', placeholder: 'Write a message', send: 'Send', gallery: 'Photo library', camera: 'Camera', photo: 'Photo', uploading: 'Uploading photo…', typingCustomer: 'Customer is typing…', typingProvider: 'Provider is typing…', sent: 'Sent', delivered: 'Delivered', read: 'Read', today: 'Today', yesterday: 'Yesterday', image: 'Image message', permissionCamera: 'Camera permission is required to take a photo.', permissionPhotos: 'Photo permission is required to attach an image.', messageTooLong: 'Messages can be up to 2,000 characters.', imageTooLarge: 'Images must be 8 MB or smaller.', imageLoadError: 'Could not load image.', refresh: 'Pull to refresh', loadOlder: 'Load earlier messages', conversationUnavailable: 'This conversation is unavailable.', system: 'Booking update', retryUpload: 'Retry upload', close: 'Close', attachment: 'Add photo', newMessage: 'New message', newMessageBody: 'You have a new message about your booking.', booking_pending_provider_approval: 'Booking request sent.', booking_accepted: 'Provider accepted the booking.', booking_provider_on_the_way: 'Provider is on the way.', booking_completed: 'Booking completed.',
  },
  ar: {
    title: 'الرسائل', empty: 'لا توجد رسائل بعد.', emptyBody: 'أرسل رسالة للتنسيق بشأن هذا الحجز.', loadError: 'تعذر تحميل هذه المحادثة.', retry: 'حاول مرة أخرى', offline: 'لم يتم إرسال الرسالة. تحقق من الاتصال وحاول مجددًا.', placeholder: 'اكتب رسالة', send: 'إرسال', gallery: 'مكتبة الصور', camera: 'الكاميرا', photo: 'صورة', uploading: 'جارٍ رفع الصورة…', typingCustomer: 'العميل يكتب…', typingProvider: 'مقدم الخدمة يكتب…', sent: 'تم الإرسال', delivered: 'تم التسليم', read: 'تمت القراءة', today: 'اليوم', yesterday: 'أمس', image: 'رسالة صورة', permissionCamera: 'يلزم إذن الكاميرا لالتقاط صورة.', permissionPhotos: 'يلزم إذن الصور لإرفاق صورة.', messageTooLong: 'الحد الأقصى للرسالة 2000 حرف.', imageTooLarge: 'يجب ألا يتجاوز حجم الصورة 8 ميجابايت.', imageLoadError: 'تعذر تحميل الصورة.', refresh: 'اسحب للتحديث', loadOlder: 'تحميل رسائل أقدم', conversationUnavailable: 'هذه المحادثة غير متاحة.', system: 'تحديث الحجز', retryUpload: 'إعادة محاولة الرفع', close: 'إغلاق', attachment: 'إضافة صورة', newMessage: 'رسالة جديدة', newMessageBody: 'لديك رسالة جديدة بشأن حجزك.', booking_pending_provider_approval: 'تم إرسال طلب الحجز.', booking_accepted: 'قبل مقدم الخدمة الحجز.', booking_provider_on_the_way: 'مقدم الخدمة في الطريق.', booking_completed: 'اكتمل الحجز.',
  },
} as const;

export type ChatCopyKey = keyof typeof copy.en;
export function useChatText() { const { language } = useLocalization(); return (key: ChatCopyKey) => copy[language][key]; }
