import Storage from 'expo-sqlite/kv-store';

import { environment } from '@/src/config/environment';
import { getSupabaseClient } from '@/src/lib/supabase';
import { emitMockRealtime } from '@/src/realtime/realtime-service';
import type { NotificationPage, WarshaNotification } from './notification-types';

const KEY = 'warsha:notifications:v1:mock-account';
const PAGE_SIZE = 20;
const mockSeed: WarshaNotification[] = [
  {id:'mock-notification-1',type:'new_booking_request',title:'Booking update',body:'Your booking has a new update.',bookingId:'MOCK-JOB-1',createdAt:new Date(Date.now()-2*3600000).toISOString()},
];
function mapRow(row: Record<string, unknown>): WarshaNotification {
  const data = row.data && typeof row.data === 'object' ? row.data as Record<string, unknown> : {};
  return {id:String(row.id),type:String(row.type),title:String(row.title??''),body:String(row.body??''),bookingId:typeof data.booking_id==='string'?data.booking_id:typeof data.bookingId==='string'?data.bookingId:undefined,providerId:typeof data.provider_id==='string'?data.provider_id:typeof data.providerId==='string'?data.providerId:undefined,readAt:typeof row.read_at==='string'?row.read_at:undefined,createdAt:String(row.created_at)};
}
async function mockRead(){const raw=await Storage.getItem(KEY);if(!raw){await Storage.setItem(KEY,JSON.stringify(mockSeed));return mockSeed}try{return JSON.parse(raw) as WarshaNotification[]}catch{return[]}}
async function mockWrite(items:WarshaNotification[]){await Storage.setItem(KEY,JSON.stringify(items))}
export async function createMockNotification(type:string,bookingId?:string,providerId?:string,dedupeKey?:string){if(environment.dataMode!=='mock')return;const items=await mockRead();if(items.some(item=>dedupeKey?item.dedupeKey===dedupeKey:item.type===type&&item.bookingId===bookingId&&item.providerId===providerId))return;const verification=type.startsWith('verification_');const financial=/^(payment_|refund_|earnings_|withdrawal_)/.test(type);const providerFinancial=/^(earnings_|withdrawal_)/.test(type);const item:WarshaNotification={id:`mock-notification-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,type,title:verification?'Verification update':financial?(providerFinancial?'Earnings update':'Payment update'):type==='new_review'?'Review received':type==='review_reply'?'Provider replied':'Booking update',body:verification?'Your provider verification has a new update.':financial?(providerFinancial?'Your earnings or withdrawal has a new update.':'Your payment has a new update.'):type==='new_review'?'A customer rated a completed booking.':type==='review_reply'?'Your provider replied to your review.':'Your booking has a new update.',bookingId,providerId,dedupeKey,createdAt:new Date().toISOString()};await mockWrite([item,...items]);emitMockRealtime({table:'notifications',event:'INSERT',id:item.id})}
const mockRepository={async list(offset=0):Promise<NotificationPage>{const items=(await mockRead()).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));return{items:items.slice(offset,offset+PAGE_SIZE),hasMore:offset+PAGE_SIZE<items.length}},async unreadCount(){return(await mockRead()).filter(item=>!item.readAt).length},async markRead(id:string){const items=await mockRead();const item=items.find(value=>value.id===id);if(item&&!item.readAt){item.readAt=new Date().toISOString();await mockWrite(items);emitMockRealtime({table:'notifications',event:'UPDATE',id})}},async markAllRead(){const items=await mockRead();const now=new Date().toISOString();let changed=false;for(const item of items)if(!item.readAt){item.readAt=now;changed=true}if(changed){await mockWrite(items);emitMockRealtime({table:'notifications',event:'UPDATE'})}},async dismiss(id:string){await mockWrite((await mockRead()).filter(item=>item.id!==id));emitMockRealtime({table:'notifications',event:'DELETE',id})}};
const supabaseRepository={async list(offset=0):Promise<NotificationPage>{const{data,error}=await getSupabaseClient().from('notifications').select('id,type,title,body,data,read_at,created_at').is('dismissed_at',null).order('created_at',{ascending:false}).range(offset,offset+PAGE_SIZE);if(error)throw error;const rows=data??[];return{items:rows.slice(0,PAGE_SIZE).map(row=>mapRow(row as Record<string,unknown>)),hasMore:rows.length>PAGE_SIZE}},async unreadCount(){const{count,error}=await getSupabaseClient().from('notifications').select('id',{count:'exact',head:true}).is('read_at',null).is('dismissed_at',null);if(error)throw error;return count??0},async markRead(id:string){const{error}=await getSupabaseClient().rpc('mark_notification_read',{p_notification_id:id});if(error)throw error},async markAllRead(){const{error}=await getSupabaseClient().rpc('mark_all_notifications_read');if(error)throw error},async dismiss(id:string){const{error}=await getSupabaseClient().rpc('dismiss_notification',{p_notification_id:id});if(error)throw error}};
export const notificationRepository=environment.dataMode==='supabase'?supabaseRepository:mockRepository;
