import { useLocalization } from '@/src/i18n/localization';

const copy = {
  en: {
    notifications:'Notifications',notificationBell:'Open notifications',markAllRead:'Mark all as read',markRead:'Mark as read',dismiss:'Dismiss notification',empty:'No notifications yet',emptyBody:'Booking updates and important account activity will appear here.',loadError:'Couldn’t load notifications.',retry:'Try again',loadMore:'Load more',newUpdate:'New update',justNow:'Just now',
    new_booking_request:'New booking request',booking_pending_provider_approval:'Booking request sent',booking_accepted:'Booking accepted',booking_rejected:'Booking rejected',booking_rescheduling_requested:'New schedule proposed',booking_reschedule_accepted:'Proposed schedule accepted',booking_reschedule_rejected:'Proposed schedule declined',booking_confirmed:'Booking confirmed',booking_provider_on_the_way:'Provider on the way',booking_provider_arrived:'Provider arrived',booking_job_started:'Work started',booking_work_in_progress:'Work in progress',booking_completed:'Work completed',booking_cancelled:'Booking cancelled',booking_no_show:'Customer no-show',booking_disputed:'Problem reported',booking_refunded:'Booking refunded',
    new_booking_requestBody:'A customer sent you a new booking request.',booking_pending_provider_approvalBody:'Your booking request was sent.',booking_acceptedBody:'The provider accepted your booking.',booking_rejectedBody:'The provider could not accept this booking.',booking_rescheduling_requestedBody:'The provider proposed another date and time.',booking_reschedule_acceptedBody:'The customer accepted your proposed schedule.',booking_reschedule_rejectedBody:'The customer declined your proposed schedule.',booking_confirmedBody:'The proposed schedule or booking was confirmed.',booking_provider_on_the_wayBody:'Your provider is on the way.',booking_provider_arrivedBody:'Your provider has arrived.',booking_job_startedBody:'Work on your booking has started.',booking_work_in_progressBody:'Your booking is now in progress.',booking_completedBody:'The provider marked the work as completed.',booking_cancelledBody:'This booking was cancelled.',booking_no_showBody:'The booking was marked as a no-show.',booking_disputedBody:'A problem was reported for this booking.',booking_refundedBody:'This booking was marked as refunded.',genericBody:'There is a new update for your booking.',
  },
  ar: {
    notifications:'الإشعارات',notificationBell:'فتح الإشعارات',markAllRead:'تحديد الكل كمقروء',markRead:'تحديد كمقروء',dismiss:'حذف الإشعار',empty:'لا توجد إشعارات حتى الآن',emptyBody:'ستظهر هنا تحديثات الحجوزات والأنشطة المهمة في حسابك.',loadError:'تعذر تحميل الإشعارات.',retry:'حاول مرة أخرى',loadMore:'عرض المزيد',newUpdate:'تحديث جديد',justNow:'الآن',
    new_booking_request:'طلب حجز جديد',booking_pending_provider_approval:'تم إرسال طلب الحجز',booking_accepted:'تم قبول الحجز',booking_rejected:'تم رفض الحجز',booking_rescheduling_requested:'اقتراح موعد جديد',booking_reschedule_accepted:'وافق العميل على الموعد',booking_reschedule_rejected:'رفض العميل الموعد',booking_confirmed:'تم تأكيد الحجز',booking_provider_on_the_way:'الفني في الطريق',booking_provider_arrived:'وصل الفني',booking_job_started:'بدأ تنفيذ العمل',booking_work_in_progress:'العمل جارٍ',booking_completed:'اكتمل العمل',booking_cancelled:'تم إلغاء الحجز',booking_no_show:'العميل لم يحضر',booking_disputed:'تم الإبلاغ عن مشكلة',booking_refunded:'تم رد المبلغ',
    new_booking_requestBody:'أرسل عميل طلب حجز جديد.',booking_pending_provider_approvalBody:'تم إرسال طلب حجزك إلى الفني.',booking_acceptedBody:'وافق الفني على حجزك.',booking_rejectedBody:'تعذر على الفني قبول هذا الحجز.',booking_rescheduling_requestedBody:'اقترح الفني تاريخًا ووقتًا آخرين.',booking_reschedule_acceptedBody:'وافق العميل على الموعد الذي اقترحته.',booking_reschedule_rejectedBody:'رفض العميل الموعد الذي اقترحته.',booking_confirmedBody:'تم تأكيد الحجز أو الموعد المقترح.',booking_provider_on_the_wayBody:'الفني في الطريق إليك.',booking_provider_arrivedBody:'وصل الفني إلى موقع الخدمة.',booking_job_startedBody:'بدأ الفني تنفيذ العمل.',booking_work_in_progressBody:'العمل في حجزك جارٍ الآن.',booking_completedBody:'حدد الفني العمل كمكتمل.',booking_cancelledBody:'تم إلغاء هذا الحجز.',booking_no_showBody:'تم تسجيل عدم الحضور لهذا الحجز.',booking_disputedBody:'تم الإبلاغ عن مشكلة في هذا الحجز.',booking_refundedBody:'تم تسجيل رد المبلغ لهذا الحجز.',genericBody:'يوجد تحديث جديد في حجزك.',
  },
} as const;

export type NotificationCopyKey = keyof typeof copy.en;
export function useNotificationText() { const { language } = useLocalization(); return (key: NotificationCopyKey) => copy[language][key]; }
export function notificationCopyKey(type: string): NotificationCopyKey {
  return type in copy.en ? type as NotificationCopyKey : 'newUpdate';
}
export function notificationBodyKey(type: string): NotificationCopyKey {
  const key = `${type}Body`;
  return key in copy.en ? key as NotificationCopyKey : 'genericBody';
}
