/**
 * Notification titles and bodies, in both languages.
 *
 * Split out of the translations module so it can be imported without
 * pulling in React Native. The web notification list needs exactly these
 * strings, and the parity rule is explicit that a second implementation of a
 * shared authority is a defect even when it looks correct — so the browser
 * reads this table rather than restating it.
 *
 * Nothing here imports anything. That is the point.
 */
const rawCopy = {
  en: {
    notifications:'Notifications',notificationBell:'Open notifications',markAllRead:'Mark all as read',markRead:'Mark as read',dismiss:'Dismiss notification',empty:'No notifications yet',emptyBody:'Booking updates and important account activity will appear here.',loadError:'Couldn’t load notifications.',retry:'Try again',loadMore:'Load more',newUpdate:'New update',justNow:'Just now',
    new_booking_request:'New booking request',booking_message:'New message',booking_pending_provider_approval:'Booking request sent',booking_accepted:'Booking accepted',booking_rejected:'Booking rejected',booking_rescheduling_requested:'New schedule proposed',booking_reschedule_accepted:'Proposed schedule accepted',booking_reschedule_rejected:'Proposed schedule declined',booking_confirmed:'Booking confirmed',booking_provider_on_the_way:'Provider on the way',booking_provider_arrived:'Provider arrived',booking_job_started:'Work started',booking_work_in_progress:'Work in progress',booking_completed:'Work completed',booking_cancelled:'Booking cancelled',booking_no_show:'Customer no-show',booking_disputed:'Problem reported',booking_refunded:'Booking refunded',operation_traveling:'Worker traveling',operation_arrived:'Worker arrived',operation_started:'Work started',operation_paused:'Work paused',operation_resumed:'Work resumed',operation_waiting_for_approval:'Approval needed',operation_additional_work:'Additional work update',operation_delay:'Delay update',operation_finished:'Work finished',operation_inspection:'Inspection ready',operation_completed:'Work completed',operation_return_visit:'Return visit update',review_unlocked:'Review available',verification_submitted:'Verification sent',verification_approved:'Identity verified',verification_rejected:'Verification needs attention',verification_resubmission_requested:'New verification photos needed',verification_expired:'Verification expired',
    new_booking_requestBody:'A customer sent you a new booking request.',booking_messageBody:'You have a new message about your booking.',booking_pending_provider_approvalBody:'Your booking request was sent.',booking_acceptedBody:'The provider accepted your booking.',booking_rejectedBody:'The provider could not accept this booking.',booking_rescheduling_requestedBody:'The provider proposed another date and time.',booking_reschedule_acceptedBody:'The customer accepted your proposed schedule.',booking_reschedule_rejectedBody:'The customer declined your proposed schedule.',booking_confirmedBody:'The proposed schedule or booking was confirmed.',booking_provider_on_the_wayBody:'Your provider is on the way.',booking_provider_arrivedBody:'Your provider has arrived.',booking_job_startedBody:'Work on your booking has started.',booking_work_in_progressBody:'Your booking is now in progress.',booking_completedBody:'The provider marked the work as completed.',booking_cancelledBody:'This booking was cancelled.',booking_no_showBody:'Customer no-show.',booking_disputedBody:'A problem was reported for this booking.',booking_refundedBody:'This booking was marked as refunded.',operation_travelingBody:'The worker is on the way.',operation_arrivedBody:'The worker arrived.',operation_startedBody:'Work on this booking started.',operation_pausedBody:'Work was paused with an auditable update.',operation_resumedBody:'Work resumed.',operation_waiting_for_approvalBody:'A customer decision is needed before work continues.',operation_additional_workBody:'There is an additional-work decision on this booking.',operation_delayBody:'The worker shared a delay update.',operation_finishedBody:'The work is ready for inspection.',operation_inspectionBody:'Review the finished work before closing the booking.',operation_completedBody:'The customer approved completion.',operation_return_visitBody:'There is a return-visit update on the same booking.',review_unlockedBody:'You can now review this completed booking.',verification_submittedBody:'Your photos were sent for review.',verification_approvedBody:'Customers can now see your verified identity.',verification_rejectedBody:'Open verification to see what needs changing.',verification_resubmission_requestedBody:'Please add the requested new photos.',verification_expiredBody:'Take new photos to restore your verified status.',genericBody:'There is a new update for your booking.',
  },
  ar: {
    notifications:'الإشعارات',notificationBell:'فتح الإشعارات',markAllRead:'تحديد الكل كمقروء',markRead:'تحديد كمقروء',dismiss:'حذف الإشعار',empty:'لا توجد إشعارات حتى الآن',emptyBody:'ستظهر هنا تحديثات الحجوزات والأنشطة المهمة في حسابك.',loadError:'تعذر تحميل الإشعارات.',retry:'حاول مرة أخرى',loadMore:'عرض المزيد',newUpdate:'تحديث جديد',justNow:'الآن',
    new_booking_request:'طلب حجز جديد',booking_pending_provider_approval:'تم إرسال طلب الحجز',booking_accepted:'تم قبول الحجز',booking_rejected:'تم رفض الحجز',booking_rescheduling_requested:'اقتراح موعد جديد',booking_reschedule_accepted:'وافق العميل على الموعد',booking_reschedule_rejected:'رفض العميل الموعد',booking_confirmed:'تم تأكيد الحجز',booking_provider_on_the_way:'الفني في الطريق',booking_provider_arrived:'وصل الفني',booking_job_started:'بدأ تنفيذ العمل',booking_work_in_progress:'العمل جارٍ',booking_completed:'اكتمل العمل',booking_cancelled:'تم إلغاء الحجز',booking_no_show:'العميل لم يحضر',booking_disputed:'تم الإبلاغ عن مشكلة',booking_refunded:'تم رد المبلغ',operation_traveling:'الصنايعي في الطريق',operation_arrived:'الصنايعي وصل',operation_started:'الشغل بدأ',operation_paused:'الشغل اتوقف مؤقتًا',operation_resumed:'الشغل اتكمل',operation_waiting_for_approval:'مطلوب موافقة',operation_additional_work:'تحديث شغل إضافي',operation_delay:'تحديث تأخير',operation_finished:'الشغل خلص',operation_inspection:'الشغل جاهز للمعاينة',operation_completed:'الشغل اكتمل',operation_return_visit:'تحديث زيارة الرجوع',review_unlocked:'المراجعة متاحة',verification_submitted:'تم إرسال التوثيق',verification_approved:'تم التحقق من الهوية',verification_rejected:'التوثيق يحتاج تعديل',verification_resubmission_requested:'مطلوب صور توثيق جديدة',verification_expired:'انتهى التوثيق',
    new_booking_requestBody:'أرسل عميل طلب حجز جديد.',booking_pending_provider_approvalBody:'تم إرسال طلب حجزك إلى الفني.',booking_acceptedBody:'وافق الفني على حجزك.',booking_rejectedBody:'تعذر على الفني قبول هذا الحجز.',booking_rescheduling_requestedBody:'اقترح الفني تاريخًا ووقتًا آخرين.',booking_reschedule_acceptedBody:'وافق العميل على الموعد الذي اقترحته.',booking_reschedule_rejectedBody:'رفض العميل الموعد الذي اقترحته.',booking_confirmedBody:'تم تأكيد الحجز أو الموعد المقترح.',booking_provider_on_the_wayBody:'الفني في الطريق إليك.',booking_provider_arrivedBody:'وصل الفني إلى موقع الخدمة.',booking_job_startedBody:'بدأ الفني تنفيذ العمل.',booking_work_in_progressBody:'العمل في حجزك جارٍ الآن.',booking_completedBody:'حدد الفني العمل كمكتمل.',booking_cancelledBody:'تم إلغاء هذا الحجز.',booking_no_showBody:'تم تسجيل عدم الحضور لهذا الحجز.',booking_disputedBody:'تم الإبلاغ عن مشكلة في هذا الحجز.',booking_refundedBody:'تم تسجيل رد المبلغ لهذا الحجز.',operation_travelingBody:'الصنايعي في الطريق.',operation_arrivedBody:'الصنايعي وصل.',operation_startedBody:'الشغل على الحجز بدأ.',operation_pausedBody:'الشغل اتوقف مؤقتًا بتحديث محفوظ في السجل.',operation_resumedBody:'الشغل اتكمل.',operation_waiting_for_approvalBody:'مطلوب قرار من العميل قبل ما الشغل يكمل.',operation_additional_workBody:'فيه قرار بخصوص شغل إضافي على الحجز.',operation_delayBody:'الصنايعي شارك تحديث تأخير.',operation_finishedBody:'الشغل جاهز للمعاينة.',operation_inspectionBody:'عاين الشغل قبل ما تقفل الحجز.',operation_completedBody:'العميل وافق على إكمال الشغل.',operation_return_visitBody:'فيه تحديث زيارة رجوع على نفس الحجز.',review_unlockedBody:'تقدر دلوقتي تراجع الحجز المكتمل.',verification_submittedBody:'تم إرسال صورك للمراجعة.',verification_approvedBody:'العملاء يقدروا يشوفوا إن هويتك موثقة.',verification_rejectedBody:'افتح التوثيق واعرف المطلوب تغييره.',verification_resubmission_requestedBody:'أضف الصور الجديدة المطلوبة.',verification_expiredBody:'صوّر صور جديدة علشان ترجع علامة التوثيق.',genericBody:'يوجد تحديث جديد في حجزك.',
  },
} as const;

export const copy = {
  en: {
    ...rawCopy.en,
    dispute_opened: 'Dispute opened', dispute_evidence_requested: 'Evidence requested', dispute_evidence_submitted: 'Evidence added', dispute_under_review: 'Dispute under review', dispute_resolved: 'Dispute resolved', dispute_closed: 'Dispute closed', dispute_cancelled: 'Dispute withdrawn',
    dispute_openedBody: 'A dispute was opened for this booking.', dispute_evidence_requestedBody: 'Warsha support requested more evidence.', dispute_evidence_submittedBody: 'New evidence was added to the dispute.', dispute_under_reviewBody: 'Warsha support is reviewing the dispute.', dispute_resolvedBody: 'A resolution is available for the dispute.', dispute_closedBody: 'The dispute was closed.', dispute_cancelledBody: 'The customer withdrew the dispute.',
  },
  ar: {
    ...rawCopy.ar,
    booking_message: 'رسالة جديدة', booking_messageBody: 'لديك رسالة جديدة بشأن حجزك.',
    dispute_opened: 'تم فتح نزاع', dispute_evidence_requested: 'مطلوب أدلة', dispute_evidence_submitted: 'اتضاف دليل', dispute_under_review: 'النزاع تحت المراجعة', dispute_resolved: 'النزاع اتحل', dispute_closed: 'النزاع اتقفل', dispute_cancelled: 'النزاع اتسحب',
    dispute_openedBody: 'اتفتح نزاع على الحجز ده.', dispute_evidence_requestedBody: 'فريق دعم ورشة طلب أدلة زيادة.', dispute_evidence_submittedBody: 'اتضاف دليل جديد للنزاع.', dispute_under_reviewBody: 'فريق دعم ورشة بيراجع النزاع.', dispute_resolvedBody: 'قرار النزاع بقى متاح.', dispute_closedBody: 'النزاع اتقفل.', dispute_cancelledBody: 'العميل سحب النزاع.',
  },
  fr: {
    ...rawCopy.en,
    notifications: 'Notifications', notificationBell: 'Ouvrir les notifications', markAllRead: 'Tout marquer comme lu', markRead: 'Marquer comme lu', dismiss: 'Masquer la notification', empty: 'Aucune notification', emptyBody: 'Les mises à jour de vos travaux et les activités importantes du compte apparaîtront ici.', loadError: 'Impossible de charger les notifications.', retry: 'Réessayer', loadMore: 'Afficher plus', newUpdate: 'Nouvelle mise à jour', justNow: "À l'instant",
    new_booking_request: 'Nouvelle demande de réservation', booking_message: 'Nouveau message', booking_pending_provider_approval: 'Demande de réservation envoyée', booking_accepted: 'Réservation acceptée', booking_rejected: 'Réservation refusée', booking_rescheduling_requested: 'Nouveau créneau proposé', booking_reschedule_accepted: 'Nouveau créneau accepté', booking_reschedule_rejected: 'Nouveau créneau refusé', booking_confirmed: 'Réservation confirmée', booking_provider_on_the_way: 'Le professionnel est en route', booking_provider_arrived: 'Le professionnel est arrivé', booking_job_started: 'Travail commencé', booking_work_in_progress: 'Travail en cours', booking_completed: 'Travail terminé', booking_cancelled: 'Réservation annulée', booking_no_show: 'Client absent', booking_disputed: 'Problème signalé', booking_refunded: 'Réservation remboursée', verification_submitted: 'Vérification envoyée', verification_approved: 'Identité vérifiée', verification_rejected: 'Vérification à corriger', verification_resubmission_requested: 'Nouvelles photos requises', verification_expired: 'Vérification expirée',
    operation_traveling: 'Professionnel en route', operation_arrived: 'Professionnel arrivé', operation_started: 'Travail commencé', operation_paused: 'Travail interrompu', operation_resumed: 'Travail repris', operation_waiting_for_approval: 'Accord requis', operation_additional_work: 'Mise à jour du travail supplémentaire', operation_delay: 'Mise à jour du retard', operation_finished: 'Travail prêt', operation_inspection: 'Contrôle requis', operation_completed: 'Travail terminé', operation_return_visit: 'Mise à jour de la visite de retour', review_unlocked: 'Avis disponible',
    new_booking_requestBody: 'Un client vous a envoyé une nouvelle demande.', booking_messageBody: 'Vous avez un nouveau message concernant votre réservation.', booking_pending_provider_approvalBody: 'Votre demande de réservation a été envoyée.', booking_acceptedBody: 'Le professionnel a accepté votre réservation.', booking_rejectedBody: "Le professionnel n'a pas pu accepter cette réservation.", booking_rescheduling_requestedBody: 'Le professionnel a proposé une autre date et heure.', booking_reschedule_acceptedBody: 'Le client a accepté le créneau proposé.', booking_reschedule_rejectedBody: 'Le client a refusé le créneau proposé.', booking_confirmedBody: 'La réservation ou le créneau proposé a été confirmé.', booking_provider_on_the_wayBody: 'Votre professionnel est en route.', booking_provider_arrivedBody: 'Votre professionnel est arrivé.', booking_job_startedBody: 'Le travail a commencé.', booking_work_in_progressBody: 'Votre réservation est en cours.', booking_completedBody: 'Le professionnel a marqué le travail comme terminé.', booking_cancelledBody: 'Cette réservation a été annulée.', booking_no_showBody: "L'absence du client a été enregistrée.", booking_disputedBody: 'Un problème a été signalé pour cette réservation.', booking_refundedBody: 'Cette réservation a été marquée comme remboursée.', verification_submittedBody: 'Vos photos ont été envoyées pour examen.', verification_approvedBody: 'Les clients peuvent voir que votre identité est vérifiée.', verification_rejectedBody: 'Ouvrez la vérification pour voir les corrections demandées.', verification_resubmission_requestedBody: 'Ajoutez les nouvelles photos demandées.', verification_expiredBody: 'Prenez de nouvelles photos pour restaurer votre statut.', genericBody: 'Une nouvelle mise à jour est disponible.',
    operation_travelingBody: 'Le professionnel est en route.', operation_arrivedBody: 'Le professionnel est arrivé.', operation_startedBody: 'Le travail a commencé.', operation_pausedBody: 'Le travail a été interrompu avec une mise à jour enregistrée.', operation_resumedBody: 'Le travail a repris.', operation_waiting_for_approvalBody: 'Votre décision est nécessaire avant la poursuite du travail.', operation_additional_workBody: 'Une décision concernant un travail supplémentaire est disponible.', operation_delayBody: 'Le professionnel a signalé un retard.', operation_finishedBody: 'Le travail est prêt à être contrôlé.', operation_inspectionBody: 'Vérifiez le travail terminé avant de clôturer la réservation.', operation_completedBody: 'Le client a approuvé la fin du travail.', operation_return_visitBody: 'Une visite de retour a été mise à jour pour cette réservation.', review_unlockedBody: 'Vous pouvez maintenant évaluer ce travail terminé.',
    dispute_opened: 'Litige ouvert', dispute_evidence_requested: 'Justificatifs demandés', dispute_evidence_submitted: 'Justificatif ajouté', dispute_under_review: 'Litige en cours d’examen', dispute_resolved: 'Litige résolu', dispute_closed: 'Litige fermé', dispute_cancelled: 'Litige retiré', dispute_openedBody: 'Un litige a été ouvert pour cette réservation.', dispute_evidence_requestedBody: "L'assistance Warsha a demandé des justificatifs supplémentaires.", dispute_evidence_submittedBody: 'Un nouveau justificatif a été ajouté.', dispute_under_reviewBody: "L'assistance Warsha examine le litige.", dispute_resolvedBody: 'Une résolution est disponible.', dispute_closedBody: 'Le litige a été fermé.', dispute_cancelledBody: 'Le client a retiré le litige.',
  },
} as const;

export type NotificationCopyKey = keyof typeof copy.en;
export function notificationCopyKey(type: string): NotificationCopyKey {
  return type in copy.en ? type as NotificationCopyKey : 'newUpdate';
}
export function notificationBodyKey(type: string): NotificationCopyKey {
  const key = `${type}Body`;
  return key in copy.en ? key as NotificationCopyKey : 'genericBody';
}
export function legacyNotificationEventCopy(language: 'en' | 'ar' | 'fr', type: string) {
  const values = copy[language] as Record<string, string>;
  if (!(type in values)) return undefined;
  return { title: values[type], body: values[`${type}Body`] ?? values.genericBody };
}
