/**
 * WPS-019 copy tables, in full English, Egyptian Arabic, and French.
 *
 * This module is deliberately free of imports so the regression suite can load
 * it directly under Node, which does not resolve the '@/' alias. The React hook
 * that consumes it lives in support-translations.ts.
 *
 * The Arabic is Egyptian spoken register, not Modern Standard translation. A
 * customer who is confused enough to open support is not helped by formal prose
 * they have to decode.
 */

export const supportCopy = {
  en: {
    helpCenter: 'Help Center',
    helpCenterIntro: 'Find an answer, or talk to us.',
    searchPlaceholder: 'Search help',
    searchAction: 'Search help articles',
    clearSearch: 'Clear search',
    recentSearches: 'Recent searches',
    popularSearches: 'Popular searches',
    suggestedForYou: 'Suggested for you',
    popularArticles: 'Most read',
    browseCategories: 'Browse by topic',
    articleCount: 'articles',
    noResults: 'No article matched that.',
    noResultsBody: 'Try a different word, or contact support and we will answer you directly.',
    approximateMatch: 'Closest match',
    queryTooShort: 'Type at least two characters.',
    wasThisHelpful: 'Was this helpful?',
    yes: 'Yes',
    no: 'No',
    thanksForFeedback: 'Thanks — that helps us write better articles.',
    relatedArticles: 'Related',
    backToHelp: 'Back to Help Center',

    contactSupport: 'Contact support',
    contactSupportBody: 'If the articles did not answer it, open a case and a person will reply.',
    myCases: 'My support cases',
    noCases: 'You have not contacted support yet.',
    noCasesBody: 'When you do, your cases and every reply will be here.',
    newCase: 'New support case',
    subject: 'What is this about?',
    subjectPlaceholder: 'A short summary',
    describe: 'Tell us what happened',
    describePlaceholder: 'The more detail you give, the faster we can help.',
    category: 'Topic',
    submit: 'Send to support',
    submitting: 'Sending…',
    caseOpened: 'Your case is open. We will reply here.',

    reply: 'Reply',
    replyPlaceholder: 'Add a reply',
    sendReply: 'Send reply',
    caseClosed: 'This case is closed. Open a new one if you still need help.',
    reopen: 'Reopen this case',
    reopenReason: 'What is still unresolved?',
    reopenWindowPassed: 'The reopen window has passed. Open a new case and mention this one.',
    reopenLimit: 'This case cannot be reopened again.',
    attach: 'Add a photo or PDF',
    attachments: 'Attachments',
    attachmentLimit: 'You have added the maximum number of files.',
    attachmentTooLarge: 'That file is larger than 8 MB.',
    attachmentWrongType: 'Only JPEG, PNG, HEIC, and PDF files can be attached.',
    attachmentDuplicate: 'That file is already attached.',
    attachmentFailed: 'The upload did not finish. Try again.',
    retryUpload: 'Retry upload',

    survey: 'How did we do?',
    surveyBody: 'Your answer is private and helps us fix what is slow.',
    surveyComment: 'Anything you want to add?',
    surveySubmit: 'Send rating',
    surveyThanks: 'Thanks for telling us.',

    status_open: 'Open',
    status_in_progress: 'Being worked on',
    status_waiting_participant: 'Waiting for you',
    status_escalated: 'Escalated',
    status_resolved: 'Resolved',
    status_closed: 'Closed',

    category_account_access: 'Signing in',
    category_booking_help: 'A booking',
    category_worker_onboarding: 'Becoming a worker',
    category_verification_help: 'Verification',
    category_payment_question: 'A payment',
    category_withdrawal_question: 'Withdrawing earnings',
    category_technical_issue: 'Something is broken',
    category_app_feedback: 'Feedback',
    category_other: 'Something else',

    loading: 'Loading',
    loadError: 'Couldn’t load that.',
    retry: 'Try again',
    close: 'Close',
    notFound: 'That is not available.',

    staffQueue: 'Support queue',
    staffOpen: 'Open',
    staffInProgress: 'In progress',
    staffWaiting: 'Waiting',
    staffEscalated: 'Escalated',
    staffMine: 'Assigned to me',
    staffBreached: 'Past first response',
    staffAssign: 'Assign to me',
    staffResolve: 'Resolve',
    staffMacros: 'Response templates',
    staffResolutionReason: 'Resolution reason',
    staffNote: 'Internal note',
    staffNoteHint: 'Internal notes are never shown to the customer.',
    staffSla: 'Response targets',
    staffMockUnavailable: 'Staff support actions need a real Supabase session.',
  },
  ar: {
    helpCenter: 'مركز المساعدة',
    helpCenterIntro: 'لاقي إجابة، أو كلّمنا.',
    searchPlaceholder: 'دوّر في المساعدة',
    searchAction: 'ابحث في مقالات المساعدة',
    clearSearch: 'امسح البحث',
    recentSearches: 'آخر عمليات بحث',
    popularSearches: 'الأكثر بحثًا',
    suggestedForYou: 'مقترح ليك',
    popularArticles: 'الأكثر قراءة',
    browseCategories: 'تصفّح حسب الموضوع',
    articleCount: 'مقال',
    noResults: 'مفيش مقال طلع بالكلام ده.',
    noResultsBody: 'جرّب كلمة تانية، أو كلّم الدعم وإحنا هنرد عليك على طول.',
    approximateMatch: 'أقرب نتيجة',
    queryTooShort: 'اكتب حرفين على الأقل.',
    wasThisHelpful: 'المقال ده فادك؟',
    yes: 'أيوة',
    no: 'لأ',
    thanksForFeedback: 'شكرًا — ده بيساعدنا نكتب أحسن.',
    relatedArticles: 'مقالات ليها علاقة',
    backToHelp: 'ارجع لمركز المساعدة',

    contactSupport: 'كلّم الدعم',
    contactSupportBody: 'لو المقالات مردتش على سؤالك، افتح حالة وحد هيرد عليك.',
    myCases: 'حالات الدعم بتاعتي',
    noCases: 'لسه ماكلمتش الدعم.',
    noCasesBody: 'أول ما تكلّمنا، هتلاقي حالاتك وكل الردود هنا.',
    newCase: 'حالة دعم جديدة',
    subject: 'الموضوع إيه؟',
    subjectPlaceholder: 'ملخص قصير',
    describe: 'قولنا اللي حصل',
    describePlaceholder: 'كل ما تفصّل أكتر، كل ما نساعدك أسرع.',
    category: 'الموضوع',
    submit: 'ابعت للدعم',
    submitting: 'جاري الإرسال…',
    caseOpened: 'حالتك اتفتحت. هنرد عليك هنا.',

    reply: 'رد',
    replyPlaceholder: 'اكتب رد',
    sendReply: 'ابعت الرد',
    caseClosed: 'الحالة دي مقفولة. افتح واحدة جديدة لو لسه محتاج مساعدة.',
    reopen: 'افتح الحالة تاني',
    reopenReason: 'إيه اللي لسه مش متظبط؟',
    reopenWindowPassed: 'مدة إعادة الفتح خلصت. افتح حالة جديدة واذكر الحالة دي.',
    reopenLimit: 'الحالة دي مش هتتفتح تاني.',
    attach: 'ضيف صورة أو ملف PDF',
    attachments: 'المرفقات',
    attachmentLimit: 'وصلت لأقصى عدد ملفات.',
    attachmentTooLarge: 'الملف ده أكبر من ٨ ميجا.',
    attachmentWrongType: 'المسموح بس JPEG و PNG و HEIC و PDF.',
    attachmentDuplicate: 'الملف ده مرفوع بالفعل.',
    attachmentFailed: 'الرفع مكملش. حاول تاني.',
    retryUpload: 'حاول ترفع تاني',

    survey: 'إيه رأيك في خدمتنا؟',
    surveyBody: 'ردّك خاص وبيساعدنا نظبّط اللي بيبطّأ.',
    surveyComment: 'عايز تضيف حاجة؟',
    surveySubmit: 'ابعت التقييم',
    surveyThanks: 'شكرًا إنك قلتلنا.',

    status_open: 'مفتوحة',
    status_in_progress: 'بنشتغل عليها',
    status_waiting_participant: 'مستنيين ردك',
    status_escalated: 'اتصعّدت',
    status_resolved: 'اتحلت',
    status_closed: 'مقفولة',

    category_account_access: 'تسجيل الدخول',
    category_booking_help: 'حجز',
    category_worker_onboarding: 'أبقى صنايعي',
    category_verification_help: 'التوثيق',
    category_payment_question: 'دفعة',
    category_withdrawal_question: 'سحب الأرباح',
    category_technical_issue: 'فيه حاجة بايظة',
    category_app_feedback: 'رأيك في التطبيق',
    category_other: 'حاجة تانية',

    loading: 'جاري التحميل',
    loadError: 'مقدرناش نحمّل ده.',
    retry: 'حاول تاني',
    close: 'اقفل',
    notFound: 'ده مش متاح.',

    staffQueue: 'قائمة الدعم',
    staffOpen: 'مفتوحة',
    staffInProgress: 'شغالين عليها',
    staffWaiting: 'مستنية',
    staffEscalated: 'متصعّدة',
    staffMine: 'مسندة ليا',
    staffBreached: 'عدّت وقت أول رد',
    staffAssign: 'اسندها ليا',
    staffResolve: 'حلّها',
    staffMacros: 'ردود جاهزة',
    staffResolutionReason: 'سبب الحل',
    staffNote: 'ملاحظة داخلية',
    staffNoteHint: 'الملاحظات الداخلية عمرها ما بتظهر للعميل.',
    staffSla: 'أهداف الرد',
    staffMockUnavailable: 'إجراءات الدعم للفريق محتاجة جلسة Supabase حقيقية.',
  },
  fr: {
    helpCenter: 'Centre d’aide',
    helpCenterIntro: 'Trouvez une réponse ou contactez-nous.',
    searchPlaceholder: 'Rechercher dans l’aide',
    searchAction: 'Rechercher dans les articles d’aide',
    clearSearch: 'Effacer la recherche',
    recentSearches: 'Recherches récentes',
    popularSearches: 'Recherches fréquentes',
    suggestedForYou: 'Suggestions pour vous',
    popularArticles: 'Articles les plus consultés',
    browseCategories: 'Parcourir par sujet',
    articleCount: 'articles',
    noResults: 'Aucun article ne correspond à cette recherche.',
    noResultsBody: 'Essayez un autre mot ou contactez l’assistance pour obtenir une réponse.',
    approximateMatch: 'Résultat le plus proche',
    queryTooShort: 'Saisissez au moins deux caractères.',
    wasThisHelpful: 'Cet article vous a-t-il aidé ?',
    yes: 'Oui', no: 'Non',
    thanksForFeedback: 'Merci — votre avis nous aide à améliorer nos articles.',
    relatedArticles: 'Articles associés',
    backToHelp: 'Retour au Centre d’aide',

    contactSupport: 'Contacter l’assistance',
    contactSupportBody: 'Si les articles ne répondent pas à votre question, ouvrez une demande. Une personne vous répondra.',
    myCases: 'Mes demandes d’assistance',
    noCases: 'Vous n’avez pas encore contacté l’assistance.',
    noCasesBody: 'Vos demandes et toutes les réponses apparaîtront ici.',
    newCase: 'Nouvelle demande d’assistance',
    subject: 'Quel est le sujet ?', subjectPlaceholder: 'Un résumé court',
    describe: 'Expliquez-nous ce qui s’est passé',
    describePlaceholder: 'Plus vous donnez de détails utiles, plus nous pouvons vous aider rapidement.',
    category: 'Sujet', submit: 'Envoyer à l’assistance', submitting: 'Envoi…',
    caseOpened: 'Votre demande est ouverte. Nous vous répondrons ici.',

    reply: 'Répondre', replyPlaceholder: 'Ajouter une réponse', sendReply: 'Envoyer la réponse',
    caseClosed: 'Cette demande est fermée. Ouvrez-en une nouvelle si vous avez encore besoin d’aide.',
    reopen: 'Rouvrir cette demande', reopenReason: 'Quel problème reste à résoudre ?',
    reopenWindowPassed: 'Le délai de réouverture est dépassé. Ouvrez une nouvelle demande en mentionnant celle-ci.',
    reopenLimit: 'Cette demande ne peut plus être rouverte.',
    attach: 'Ajouter une photo ou un PDF', attachments: 'Pièces jointes',
    attachmentLimit: 'Vous avez atteint le nombre maximal de fichiers.',
    attachmentTooLarge: 'Ce fichier dépasse 8 Mo.',
    attachmentWrongType: 'Seuls les fichiers JPEG, PNG, HEIC et PDF sont acceptés.',
    attachmentDuplicate: 'Ce fichier est déjà joint.',
    attachmentFailed: 'Le fichier n’a pas été entièrement envoyé. Réessayez.',
    retryUpload: 'Réessayer l’envoi',

    survey: 'Comment s’est passée notre assistance ?',
    surveyBody: 'Votre réponse reste privée et nous aide à améliorer les délais.',
    surveyComment: 'Souhaitez-vous ajouter quelque chose ?', surveySubmit: 'Envoyer l’évaluation', surveyThanks: 'Merci pour votre avis.',

    status_open: 'Ouverte', status_in_progress: 'En cours', status_waiting_participant: 'En attente de votre réponse', status_escalated: 'Transmise', status_resolved: 'Résolue', status_closed: 'Fermée',
    category_account_access: 'Connexion au compte', category_booking_help: 'Un travail', category_worker_onboarding: 'Devenir professionnel', category_verification_help: 'Vérification', category_payment_question: 'Un paiement', category_withdrawal_question: 'Retrait des revenus', category_technical_issue: 'Problème technique', category_app_feedback: 'Avis sur l’application', category_other: 'Autre sujet',
    loading: 'Chargement', loadError: 'Impossible de charger ces informations.', retry: 'Réessayer', close: 'Fermer', notFound: 'Cet élément n’est pas disponible.',

    staffQueue: 'File d’assistance', staffOpen: 'Ouvertes', staffInProgress: 'En cours', staffWaiting: 'En attente', staffEscalated: 'Transmises', staffMine: 'Mes demandes', staffBreached: 'Premier délai de réponse dépassé', staffAssign: 'Me l’attribuer', staffResolve: 'Résoudre', staffMacros: 'Modèles de réponse', staffResolutionReason: 'Motif de résolution', staffNote: 'Note interne', staffNoteHint: 'Les notes internes ne sont jamais affichées au client.', staffSla: 'Objectifs de réponse', staffMockUnavailable: 'Les actions du personnel exigent une véritable session Supabase.',
  },
} as const;

export type SupportTextKey = keyof typeof supportCopy.en;
