import Storage from 'expo-sqlite/kv-store';
import { File } from 'expo-file-system';
import { environment } from '@/src/config/environment';
import { getSupabaseClient } from '@/src/lib/supabase';
import type { ProviderDraft } from './provider-types';
import { emptyProviderDraft } from './provider-types';
const KEY='warsha:provider-foundation:v1';
export interface ProviderRepository{load():Promise<ProviderDraft|null>;activate(name:string):Promise<ProviderDraft>;save(value:ProviderDraft,submit?:boolean):Promise<ProviderDraft>;setAvailability(available:boolean):Promise<ProviderDraft>;uploadAvatar(uri:string,mime?:string):Promise<string>}
const mock:ProviderRepository={async load(){const raw=await Storage.getItem(KEY);if(!raw)return null;const saved=JSON.parse(raw) as ProviderDraft&{isOnline?:boolean};const next={...saved,id:'mostafa',isAvailable:saved.isAvailable??saved.isOnline??false};delete (next as {isOnline?:boolean}).isOnline;if(saved.id!==next.id||saved.isAvailable===undefined)await Storage.setItem(KEY,JSON.stringify(next));return next},async activate(displayName){const old=await this.load();if(old)return old;const next={...emptyProviderDraft,id:'mostafa',displayName};await Storage.setItem(KEY,JSON.stringify(next));return next},async save(value,submit){const next={...value,id:'mostafa',status:submit?'submitted':value.status} as ProviderDraft;await Storage.setItem(KEY,JSON.stringify(next));return next},async setAvailability(isAvailable){const current=await this.load();if(!current)throw new Error('Provider profile not found');const next={...current,isAvailable};await Storage.setItem(KEY,JSON.stringify(next));return next},async uploadAvatar(uri){return uri}};
function map(row:Record<string,unknown>):ProviderDraft{const links=(row.provider_services as Record<string,unknown>[])??[];return{id:String(row.id),status:String(row.onboarding_status??'draft') as ProviderDraft['status'],displayName:String(row.display_name??''),avatarUrl:String(row.avatar_url??''),profession:String(row.profession_key??''),about:String(row.about??''),experienceYears:Number(row.experience_years??0),ratingAverage:Number(row.rating_average??0),languages:(row.languages as string[])??[],skills:(row.skills as string[])??[],categoryIds:(row.category_ids as string[])??[],services:links.map(x=>({serviceId:String(x.service_id),name:String((x.service as Record<string,unknown>)?.name??''),price:Number(x.custom_price_egp??0),pricingModel:String(x.pricing_type??'starting') as ProviderDraft['services'][number]['pricingModel'],transportationFee:Number(x.transportation_fee_egp??0),emergencySurcharge:Number(x.emergency_surcharge_egp??0)})),areas:((row.provider_service_areas as Record<string,unknown>[])??[]).map(x=>({governorate:String(x.governorate),district:String(x.district??''),radiusKm:Number(x.radius_km??0)})),serviceRadiusKm:Number(row.service_radius_km??15),isAvailable:Boolean(row.is_available),emergencyAvailable:Boolean(row.emergency_available),temporaryUnavailableUntil:row.temporary_unavailable_until?String(row.temporary_unavailable_until):undefined,agreementAccepted:Boolean(row.provider_agreement_accepted_at)}}
async function currentUser(){const{data,error}=await getSupabaseClient().auth.getUser();if(error)throw error;return data.user}
async function loadSupabase(){const user=await currentUser();if(!user)return null;const{data,error}=await getSupabaseClient().from('provider_profiles').select('*,provider_services(*,service:services(name)),provider_service_areas(*)').eq('user_id',user.id).maybeSingle();if(error)throw error;return data?map(data as Record<string,unknown>):null}
const supabase:ProviderRepository={load:loadSupabase,async activate(displayName){const{error}=await getSupabaseClient().rpc('activate_provider_role',{p_display_name:displayName});if(error)throw error;const loaded=await loadSupabase();if(!loaded)throw new Error('Unable to load provider profile');return loaded},async save(value,submit){const{error}=await getSupabaseClient().rpc('save_provider_foundation',{p_profile:value,p_submit:Boolean(submit)});if(error)throw error;const loaded=await loadSupabase();if(!loaded)throw new Error('Unable to load provider profile');return loaded},async setAvailability(available){const{error}=await getSupabaseClient().rpc('mark_worker_available',{p_available:available});if(error)throw error;const loaded=await loadSupabase();if(!loaded)throw new Error('Unable to load provider profile');return loaded},async uploadAvatar(uri,mimeType='image/jpeg'){const user=await currentUser();if(!user)throw new Error('Authentication required');const file=new File(uri);if(!file.exists||file.size>5*1024*1024||!mimeType.startsWith('image/'))throw new Error('Invalid profile image');const path=`${user.id}/provider-avatar${file.extension||'.jpg'}`;const client=getSupabaseClient();const{data:old}=await client.storage.from('profile-images').list(user.id);const{error}=await client.storage.from('profile-images').upload(path,await file.arrayBuffer(),{contentType:mimeType,upsert:true});if(error)throw error;const stale=(old??[]).map(x=>`${user.id}/${x.name}`).filter(x=>x!==path);if(stale.length)void client.storage.from('profile-images').remove(stale);return client.storage.from('profile-images').getPublicUrl(path).data.publicUrl}};
export const providerRepository=environment.dataMode==='supabase'?supabase:mock;
export async function listProviderServiceOptions(){if(environment.dataMode==='mock'){const{providers}=await import('@/src/data/mock-data');return[...new Map(providers.flatMap(x=>x.services).map(x=>[x.id,{id:x.id,name:x.name}])).values()]}const{data,error}=await getSupabaseClient().from('services').select('id,name').eq('is_active',true).is('deleted_at',null).order('name');if(error)throw error;return data}
