import Storage from 'expo-sqlite/kv-store';
import { createContext,PropsWithChildren,useCallback,useContext,useEffect,useMemo,useState } from 'react';
import { useAuth } from '@/src/auth/auth-context';
import { dataErrorKey,logDataError } from '@/src/data/data-errors';
import type { TranslationKey } from '@/src/i18n/translations';
import { providerRepository } from './provider-repository';
import type { ProviderDraft } from './provider-types';
type AppMode='customer'|'provider';type Value={profile:ProviderDraft|null;mode:AppMode;loading:boolean;saving:boolean;error:TranslationKey|null;activate:(name:string)=>Promise<void>;save:(value:ProviderDraft,submit?:boolean)=>Promise<void>;setMode:(mode:AppMode)=>Promise<void>;reload:()=>Promise<void>;uploadAvatar:(uri:string,mime?:string)=>Promise<string>};const Context=createContext<Value|null>(null);const MODE_KEY='warsha:selected-app-mode:v1';
export function ProviderFoundationProvider({children}:PropsWithChildren){const{mode:dataMode,user}=useAuth();const[profile,setProfile]=useState<ProviderDraft|null>(null);const[mode,setModeState]=useState<AppMode>('customer');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState<TranslationKey|null>(null);const reload=useCallback(async()=>{if(dataMode==='supabase'&&!user){setProfile(null);setLoading(false);return}setLoading(true);try{const[next,savedMode]=await Promise.all([providerRepository.load(),Storage.getItem(MODE_KEY)]);setProfile(next);setModeState(savedMode==='provider'&&next?'provider':'customer');setError(null)}catch(reason){logDataError('provider foundation',reason);setError(dataErrorKey(reason))}finally{setLoading(false)}},[dataMode,user]);useEffect(()=>{void reload()},[reload]);const value=useMemo<Value>(()=>({profile,mode,loading,saving,error,reload,activate:async name=>{setSaving(true);try{setProfile(await providerRepository.activate(name));await Storage.setItem(MODE_KEY,'provider');setModeState('provider')}catch(reason){logDataError('provider activation',reason);setError(dataErrorKey(reason));throw reason}finally{setSaving(false)}},save:async(value,submit)=>{setSaving(true);try{setProfile(await providerRepository.save(value,submit));setError(null)}catch(reason){logDataError('provider save',reason);setError(dataErrorKey(reason));throw reason}finally{setSaving(false)}},setMode:async next=>{if(next==='provider'&&!profile)return;await Storage.setItem(MODE_KEY,next);setModeState(next)},uploadAvatar:(uri,mime)=>providerRepository.uploadAvatar(uri,mime)}),[error,loading,mode,profile,reload,saving]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useProviderFoundation(){const value=useContext(Context);if(!value)throw new Error('useProviderFoundation must be used within ProviderFoundationProvider');return value}
