import { useLocalization } from '@/src/i18n/localization';

const copy = {
  en: {
    homeTitle: 'Your work',
    available: 'Available',
    unavailable: 'Unavailable',
    suspendedTitle: 'Your worker account is on hold',
    suspendedBody: 'Open support to understand what happens next and how to resolve it.',
    suspendedAction: 'Get help',
    activeJobTitle: 'Continue your current job',
    activeJobBody: 'The next job step is ready.',
    activeJobAction: 'Continue job',
    newRequestsTitle: (count: number) => `You have ${count} new ${count === 1 ? 'request' : 'requests'}`,
    newRequestsBody: 'Open them now and choose the work that suits you.',
    newRequestsAction: 'View requests',
    verifyTitle: 'Complete verification',
    verifyBody: 'Finish the remaining steps so your account is ready.',
    verifyAction: 'Continue',
    reviewTitle: 'Your documents are being reviewed',
    reviewBody: 'We will tell you as soon as there is an update.',
    reviewAction: 'View status',
    waitingTitle: "You're available",
    waitingBody: "We'll notify you when work arrives.",
    unavailableTitle: "You're unavailable",
    unavailableBody: 'Go available when you are ready for new work.',
    goAvailable: 'Go available',
    newRequests: 'New requests',
    myJobs: 'My jobs',
    verification: 'Verification',
    earnings: 'Earnings',
    myProfile: 'My profile',
    support: 'Support',
    settings: 'Settings',
    requestService: 'Request a service',
    requestServiceHint: 'Need work done at home?',
    notifications: 'Notifications',
    messages: 'Messages',
    jobsTitle: 'My jobs',
    settingsTitle: 'Settings',
    appearance: 'Appearance',
    notificationSettings: 'Notification settings',
    privacy: 'Privacy and account',
    backHome: 'Back to your work',
    journeyTitle: 'Set up your work account',
    journeyStep: 'Step',
    welcomeTitle: 'Welcome to Warsha',
    welcomeBody: 'We will guide you. Finish one simple step at a time.',
    basicTitle: 'Tell customers about you',
    basicBody: 'Add your name and a clear photo. The introduction and experience are your choice.',
    fullName: 'Full name',
    about: 'A short introduction',
    aboutExample: 'Example: I repair air conditioners and have worked in this trade for years.',
    experience: 'Years of experience',
    experienceExample: 'Example: 5',
    addPhoto: 'Add your photo',
    tradeTitle: 'Choose your trade',
    tradeBody: 'Choose the work you can do.',
    profession: 'Your trade',
    services: 'Services you offer',
    areaTitle: 'Where can you work?',
    areaBody: 'Add your service area and your current address.',
    governorate: 'Governorate',
    district: 'Area',
    addAddress: 'Add current address',
    identityTitle: 'Verify your identity',
    identityBody: 'Take your ID photos and a selfie. We will guide you.',
    certificateTitle: 'Upload the criminal-record certificate',
    certificateBody: 'You obtain the official certificate, then upload it here.',
    reviewJourneyTitle: 'Your application is complete',
    reviewJourneyBody: 'We will show your status here and tell you if anything is needed.',
    saveContinue: 'Save and continue',
    continueJourney: 'Continue',
    retry: 'Try again',
    requiredFields: 'Please complete this step first.',
    required: 'Required',
    optional: 'Optional',
    privateLabel: 'Private',
    photoPurpose: 'Customers will see this photo.',
    fullNamePurpose: 'Customers will see your name.',
    aboutPurpose: 'Customers will see this only if you add it.',
    experiencePurpose: 'Customers may see this on your profile.',
    professionPlural: 'Profession(s)',
    professionPurpose: 'Warsha uses this to send you suitable jobs.',
    servicesPurpose: 'Choose the specific work customers can request.',
    governoratePurpose: 'Choose the governorate where you work.',
    districtPurpose: 'Choose the area where you work.',
    currentAddressPurpose: "Warsha uses this for job matching. Customers won't see your exact home address.",
    workLocationTitle: 'Your work location',
    workLocationIntro: "Warsha uses your location to find jobs near you. Customers won't see your exact home address.",
    selectedWorkArea: 'Your selected work area',
    useCurrentLocation: 'Use my current location',
    chooseLocationOnMap: 'Choose location on map',
    searchAddress: 'Search for an address',
    searchAddressPlaceholder: 'Type a street or place',
    locationSaved: 'Location saved',
    locationPartial: 'Location found. Review the address before continuing.',
    locationLookupFailed: 'Location obtained, but the address could not be looked up. You can still continue with your selected work area.',
    locationLocating: 'Locating…',
    locationResolving: 'Resolving address…',
    locationFailed: 'We could not get that location. Try another option.',
    locationPermissionDenied: 'Location permission was not granted. Choose another option, or allow it in Settings.',
    locationServicesDisabled: 'Location services are off. Turn them on, then try again.',
    locationDeviceUnavailable: 'Your device has no location fix yet. If you are using an emulator, set a simulated location and try again.',
    locationNoResults: 'No matching places found. Try a simpler search.',
    locationProviderUnavailable: 'Map and address search are unavailable right now. You can still use your current location.',
    locationPermissionOptional: 'Location permission is optional. You can choose another method instead.',
    locationLoading: 'Finding your location',
    locationRequired: 'Choose your location before continuing.',
    mapDragHint: 'Tap the map or move the pin to your work location.',
    workAreaMissing: 'Go back and choose your governorate and area first.',
    identityPurpose: 'Warsha uses this only to verify your identity.',
    certificatePurpose: 'Warsha uses this only for worker verification.',
    chooseProfessions: 'Choose professions',
    changeProfessions: 'Change professions',
    searchProfessions: 'Search professions',
    removeProfession: 'Remove',
    selected: 'selected',
    done: 'Done',
    close: 'Close',
    selectGovernorate: 'Choose governorate',
    selectArea: 'Choose area',
    searchPlaces: 'Search places',
    changePhoto: 'Change photo',
    choosePhotoSource: 'Add your photo',
    photoPreviewTitle: 'Check your photo',
    photoSourceHint: 'Use a clear photo of your face.',
    takePhoto: 'Take photo',
    chooseGallery: 'Choose from gallery',
    usePhoto: 'Use this photo',
    retake: 'Retake',
    chooseAnother: 'Choose another',
    photoPermission: 'Allow photo access to continue.',
    photoProcessing: 'Preparing your photo',
    photoProcessingError: 'This photo could not be prepared. Choose another one.',
    photoUploadError: 'This photo could not be saved. Try again.',
    loadingNextStep: 'Opening the next step',
  },
  ar: {
    homeTitle: 'شغلك',
    available: 'متاح',
    unavailable: 'غير متاح',
    suspendedTitle: 'حسابك كصنايعي موقوف مؤقتاً',
    suspendedBody: 'افتح المساعدة علشان تعرف الخطوة الجاية وإزاي تحل المشكلة.',
    suspendedAction: 'اطلب مساعدة',
    activeJobTitle: 'كمّل شغلك الحالي',
    activeJobBody: 'الخطوة الجاية في الشغل جاهزة.',
    activeJobAction: 'كمّل الشغل',
    newRequestsTitle: (count: number) => `عندك ${count} طلب شغل جديد`,
    newRequestsBody: 'افتح الطلبات واختار الشغل المناسب ليك.',
    newRequestsAction: 'شوف الطلبات',
    verifyTitle: 'كمّل التحقق',
    verifyBody: 'خلّص الخطوات الناقصة علشان حسابك يبقى جاهز.',
    verifyAction: 'كمّل',
    reviewTitle: 'مستنداتك بتتراجع',
    reviewBody: 'هنقولك أول ما يكون في جديد.',
    reviewAction: 'شوف الحالة',
    waitingTitle: 'إنت متاح للشغل',
    waitingBody: 'هنبعتلك أول ما يوصلك شغل.',
    unavailableTitle: 'إنت غير متاح دلوقتي',
    unavailableBody: 'خلّي نفسك متاح لما تبقى جاهز لشغل جديد.',
    goAvailable: 'خلّيني متاح',
    newRequests: 'طلبات جديدة',
    myJobs: 'شغلي',
    verification: 'التحقق',
    earnings: 'أرباحي',
    myProfile: 'ملفي',
    support: 'المساعدة',
    settings: 'الإعدادات',
    requestService: 'اطلب خدمة',
    requestServiceHint: 'محتاج حاجة تتعمل في البيت؟',
    notifications: 'الإشعارات',
    messages: 'الرسائل',
    jobsTitle: 'شغلي',
    settingsTitle: 'الإعدادات',
    appearance: 'شكل التطبيق',
    notificationSettings: 'إعدادات الإشعارات',
    privacy: 'الخصوصية والحساب',
    backHome: 'ارجع لشغلك',
    journeyTitle: 'جهّز حساب شغلك',
    journeyStep: 'خطوة',
    welcomeTitle: 'أهلاً بيك في ورشة',
    welcomeBody: 'هنمشي معاك خطوة بخطوة. خلّص حاجة واحدة كل مرة.',
    basicTitle: 'عرّف العملاء بيك',
    basicBody: 'ضيف اسمك وصورة واضحة. النبذة وسنين الخبرة اختياريين.',
    fullName: 'الاسم بالكامل',
    about: 'كلمتين عن شغلك',
    aboutExample: 'مثال: بصلّح تكييفات وبشتغل في المهنة من سنين.',
    experience: 'سنين الخبرة',
    experienceExample: 'مثال: 5',
    addPhoto: 'ضيف صورتك',
    tradeTitle: 'اختار مهنتك',
    tradeBody: 'اختار الشغل اللي بتعرف تعمله.',
    profession: 'مهنتك',
    services: 'الخدمات اللي بتقدمها',
    areaTitle: 'بتشتغل فين؟',
    areaBody: 'ضيف منطقة شغلك وعنوانك الحالي.',
    governorate: 'المحافظة',
    district: 'المنطقة',
    addAddress: 'ضيف عنوانك الحالي',
    identityTitle: 'اتحقق من هويتك',
    identityBody: 'صوّر البطاقة وخد سيلفي. هنمشي معاك خطوة بخطوة.',
    certificateTitle: 'ارفع الفيش والتشبيه',
    certificateBody: 'إنت اللي بتطلع الشهادة الرسمية وبعدها ترفعها هنا.',
    reviewJourneyTitle: 'طلبك اكتمل',
    reviewJourneyBody: 'هنوضحلك الحالة هنا ونقولك لو محتاجين حاجة.',
    saveContinue: 'احفظ وكمّل',
    continueJourney: 'كمّل',
    retry: 'جرّب تاني',
    requiredFields: 'كمّل الخطوة دي الأول.',
    required: 'مطلوب',
    optional: 'اختياري',
    privateLabel: 'خاص',
    photoPurpose: 'العملاء هيشوفوا الصورة دي.',
    fullNamePurpose: 'العملاء هيشوفوا اسمك.',
    aboutPurpose: 'العملاء هيشوفوا النبذة بس لو ضفتها.',
    experiencePurpose: 'العملاء ممكن يشوفوا سنين الخبرة في ملفك.',
    professionPlural: 'المهنة أو المهن',
    professionPurpose: 'ورشة بتستخدمها علشان تبعتلك شغل مناسب.',
    servicesPurpose: 'اختار الشغل المحدد اللي العميل يقدر يطلبه.',
    governoratePurpose: 'اختار المحافظة اللي بتشتغل فيها.',
    districtPurpose: 'اختار المنطقة اللي بتشتغل فيها.',
    currentAddressPurpose: 'ورشة بتستخدم عنوانك لمطابقة الشغل. العميل مش هيشوف عنوان بيتك بالتفصيل.',
    workLocationTitle: 'مكان شغلك',
    workLocationIntro: 'ورشة بتستخدم موقعك علشان تلاقي شغل قريب منك. العملاء مش هيشوفوا عنوان بيتك بالتفصيل.',
    selectedWorkArea: 'منطقة الشغل اللي اخترتها',
    useCurrentLocation: 'استخدم موقعي الحالي',
    chooseLocationOnMap: 'اختار الموقع على الخريطة',
    searchAddress: 'دوّر على عنوان',
    searchAddressPlaceholder: 'اكتب شارع أو مكان',
    locationSaved: 'الموقع اتحفظ',
    locationPartial: 'لقينا الموقع. راجع العنوان قبل ما تكمّل.',
    locationLookupFailed: 'حددنا الموقع، لكن ما قدرناش نجيب العنوان. تقدر تكمّل بمنطقة الشغل اللي اخترتها.',
    locationLocating: 'بنحدد موقعك…',
    locationResolving: 'بنجيب العنوان…',
    locationFailed: 'معرفناش نجيب الموقع ده. جرّب طريقة تانية.',
    locationPermissionDenied: 'إذن الموقع متوافقش عليه. اختار طريقة تانية أو اسمح به من الإعدادات.',
    locationServicesDisabled: 'خدمات الموقع مقفولة. افتحها وحاول تاني.',
    locationDeviceUnavailable: 'الجهاز لسه محددش موقع. لو بتستخدم محاكي، حدد له موقع تجريبي وحاول تاني.',
    locationNoResults: 'ملقيناش مكان مطابق. جرّب بحث أبسط.',
    locationProviderUnavailable: 'الخريطة والبحث عن عنوان مش متاحين دلوقتي. تقدر تستخدم موقعك الحالي.',
    locationPermissionOptional: 'إذن الموقع اختياري. تقدر تختار طريقة تانية بدل كده.',
    locationLoading: 'بندور على موقعك',
    locationRequired: 'اختار موقعك علشان تكمل.',
    mapDragHint: 'اضغط على الخريطة أو حرّك العلامة لمكان شغلك.',
    workAreaMissing: 'ارجع واختار المحافظة والمنطقة الأول.',
    identityPurpose: 'ورشة بتستخدمها بس للتأكد من هويتك.',
    certificatePurpose: 'ورشة بتستخدمها بس للتحقق من الصنايعي.',
    chooseProfessions: 'اختار مهنتك',
    changeProfessions: 'غيّر المهن',
    searchProfessions: 'دوّر على مهنة',
    removeProfession: 'احذف',
    selected: 'مختارة',
    done: 'تم',
    close: 'اقفل',
    selectGovernorate: 'اختار المحافظة',
    selectArea: 'اختار المنطقة',
    searchPlaces: 'دوّر على مكان',
    changePhoto: 'غيّر الصورة',
    choosePhotoSource: 'ضيف صورتك',
    photoPreviewTitle: 'راجع صورتك',
    photoSourceHint: 'استخدم صورة واضحة لوشك.',
    takePhoto: 'صوّر دلوقتي',
    chooseGallery: 'اختار من الصور',
    usePhoto: 'استخدم الصورة دي',
    retake: 'صوّر تاني',
    chooseAnother: 'اختار صورة تانية',
    photoPermission: 'اسمح للتطبيق يفتح الكاميرا أو الصور علشان تكمل.',
    photoProcessing: 'بنجهّز صورتك',
    photoProcessingError: 'معرفناش نجهّز الصورة دي. اختار صورة تانية.',
    photoUploadError: 'معرفناش نحفظ الصورة. جرّب تاني.',
    loadingNextStep: 'بنفتح الخطوة الجاية',
  },
} as const;

export type WorkerCopyKey = Exclude<keyof typeof copy.en, 'newRequestsTitle'>;

export function useWorkerText() {
  const { language } = useLocalization();
  const selected = language === 'ar' ? copy.ar : copy.en;
  return {
    text: (key: WorkerCopyKey) => selected[key],
    newRequestsTitle: (count: number) => selected.newRequestsTitle(count),
  };
}
