import { useLocalization } from '@/src/i18n/localization';

const copy = {
  en: {
    homeTitle: 'Your work',
    available: 'Available',
    unavailable: 'Unavailable',
    suspendedTitle: 'Your worker account is on hold',
    suspendedBody: 'Open support to understand what happens next and how to resolve it.',
    suspendedAction: 'Get help',
    activeJobTitle: 'Continue your current job',
    activeJobBody: 'The next job step is ready.',
    activeJobAction: 'Continue job',
    newRequestsTitle: (count: number) => `You have ${count} new ${count === 1 ? 'request' : 'requests'}`,
    newRequestsBody: 'Open them now and choose the work that suits you.',
    newRequestsAction: 'View requests',
    verifyTitle: 'Complete verification',
    verifyBody: 'Finish the remaining steps so your account is ready.',
    verifyAction: 'Continue',
    reviewTitle: 'Your documents are being reviewed',
    reviewBody: 'We will tell you as soon as there is an update.',
    reviewAction: 'View status',
    waitingTitle: "You're available",
    waitingBody: "We'll notify you when work arrives.",
    unavailableTitle: "You're unavailable",
    unavailableBody: 'Go available when you are ready for new work.',
    goAvailable: 'Go available',
    newRequests: 'New requests',
    myJobs: 'My jobs',
    verification: 'Verification',
    earnings: 'Earnings',
    myProfile: 'My profile',
    support: 'Support',
    settings: 'Settings',
    requestService: 'Request a service',
    requestServiceHint: 'Need work done at home?',
    notifications: 'Notifications',
    messages: 'Messages',
    jobsTitle: 'My jobs',
    settingsTitle: 'Settings',
    appearance: 'Appearance',
    notificationSettings: 'Notification settings',
    privacy: 'Privacy and account',
    backHome: 'Back to your work',
    journeyTitle: 'Set up your work account',
    journeyStep: 'Step',
    welcomeTitle: 'Welcome to Warsha',
    welcomeBody: 'We will guide you. Finish one simple step at a time.',
    basicTitle: 'Tell customers about you',
    basicBody: 'Add your name and a clear photo. The introduction and experience are your choice.',
    fullName: 'Full name',
    about: 'A short introduction',
    aboutExample: 'Example: I repair air conditioners and have worked in this trade for years.',
    experience: 'Years of experience',
    experienceExample: 'Example: 5',
    addPhoto: 'Add your photo',
    tradeTitle: 'Select your profession',
    tradeBody: 'Choose the kind of work you do.',
    profession: 'Your profession',
    services: 'Services you offer',
    servicesBody: 'Choose the specific jobs you can take.',
    chooseProfessionFirst: 'Choose your profession first, then pick the jobs you can take.',
    selectAllServices: 'Select every job in this trade',
    noServicesChosen: 'No jobs chosen yet',
    servicesSelectedOne: '1 job selected',
    servicesSelectedMany: (count: number) => `${count} jobs selected`,
    noServicesAvailable: 'Warsha has no jobs listed for this trade yet.',
    professionRequired: 'Select at least one profession.',
    serviceRequired: 'Choose at least one job you can take.',
    professionWithdrawn: 'Warsha no longer offers this trade. Choose the one that matches your work.',
    serviceOutsideProfession: 'Some chosen jobs do not belong to your professions. Open each trade and check the list.',
    profileIncomplete: 'Some profile details are missing. Check your name, photo and years of experience.',
    areaInvalid: 'Check the governorate and area you chose.',
    withdrawnProfessionNotice: 'Your account still records a trade Warsha no longer offers. Choose the concrete trade that matches your work.',
    historicalServicesTitle: 'Previously offered services',
    historicalServicesBody: 'These saved services remain on your profile. Choose a current profession to review which jobs you can still offer.',
    areaTitle: 'Where can you work?',
    areaBody: 'Add your service area and your current address.',
    governorate: 'Governorate',
    district: 'Area',
    addAddress: 'Add current address',
    identityTitle: 'Verify your identity',
    identityBody: 'Take your ID photos and a selfie. We will guide you.',
    certificateTitle: 'Upload the criminal-record certificate',
    certificateBody: 'You obtain the official certificate, then upload it here.',
    reviewJourneyTitle: 'Your application is complete',
    reviewJourneyBody: 'We will show your status here and tell you if anything is needed.',
    saveContinue: 'Save and continue',
    continueJourney: 'Continue',
    retry: 'Try again',
    requiredFields: 'Please complete this step first.',
    required: 'Required',
    optional: 'Optional',
    privateLabel: 'Private',
    photoPurpose: 'Customers will see this photo.',
    fullNamePurpose: 'Customers will see your name.',
    aboutPurpose: 'Customers will see this only if you add it.',
    experiencePurpose: 'Customers may see this on your profile.',
    professionPlural: 'Your profession',
    professionPurpose: 'Warsha uses this to send you suitable jobs.',
    servicesPurpose: 'Choose the specific jobs you can take.',
    governoratePurpose: 'Choose the governorate where you work.',
    districtPurpose: 'Choose the area where you work.',
    currentAddressPurpose: "Warsha uses this for job matching. Customers won't see your exact home address.",
    workLocationTitle: 'Your work location',
    workLocationIntro: "Warsha uses your location to find jobs near you. Customers won't see your exact home address.",
    selectedWorkArea: 'Your selected work area',
    useCurrentLocation: 'Use my current location',
    chooseLocationOnMap: 'Choose location on map',
    searchAddress: 'Search for an address',
    searchAddressPlaceholder: 'Type a street or place',
    locationSaved: 'Location saved',
    locationPartial: 'Location found. Review the address before continuing.',
    locationLookupFailed: 'Location obtained, but the address could not be looked up. You can still continue with your selected work area.',
    locationLocating: 'Locating…',
    locationResolving: 'Resolving address…',
    locationFailed: 'We could not get that location. Try another option.',
    locationPermissionDenied: 'Location permission was not granted. Choose another option, or allow it in Settings.',
    locationServicesDisabled: 'Location services are off. Turn them on, then try again.',
    locationDeviceUnavailable: 'Your device has no location fix yet. If you are using an emulator, set a simulated location and try again.',
    locationNoResults: 'No matching places found. Try a simpler search.',
    locationProviderUnavailable: 'Map and address search are unavailable right now. You can still use your current location.',
    locationPermissionOptional: 'Location permission is optional. You can choose another method instead.',
    locationLoading: 'Finding your location',
    locationRequired: 'Choose your location before continuing.',
    mapDragHint: 'Tap the map or move the pin to your work location.',
    workAreaMissing: 'Go back and choose your governorate and area first.',
    identityPurpose: 'Warsha uses this only to verify your identity.',
    certificatePurpose: 'Warsha uses this only for worker verification.',
    chooseProfessions: 'Select your profession',
    changeProfessions: 'Change your profession',
    searchProfessions: 'Search professions',
    removeProfession: 'Remove',
    selected: 'selected',
    done: 'Done',
    close: 'Close',
    selectGovernorate: 'Choose governorate',
    selectArea: 'Choose area',
    searchPlaces: 'Search places',
    changePhoto: 'Change photo',
    choosePhotoSource: 'Add your photo',
    photoPreviewTitle: 'Check your photo',
    photoSourceHint: 'Use a clear photo of your face.',
    takePhoto: 'Take photo',
    chooseGallery: 'Choose from gallery',
    usePhoto: 'Use this photo',
    retake: 'Retake',
    chooseAnother: 'Choose another',
    photoPermission: 'Allow photo access to continue.',
    photoProcessing: 'Preparing your photo',
    photoProcessingError: 'This photo could not be prepared. Choose another one.',
    photoUploadError: 'This photo could not be saved. Try again.',
    loadingNextStep: 'Opening the next step',
  },
  ar: {
    homeTitle: 'شغلك',
    available: 'متاح',
    unavailable: 'غير متاح',
    suspendedTitle: 'حسابك كصنايعي موقوف مؤقتاً',
    suspendedBody: 'افتح المساعدة علشان تعرف الخطوة الجاية وإزاي تحل المشكلة.',
    suspendedAction: 'اطلب مساعدة',
    activeJobTitle: 'كمّل شغلك الحالي',
    activeJobBody: 'الخطوة الجاية في الشغل جاهزة.',
    activeJobAction: 'كمّل الشغل',
    newRequestsTitle: (count: number) => `عندك ${count} طلب شغل جديد`,
    newRequestsBody: 'افتح الطلبات واختار الشغل المناسب ليك.',
    newRequestsAction: 'شوف الطلبات',
    verifyTitle: 'كمّل التحقق',
    verifyBody: 'خلّص الخطوات الناقصة علشان حسابك يبقى جاهز.',
    verifyAction: 'كمّل',
    reviewTitle: 'مستنداتك بتتراجع',
    reviewBody: 'هنقولك أول ما يكون في جديد.',
    reviewAction: 'شوف الحالة',
    waitingTitle: 'إنت متاح للشغل',
    waitingBody: 'هنبعتلك أول ما يوصلك شغل.',
    unavailableTitle: 'إنت غير متاح دلوقتي',
    unavailableBody: 'خلّي نفسك متاح لما تبقى جاهز لشغل جديد.',
    goAvailable: 'خلّيني متاح',
    newRequests: 'طلبات جديدة',
    myJobs: 'شغلي',
    verification: 'التحقق',
    earnings: 'أرباحي',
    myProfile: 'ملفي',
    support: 'المساعدة',
    settings: 'الإعدادات',
    requestService: 'اطلب خدمة',
    requestServiceHint: 'محتاج حاجة تتعمل في البيت؟',
    notifications: 'الإشعارات',
    messages: 'الرسائل',
    jobsTitle: 'شغلي',
    settingsTitle: 'الإعدادات',
    appearance: 'شكل التطبيق',
    notificationSettings: 'إعدادات الإشعارات',
    privacy: 'الخصوصية والحساب',
    backHome: 'ارجع لشغلك',
    journeyTitle: 'جهّز حساب شغلك',
    journeyStep: 'خطوة',
    welcomeTitle: 'أهلاً بيك في ورشة',
    welcomeBody: 'هنمشي معاك خطوة بخطوة. خلّص حاجة واحدة كل مرة.',
    basicTitle: 'عرّف العملاء بيك',
    basicBody: 'ضيف اسمك وصورة واضحة. النبذة وسنين الخبرة اختياريين.',
    fullName: 'الاسم بالكامل',
    about: 'كلمتين عن شغلك',
    aboutExample: 'مثال: بصلّح تكييفات وبشتغل في المهنة من سنين.',
    experience: 'سنين الخبرة',
    experienceExample: 'مثال: 5',
    addPhoto: 'ضيف صورتك',
    tradeTitle: 'اختار مهنتك',
    tradeBody: 'اختار نوع الشغل اللي بتعمله.',
    profession: 'مهنتك',
    services: 'الخدمات اللي بتقدمها',
    servicesBody: 'اختار الشغلانات اللي تقدر تستلمها.',
    chooseProfessionFirst: 'اختار مهنتك الأول، وبعدها اختار الشغلانات اللي تقدر تستلمها.',
    selectAllServices: 'اختار كل شغلانات المهنة دي',
    noServicesChosen: 'لسه ما اخترتش شغلانات',
    servicesSelectedOne: 'شغلانة واحدة مختارة',
    servicesSelectedMany: (count: number) => `${count} شغلانات مختارة`,
    noServicesAvailable: 'ورشة لسه ما عندهاش شغلانات للمهنة دي.',
    professionRequired: 'اختار مهنة واحدة على الأقل.',
    serviceRequired: 'اختار شغلانة واحدة على الأقل تقدر تستلمها.',
    professionWithdrawn: 'ورشة ما بقتش بتقدم المهنة دي. اختار المهنة اللي بتوصف شغلك.',
    serviceOutsideProfession: 'في شغلانات مختارة مش تابعة لمهنك. افتح كل مهنة وراجع القايمة.',
    profileIncomplete: 'في بيانات ناقصة في ملفك. راجع اسمك وصورتك وسنين الخبرة.',
    areaInvalid: 'راجع المحافظة والمنطقة اللي اخترتهم.',
    withdrawnProfessionNotice: 'حسابك لسه مسجّل عليه مهنة ورشة ما بقتش بتقدمها. اختار المهنة المحددة اللي بتوصف شغلك.',
    historicalServicesTitle: 'خدمات كنت بتقدمها قبل كده',
    historicalServicesBody: 'الخدمات المحفوظة دي لسه في ملفك. اختار مهنة حالية علشان تراجع الشغلانات اللي تقدر تفضل تقدمها.',
    areaTitle: 'بتشتغل فين؟',
    areaBody: 'ضيف منطقة شغلك وعنوانك الحالي.',
    governorate: 'المحافظة',
    district: 'المنطقة',
    addAddress: 'ضيف عنوانك الحالي',
    identityTitle: 'اتحقق من هويتك',
    identityBody: 'صوّر البطاقة وخد سيلفي. هنمشي معاك خطوة بخطوة.',
    certificateTitle: 'ارفع الفيش والتشبيه',
    certificateBody: 'إنت اللي بتطلع الشهادة الرسمية وبعدها ترفعها هنا.',
    reviewJourneyTitle: 'طلبك اكتمل',
    reviewJourneyBody: 'هنوضحلك الحالة هنا ونقولك لو محتاجين حاجة.',
    saveContinue: 'احفظ وكمّل',
    continueJourney: 'كمّل',
    retry: 'جرّب تاني',
    requiredFields: 'كمّل الخطوة دي الأول.',
    required: 'مطلوب',
    optional: 'اختياري',
    privateLabel: 'خاص',
    photoPurpose: 'العملاء هيشوفوا الصورة دي.',
    fullNamePurpose: 'العملاء هيشوفوا اسمك.',
    aboutPurpose: 'العملاء هيشوفوا النبذة بس لو ضفتها.',
    experiencePurpose: 'العملاء ممكن يشوفوا سنين الخبرة في ملفك.',
    professionPlural: 'مهنتك',
    professionPurpose: 'ورشة بتستخدمها علشان تبعتلك شغل مناسب.',
    servicesPurpose: 'اختار الشغلانات اللي تقدر تستلمها.',
    governoratePurpose: 'اختار المحافظة اللي بتشتغل فيها.',
    districtPurpose: 'اختار المنطقة اللي بتشتغل فيها.',
    currentAddressPurpose: 'ورشة بتستخدم عنوانك لمطابقة الشغل. العميل مش هيشوف عنوان بيتك بالتفصيل.',
    workLocationTitle: 'مكان شغلك',
    workLocationIntro: 'ورشة بتستخدم موقعك علشان تلاقي شغل قريب منك. العملاء مش هيشوفوا عنوان بيتك بالتفصيل.',
    selectedWorkArea: 'منطقة الشغل اللي اخترتها',
    useCurrentLocation: 'استخدم موقعي الحالي',
    chooseLocationOnMap: 'اختار الموقع على الخريطة',
    searchAddress: 'دوّر على عنوان',
    searchAddressPlaceholder: 'اكتب شارع أو مكان',
    locationSaved: 'الموقع اتحفظ',
    locationPartial: 'لقينا الموقع. راجع العنوان قبل ما تكمّل.',
    locationLookupFailed: 'حددنا الموقع، لكن ما قدرناش نجيب العنوان. تقدر تكمّل بمنطقة الشغل اللي اخترتها.',
    locationLocating: 'بنحدد موقعك…',
    locationResolving: 'بنجيب العنوان…',
    locationFailed: 'معرفناش نجيب الموقع ده. جرّب طريقة تانية.',
    locationPermissionDenied: 'إذن الموقع متوافقش عليه. اختار طريقة تانية أو اسمح به من الإعدادات.',
    locationServicesDisabled: 'خدمات الموقع مقفولة. افتحها وحاول تاني.',
    locationDeviceUnavailable: 'الجهاز لسه محددش موقع. لو بتستخدم محاكي، حدد له موقع تجريبي وحاول تاني.',
    locationNoResults: 'ملقيناش مكان مطابق. جرّب بحث أبسط.',
    locationProviderUnavailable: 'الخريطة والبحث عن عنوان مش متاحين دلوقتي. تقدر تستخدم موقعك الحالي.',
    locationPermissionOptional: 'إذن الموقع اختياري. تقدر تختار طريقة تانية بدل كده.',
    locationLoading: 'بندور على موقعك',
    locationRequired: 'اختار موقعك علشان تكمل.',
    mapDragHint: 'اضغط على الخريطة أو حرّك العلامة لمكان شغلك.',
    workAreaMissing: 'ارجع واختار المحافظة والمنطقة الأول.',
    identityPurpose: 'ورشة بتستخدمها بس للتأكد من هويتك.',
    certificatePurpose: 'ورشة بتستخدمها بس للتحقق من الصنايعي.',
    chooseProfessions: 'اختار مهنتك',
    changeProfessions: 'غيّر مهنتك',
    searchProfessions: 'دوّر على مهنة',
    removeProfession: 'احذف',
    selected: 'مختارة',
    done: 'تم',
    close: 'اقفل',
    selectGovernorate: 'اختار المحافظة',
    selectArea: 'اختار المنطقة',
    searchPlaces: 'دوّر على مكان',
    changePhoto: 'غيّر الصورة',
    choosePhotoSource: 'ضيف صورتك',
    photoPreviewTitle: 'راجع صورتك',
    photoSourceHint: 'استخدم صورة واضحة لوشك.',
    takePhoto: 'صوّر دلوقتي',
    chooseGallery: 'اختار من الصور',
    usePhoto: 'استخدم الصورة دي',
    retake: 'صوّر تاني',
    chooseAnother: 'اختار صورة تانية',
    photoPermission: 'اسمح للتطبيق يفتح الكاميرا أو الصور علشان تكمل.',
    photoProcessing: 'بنجهّز صورتك',
    photoProcessingError: 'معرفناش نجهّز الصورة دي. اختار صورة تانية.',
    photoUploadError: 'معرفناش نحفظ الصورة. جرّب تاني.',
    loadingNextStep: 'بنفتح الخطوة الجاية',
  },
  fr: {
    homeTitle: 'Votre travail',
    available: 'Disponible',
    unavailable: 'Indisponible',
    suspendedTitle: 'Votre compte professionnel est suspendu',
    suspendedBody: 'Ouvrez l’assistance pour comprendre la suite et comment régulariser.',
    suspendedAction: 'Obtenir de l’aide',
    activeJobTitle: 'Poursuivez votre travail en cours',
    activeJobBody: 'L’étape suivante est prête.',
    activeJobAction: 'Continuer le travail',
    newRequestsTitle: (count: number) => `Vous avez ${count} nouvelle${count === 1 ? '' : 's'} demande${count === 1 ? '' : 's'}`,
    newRequestsBody: 'Ouvrez-les et choisissez le travail qui vous convient.',
    newRequestsAction: 'Voir les demandes',
    verifyTitle: 'Terminer la vérification',
    verifyBody: 'Terminez les étapes restantes pour que votre compte soit prêt.',
    verifyAction: 'Continuer',
    reviewTitle: 'Vos documents sont en cours d’examen',
    reviewBody: 'Nous vous préviendrons dès qu’il y a du nouveau.',
    reviewAction: 'Voir le statut',
    waitingTitle: 'Vous êtes disponible',
    waitingBody: 'Nous vous préviendrons dès qu’un travail arrive.',
    unavailableTitle: 'Vous êtes indisponible',
    unavailableBody: 'Repassez disponible quand vous êtes prêt à travailler.',
    goAvailable: 'Passer disponible',
    newRequests: 'Nouvelles demandes',
    myJobs: 'Mes travaux',
    verification: 'Vérification',
    earnings: 'Revenus',
    myProfile: 'Mon profil',
    support: 'Assistance',
    settings: 'Réglages',
    requestService: 'Demander un service',
    requestServiceHint: 'Besoin d’une intervention chez vous ?',
    notifications: 'Notifications',
    messages: 'Messages',
    jobsTitle: 'Mes travaux',
    settingsTitle: 'Réglages',
    appearance: 'Apparence',
    notificationSettings: 'Réglages des notifications',
    privacy: 'Confidentialité et compte',
    backHome: 'Retour à votre travail',
    journeyTitle: 'Configurez votre compte professionnel',
    journeyStep: 'Étape',
    welcomeTitle: 'Bienvenue sur Warsha',
    welcomeBody: 'Nous vous guidons. Une étape simple à la fois.',
    basicTitle: 'Présentez-vous aux clients',
    basicBody: 'Ajoutez votre nom et une photo nette. La présentation et l’expérience sont facultatives.',
    fullName: 'Nom complet',
    about: 'Une courte présentation',
    aboutExample: 'Exemple : je répare les climatiseurs et j’exerce ce métier depuis des années.',
    experience: 'Années d’expérience',
    experienceExample: 'Exemple : 5',
    addPhoto: 'Ajoutez votre photo',
    tradeTitle: 'Choisissez votre métier',
    tradeBody: 'Choisissez le type de travail que vous faites.',
    profession: 'Votre métier',
    services: 'Les services que vous proposez',
    servicesBody: 'Choisissez les interventions précises que vous pouvez accepter.',
    chooseProfessionFirst: 'Choisissez d’abord votre métier, puis les interventions que vous pouvez accepter.',
    selectAllServices: 'Sélectionner toutes les interventions de ce métier',
    noServicesChosen: 'Aucune intervention choisie',
    servicesSelectedOne: '1 intervention sélectionnée',
    servicesSelectedMany: (count: number) => `${count} interventions sélectionnées`,
    noServicesAvailable: 'Warsha ne propose pas encore d’intervention pour ce métier.',
    professionRequired: 'Choisissez au moins un métier.',
    serviceRequired: 'Choisissez au moins une intervention que vous pouvez accepter.',
    professionWithdrawn: 'Warsha ne propose plus ce métier. Choisissez celui qui correspond à votre travail.',
    serviceOutsideProfession: 'Certaines interventions choisies n’appartiennent pas à vos métiers. Ouvrez chaque métier et vérifiez la liste.',
    profileIncomplete: 'Des informations manquent dans votre profil. Vérifiez votre nom, votre photo et vos années d’expérience.',
    areaInvalid: 'Vérifiez le gouvernorat et la zone que vous avez choisis.',
    withdrawnProfessionNotice: 'Votre compte enregistre encore un métier que Warsha ne propose plus. Choisissez le métier précis qui correspond à votre travail.',
    historicalServicesTitle: 'Services proposés auparavant',
    historicalServicesBody: 'Ces services enregistrés restent dans votre profil. Choisissez un métier actuel pour vérifier les interventions que vous pouvez encore proposer.',
    areaTitle: 'Où pouvez-vous travailler ?',
    areaBody: 'Ajoutez votre zone d’intervention et votre adresse actuelle.',
    governorate: 'Gouvernorat',
    district: 'Zone',
    addAddress: 'Ajouter l’adresse actuelle',
    identityTitle: 'Vérifiez votre identité',
    identityBody: 'Photographiez votre pièce d’identité et prenez un selfie. Nous vous guidons.',
    certificateTitle: 'Téléversez l’extrait de casier judiciaire',
    certificateBody: 'Vous obtenez le document officiel, puis vous le téléversez ici.',
    reviewJourneyTitle: 'Votre dossier est complet',
    reviewJourneyBody: 'Nous afficherons votre statut ici et vous dirons si quelque chose manque.',
    saveContinue: 'Enregistrer et continuer',
    continueJourney: 'Continuer',
    retry: 'Réessayer',
    requiredFields: 'Terminez d’abord cette étape.',
    required: 'Obligatoire',
    optional: 'Facultatif',
    privateLabel: 'Privé',
    photoPurpose: 'Les clients verront cette photo.',
    fullNamePurpose: 'Les clients verront votre nom.',
    aboutPurpose: 'Les clients ne la verront que si vous l’ajoutez.',
    experiencePurpose: 'Les clients peuvent la voir sur votre profil.',
    professionPlural: 'Votre métier',
    professionPurpose: 'Warsha s’en sert pour vous envoyer des travaux adaptés.',
    servicesPurpose: 'Choisissez les interventions précises que vous pouvez accepter.',
    governoratePurpose: 'Choisissez le gouvernorat où vous travaillez.',
    districtPurpose: 'Choisissez la zone où vous travaillez.',
    currentAddressPurpose: 'Warsha s’en sert pour l’attribution des travaux. Les clients ne verront pas votre adresse exacte.',
    workLocationTitle: 'Votre lieu de travail',
    workLocationIntro: 'Warsha utilise votre position pour trouver des travaux près de chez vous. Les clients ne verront pas votre adresse exacte.',
    selectedWorkArea: 'Votre zone d’intervention choisie',
    useCurrentLocation: 'Utiliser ma position actuelle',
    chooseLocationOnMap: 'Choisir sur la carte',
    searchAddress: 'Rechercher une adresse',
    searchAddressPlaceholder: 'Saisissez une rue ou un lieu',
    locationSaved: 'Position enregistrée',
    locationPartial: 'Position trouvée. Vérifiez l’adresse avant de continuer.',
    locationLookupFailed: 'Position obtenue, mais l’adresse n’a pas pu être trouvée. Vous pouvez continuer avec la zone choisie.',
    locationLocating: 'Localisation…',
    locationResolving: 'Recherche de l’adresse…',
    locationFailed: 'Nous n’avons pas pu obtenir cette position. Essayez autrement.',
    locationPermissionDenied: 'L’autorisation de localisation n’a pas été accordée. Choisissez une autre méthode ou autorisez-la dans les Réglages.',
    locationServicesDisabled: 'Les services de localisation sont désactivés. Activez-les puis réessayez.',
    locationDeviceUnavailable: 'Votre appareil n’a pas encore de position. Sur un émulateur, définissez une position simulée puis réessayez.',
    locationNoResults: 'Aucun lieu correspondant. Essayez une recherche plus simple.',
    locationProviderUnavailable: 'La carte et la recherche d’adresse sont indisponibles. Vous pouvez utiliser votre position actuelle.',
    locationPermissionOptional: 'L’autorisation de localisation est facultative. Vous pouvez choisir une autre méthode.',
    locationLoading: 'Recherche de votre position',
    locationRequired: 'Choisissez votre position avant de continuer.',
    mapDragHint: 'Touchez la carte ou déplacez le repère vers votre lieu de travail.',
    workAreaMissing: 'Revenez en arrière et choisissez d’abord votre gouvernorat et votre zone.',
    identityPurpose: 'Warsha s’en sert uniquement pour vérifier votre identité.',
    certificatePurpose: 'Warsha s’en sert uniquement pour la vérification des professionnels.',
    chooseProfessions: 'Choisir votre métier',
    changeProfessions: 'Changer de métier',
    searchProfessions: 'Rechercher un métier',
    removeProfession: 'Retirer',
    selected: 'sélectionné(s)',
    done: 'Terminé',
    close: 'Fermer',
    selectGovernorate: 'Choisir le gouvernorat',
    selectArea: 'Choisir la zone',
    searchPlaces: 'Rechercher un lieu',
    changePhoto: 'Changer la photo',
    choosePhotoSource: 'Ajoutez votre photo',
    photoPreviewTitle: 'Vérifiez votre photo',
    photoSourceHint: 'Utilisez une photo nette de votre visage.',
    takePhoto: 'Prendre une photo',
    chooseGallery: 'Choisir dans la galerie',
    usePhoto: 'Utiliser cette photo',
    retake: 'Reprendre',
    chooseAnother: 'Choisir une autre',
    photoPermission: 'Autorisez l’accès aux photos pour continuer.',
    photoProcessing: 'Préparation de votre photo',
    photoProcessingError: 'Cette photo n’a pas pu être préparée. Choisissez-en une autre.',
    photoUploadError: 'Cette photo n’a pas pu être enregistrée. Réessayez.',
    loadingNextStep: 'Ouverture de l’étape suivante',
  },
} as const;

export type WorkerCopyKey = Exclude<keyof typeof copy.en, 'newRequestsTitle' | 'servicesSelectedMany'>;

/**
 * The worker journey's own words, in the three languages Warsha speaks.
 *
 * French used to resolve to English here -- `language === 'ar' ? ar : en` --
 * so a French-speaking worker set up their entire account in English while the
 * rest of the product spoke to them in French. Selecting by language means the
 * French block is the thing that has to stay complete, and the type makes an
 * incomplete one a compile error rather than a silent fallback.
 */
export function useWorkerText() {
  const { language } = useLocalization();
  const selected = copy[language] ?? copy.en;
  return {
    text: (key: WorkerCopyKey) => selected[key],
    newRequestsTitle: (count: number) => selected.newRequestsTitle(count),
    /** "1 job selected" and "5 jobs selected" are different sentences in
     *  Arabic and French as well as English, so the count picks the sentence
     *  rather than being interpolated into one. */
    servicesSelected: (count: number) => (count === 1
      ? selected.servicesSelectedOne
      : selected.servicesSelectedMany(count)),
  };
}
