/**
 * WPS-020 vocabulary, English and Egyptian Arabic.
 *
 * Import-free so the regression suite can assert key parity and Arabic script
 * coverage without a bundler. Arabic is spoken register, matching the rest of
 * Warsha: someone hunting for a plumber is not helped by formal prose.
 */
export const discoveryCopy = {
  en: {
    // Appearance
    appearance: 'Appearance',
    appearanceHint: 'Choose Warsha’s appearance, or match your device setting.',
    appearanceSystem: 'System',
    appearanceLight: 'Light',
    appearanceDark: 'Dark',
    appearanceSystemHint: 'Follows your device. Changing your phone’s setting changes Warsha straight away.',
    appearanceLightHint: 'Always light, whatever your device is set to.',
    appearanceDarkHint: 'Always dark, whatever your device is set to.',
    appearanceSelected: 'Selected',
    appearanceSaved: 'Saved on this device',
    appearanceSyncedHint: 'Signed in, your choice follows your account to your other devices.',
    appearanceGuestHint: 'Saved on this device. Sign in to carry it to your other devices.',
    appearanceCurrentlyLight: 'Currently showing the light appearance.',
    appearanceCurrentlyDark: 'Currently showing the dark appearance.',

    // Search
    searchTitle: 'Find a professional',
    searchPlaceholder: 'Service, trade, area, or name',
    searchAction: 'Search',
    searchClear: 'Clear search',
    searchResults: 'results',
    searchOneResult: 'result',
    searchLoading: 'Searching…',
    searchRetry: 'Try again',
    searchFailed: 'Search could not finish.',
    searchOffline: 'You appear to be offline. Check your connection and try again.',
    searchApproximate: 'No exact match. Showing close matches.',
    searchEmptyTitle: 'No professionals matched',
    searchEmptyBody: 'Try a trade, a service, an area, or a simpler description of the problem.',
    searchBrowseTitle: 'Browse professionals',
    loadMore: 'Show more',
    endOfResults: 'That’s everyone matching your search.',

    // Suggestions
    recentSearches: 'Recent searches',
    clearRecentSearches: 'Clear recent searches',
    suggestedCategories: 'Browse by trade',
    commonServices: 'Common services',
    commonServicesHint: 'Ranked by how many professionals offer them.',
    providersOffering: 'professionals',

    // Filters
    filters: 'Filters',
    openFilters: 'Open filters',
    closeFilters: 'Close filters',
    activeFilters: 'active',
    resetFilters: 'Reset all',
    removeFilter: 'Remove filter',
    filterCategory: 'Trade',
    filterArea: 'Area',
    filterRating: 'Minimum rating',
    filterCompletedJobs: 'Completed jobs',
    filterDistance: 'Within',
    filterAvailableNow: 'Available now',
    filterSkillVerified: 'Verified skill certificate',
    filterCertificateVerified: 'Approved professional certificate',
    filterEmergency: 'Emergency available',
    filterPricing: 'Price model',
    filterLanguage: 'Language',
    filterAny: 'Any',

    // Sorting
    sortBy: 'Sort by',
    sortRecommended: 'Recommended',
    sortDistance: 'Distance',
    sortRating: 'Rating',
    sortMostReviewed: 'Most reviewed',
    sortAvailability: 'Availability',
    sortRecommendedHint: 'Uses Warsha’s marketplace ranking policy. No professional pays for placement.',
    sortDistanceHint: 'Needs a location. Not offered while Warsha only knows your area.',
    sortRatingHint: 'Average rating, with review count shown so a single review is visible as one review.',

    // Location
    locationChooseArea: 'Choose your area',
    areaHint: 'Warsha sorts by area, not by tracking you. No location permission is requested to browse.',
    areaTitle: 'Choose an area',

    // Discovery sections
    discoverTitle: 'What do you need help with?',
    availableNearby: 'Available near you',
    trustedWorkers: 'Proven professionals',
    trustedWorkersHint: 'Verified skill certificate and completed work on Warsha.',
    savedWorkers: 'Workers you saved',
    continueLooking: 'Continue where you left off',
    viewAll: 'View all',

    // Recently viewed
    recentlyViewed: 'Recently viewed',
    recentlyViewedHint: 'Only you can see this. It never affects who is shown to anyone else.',
    clearRecentlyViewed: 'Clear history',
    recentlyViewedEmpty: 'Professionals you open will appear here.',
    historyCleared: 'History cleared',

    // Favourites
    favourites: 'Favourites',
    favouritesEmpty: 'No saved professionals yet',
    favouritesEmptyBody: 'Tap the heart on a professional to save them here.',
    favouritesSignedOut: 'Sign in to save professionals to your account.',
    favouriteUnavailable: 'This professional is not accepting work right now.',
    addFavourite: 'Save professional',
    removeFavourite: 'Remove from saved',

    // Result card
    verifiedIdentity: 'Identity verified',
    verifiedSkill: 'Skill certificate',
    verifiedCertificate: 'Professional certificate',
    availableNow: 'Available now',
    unavailableNow: 'Not available now',
    emergencyAvailable: 'Emergency',
    reviewsLabel: 'reviews',
    oneReviewLabel: 'review',
    noReviewsYet: 'No reviews yet',
    jobsLabel: 'jobs done',
    kilometresAway: 'km away',
    startingFrom: 'From',
  },
  ar: {
    appearance: 'شكل التطبيق',
    appearanceHint: 'اختار شكل ورشة، أو خليه يتغير حسب إعدادات جهازك.',
    appearanceSystem: 'حسب الجهاز',
    appearanceLight: 'فاتح',
    appearanceDark: 'داكن',
    appearanceSystemHint: 'بيمشي مع جهازك. لو غيّرت إعداد الموبايل، ورشة بتتغير على طول.',
    appearanceLightHint: 'فاتح دايمًا، مهما كان إعداد جهازك.',
    appearanceDarkHint: 'داكن دايمًا، مهما كان إعداد جهازك.',
    appearanceSelected: 'مختار',
    appearanceSaved: 'متحفظ على الجهاز ده',
    appearanceSyncedHint: 'وانت داخل بحسابك، اختيارك بيمشي معاك على أجهزتك التانية.',
    appearanceGuestHint: 'متحفظ على الجهاز ده. سجّل دخول علشان يمشي معاك على أجهزتك التانية.',
    appearanceCurrentlyLight: 'الشكل الحالي فاتح.',
    appearanceCurrentlyDark: 'الشكل الحالي داكن.',

    searchTitle: 'دوّر على صنايعي',
    searchPlaceholder: 'خدمة أو مهنة أو منطقة أو اسم',
    searchAction: 'بحث',
    searchClear: 'مسح البحث',
    searchResults: 'نتيجة',
    searchOneResult: 'نتيجة',
    searchLoading: 'بندوّر…',
    searchRetry: 'حاول تاني',
    searchFailed: 'البحث ما قدرش يخلص.',
    searchOffline: 'يظهر إن مفيش نت. اتأكد من الاتصال وحاول تاني.',
    searchApproximate: 'مفيش نتيجة مطابقة بالظبط. دي أقرب نتائج.',
    searchEmptyTitle: 'مفيش صنايعية مطابقين',
    searchEmptyBody: 'جرّب مهنة أو خدمة أو منطقة أو وصف أبسط للمشكلة.',
    searchBrowseTitle: 'تصفح الصنايعية',
    loadMore: 'عرض المزيد',
    endOfResults: 'دول كل اللي مطابقين لبحثك.',

    recentSearches: 'آخر عمليات البحث',
    clearRecentSearches: 'مسح آخر عمليات البحث',
    suggestedCategories: 'تصفح حسب المهنة',
    commonServices: 'خدمات شائعة',
    commonServicesHint: 'مرتبة حسب عدد الصنايعية اللي بيقدموها.',
    providersOffering: 'صنايعي',

    filters: 'التصفية',
    openFilters: 'فتح التصفية',
    closeFilters: 'قفل التصفية',
    activeFilters: 'مفعّلة',
    resetFilters: 'مسح الكل',
    removeFilter: 'إزالة التصفية',
    filterCategory: 'المهنة',
    filterArea: 'المنطقة',
    filterRating: 'أقل تقييم',
    filterCompletedJobs: 'شغل مكتمل',
    filterDistance: 'في حدود',
    filterAvailableNow: 'متاح دلوقتي',
    filterSkillVerified: 'شهادة مهارة موثقة',
    filterCertificateVerified: 'شهادة مهنية معتمدة',
    filterEmergency: 'بيشتغل طوارئ',
    filterPricing: 'طريقة التسعير',
    filterLanguage: 'اللغة',
    filterAny: 'الكل',

    sortBy: 'الترتيب',
    sortRecommended: 'المقترح',
    sortDistance: 'المسافة',
    sortRating: 'التقييم',
    sortMostReviewed: 'الأكثر تقييمًا',
    sortAvailability: 'المتاح دلوقتي',
    sortRecommendedHint: 'بيستخدم سياسة ترتيب السوق في ورشة. مفيش صنايعي بيدفع علشان يظهر قدام.',
    sortDistanceHint: 'محتاج موقع. مش متاح طالما ورشة عارفة منطقتك بس.',
    sortRatingHint: 'متوسط التقييم، وعدد التقييمات ظاهر علشان تقييم واحد يبان إنه تقييم واحد.',

    locationChooseArea: 'اختار منطقتك',
    areaHint: 'ورشة بترتب حسب المنطقة، مش بتتبعك. مش بنطلب إذن الموقع علشان تتصفح.',
    areaTitle: 'اختار منطقة',

    discoverTitle: 'محتاج مساعدة في إيه؟',
    availableNearby: 'متاحين جنبك',
    trustedWorkers: 'صنايعية بسجل شغل',
    trustedWorkersHint: 'شهادة مهارة موثقة وشغل مكتمل على ورشة.',
    savedWorkers: 'صنايعية حفظتهم',
    continueLooking: 'كمّل من حيث ما وقفت',
    viewAll: 'عرض الكل',

    recentlyViewed: 'شوفتهم مؤخرًا',
    recentlyViewedHint: 'انت بس اللي بتشوف ده. ومش بيأثر على مين بيظهر لأي حد تاني.',
    clearRecentlyViewed: 'مسح السجل',
    recentlyViewedEmpty: 'الصنايعية اللي هتفتحهم هيظهروا هنا.',
    historyCleared: 'اتمسح السجل',

    favourites: 'المفضلة',
    favouritesEmpty: 'مفيش صنايعية محفوظين لسه',
    favouritesEmptyBody: 'اضغط على علامة القلب علشان تحفظ الصنايعي هنا.',
    favouritesSignedOut: 'سجّل دخول علشان تحفظ الصنايعية في حسابك.',
    favouriteUnavailable: 'الصنايعي ده مش بيستقبل شغل دلوقتي.',
    addFavourite: 'حفظ الصنايعي',
    removeFavourite: 'إزالة من المحفوظين',

    verifiedIdentity: 'هوية موثقة',
    verifiedSkill: 'شهادة مهارة',
    verifiedCertificate: 'شهادة مهنية',
    availableNow: 'متاح دلوقتي',
    unavailableNow: 'مش متاح دلوقتي',
    emergencyAvailable: 'طوارئ',
    reviewsLabel: 'تقييم',
    oneReviewLabel: 'تقييم',
    noReviewsYet: 'لسه مفيش تقييمات',
    jobsLabel: 'شغلانة مكتملة',
    kilometresAway: 'كم',
    startingFrom: 'من',
  },
} as const;

export type DiscoveryTextKey = keyof typeof discoveryCopy.en;
