/**
 * WPS-020 vocabulary, English and Egyptian Arabic, with a French layer.
 *
 * Import-free so the regression suite can assert key parity and Arabic script
 * coverage without a bundler. Arabic is spoken register, matching the rest of
 * Warsha: someone hunting for a plumber is not helped by formal prose.
 *
 * French is a layer over English rather than a third full table, the same shape
 * `web/lib/copy.ts` and `lib/app-copy.fr.ts` already use. The hook used to map
 * French to English wholesale, which was mostly invisible — until Language and
 * appearance moved into Settings, at which point a French speaker opened the
 * screen for choosing their language and found it written in English. Keys
 * translated here are French; the rest fall back to English exactly as before,
 * so this adds coverage without pretending the whole table is translated.
 */
const baseDiscoveryCopy = {
  en: {
    // Appearance
    settingsLanguageAppearance: 'Language & appearance',
    language: 'Language',
    languageHint: 'Choose the language Warsha uses.',
    languageDeviceHint: 'Warsha follows your phone’s language until you choose one here.',
    languageChosenHint: 'Saved. Warsha stays in this language.',
    appearance: 'Appearance',
    appearanceHint: 'Choose Warsha’s appearance, or match your device setting.',
    appearanceSystem: 'System',
    appearanceLight: 'Light',
    appearanceDark: 'Dark',
    appearanceSystemHint: 'Follows your device. Changing your phone’s setting changes Warsha straight away.',
    appearanceLightHint: 'Always light, whatever your device is set to.',
    appearanceDarkHint: 'Always dark, whatever your device is set to.',
    appearanceSelected: 'Selected',
    appearanceSaved: 'Saved on this device',
    appearanceSyncedHint: 'Signed in, your choice follows your account to your other devices.',
    appearanceGuestHint: 'Saved on this device. Sign in to carry it to your other devices.',
    appearanceCurrentlyLight: 'Currently showing the light appearance.',
    appearanceCurrentlyDark: 'Currently showing the dark appearance.',

    // Search
    searchTitle: 'Find a professional',
    searchPlaceholder: 'Service, trade, area, or name',
    searchAction: 'Search',
    searchClear: 'Clear search',
    searchResults: 'results',
    searchOneResult: 'result',
    searchLoading: 'Searching…',
    searchRetry: 'Try again',
    searchFailed: 'Search could not finish.',
    searchOffline: 'You appear to be offline. Check your connection and try again.',
    searchApproximate: 'No exact match. Showing close matches.',
    searchEmptyTitle: 'No professionals matched',
    searchEmptyBody: 'Try a trade, a service, an area, or a simpler description of the problem.',
    searchBrowseTitle: 'Browse professionals',
    loadMore: 'Show more',
    endOfResults: 'That’s everyone matching your search.',

    // Suggestions
    recentSearches: 'Recent searches',
    clearRecentSearches: 'Clear recent searches',
    suggestedCategories: 'Browse by trade',
    commonServices: 'Common services',
    commonServicesHint: 'Ranked by how many professionals offer them.',
    providersOffering: 'professionals',

    // Filters
    filters: 'Filters',
    openFilters: 'Open filters',
    closeFilters: 'Close filters',
    activeFilters: 'active',
    resetFilters: 'Reset all',
    removeFilter: 'Remove filter',
    filterCategory: 'Trade',
    filterArea: 'Area',
    filterRating: 'Minimum rating',
    filterCompletedJobs: 'Completed jobs',
    filterDistance: 'Within',
    filterAvailableNow: 'Available now',
    filterSkillVerified: 'Verified skill certificate',
    filterCertificateVerified: 'Approved professional certificate',
    filterEmergency: 'Emergency available',
    filterPricing: 'Price model',
    filterLanguage: 'Language',
    filterAny: 'Any',

    // Sorting
    sortBy: 'Sort by',
    sortRecommended: 'Recommended',
    sortDistance: 'Distance',
    sortRating: 'Rating',
    sortMostReviewed: 'Most reviewed',
    sortAvailability: 'Availability',
    sortRecommendedHint: 'Uses Warsha’s marketplace ranking policy. No professional pays for placement.',
    sortDistanceHint: 'Needs a location. Not offered while Warsha only knows your area.',
    sortRatingHint: 'Average rating, with review count shown so a single review is visible as one review.',

    // Location
    locationChooseArea: 'Choose your area',
    areaHint: 'Warsha sorts by area, not by tracking you. No location permission is requested to browse.',
    areaTitle: 'Choose an area',

    // Discovery sections
    discoverTitle: 'What do you need help with?',
    availableNearby: 'Available near you',
    trustedWorkers: 'Proven professionals',
    trustedWorkersHint: 'Verified skill certificate and completed work on Warsha.',
    savedWorkers: 'Professionals you saved',
    continueLooking: 'Continue where you left off',
    viewAll: 'View all',

    // Recently viewed
    recentlyViewed: 'Recently viewed',
    recentlyViewedHint: 'Only you can see this. It never affects who is shown to anyone else.',
    clearRecentlyViewed: 'Clear history',
    recentlyViewedEmpty: 'Professionals you open will appear here.',
    historyCleared: 'History cleared',

    // Favourites
    favourites: 'Favourites',
    favouritesEmpty: 'No saved professionals yet',
    favouritesEmptyBody: 'Tap the heart on a professional to save them here.',
    favouritesSignedOut: 'Sign in to save professionals to your account.',
    favouriteUnavailable: 'This professional is not accepting work right now.',
    addFavourite: 'Save professional',
    removeFavourite: 'Remove from saved',

    // Result card
    verifiedIdentity: 'Identity verified',
    verifiedSkill: 'Skill certificate',
    verifiedCertificate: 'Professional certificate',
    availableNow: 'Available now',
    unavailableNow: 'Not available now',
    emergencyAvailable: 'Emergency',
    reviewsLabel: 'reviews',
    oneReviewLabel: 'review',
    noReviewsYet: 'No reviews yet',
    jobsLabel: 'jobs done',
    kilometresAway: 'km away',
    startingFrom: 'From',
  },
  ar: {
    settingsLanguageAppearance: 'اللغة والشكل',
    language: 'اللغة',
    languageHint: 'اختار اللغة اللي ورشة تشتغل بيها.',
    languageDeviceHint: 'ورشة بتمشي مع لغة موبايلك لحد ما تختار لغة من هنا.',
    languageChosenHint: 'اتحفظت. ورشة هتفضل باللغة دي.',
    appearance: 'شكل التطبيق',
    appearanceHint: 'اختار شكل ورشة، أو خليه يتغير حسب إعدادات جهازك.',
    appearanceSystem: 'حسب الجهاز',
    appearanceLight: 'فاتح',
    appearanceDark: 'داكن',
    appearanceSystemHint: 'بيمشي مع جهازك. لو غيّرت إعداد الموبايل، ورشة بتتغير على طول.',
    appearanceLightHint: 'فاتح دايمًا، مهما كان إعداد جهازك.',
    appearanceDarkHint: 'داكن دايمًا، مهما كان إعداد جهازك.',
    appearanceSelected: 'مختار',
    appearanceSaved: 'متحفظ على الجهاز ده',
    appearanceSyncedHint: 'وانت داخل بحسابك، اختيارك بيمشي معاك على أجهزتك التانية.',
    appearanceGuestHint: 'متحفظ على الجهاز ده. سجّل دخول علشان يمشي معاك على أجهزتك التانية.',
    appearanceCurrentlyLight: 'الشكل الحالي فاتح.',
    appearanceCurrentlyDark: 'الشكل الحالي داكن.',

    searchTitle: 'دوّر على صنايعي',
    searchPlaceholder: 'خدمة أو مهنة أو منطقة أو اسم',
    searchAction: 'بحث',
    searchClear: 'مسح البحث',
    searchResults: 'نتيجة',
    searchOneResult: 'نتيجة',
    searchLoading: 'بندوّر…',
    searchRetry: 'حاول تاني',
    searchFailed: 'البحث ما قدرش يخلص.',
    searchOffline: 'يظهر إن مفيش نت. اتأكد من الاتصال وحاول تاني.',
    searchApproximate: 'مفيش نتيجة مطابقة بالظبط. دي أقرب نتائج.',
    searchEmptyTitle: 'مفيش صنايعية مطابقين',
    searchEmptyBody: 'جرّب مهنة أو خدمة أو منطقة أو وصف أبسط للمشكلة.',
    searchBrowseTitle: 'تصفح الصنايعية',
    loadMore: 'عرض المزيد',
    endOfResults: 'دول كل اللي مطابقين لبحثك.',

    recentSearches: 'آخر عمليات البحث',
    clearRecentSearches: 'مسح آخر عمليات البحث',
    suggestedCategories: 'تصفح حسب المهنة',
    commonServices: 'خدمات شائعة',
    commonServicesHint: 'مرتبة حسب عدد الصنايعية اللي بيقدموها.',
    providersOffering: 'صنايعي',

    filters: 'التصفية',
    openFilters: 'فتح التصفية',
    closeFilters: 'قفل التصفية',
    activeFilters: 'مفعّلة',
    resetFilters: 'مسح الكل',
    removeFilter: 'إزالة التصفية',
    filterCategory: 'المهنة',
    filterArea: 'المنطقة',
    filterRating: 'أقل تقييم',
    filterCompletedJobs: 'شغل مكتمل',
    filterDistance: 'في حدود',
    filterAvailableNow: 'متاح دلوقتي',
    filterSkillVerified: 'شهادة مهارة موثقة',
    filterCertificateVerified: 'شهادة مهنية معتمدة',
    filterEmergency: 'بيشتغل طوارئ',
    filterPricing: 'طريقة التسعير',
    filterLanguage: 'اللغة',
    filterAny: 'الكل',

    sortBy: 'الترتيب',
    sortRecommended: 'المقترح',
    sortDistance: 'المسافة',
    sortRating: 'التقييم',
    sortMostReviewed: 'الأكثر تقييمًا',
    sortAvailability: 'المتاح دلوقتي',
    sortRecommendedHint: 'بيستخدم سياسة ترتيب السوق في ورشة. مفيش صنايعي بيدفع علشان يظهر قدام.',
    sortDistanceHint: 'محتاج موقع. مش متاح طالما ورشة عارفة منطقتك بس.',
    sortRatingHint: 'متوسط التقييم، وعدد التقييمات ظاهر علشان تقييم واحد يبان إنه تقييم واحد.',

    locationChooseArea: 'اختار منطقتك',
    areaHint: 'ورشة بترتب حسب المنطقة، مش بتتبعك. مش بنطلب إذن الموقع علشان تتصفح.',
    areaTitle: 'اختار منطقة',

    discoverTitle: 'محتاج مساعدة في إيه؟',
    availableNearby: 'متاحين جنبك',
    trustedWorkers: 'صنايعية بسجل شغل',
    trustedWorkersHint: 'شهادة مهارة موثقة وشغل مكتمل على ورشة.',
    savedWorkers: 'صنايعية حفظتهم',
    continueLooking: 'كمّل من حيث ما وقفت',
    viewAll: 'عرض الكل',

    recentlyViewed: 'شوفتهم مؤخرًا',
    recentlyViewedHint: 'انت بس اللي بتشوف ده. ومش بيأثر على مين بيظهر لأي حد تاني.',
    clearRecentlyViewed: 'مسح السجل',
    recentlyViewedEmpty: 'الصنايعية اللي هتفتحهم هيظهروا هنا.',
    historyCleared: 'اتمسح السجل',

    favourites: 'المفضلة',
    favouritesEmpty: 'مفيش صنايعية محفوظين لسه',
    favouritesEmptyBody: 'اضغط على علامة القلب علشان تحفظ الصنايعي هنا.',
    favouritesSignedOut: 'سجّل دخول علشان تحفظ الصنايعية في حسابك.',
    favouriteUnavailable: 'الصنايعي ده مش بيستقبل شغل دلوقتي.',
    addFavourite: 'حفظ الصنايعي',
    removeFavourite: 'إزالة من المحفوظين',

    verifiedIdentity: 'هوية موثقة',
    verifiedSkill: 'شهادة مهارة',
    verifiedCertificate: 'شهادة مهنية',
    availableNow: 'متاح دلوقتي',
    unavailableNow: 'مش متاح دلوقتي',
    emergencyAvailable: 'طوارئ',
    reviewsLabel: 'تقييم',
    oneReviewLabel: 'تقييم',
    noReviewsYet: 'لسه مفيش تقييمات',
    jobsLabel: 'شغلانة مكتملة',
    kilometresAway: 'كم',
    startingFrom: 'من',
  },
} as const;

export const discoveryCopy = {
  ...baseDiscoveryCopy,
  fr: {
    ...baseDiscoveryCopy.en,
    settingsLanguageAppearance: 'Langue et apparence',
    language: 'Langue',
    languageHint: 'Choisissez la langue utilisée par Warsha.',
    languageDeviceHint: 'Warsha suit la langue de votre téléphone tant que vous n’en choisissez pas une ici.',
    languageChosenHint: 'Enregistré. Warsha reste dans cette langue.',
    appearance: 'Apparence',
    appearanceHint: 'Choisissez l’apparence de Warsha, ou suivez le réglage de votre appareil.',
    appearanceSystem: 'Système',
    appearanceLight: 'Clair',
    appearanceDark: 'Sombre',
    appearanceSystemHint: 'Suit votre appareil. Changer le réglage du téléphone change Warsha aussitôt.',
    appearanceLightHint: 'Toujours clair, quel que soit le réglage de l’appareil.',
    appearanceDarkHint: 'Toujours sombre, quel que soit le réglage de l’appareil.',
    appearanceSelected: 'Sélectionné',
    appearanceSaved: 'Enregistré sur cet appareil',
    appearanceSyncedHint: 'Connecté, votre choix suit votre compte sur vos autres appareils.',
    appearanceGuestHint: 'Enregistré sur cet appareil. Connectez-vous pour le retrouver ailleurs.',
    appearanceCurrentlyLight: 'Apparence claire actuellement affichée.',
    appearanceCurrentlyDark: 'Apparence sombre actuellement affichée.',
  
    /*
     * Everything below was English until 2026-09-10.
     *
     * Eighty-three of a hundred and two keys fell through the
     * `...discoveryCopy.en` spread, so a French customer searched with an
     * English placeholder, filtered by "Minimum rating", and read "No
     * professionals matched" -- on the surface they use most.
     */
    searchTitle: 'Trouver un professionnel',
    searchPlaceholder: 'Service, métier, quartier ou nom',
    searchAction: 'Rechercher',
    searchClear: 'Effacer la recherche',
    searchResults: 'résultats',
    searchOneResult: 'résultat',
    searchLoading: 'Recherche…',
    searchRetry: 'Réessayer',
    searchFailed: "La recherche n'a pas abouti.",
    searchOffline: 'Vous semblez hors ligne. Vérifiez votre connexion et réessayez.',
    searchApproximate: 'Aucune correspondance exacte. Voici les résultats les plus proches.',
    searchEmptyTitle: 'Aucun professionnel trouvé',
    searchEmptyBody: 'Essayez un métier, un service, un quartier, ou décrivez le problème plus simplement.',
    searchBrowseTitle: 'Parcourir les professionnels',
    loadMore: 'Afficher plus',
    endOfResults: 'Vous avez vu tous les résultats.',
    recentSearches: 'Recherches récentes',
    clearRecentSearches: 'Effacer les recherches récentes',
    suggestedCategories: 'Parcourir par métier',
    commonServices: 'Services courants',
    commonServicesHint: 'Classés selon le nombre de professionnels qui les proposent.',
    providersOffering: 'professionnels',
    filters: 'Filtres',
    openFilters: 'Ouvrir les filtres',
    closeFilters: 'Fermer les filtres',
    activeFilters: 'actifs',
    resetFilters: 'Tout réinitialiser',
    removeFilter: 'Retirer le filtre',
    filterCategory: 'Métier',
    filterArea: 'Quartier',
    filterRating: 'Note minimale',
    filterCompletedJobs: 'Travaux terminés',
    filterDistance: 'À moins de',
    filterAvailableNow: 'Disponible maintenant',
    filterSkillVerified: 'Certificat de compétence vérifié',
    filterCertificateVerified: 'Certificat professionnel approuvé',
    filterEmergency: 'Disponible en urgence',
    filterPricing: 'Mode de tarification',
    filterLanguage: 'Langue',
    filterAny: 'Peu importe',
    sortBy: 'Trier par',
    sortRecommended: 'Recommandés',
    sortDistance: 'Distance',
    sortRating: 'Note',
    sortMostReviewed: 'Les plus évalués',
    sortAvailability: 'Disponibilité',
    sortRecommendedHint: 'Utilise la politique de classement de Warsha. Aucun professionnel ne paie pour être mieux placé.',
    sortDistanceHint: 'Nécessite une position. Indisponible tant que Warsha ne connaît que votre quartier.',
    sortRatingHint: "Note moyenne, avec le nombre d'avis affiché pour qu'un avis unique se voie comme tel.",
    locationChooseArea: 'Choisissez votre quartier',
    areaHint: "Warsha trie par quartier, sans vous suivre. Aucune autorisation de localisation n'est demandée pour parcourir.",
    areaTitle: 'Choisir un quartier',
    discoverTitle: 'De quoi avez-vous besoin ?',
    availableNearby: 'Disponibles près de chez vous',
    trustedWorkers: 'Professionnels confirmés',
    trustedWorkersHint: 'Certificat de compétence vérifié et travaux terminés sur Warsha.',
    savedWorkers: 'Professionnels enregistrés',
    continueLooking: 'Reprendre où vous en étiez',
    viewAll: 'Tout voir',
    recentlyViewed: 'Consultés récemment',
    recentlyViewedHint: "Vous seul voyez ceci. Cela n'influence jamais ce qui est montré aux autres.",
    clearRecentlyViewed: "Effacer l'historique",
    recentlyViewedEmpty: 'Les professionnels que vous ouvrez apparaîtront ici.',
    historyCleared: 'Historique effacé',
    favourites: 'Favoris',
    favouritesEmpty: 'Aucun professionnel enregistré',
    favouritesEmptyBody: "Touchez le cœur sur un professionnel pour l'enregistrer ici.",
    favouritesSignedOut: 'Connectez-vous pour enregistrer des professionnels dans votre compte.',
    favouriteUnavailable: "Ce professionnel n'accepte pas de travaux en ce moment.",
    addFavourite: 'Enregistrer le professionnel',
    removeFavourite: 'Retirer des enregistrés',
    verifiedIdentity: 'Identité vérifiée',
    verifiedSkill: 'Certificat de compétence',
    verifiedCertificate: 'Certificat professionnel',
    availableNow: 'Disponible maintenant',
    unavailableNow: 'Indisponible pour le moment',
    emergencyAvailable: 'Urgence',
    reviewsLabel: 'avis',
    oneReviewLabel: 'avis',
    noReviewsYet: 'Aucun avis pour le moment',
    jobsLabel: 'travaux réalisés',
    kilometresAway: 'km',
    startingFrom: 'À partir de',
  },
} as const;

export type DiscoveryTextKey = keyof typeof discoveryCopy.en;
