import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ScreenHeader } from '@/components/warsha/ScreenHeader';
import { AppText } from '@/components/warsha/Typography';
import { colors, radii, spacing, typography } from '@/constants/theme';
import { useLocalization } from '@/src/i18n/localization';
import { useNotifications } from '@/src/notifications/notification-context';
import { notificationBodyKey, notificationCopyKey, useNotificationText } from '@/src/notifications/notification-translations';
import type { WarshaNotification } from '@/src/notifications/notification-types';
import { localeFor } from '@/src/utils/date-format';

export default function NotificationsScreen(){const state=useNotifications();const nt=useNotificationText();return <SafeAreaView style={styles.safe}><FlatList data={state.items} keyExtractor={item=>item.id} refreshing={state.refreshing} onRefresh={()=>void state.reload()} onEndReached={()=>void state.loadMore()} onEndReachedThreshold={.35} contentContainerStyle={styles.content} ItemSeparatorComponent={()=><View style={{height:spacing.sm}}/>} ListHeaderComponent={<View style={styles.header}><ScreenHeader title={nt('notifications')} subtitle={state.unreadCount?`${state.unreadCount} ${nt('newUpdate')}`:undefined}/>{state.unreadCount?<Pressable accessibilityRole="button" accessibilityLabel={nt('markAllRead')} onPress={()=>void state.markAllRead()} style={styles.markAll}><MaterialIcons name="done-all" size={18} color={colors.textPrimary}/><AppText style={styles.markAllText}>{nt('markAllRead')}</AppText></Pressable>:null}</View>} renderItem={({item})=><NotificationCard item={item}/>} ListEmptyComponent={state.loading?<State loading text={nt('notifications')}/>:state.error?<State icon="error-outline" text={nt('loadError')} action={nt('retry')} onPress={()=>void state.reload()}/>:<State icon="notifications-none" text={nt('empty')} body={nt('emptyBody')}/>} ListFooterComponent={state.loadingMore?<ActivityIndicator style={styles.footer} color={colors.white}/>:state.hasMore?<Pressable accessibilityRole="button" accessibilityLabel={nt('loadMore')} onPress={()=>void state.loadMore()} style={styles.more}><AppText>{nt('loadMore')}</AppText></Pressable>:null}/></SafeAreaView>}
function NotificationCard({item}:{item:WarshaNotification}){const state=useNotifications();const nt=useNotificationText();const{isRTL,language}=useLocalization();return <Pressable accessibilityRole="button" accessibilityLabel={`${nt(notificationCopyKey(item.type))}. ${nt(notificationBodyKey(item.type))}`} onPress={()=>void state.open(item)} style={[styles.card,!item.readAt&&styles.unread,isRTL&&styles.rtl]}><View style={[styles.dot,!item.readAt&&styles.dotActive]}/><View style={styles.grow}><AppText style={styles.title}>{nt(notificationCopyKey(item.type))}</AppText><AppText style={styles.body}>{nt(notificationBodyKey(item.type))}</AppText><AppText style={styles.time}>{relativeTime(item.createdAt,language,nt('justNow'))}</AppText></View><View style={styles.actions}>{!item.readAt?<Pressable accessibilityRole="button" accessibilityLabel={nt('markRead')} hitSlop={8} onPress={event=>{event.stopPropagation();void state.markRead(item.id)}}><MaterialIcons name="done" size={19} color={colors.textSecondary}/></Pressable>:null}<Pressable accessibilityRole="button" accessibilityLabel={nt('dismiss')} hitSlop={8} onPress={event=>{event.stopPropagation();void state.dismiss(item.id)}}><MaterialIcons name="close" size={19} color={colors.textSecondary}/></Pressable></View></Pressable>}
function State({icon,text,body,action,onPress,loading}:{icon?:React.ComponentProps<typeof MaterialIcons>['name'];text:string;body?:string;action?:string;onPress?:()=>void;loading?:boolean}){return <View style={styles.state}>{loading?<ActivityIndicator color={colors.white}/>:icon?<MaterialIcons name={icon} size={40} color={colors.textMuted}/>:null}<AppText style={styles.stateTitle}>{text}</AppText>{body?<AppText style={styles.stateBody}>{body}</AppText>:null}{action?<Pressable accessibilityRole="button" accessibilityLabel={action} onPress={onPress} style={styles.retry}><AppText>{action}</AppText></Pressable>:null}</View>}
function relativeTime(value:string,language:'en'|'ar',justNow:string){const elapsed=Date.now()-Date.parse(value);const formatter=new Intl.RelativeTimeFormat(localeFor(language),{numeric:'auto'});if(elapsed<60000)return justNow;if(elapsed<3600000)return formatter.format(-Math.max(1,Math.round(elapsed/60000)),'minute');if(elapsed<86400000)return formatter.format(-Math.max(1,Math.round(elapsed/3600000)),'hour');return formatter.format(-Math.max(1,Math.round(elapsed/86400000)),'day')}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,paddingBottom:spacing.xxxl,maxWidth:720,width:'100%',alignSelf:'center',flexGrow:1},header:{gap:spacing.md,marginBottom:spacing.lg},markAll:{alignSelf:'flex-start',minHeight:42,flexDirection:'row',alignItems:'center',gap:spacing.sm,paddingHorizontal:spacing.md,borderWidth:1,borderColor:colors.border,borderRadius:radii.pill},markAllText:{fontSize:12,fontWeight:typography.semibold},card:{minHeight:112,flexDirection:'row',gap:spacing.md,padding:spacing.lg,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,backgroundColor:colors.surface},rtl:{flexDirection:'row-reverse'},unread:{backgroundColor:colors.surfaceElevated,borderColor:colors.borderSoft},dot:{width:7,height:7,borderRadius:4,marginTop:7,backgroundColor:'transparent'},dotActive:{backgroundColor:colors.white},grow:{flex:1,gap:5},title:{fontSize:15,fontWeight:typography.bold},body:{fontSize:13,lineHeight:19,color:colors.textSecondary},time:{fontSize:11,color:colors.textMuted},actions:{gap:spacing.lg,alignItems:'center'},state:{minHeight:360,alignItems:'center',justifyContent:'center',gap:spacing.md,padding:spacing.xl},stateTitle:{fontSize:18,fontWeight:typography.semibold,textAlign:'center'},stateBody:{fontSize:13,lineHeight:19,color:colors.textMuted,textAlign:'center'},retry:{minHeight:44,paddingHorizontal:spacing.lg,borderWidth:1,borderColor:colors.border,borderRadius:radii.md,justifyContent:'center'},more:{minHeight:46,alignItems:'center',justifyContent:'center',marginTop:spacing.md},footer:{margin:spacing.lg}});
