import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { Image } from 'expo-image';
import * as ImagePicker from 'expo-image-picker';
import { router } from 'expo-router';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ProviderJobsContent } from '@/components/warsha/ProviderJobsContent';
import { ScreenHeader } from '@/components/warsha/ScreenHeader';
import { AppText } from '@/components/warsha/Typography';
import { colors, radii, spacing, typography } from '@/constants/theme';
import { useMarketplaceData } from '@/src/data/marketplace-context';
import { useLocalization } from '@/src/i18n/localization';
import { usePaymentText } from '@/src/i18n/payment-translations';
import { useProviderText } from '@/src/i18n/provider-translations';
import { useVerificationText, type VerificationCopyKey } from '@/src/i18n/verification-translations';
import { useProviderJobs } from '@/src/provider-jobs/provider-job-context';
import { useProviderFoundation } from '@/src/providers/provider-context';
import { listProviderServiceOptions } from '@/src/providers/provider-repository';
import { emptyProviderDraft, type ProviderDraft, type ProviderPricingModel } from '@/src/providers/provider-types';
import { useVerification } from '@/src/verification/verification-context';
import type { VerificationStatus } from '@/src/verification/verification-types';

type Section='jobs'|'profile';
const pricing:ProviderPricingModel[]=['fixed','starting','hourly','inspection','quote'];
const pricingLabels:Record<'en'|'ar',Record<ProviderPricingModel,string>>={en:{fixed:'Fixed price',starting:'Starting from',hourly:'Hourly',inspection:'Inspection fee',quote:'Quote required'},ar:{fixed:'سعر ثابت',starting:'يبدأ من',hourly:'بالساعة',inspection:'رسوم معاينة',quote:'تحتاج عرض سعر'}};
const sectionIcons:Record<Section,React.ComponentProps<typeof MaterialIcons>['name']>={jobs:'work-outline',profile:'person-outline'};
const verificationStatusCopy:Record<VerificationStatus,VerificationCopyKey>={not_started:'notStarted',draft:'draft',submitted:'submitted',under_review:'underReview',approved:'approved',rejected:'rejected',requires_resubmission:'requiresResubmission',expired:'expired'};

export default function ProviderMode(){
  const pt=useProviderText();const payText=usePaymentText();const{t,isRTL,language}=useLocalization();const{categories}=useMarketplaceData();const state=useProviderFoundation();const jobState=useProviderJobs();const verificationState=useVerification();
  const[draft,setDraft]=useState<ProviderDraft>(state.profile??emptyProviderDraft);const[section,setSection]=useState<Section>('jobs');const[step,setStep]=useState(0);const[options,setOptions]=useState<{id:string;name:string}[]>([]);const[optionsLoading,setOptionsLoading]=useState(true);const[optionsError,setOptionsError]=useState(false);const optionsRequest=useRef(0);
  const loadOptions=useCallback(async()=>{const request=++optionsRequest.current;setOptionsLoading(true);setOptionsError(false);try{const value=await listProviderServiceOptions();if(request===optionsRequest.current)setOptions(value)}catch{if(request===optionsRequest.current){setOptions([]);setOptionsError(true)}}finally{if(request===optionsRequest.current)setOptionsLoading(false)}},[]);
  useEffect(()=>{if(state.profile)setDraft(state.profile)},[state.profile]);
  useEffect(()=>{void loadOptions();return()=>{optionsRequest.current+=1}},[loadOptions]);
  const ready=useMemo(()=>Boolean(draft.displayName.trim()&&draft.profession.trim()&&draft.categoryIds.length&&draft.services.length&&draft.areas[0]?.governorate.trim()&&draft.agreementAccepted),[draft]);
  if(state.loading)return <Page><ActivityIndicator color={colors.white}/></Page>;
  const save=async(submit=false)=>{if(!draft.displayName.trim()||!draft.profession.trim()||(submit&&!ready)){Alert.alert(pt('foundation'),pt('required'));return}try{await state.save(draft,submit);Alert.alert(pt('saved'))}catch{Alert.alert(pt('foundation'),pt('retry'))}};
  const pick=async()=>{const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:.75});if(!result.canceled){try{const url=await state.uploadAvatar(result.assets[0].uri,result.assets[0].mimeType);setDraft(current=>({...current,avatarUrl:url}))}catch{Alert.alert(pt('profilePhoto'),pt('retry'))}}};
  return <SafeAreaView style={styles.safe}><View style={styles.header}><ScreenHeader title={pt(section==='profile'?'providerProfile':'jobs')}/><View style={[styles.nav,isRTL&&styles.reverse]}>{(['jobs','profile'] as Section[]).map(item=><Pressable key={item} onPress={()=>setSection(item)} style={[styles.navItem,section===item&&styles.active]}><MaterialIcons name={sectionIcons[item]} size={26} color={section===item?colors.background:colors.textMuted}/><AppText style={section===item&&styles.dark}>{pt(item)}</AppText></Pressable>)}</View></View><ScrollView refreshControl={<RefreshControl refreshing={jobState.refreshing||verificationState.refreshing} onRefresh={()=>void Promise.all([jobState.reload(true),verificationState.reload(true)])} tintColor={colors.white}/>} contentContainerStyle={[styles.content,isRTL&&{direction:'rtl'}]}>
    {section==='jobs'?<><Pressable accessibilityRole="button" accessibilityLabel={language==='ar'?'عروض الأسعار':'Quote invitations'} onPress={()=>router.push('/worker-quotes')} style={styles.earnings}><View style={styles.earningsIcon}><MaterialIcons name="request-quote" size={28} color={colors.background}/></View><View style={styles.grow}><AppText style={styles.title}>{language==='ar'?'عروض الأسعار':'Quote invitations'}</AppText><AppText style={styles.mutedLeft}>{language==='ar'?'راجع الطلبات وابعت أو عدّل عرضك':'Review requests and send or revise your quote'}</AppText></View><MaterialIcons name={isRTL?'arrow-back':'arrow-forward'} size={24} color={colors.white}/></Pressable><Pressable accessibilityRole="button" accessibilityLabel={payText('earnings')} onPress={()=>router.push('/provider-earnings')} style={styles.earnings}><View style={styles.earningsIcon}><MaterialIcons name="payments" size={28} color={colors.background}/></View><View style={styles.grow}><AppText style={styles.title}>{payText('earnings')}</AppText><AppText style={styles.mutedLeft}>{payText('availableWithdraw')} · {payText('pending')} · {payText('paidOut')}</AppText></View><MaterialIcons name={isRTL?'arrow-back':'arrow-forward'} size={24} color={colors.white}/></Pressable><VerificationSummary/><ProviderJobsContent/></>:null}
    {section==='profile'?<><View style={styles.steps}>{[0,1,2,3].map(index=><Pressable accessibilityLabel={[pt('publicInfo'),pt('servicesPricing'),pt('areasAvailability'),pt('reviewSubmit')][index]} key={index} onPress={()=>setStep(index)} style={[styles.step,step===index&&styles.active]}><AppText style={step===index&&styles.dark}>{index+1}</AppText></Pressable>)}</View>
      {step===0?<Card><Pressable accessibilityLabel={pt('profilePhoto')} onPress={()=>void pick()} style={styles.photo}>{draft.avatarUrl?<Image source={{uri:draft.avatarUrl}} style={styles.photo}/>:<MaterialIcons name="add-a-photo" size={28} color={colors.white}/>}</Pressable><Field label={pt('displayName')} value={draft.displayName} onChangeText={displayName=>setDraft(current=>({...current,displayName}))}/><Field label={pt('profession')} value={draft.profession} onChangeText={profession=>setDraft(current=>({...current,profession}))}/><Field label={pt('bio')} value={draft.about} multiline onChangeText={about=>setDraft(current=>({...current,about}))}/><Field label={pt('experience')} value={String(draft.experienceYears)} keyboardType="number-pad" onChangeText={value=>setDraft(current=>({...current,experienceYears:Number(value)||0}))}/><Field label={pt('languagesHint')} value={draft.languages.join(', ')} onChangeText={value=>setDraft(current=>({...current,languages:value.split(',').map(item=>item.trim()).filter(Boolean)}))}/><Field label={pt('skillsHint')} value={draft.skills.join(', ')} onChangeText={value=>setDraft(current=>({...current,skills:value.split(',').map(item=>item.trim()).filter(Boolean)}))}/><AppText style={styles.title}>{pt('categoriesLabel')}</AppText><Wrap>{categories.map(category=><Chip key={category.id} label={t(category.label)} selected={draft.categoryIds.includes(category.id)} onPress={()=>setDraft(current=>({...current,categoryIds:current.categoryIds.includes(category.id)?current.categoryIds.filter(id=>id!==category.id):[...current.categoryIds,category.id]}))}/>)}</Wrap></Card>:null}
      {step===1?<Card><AppText style={styles.title}>{pt('offeredServices')}</AppText>{optionsLoading?<ActivityIndicator color={colors.white}/>:optionsError?<View style={styles.optionError}><AppText style={styles.muted}>{pt('retry')}</AppText><Pressable accessibilityRole="button" accessibilityLabel={pt('retry')} onPress={()=>void loadOptions()} style={styles.outline}><AppText>{pt('retry')}</AppText></Pressable></View>:options.map(option=>{const selected=draft.services.find(item=>item.serviceId===option.id);return <View key={option.id} style={styles.service}><Chip label={option.name} selected={Boolean(selected)} onPress={()=>setDraft(current=>({...current,services:selected?current.services.filter(item=>item.serviceId!==option.id):[...current.services,{serviceId:option.id,name:option.name,price:0,pricingModel:'starting',transportationFee:0,emergencySurcharge:0}]}))}/>{selected?<><Field label={pt('price')} value={String(selected.price)} keyboardType="decimal-pad" onChangeText={value=>changeService(setDraft,option.id,{price:Number(value)||0})}/><Wrap>{pricing.map(model=><Chip key={model} label={pricingLabels[language][model]} selected={selected.pricingModel===model} onPress={()=>changeService(setDraft,option.id,{pricingModel:model})}/>)}</Wrap><Field label={pt('transport')} value={String(selected.transportationFee)} keyboardType="decimal-pad" onChangeText={value=>changeService(setDraft,option.id,{transportationFee:Number(value)||0})}/><Field label={pt('emergencyFee')} value={String(selected.emergencySurcharge)} keyboardType="decimal-pad" onChangeText={value=>changeService(setDraft,option.id,{emergencySurcharge:Number(value)||0})}/></>:null}</View>})}</Card>:null}
      {step===2?<Card><Field label={pt('governorate')} value={draft.areas[0]?.governorate??''} onChangeText={value=>setDraft(current=>({...current,areas:[{governorate:value,district:current.areas[0]?.district??'',radiusKm:current.serviceRadiusKm}]}))}/><Field label={pt('district')} value={draft.areas[0]?.district??''} onChangeText={value=>setDraft(current=>({...current,areas:[{governorate:current.areas[0]?.governorate??'',district:value,radiusKm:current.serviceRadiusKm}]}))}/><Field label={pt('radius')} value={String(draft.serviceRadiusKm)} keyboardType="number-pad" onChangeText={value=>setDraft(current=>({...current,serviceRadiusKm:Number(value)||1}))}/><Toggle label={draft.isAvailable?pt('available'):pt('unavailable')} value={draft.isAvailable} onPress={()=>{const available=!draft.isAvailable;setDraft(current=>({...current,isAvailable:available}));void state.setAvailability(available).catch(()=>setDraft(current=>({...current,isAvailable:!available})))}}/><Toggle label={pt('emergency')} value={draft.emergencyAvailable} onPress={()=>setDraft(current=>({...current,emergencyAvailable:!current.emergencyAvailable}))}/></Card>:null}
      {step===3?<Card><AppText style={styles.title}>{pt('readyForWork')}</AppText><AppText style={styles.muted}>{ready?pt('readyForWorkHelp'):pt('required')}</AppText><Toggle label={pt('agreement')} value={draft.agreementAccepted} onPress={()=>setDraft(current=>({...current,agreementAccepted:!current.agreementAccepted}))}/><Pressable disabled={state.saving} onPress={()=>void save(false)} style={styles.outline}><AppText>{pt('saveDraft')}</AppText></Pressable><Pressable disabled={state.saving||!ready} onPress={()=>void save(true)} style={[styles.primary,!ready&&styles.disabled]}>{state.saving?<ActivityIndicator color={colors.background}/>:<AppText style={styles.dark}>{pt('goLive')}</AppText>}</Pressable></Card>:null}
    </>:null}
  </ScrollView></SafeAreaView>;
}

function changeService(set:React.Dispatch<React.SetStateAction<ProviderDraft>>,id:string,patch:Partial<ProviderDraft['services'][number]>){set(current=>({...current,services:current.services.map(item=>item.serviceId===id?{...item,...patch}:item)}))}
function Page({children}:{children:React.ReactNode}){return <SafeAreaView style={styles.safe}><View style={styles.center}>{children}</View></SafeAreaView>}
function Card({children}:{children:React.ReactNode}){return <View style={styles.card}>{children}</View>}
function Wrap({children}:{children:React.ReactNode}){return <View style={styles.wrap}>{children}</View>}
function Chip({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.chip,selected&&styles.selected]}><AppText>{label}</AppText></Pressable>}
function Toggle({label,value,onPress}:{label:string;value:boolean;onPress:()=>void}){return <Pressable accessibilityRole="checkbox" accessibilityState={{checked:value}} onPress={onPress} style={styles.toggle}><MaterialIcons name={value?'check-box':'check-box-outline-blank'} size={21} color={colors.white}/><AppText>{label}</AppText></Pressable>}
function Field({label,...props}:{label:string}&React.ComponentProps<typeof TextInput>){const{isRTL}=useLocalization();return <TextInput {...props} accessibilityLabel={label} placeholder={label} placeholderTextColor={colors.textMuted} style={[styles.input,props.multiline&&styles.multiline,{textAlign:isRTL?'right':'left'}]}/>}
function VerificationSummary(){const state=useVerification();const vt=useVerificationText();const verification=state.verification;if(state.loading)return <Card><ActivityIndicator color={colors.white}/></Card>;const status=verification?.status??'not_started';const action=status==='not_started'?vt('startVerification'):['draft','rejected','requires_resubmission','expired'].includes(status)?vt('continueVerification'):vt('reviewVerification');return <Card><View style={styles.verificationRow}><View style={styles.verificationIcon}><MaterialIcons name={verification?.identityVerified?'verified':'shield'} size={30} color={colors.background}/></View><View style={styles.grow}><AppText style={styles.title}>{vt('verification')}</AppText><AppText style={styles.mutedLeft}>{vt(verificationStatusCopy[status])}</AppText></View></View>{verification?.rejectionReason?<AppText style={styles.reason}>{verification.rejectionReason}</AppText>:null}<Pressable accessibilityRole="button" accessibilityLabel={action} onPress={()=>router.push('/provider-verification')} style={styles.primary}><MaterialIcons name="arrow-forward" size={24} color={colors.background}/><AppText style={styles.dark}>{action}</AppText></Pressable></Card>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{padding:spacing.lg,gap:spacing.md},nav:{flexDirection:'row',gap:spacing.sm},reverse:{flexDirection:'row-reverse'},navItem:{flex:1,minHeight:64,alignItems:'center',justifyContent:'center',gap:4,borderRadius:radii.lg,borderWidth:1,borderColor:colors.border},active:{backgroundColor:colors.white},dark:{color:colors.background,fontWeight:typography.bold},content:{padding:spacing.lg,paddingBottom:spacing.xxxl,gap:spacing.lg,maxWidth:720,width:'100%',alignSelf:'center'},center:{flex:1,alignItems:'center',justifyContent:'center',gap:spacing.md,padding:spacing.xl},card:{borderWidth:1,borderColor:colors.border,borderRadius:radii.xl,backgroundColor:colors.surface,padding:spacing.lg,gap:spacing.md},earnings:{minHeight:82,flexDirection:'row',alignItems:'center',gap:spacing.md,borderWidth:1,borderColor:colors.border,borderRadius:radii.xl,backgroundColor:colors.surface,padding:spacing.lg},earningsIcon:{width:52,height:52,borderRadius:18,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},title:{fontSize:17,fontWeight:typography.bold},muted:{color:colors.textMuted,textAlign:'center'},mutedLeft:{color:colors.textMuted},optionError:{gap:spacing.md},primary:{minHeight:58,flexDirection:'row',gap:spacing.sm,borderRadius:radii.lg,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},outline:{minHeight:54,borderRadius:radii.lg,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},disabled:{opacity:.45},steps:{flexDirection:'row',gap:spacing.sm},step:{flex:1,height:48,borderRadius:radii.md,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},photo:{width:96,height:96,borderRadius:48,backgroundColor:colors.surfaceElevated,alignItems:'center',justifyContent:'center',overflow:'hidden'},input:{minHeight:54,borderWidth:1,borderColor:colors.border,borderRadius:radii.md,backgroundColor:colors.surfaceElevated,color:colors.white,paddingHorizontal:spacing.md},multiline:{height:110,textAlignVertical:'top'},wrap:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},chip:{minHeight:46,paddingHorizontal:spacing.md,borderRadius:radii.pill,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},selected:{borderColor:colors.white,backgroundColor:colors.surfaceSoft},service:{gap:spacing.sm,borderTopWidth:1,borderTopColor:colors.border,paddingTop:spacing.md},toggle:{minHeight:48,flexDirection:'row',alignItems:'center',gap:spacing.sm},verificationRow:{flexDirection:'row',alignItems:'center',gap:spacing.md},verificationIcon:{width:54,height:54,borderRadius:18,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},grow:{flex:1},reason:{color:colors.error,lineHeight:20}});
