import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { Image } from 'expo-image';
import * as ImagePicker from 'expo-image-picker';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ProviderDashboardContent, ProviderJobsContent } from '@/components/warsha/ProviderJobsContent';
import { ScreenHeader } from '@/components/warsha/ScreenHeader';
import { AppText } from '@/components/warsha/Typography';
import { colors, radii, spacing, typography } from '@/constants/theme';
import { useMarketplaceData } from '@/src/data/marketplace-context';
import { useLocalization } from '@/src/i18n/localization';
import { useProviderText } from '@/src/i18n/provider-translations';
import { useProviderJobs } from '@/src/provider-jobs/provider-job-context';
import { useProviderFoundation } from '@/src/providers/provider-context';
import { listProviderServiceOptions } from '@/src/providers/provider-repository';
import { emptyProviderDraft, providerCompletion, type ProviderDraft, type ProviderPricingModel } from '@/src/providers/provider-types';

type Section='dashboard'|'jobs'|'calendar'|'messages'|'profile';
const pricing:ProviderPricingModel[]=['fixed','starting','hourly','inspection','quote'];
const sectionIcons:Record<Section,React.ComponentProps<typeof MaterialIcons>['name']>={dashboard:'space-dashboard',jobs:'work-outline',calendar:'calendar-month',messages:'chat-bubble-outline',profile:'person-outline'};

export default function ProviderMode(){
  const pt=useProviderText();const{t,isRTL}=useLocalization();const{categories}=useMarketplaceData();const state=useProviderFoundation();const jobState=useProviderJobs();
  const[draft,setDraft]=useState<ProviderDraft>(state.profile??emptyProviderDraft);const[section,setSection]=useState<Section>('dashboard');const[step,setStep]=useState(0);const[options,setOptions]=useState<{id:string;name:string}[]>([]);
  useEffect(()=>{if(state.profile)setDraft(state.profile)},[state.profile]);
  useEffect(()=>{let active=true;void listProviderServiceOptions().then(value=>{if(active)setOptions(value)}).catch(()=>{});return()=>{active=false}},[]);
  const completion=useMemo(()=>providerCompletion(draft),[draft]);
  if(state.loading)return <Page><ActivityIndicator color={colors.white}/></Page>;
  const save=async(submit=false)=>{if(!draft.displayName.trim()||!draft.profession.trim()||(submit&&completion<100)){Alert.alert(pt('foundation'),pt('required'));return}try{await state.save(draft,submit);Alert.alert(pt('saved'))}catch{Alert.alert(pt('foundation'),pt('retry'))}};
  const pick=async()=>{const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:.75});if(!result.canceled){try{const url=await state.uploadAvatar(result.assets[0].uri,result.assets[0].mimeType);setDraft(current=>({...current,avatarUrl:url}))}catch{Alert.alert(pt('profilePhoto'),pt('retry'))}}};
  return <SafeAreaView style={styles.safe}><View style={styles.header}><ScreenHeader title={pt(section==='profile'?'providerProfile':section)}/><View style={[styles.nav,isRTL&&styles.reverse]}>{(['dashboard','jobs','calendar','messages','profile'] as Section[]).map(item=><Pressable key={item} onPress={()=>setSection(item)} style={[styles.navItem,section===item&&styles.active]}><MaterialIcons name={sectionIcons[item]} size={18} color={section===item?colors.background:colors.textMuted}/><AppText style={section===item&&styles.dark}>{pt(item)}</AppText></Pressable>)}</View></View><ScrollView refreshControl={<RefreshControl refreshing={jobState.refreshing} onRefresh={()=>void jobState.reload(true)} tintColor={colors.white}/>} contentContainerStyle={[styles.content,isRTL&&{direction:'rtl'}]}>
    {section==='dashboard'?<ProviderDashboardContent onViewJobs={()=>setSection('jobs')}/>:null}
    {section==='jobs'?<ProviderJobsContent/>:null}
    {section==='messages'?<Empty icon="chat-bubble-outline" text={pt('messagesComing')}/>:null}
    {section==='calendar'?<Card><AppText style={styles.title}>{pt('workingDays')}</AppText>{draft.availability.filter(item=>item.enabled).map(item=><AppText key={item.weekday} style={styles.muted}>{item.weekday}: {item.startTime} – {item.endTime}</AppText>)}</Card>:null}
    {section==='profile'?<><View style={styles.steps}>{[0,1,2,3].map(index=><Pressable accessibilityLabel={[pt('publicInfo'),pt('servicesPricing'),pt('areasAvailability'),pt('reviewSubmit')][index]} key={index} onPress={()=>setStep(index)} style={[styles.step,step===index&&styles.active]}><AppText style={step===index&&styles.dark}>{index+1}</AppText></Pressable>)}</View>
      {step===0?<Card><Pressable accessibilityLabel={pt('profilePhoto')} onPress={()=>void pick()} style={styles.photo}>{draft.avatarUrl?<Image source={{uri:draft.avatarUrl}} style={styles.photo}/>:<MaterialIcons name="add-a-photo" size={28} color={colors.white}/>}</Pressable><Field label={pt('displayName')} value={draft.displayName} onChangeText={displayName=>setDraft(current=>({...current,displayName}))}/><Field label={pt('profession')} value={draft.profession} onChangeText={profession=>setDraft(current=>({...current,profession}))}/><Field label={pt('bio')} value={draft.about} multiline onChangeText={about=>setDraft(current=>({...current,about}))}/><Field label={pt('experience')} value={String(draft.experienceYears)} keyboardType="number-pad" onChangeText={value=>setDraft(current=>({...current,experienceYears:Number(value)||0}))}/><Field label={pt('languagesHint')} value={draft.languages.join(', ')} onChangeText={value=>setDraft(current=>({...current,languages:value.split(',').map(item=>item.trim()).filter(Boolean)}))}/><Field label={pt('skillsHint')} value={draft.skills.join(', ')} onChangeText={value=>setDraft(current=>({...current,skills:value.split(',').map(item=>item.trim()).filter(Boolean)}))}/><AppText style={styles.title}>{pt('categoriesLabel')}</AppText><Wrap>{categories.map(category=><Chip key={category.id} label={t(category.label)} selected={draft.categoryIds.includes(category.id)} onPress={()=>setDraft(current=>({...current,categoryIds:current.categoryIds.includes(category.id)?current.categoryIds.filter(id=>id!==category.id):[...current.categoryIds,category.id]}))}/>)}</Wrap></Card>:null}
      {step===1?<Card><AppText style={styles.title}>{pt('offeredServices')}</AppText>{options.map(option=>{const selected=draft.services.find(item=>item.serviceId===option.id);return <View key={option.id} style={styles.service}><Chip label={option.name} selected={Boolean(selected)} onPress={()=>setDraft(current=>({...current,services:selected?current.services.filter(item=>item.serviceId!==option.id):[...current.services,{serviceId:option.id,name:option.name,price:0,pricingModel:'starting',transportationFee:0,emergencySurcharge:0}]}))}/>{selected?<><Field label={pt('price')} value={String(selected.price)} keyboardType="decimal-pad" onChangeText={value=>changeService(setDraft,option.id,{price:Number(value)||0})}/><Wrap>{pricing.map(model=><Chip key={model} label={model} selected={selected.pricingModel===model} onPress={()=>changeService(setDraft,option.id,{pricingModel:model})}/>)}</Wrap><Field label={pt('transport')} value={String(selected.transportationFee)} keyboardType="decimal-pad" onChangeText={value=>changeService(setDraft,option.id,{transportationFee:Number(value)||0})}/><Field label={pt('emergencyFee')} value={String(selected.emergencySurcharge)} keyboardType="decimal-pad" onChangeText={value=>changeService(setDraft,option.id,{emergencySurcharge:Number(value)||0})}/></>:null}</View>})}</Card>:null}
      {step===2?<Card><Field label={pt('governorate')} value={draft.areas[0]?.governorate??''} onChangeText={value=>setDraft(current=>({...current,areas:[{governorate:value,district:current.areas[0]?.district??'',radiusKm:current.serviceRadiusKm}]}))}/><Field label={pt('district')} value={draft.areas[0]?.district??''} onChangeText={value=>setDraft(current=>({...current,areas:[{governorate:current.areas[0]?.governorate??'',district:value,radiusKm:current.serviceRadiusKm}]}))}/><Field label={pt('radius')} value={String(draft.serviceRadiusKm)} keyboardType="number-pad" onChangeText={value=>setDraft(current=>({...current,serviceRadiusKm:Number(value)||1}))}/><Toggle label={pt('online')} value={draft.isOnline} onPress={()=>setDraft(current=>({...current,isOnline:!current.isOnline}))}/><Toggle label={pt('emergency')} value={draft.emergencyAvailable} onPress={()=>setDraft(current=>({...current,emergencyAvailable:!current.emergencyAvailable}))}/>{draft.availability.map((availability,index)=><View key={availability.weekday} style={styles.schedule}><Toggle label={`${pt('workingDays')} ${availability.weekday}`} value={availability.enabled} onPress={()=>setDraft(current=>({...current,availability:current.availability.map((item,itemIndex)=>itemIndex===index?{...item,enabled:!item.enabled}:item)}))}/><Field label={pt('start')} value={availability.startTime} onChangeText={value=>setDraft(current=>({...current,availability:current.availability.map((item,itemIndex)=>itemIndex===index?{...item,startTime:value}:item)}))}/><Field label={pt('end')} value={availability.endTime} onChangeText={value=>setDraft(current=>({...current,availability:current.availability.map((item,itemIndex)=>itemIndex===index?{...item,endTime:value}:item)}))}/></View>)}</Card>:null}
      {step===3?<Card><AppText style={styles.big}>{completion}%</AppText><Toggle label={pt('agreement')} value={draft.agreementAccepted} onPress={()=>setDraft(current=>({...current,agreementAccepted:!current.agreementAccepted}))}/><Pressable disabled={state.saving} onPress={()=>void save(false)} style={styles.outline}><AppText>{pt('saveDraft')}</AppText></Pressable><Pressable disabled={state.saving} onPress={()=>void save(true)} style={styles.primary}>{state.saving?<ActivityIndicator color={colors.background}/>:<AppText style={styles.dark}>{pt('submit')}</AppText>}</Pressable></Card>:null}
    </>:null}
  </ScrollView></SafeAreaView>;
}

function changeService(set:React.Dispatch<React.SetStateAction<ProviderDraft>>,id:string,patch:Partial<ProviderDraft['services'][number]>){set(current=>({...current,services:current.services.map(item=>item.serviceId===id?{...item,...patch}:item)}))}
function Page({children}:{children:React.ReactNode}){return <SafeAreaView style={styles.safe}><View style={styles.center}>{children}</View></SafeAreaView>}
function Card({children}:{children:React.ReactNode}){return <View style={styles.card}>{children}</View>}
function Wrap({children}:{children:React.ReactNode}){return <View style={styles.wrap}>{children}</View>}
function Chip({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.chip,selected&&styles.selected]}><AppText>{label}</AppText></Pressable>}
function Toggle({label,value,onPress}:{label:string;value:boolean;onPress:()=>void}){return <Pressable accessibilityRole="checkbox" accessibilityState={{checked:value}} onPress={onPress} style={styles.toggle}><MaterialIcons name={value?'check-box':'check-box-outline-blank'} size={21} color={colors.white}/><AppText>{label}</AppText></Pressable>}
function Field({label,...props}:{label:string}&React.ComponentProps<typeof TextInput>){const{isRTL}=useLocalization();return <TextInput {...props} accessibilityLabel={label} placeholder={label} placeholderTextColor={colors.textMuted} style={[styles.input,props.multiline&&styles.multiline,{textAlign:isRTL?'right':'left'}]}/>}
function Empty({icon,text}:{icon:React.ComponentProps<typeof MaterialIcons>['name'];text:string}){return <View style={styles.center}><MaterialIcons name={icon} size={42} color={colors.textMuted}/><AppText style={styles.muted}>{text}</AppText></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{padding:spacing.lg,gap:spacing.md},nav:{flexDirection:'row',gap:4},reverse:{flexDirection:'row-reverse'},navItem:{flex:1,minHeight:54,alignItems:'center',justifyContent:'center',gap:3,borderRadius:radii.md},active:{backgroundColor:colors.white},dark:{color:colors.background,fontWeight:typography.bold},content:{padding:spacing.lg,paddingBottom:spacing.xxxl,gap:spacing.lg,maxWidth:720,width:'100%',alignSelf:'center'},center:{flex:1,alignItems:'center',justifyContent:'center',gap:spacing.md,padding:spacing.xl},card:{borderWidth:1,borderColor:colors.border,borderRadius:radii.xl,backgroundColor:colors.surface,padding:spacing.lg,gap:spacing.md},title:{fontSize:17,fontWeight:typography.bold},big:{fontSize:30,fontWeight:typography.bold},muted:{color:colors.textMuted,textAlign:'center'},primary:{minHeight:52,borderRadius:radii.lg,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},outline:{minHeight:52,borderRadius:radii.lg,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},steps:{flexDirection:'row',gap:spacing.sm},step:{flex:1,height:38,borderRadius:radii.md,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},photo:{width:88,height:88,borderRadius:44,backgroundColor:colors.surfaceElevated,alignItems:'center',justifyContent:'center',overflow:'hidden'},input:{minHeight:50,borderWidth:1,borderColor:colors.border,borderRadius:radii.md,backgroundColor:colors.surfaceElevated,color:colors.white,paddingHorizontal:spacing.md},multiline:{height:110,textAlignVertical:'top'},wrap:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},chip:{minHeight:42,paddingHorizontal:spacing.md,borderRadius:radii.pill,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},selected:{borderColor:colors.white,backgroundColor:colors.surfaceSoft},service:{gap:spacing.sm,borderTopWidth:1,borderTopColor:colors.border,paddingTop:spacing.md},toggle:{minHeight:44,flexDirection:'row',alignItems:'center',gap:spacing.sm},schedule:{gap:spacing.sm,borderTopWidth:1,borderTopColor:colors.border,paddingTop:spacing.md}});
