import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { FlatList, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ProviderListItem } from '@/components/warsha/ProviderListItem'; import { ScreenHeader } from '@/components/warsha/ScreenHeader'; import { AppText } from '@/components/warsha/Typography';
import { colors,radii,spacing,typography } from '@/constants/theme'; import { useMarketplaceData } from '@/src/data/marketplace-context'; import { useLocalization } from '@/src/i18n/localization'; import type { TranslationKey } from '@/src/i18n/translations';
type Sort='recommended'|'nearest'|'topRated'|'lowestPrice';
export default function SearchScreen(){const params=useLocalSearchParams<{q?:string}>();const{t,isRTL}=useLocalization();const{providers}=useMarketplaceData();const[query,setQuery]=useState(params.q??'');const[sort,setSort]=useState<Sort>('recommended');const[available,setAvailable]=useState(false);const[verified,setVerified]=useState(false);const results=useMemo(()=>{const needle=query.trim().toLowerCase();const filtered=providers.filter((provider)=>(!available||provider.available)&&(!verified||provider.verified)&&(!needle||[provider.name,provider.location,provider.about,...provider.skills,t(provider.profession)].join(' ').toLowerCase().includes(needle)));return [...filtered].sort((a,b)=>sort==='nearest'?a.distance-b.distance:sort==='topRated'?b.rating-a.rating:sort==='lowestPrice'?a.price-b.price:b.rating*10+b.reviewCount/100-(a.rating*10+a.reviewCount/100));},[available,providers,query,sort,t,verified]);const sorts:Sort[]=['recommended','nearest','topRated','lowestPrice'];return <SafeAreaView style={styles.safe}><FlatList data={results} keyExtractor={(item)=>item.id} renderItem={({item})=><ProviderListItem provider={item}/>} ItemSeparatorComponent={()=><View style={{height:spacing.md}}/>} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" ListHeaderComponent={<View style={styles.header}><ScreenHeader title={t('searchProviders')} subtitle={`${results.length} ${t('providersFound')}`}/><View style={[styles.search,isRTL&&styles.reverse]}><MaterialIcons name="search" size={23} color={colors.textPrimary}/><TextInput value={query} onChangeText={setQuery} autoFocus={!params.q} placeholder={t('searchHint')} placeholderTextColor={colors.textMuted} style={[styles.input,{textAlign:isRTL?'right':'left',writingDirection:isRTL?'rtl':'ltr'}]}/>{query?<Pressable onPress={()=>setQuery('')}><MaterialIcons name="close" size={20} color={colors.textSecondary}/></Pressable>:null}</View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={[styles.chips,isRTL&&styles.reverse]}>{sorts.map((item)=><Chip key={item} label={t(item as TranslationKey)} selected={sort===item} onPress={()=>setSort(item)}/>)}<Chip label={t('availableOnly')} selected={available} onPress={()=>setAvailable(!available)}/><Chip label={t('verifiedOnly')} selected={verified} onPress={()=>setVerified(!verified)}/></ScrollView></View>} ListEmptyComponent={<AppText style={styles.empty}>{t('noProviders')}</AppText>}/></SafeAreaView>}
function Chip({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.chip,selected&&styles.chipSelected]}><AppText style={[styles.chipText,selected&&styles.chipTextSelected]}>{label}</AppText></Pressable>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,paddingBottom:spacing.xxxl},header:{gap:spacing.md,marginBottom:spacing.lg},search:{height:56,borderRadius:20,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surfaceElevated,flexDirection:'row',alignItems:'center',paddingHorizontal:spacing.lg,gap:spacing.md},reverse:{flexDirection:'row-reverse'},input:{flex:1,color:colors.textPrimary,fontFamily:typography.family,fontSize:15,paddingVertical:0},chips:{gap:spacing.sm,paddingEnd:spacing.sm},chip:{height:36,paddingHorizontal:14,borderRadius:radii.pill,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},chipSelected:{backgroundColor:colors.white,borderColor:colors.white},chipText:{fontSize:12,color:colors.textSecondary,fontWeight:typography.medium},chipTextSelected:{color:colors.background},empty:{padding:spacing.xxxl,textAlign:'center',color:colors.textMuted}});






