import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { router,useFocusEffect,useLocalSearchParams } from 'expo-router';
import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,TextInput,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ScreenHeader } from '@/components/warsha/ScreenHeader';
import { AppText } from '@/components/warsha/Typography';
import { colors,radii,spacing,typography } from '@/constants/theme';
import { useLocalization } from '@/src/i18n/localization';
import { useMarketplaceIntelligence } from '@/src/marketplace-intelligence/marketplace-context';
import { useMarketplaceText } from '@/src/marketplace-intelligence/marketplace-translations';
import { quoteSelectionOpen,type MarketplaceRequest,type QuoteSort,type WorkerQuote } from '@/src/marketplace-intelligence/marketplace-types';

const sorts:QuoteSort[]=['best_value','lowest_price','highest_rated','closest','fastest_arrival','most_experienced'];
export default function MarketplaceRequestDetail(){const{id}=useLocalSearchParams<{id:string}>();const mt=useMarketplaceText();const{isRTL,language}=useLocalization();const market=useMarketplaceIntelligence();const[request,setRequest]=useState<MarketplaceRequest>();const[quotes,setQuotes]=useState<WorkerQuote[]>([]);const[sort,setSort]=useState<QuoteSort>('best_value');const[loading,setLoading]=useState(true);const[clarifying,setClarifying]=useState(false);const[clarification,setClarification]=useState('');const[now,setNow]=useState(Date.now());
  const load=useCallback(async()=>{try{const value=await market.loadRequest(id,sort);setRequest(value.request);setQuotes(value.quotes)}catch{setRequest(undefined)}finally{setLoading(false)}},[id,market,sort]);useFocusEffect(useCallback(()=>{void load()},[load]));useEffect(()=>{const timer=setInterval(()=>{setNow(Date.now());void load()},5000);return()=>clearInterval(timer)},[load]);
  const select=async(quoteId:string)=>{if(!request)return;try{await market.select(request,quoteId);await load()}catch{Alert.alert(mt('selectionWindow'))}};const cancel=()=>Alert.alert(mt('cancelRequest'),request?.issueDescription,[{text:mt('back'),style:'cancel'},{text:mt('cancelRequest'),style:'destructive',onPress:async()=>{await market.cancel(id,'customer_cancelled');await load()}}]);const saveEdit=async()=>{if(!request||clarification.trim().length<8)return;try{const next=await market.edit(request,{descriptionClarification:clarification.trim()});setClarifying(false);if(next!==id)router.replace({pathname:'/marketplace-request/[id]',params:{id:next}});else await load()}catch{Alert.alert(mt('error'))}};
  if(loading)return <Center><ActivityIndicator color={colors.white}/></Center>;if(!request)return <Center><AppText>{mt('error')}</AppText></Center>;
  const selectable=quoteSelectionOpen(request,now);const seconds=Math.max(0,Math.ceil((Date.parse(request.expiresAt)-now)/1000));const active=!['cancelled','expired','converted_to_booking','closed'].includes(request.status);
  return <SafeAreaView style={styles.safe}><ScreenHeader title={mt('quotes')}/><ScrollView contentContainerStyle={[styles.content,isRTL&&{direction:'rtl'}]}>
    <View style={styles.hero}><View style={styles.between}><View style={styles.statusIcon}><MaterialIcons name={request.status==='converted_to_booking'?'check':'auto-awesome'} size={27} color={colors.background}/></View><AppText style={styles.timer}>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</AppText></View><AppText style={styles.title}>{mt(request.status as Parameters<typeof mt>[0])}</AppText><AppText style={styles.muted}>{request.issueDescription}</AppText><AppText style={styles.muted}>{request.area.district}, {request.area.governorate}</AppText></View>
    {active?<View style={styles.actions}><Pressable onPress={()=>setClarifying(value=>!value)} style={styles.outline}><AppText>{mt('editClarification')}</AppText></Pressable><Pressable onPress={cancel} style={styles.outline}><AppText>{mt('cancelRequest')}</AppText></Pressable></View>:null}
    {clarifying?<View style={styles.card}><TextInput value={clarification} onChangeText={setClarification} multiline placeholder={mt('descriptionPlaceholder')} placeholderTextColor={colors.textMuted} style={[styles.input,{textAlign:isRTL?'right':'left'}]}/><Pressable disabled={clarification.trim().length<8} onPress={()=>void saveEdit()} style={styles.primary}><AppText style={styles.primaryText}>{mt('saveClarification')}</AppText></Pressable></View>:null}
    {request.status==='expired'?<Pressable onPress={async()=>{const next=await market.retry(id,'retry');router.replace({pathname:'/marketplace-request/[id]',params:{id:next}})}} style={styles.primary}><AppText style={styles.primaryText}>{mt('retry')}</AppText></Pressable>:null}
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.sorts}>{sorts.map(item=><Pressable key={item} onPress={()=>setSort(item)} style={[styles.sort,sort===item&&styles.selected]}><AppText>{mt(item)}</AppText></Pressable>)}</ScrollView>
    {!selectable&&quotes.length&&active?<View style={styles.notice}><MaterialIcons name="schedule" size={20} color={colors.white}/><AppText style={styles.noticeText}>{mt('selectionWindow')}</AppText></View>:null}
    {quotes.length?quotes.map(quote=><View key={quote.id} style={[styles.card,request.selectedQuoteId===quote.id&&styles.selectedCard]}><View style={styles.between}><View><AppText style={styles.quoteName}>{quote.workerName}</AppText><AppText style={styles.muted}>★ {quote.workerRating.toFixed(1)} · {quote.completedJobs}</AppText></View><AppText style={styles.price}>{(quote.priceMinor/100).toLocaleString(language==='ar'?'ar-EG':'en-EG')} {quote.currency}</AppText></View><AppText style={styles.muted}>{quote.message}</AppText><View style={styles.terms}><Term icon="schedule" text={`${quote.etaMinutes??'—'} ${mt('minutes')}`}/><Term icon="timelapse" text={`${quote.estimatedDurationMinutes} ${mt('minutes')}`}/><Term icon="payments" text={quote.supportedPaymentMethods.join(' / ')}/></View>{active&&request.selectedQuoteId!==quote.id?<Pressable disabled={!selectable} onPress={()=>void select(quote.id)} style={[styles.primary,!selectable&&styles.disabled]}><AppText style={styles.primaryText}>{mt('selectQuote')}</AppText></Pressable>:null}</View>):<View style={styles.empty}><AppText style={styles.muted}>{mt('noQuotes')}</AppText></View>}
    {request.convertedBookingId?<Pressable onPress={()=>router.replace({pathname:'/booking/[id]',params:{id:request.convertedBookingId!}})} style={styles.primary}><AppText style={styles.primaryText}>{mt('converted_to_booking')}</AppText></Pressable>:null}
  </ScrollView></SafeAreaView>}
function Term({icon,text}:{icon:React.ComponentProps<typeof MaterialIcons>['name'];text:string}){return <View style={styles.term}><MaterialIcons name={icon} size={17} color={colors.textMuted}/><AppText style={styles.muted}>{text}</AppText></View>}
function Center({children}:{children:React.ReactNode}){return <SafeAreaView style={styles.safe}><View style={styles.center}>{children}</View></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,paddingBottom:spacing.xxxl,gap:spacing.md,maxWidth:720,width:'100%',alignSelf:'center'},center:{flex:1,alignItems:'center',justifyContent:'center'},hero:{padding:spacing.lg,gap:spacing.sm,borderRadius:radii.xl,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},between:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.md},statusIcon:{width:48,height:48,borderRadius:16,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},timer:{fontVariant:['tabular-nums'],color:colors.textSecondary},title:{fontSize:22,fontWeight:typography.bold},muted:{color:colors.textMuted,lineHeight:20},actions:{flexDirection:'row',gap:spacing.sm},outline:{flex:1,minHeight:48,borderWidth:1,borderColor:colors.border,borderRadius:radii.md,alignItems:'center',justifyContent:'center',paddingHorizontal:spacing.sm},input:{minHeight:105,textAlignVertical:'top',borderWidth:1,borderColor:colors.border,borderRadius:radii.md,color:colors.white,padding:spacing.md},sorts:{gap:spacing.sm},sort:{minHeight:44,paddingHorizontal:spacing.md,borderRadius:radii.pill,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},selected:{borderColor:colors.white,backgroundColor:colors.surfaceSoft},notice:{flexDirection:'row',alignItems:'center',gap:spacing.sm,padding:spacing.md,borderRadius:radii.md,backgroundColor:colors.surfaceSoft},noticeText:{flex:1,color:colors.textSecondary},card:{gap:spacing.md,padding:spacing.lg,borderWidth:1,borderColor:colors.border,borderRadius:radii.xl,backgroundColor:colors.surface},selectedCard:{borderColor:colors.white},quoteName:{fontSize:18,fontWeight:typography.bold},price:{fontSize:19,fontWeight:typography.bold},terms:{flexDirection:'row',flexWrap:'wrap',gap:spacing.md},term:{flexDirection:'row',alignItems:'center',gap:5},primary:{minHeight:52,backgroundColor:colors.white,borderRadius:radii.lg,alignItems:'center',justifyContent:'center',paddingHorizontal:spacing.md},primaryText:{color:colors.background,fontWeight:typography.bold},disabled:{opacity:.4},empty:{padding:spacing.xl,alignItems:'center'}});
