import { File } from 'expo-file-system';
import { getSupabaseClient } from '@/src/lib/supabase';
import type { Address,Booking,BookingStatus,NewBooking,PriceBreakdown } from '@/src/bookings/booking-types';
import type { AddressRepository,BookingRepository,CustomerProfileRepository,FavouriteRepository } from './types';

async function userId(){const{data,error}=await getSupabaseClient().auth.getUser();if(error)throw error;if(!data.user)throw new Error('Authentication required');return data.user.id}
function mapAddress(x:Record<string,unknown>):Address{return{id:String(x.id),label:String(x.label),governorate:String(x.governorate),district:String(x.district??''),street:String(x.street??x.address_line??''),building:String(x.building??''),floor:String(x.floor??''),apartment:String(x.apartment??''),landmark:String(x.landmark??''),instructions:String(x.instructions??''),isDefault:Boolean(x.is_default)}}
export function mapBooking(row:Record<string,unknown>):Booking{const history=(row.booking_status_history as Record<string,unknown>[]??[]).map(event=>({status:String(event.status) as BookingStatus,at:String(event.created_at),note:typeof event.metadata==='object'&&event.metadata?String((event.metadata as Record<string,unknown>).note??''):undefined}));const attachments=(row.booking_attachments as Record<string,unknown>[]??[]).map(item=>({id:String(item.id),uri:String(item.signed_url??''),fileName:String(item.storage_path).split('/').pop(),mimeType:String(item.mime_type??'image/jpeg'),kind:String(item.attachment_kind??'customer_issue') as Booking['attachments'][number]['kind']}));return{id:String(row.id),providerId:String(row.provider_id),serviceId:String(row.service_id),serviceName:String(row.service_name_snapshot),customerName:String(row.customer_name_snapshot??''),issueDescription:String(row.issue_description),notes:String(row.notes??''),attachments,address:String(row.address_snapshot),date:String(row.scheduled_date),time:String(row.scheduled_time).slice(0,5),bookingType:String(row.booking_type??'scheduled') as Booking['bookingType'],priceBreakdown:(row.price_breakdown??undefined) as PriceBreakdown|undefined,price:Number(row.final_price_egp??row.estimated_price_egp),pricingType:String(row.pricing_type) as Booking['pricingType'],status:String(row.status) as BookingStatus,history,createdAt:String(row.created_at),updatedAt:String(row.updated_at),cancellationReason:row.cancellation_reason as Booking['cancellationReason'],rejectionReason:row.rejection_reason?String(row.rejection_reason):undefined,proposedDate:row.proposed_scheduled_date?String(row.proposed_scheduled_date):undefined,proposedTime:row.proposed_scheduled_time?String(row.proposed_scheduled_time).slice(0,5):undefined,providerRescheduleNote:row.provider_reschedule_note?String(row.provider_reschedule_note):undefined,completionNotes:row.completion_notes?String(row.completion_notes):undefined}}
export async function withSignedAttachments(rows:Record<string,unknown>[]){const client=getSupabaseClient();return Promise.all(rows.map(async row=>{const items=row.booking_attachments as Record<string,unknown>[]??[];if(items.length){const{data}=await client.storage.from('booking-attachments').createSignedUrls(items.map(item=>String(item.storage_path)),3600);row.booking_attachments=items.map((item,index)=>({...item,signed_url:data?.[index]?.signedUrl??''}))}const booking=mapBooking(row);if(booking.bookingType==='emergency')booking.time='ASAP';return booking}))}

export const supabaseFavouriteRepository:FavouriteRepository={async list(){const{data,error}=await getSupabaseClient().from('favourites').select('provider_id');if(error)throw error;return data.map(x=>x.provider_id)},async add(providerId){const customer_id=await userId();const{error}=await getSupabaseClient().from('favourites').upsert({customer_id,provider_id:providerId},{onConflict:'customer_id,provider_id'});if(error)throw error},async remove(providerId){const customer_id=await userId();const{error}=await getSupabaseClient().from('favourites').delete().eq('customer_id',customer_id).eq('provider_id',providerId);if(error)throw error}};

export const supabaseAddressRepository:AddressRepository={async list(){const{data,error}=await getSupabaseClient().from('addresses').select('*').is('deleted_at',null).order('is_default',{ascending:false}).order('created_at');if(error)throw error;return data.map(mapAddress)},async add(input){const customer_id=await userId();const{data,error}=await getSupabaseClient().from('addresses').insert({customer_id,label:input.label,address_line:input.street,street:input.street,building:input.building,floor:input.floor,apartment:input.apartment,landmark:input.landmark,instructions:input.instructions,governorate:input.governorate,district:input.district,is_default:input.isDefault??false}).select().single();if(error)throw error;return mapAddress(data)},async update(id,input){const{data,error}=await getSupabaseClient().from('addresses').update({label:input.label,address_line:input.street,street:input.street,building:input.building,floor:input.floor,apartment:input.apartment,landmark:input.landmark,instructions:input.instructions,governorate:input.governorate,district:input.district,is_default:input.isDefault??false}).eq('id',id).select().single();if(error)throw error;return mapAddress(data)},async remove(id){const{error}=await getSupabaseClient().from('addresses').update({deleted_at:new Date().toISOString(),is_default:false}).eq('id',id);if(error)throw error},async setDefault(id){const{error}=await getSupabaseClient().rpc('set_default_address',{address_id:id});if(error)throw error}};

export const supabaseCustomerProfileRepository:CustomerProfileRepository={async get(email){await getSupabaseClient().rpc('ensure_customer_profile');const{data,error}=await getSupabaseClient().from('profiles').select('id,display_name,preferred_language').single();if(error)throw error;return{id:data.id,displayName:data.display_name,preferredLanguage:data.preferred_language,email}},async update(input){const id=await userId();const{data:{user}}=await getSupabaseClient().auth.getUser();const{data,error}=await getSupabaseClient().from('profiles').update({display_name:input.displayName,preferred_language:input.preferredLanguage}).eq('id',id).select('id,display_name,preferred_language').single();if(error)throw error;return{id:data.id,displayName:data.display_name,preferredLanguage:data.preferred_language,email:user?.email??''}}};

async function listBookings(){const{data,error}=await getSupabaseClient().from('bookings').select('*,booking_status_history(*),booking_attachments(*)').is('deleted_at',null).order('created_at',{ascending:false});if(error)throw error;return withSignedAttachments(data as Record<string,unknown>[])}
export async function rollbackBookingAttachmentUpload(bookingId:string,uploaderId:string,paths:string[]){if(!paths.length)return;const client=getSupabaseClient();const cleanupResults=await Promise.allSettled([(async()=>{const{error}=await client.from('booking_attachments').delete().eq('booking_id',bookingId).eq('uploader_id',uploaderId).in('storage_path',paths);if(error)throw error})(),(async()=>{const{error}=await client.storage.from('booking-attachments').remove(paths);if(error)throw error})()]);if(__DEV__)cleanupResults.forEach((result,index)=>{if(result.status==='rejected')console.warn(`Booking attachment ${index===0?'metadata':'object'} rollback failed`,result.reason)})}
async function uploadAttachments(bookingId:string,input:NewBooking){if(!input.attachments.length)return;const uid=await userId();const client=getSupabaseClient();const uploaded:string[]=[];try{for(const attachment of input.attachments){const file=new File(attachment.uri);if(file.size>8*1024*1024)throw new Error('Attachment exceeds size limit');const extension=file.extension||'.jpg';const path=`${uid}/${bookingId}/${attachment.id}${extension}`;const{error}=await client.storage.from('booking-attachments').upload(path,await file.arrayBuffer(),{contentType:attachment.mimeType||file.type||'image/jpeg',upsert:false});if(error)throw error;uploaded.push(path);const{error:metadataError}=await client.from('booking_attachments').insert({booking_id:bookingId,uploader_id:uid,storage_path:path,mime_type:attachment.mimeType||file.type||'image/jpeg'});if(metadataError)throw metadataError}}catch(error){await rollbackBookingAttachmentUpload(bookingId,uid,uploaded);throw error}}
export const supabaseBookingRepository:BookingRepository={async list(){return listBookings()},async create(input){const key=`${await userId()}:${input.providerId}:${input.serviceId}:${input.date}:${input.time}`;const{data,error}=await getSupabaseClient().rpc('create_customer_booking',{p_provider_id:input.providerId,p_service_id:input.serviceId,p_issue_description:input.issueDescription,p_notes:input.notes,p_address_id:typeof input.address==='string'?null:input.address.id,p_scheduled_date:input.date,p_scheduled_time:input.time==='ASAP'?'00:00':input.time,p_booking_type:input.bookingType,p_idempotency_key:key});if(error)throw error;const id=String(data);await uploadAttachments(id,input);return(await listBookings()).find(item=>item.id===id)!},async cancel(id,reason){const{error}=await getSupabaseClient().rpc('cancel_customer_booking',{p_booking_id:id,p_reason:reason});if(error)throw error;return(await listBookings()).find(item=>item.id===id)!},async reschedule(id,date,time){const{error}=await getSupabaseClient().rpc('reschedule_customer_booking',{p_booking_id:id,p_scheduled_date:date,p_scheduled_time:time});if(error)throw error;return(await listBookings()).find(item=>item.id===id)!}};
