/**
 * WPS-023 copy, English and Egyptian Arabic.
 *
 * Two things this copy will not do.
 *
 * It will not imply a government integration. Warsha does not fetch anybody's
 * certificate; the worker gets it themselves and uploads it, and the Arabic
 * says exactly that using the name people actually use — الفيش والتشبيه.
 *
 * It will not promise a review time. There is no measured turnaround and no
 * staffed queue yet, so every waiting message says what is happening and who
 * has it, and stops. "Within 48 hours" would be a number invented to make a
 * screen feel better.
 */

export const onboardingCopy = {
  en: {
    // Gateway
    gatewayWelcome: 'Welcome to Warsha',
    gatewayIntro: 'Sign in to book a service, or create an account to get started.',
    signIn: 'Sign in',
    createAccount: 'Create account',
    gatewayHelp: 'Help',
    gatewayPrivacy: 'Privacy',
    gatewayTerms: 'Terms',
    gatewayLoading: 'Loading Warsha',

    // Role choice
    roleQuestion: 'How will you use Warsha?',
    roleCustomer: 'Customer',
    roleCustomerHint: 'Book plumbers, electricians, carpenters and more.',
    roleWorker: 'Worker',
    roleWorkerHint: 'Offer your services. Needs identity checks before you can start.',
    roleContinue: 'Continue',
    roleBothNote: 'Every account can book services. Choosing Worker also starts your application.',
    roleLocked: 'Your account type cannot be changed while your application is being reviewed.',
    accountSetupIncomplete: 'This signed-in account did not finish Warsha account setup.',
    accountSetupResume: 'Continue the registration you already started.',
    accountSetupCustomerRecovery:
      'This account already has a customer profile. Continue to finish its customer setup.',
    accountSetupCustomerRecoveryAction: 'Continue customer setup',
    accountSetupUnavailable:
      'We cannot safely recover how this account was registered. Try loading it again, or sign out and contact support.',
    accountStateUnavailable:
      'We could not load this account setup. Try again, or sign out and use another account.',

    // Customer address
    addressTitle: 'Where do you need the work done?',
    addressIntro: 'Workers only see this after you book, and only what they need to find you.',
    addressUseLocation: 'Use my current location',
    addressSearch: 'Search for an address',
    addressChooseMap: 'Choose location on map',
    addressSearchPlaceholder: 'Type a street or place',
    addressLocationSaved: 'Location saved',
    addressLocationFailed: 'We could not get that location. Try another option.',
    addressLocationPermissionDenied: 'Location permission was not granted. Choose another option, or allow it in Settings.',
    addressLocationServicesDisabled: 'Location services are off. Turn them on, then try again.',
    addressLocationDeviceUnavailable: 'Your device has no location fix yet. If you are using an emulator, set a simulated location and try again.',
    addressNoSearchResults: 'No matching places found. Try a simpler search.',
    addressLocationLoading: 'Finding the location',
    addressMapDragHint: 'Tap the map or move the pin to the exact destination.',
    addressManual: 'Enter the address myself',
    addressPlaceOnMap: 'Place the pin myself',
    addressUnavailable: 'Not available yet',
    addressLocationUnavailableNote:
      'Map and address search are not enabled in this environment. Use your current location, then complete the structured address below.',
    addressGovernorate: 'Governorate',
    addressCity: 'City or district',
    addressSelectGovernorate: 'Choose governorate',
    addressSelectDistrict: 'Choose city or district',
    addressSearchAdministrativeArea: 'Search governorates and districts',
    close: 'Close',
    addressStreet: 'Street',
    addressBuilding: 'Building',
    addressFloor: 'Floor',
    addressApartment: 'Apartment',
    addressLandmark: 'Nearby landmark',
    addressNotes: 'Notes for the worker',
    addressLatitude: 'Latitude',
    addressLongitude: 'Longitude',
    addressPinRequired: 'A confirmed pin is needed before you can book.',
    addressPinInvalid: 'Those coordinates are outside the possible range.',
    addressConfirm: 'Confirm this location',
    addressConfirmed: 'Location confirmed',
    addressCorrect: 'Change the pin',
    addressPermissionOptional: 'Location permission is optional. You never have to grant it.',

    // Worker onboarding
    workerTitle: 'Your worker application',
    workerIntro: 'Finish these steps and a member of our team will review your application.',
    workerStepsRemaining: 'Steps remaining',
    workerAllStepsDone: 'Every step is done. Your application is with our team.',
    workerAgreementTitle: 'Worker terms',
    workerAgreementBody: 'You accept the worker terms and the way Warsha handles your documents.',
    workerAgreementAccept: 'I accept',
    workerAgreementAccepted: 'Accepted',
    workerDocumentConsent: 'I agree to Warsha processing my identity document and certificate.',

    // Identity capture
    identityTitle: 'National ID',
    identityIntro: 'We need clear photos of both sides. Only our verification team can open them.',
    identityFront: 'Front of your National ID',
    identityBack: 'Back of your National ID',
    identityCapture: 'Take a photo',
    identityChoose: 'Choose a file',
    identityRetake: 'Retake',
    identityPreview: 'Photo captured',
    identityUploading: 'Uploading',
    identityUploadFailed: 'The upload did not finish. Your photo is still here — try again.',
    identityCameraPermission:
      'Warsha needs the camera to photograph your ID. You can pick a saved file instead.',
    identityFrameGuide: 'Fit the whole card inside the frame, on a flat surface.',
    identityWarnBlurry: 'This looks blurry. Hold steady and try again.',
    identityWarnGlare: 'There is glare on the card. Tilt it away from the light.',
    identityWarnResolution: 'This photo is low resolution. Move closer and retake.',
    identityWarnEdges: 'Some of the card edges are cut off.',
    identityFieldsTitle: 'Check your details',
    identityFieldsIntro: 'Correct anything that is wrong. What you confirm is what we review.',
    identityLegalName: 'Full name as printed',
    identityNumber: 'National ID number',
    identityNumberHelp: 'Fourteen digits. We store only the last four and a one-way fingerprint.',
    identityNumberInvalid: 'A National ID number is fourteen digits.',
    identityDateOfBirth: 'Date of birth',
    identityExpiry: 'Expiry date',
    identityManualEntry: 'Type this one in yourself',
    identityConfirmFields: 'Confirm my details',
    identitySubmit: 'Send for review',
    identitySubmitted: 'Your documents are with our team.',
    identityNoExtraction:
      'Automatic reading is switched off, so please type your details from the card.',

    // Criminal record
    certificateTitle: 'Criminal-record certificate',
    certificateWhat: 'The official فيش وتشبيه certificate.',
    certificateHowIntro:
      'You get this certificate yourself from the authorities and upload it here. Warsha cannot request it for you and has no access to any government system.',
    certificateIssueDate: 'Issue date',
    certificateReference: 'Document number (if shown)',
    certificateDeclaredName: 'Name on the certificate',
    certificateUpload: 'Upload the certificate',
    certificateFormats: 'A photo or a PDF, up to 8 MB.',
    certificateSubmitted: 'Your certificate is with our verification team.',
    certificateAcknowledge:
      'I confirm this is my own certificate and the details on it are mine.',
    certificateWrongFormat: 'That file type is not accepted. Use a photo or a PDF.',
    certificateTooLarge: 'That file is larger than 8 MB.',
    certificateFutureDate: 'The issue date cannot be in the future.',
    certificatePrivacy:
      'Only the verification team can open this document, every time it is opened is recorded, and it is never shown to customers.',

    // States
    stateAccountCreated: 'Your account is ready. Start your application.',
    stateOnboardingIncomplete: 'Some steps are still outstanding.',
    stateIdentityRequired: 'Add both sides of your National ID.',
    stateIdentitySubmitted: 'Your identity documents are waiting for review.',
    stateIdentityUnderReview: 'Someone is reviewing your identity documents.',
    stateCertificateRequired: 'Upload your official certificate.',
    stateCertificateSubmitted: 'Your certificate is waiting for review.',
    stateCertificateUnderReview: 'Someone is reviewing your certificate.',
    stateCorrectionRequired: 'Something needs your attention.',
    stateManualReview: 'A reviewer is looking at your application.',
    stateRejected: 'We could not approve your application.',
    stateAppealPending: 'Your appeal is with a different reviewer.',
    stateApproved: 'Approved. We are finishing setting up your account.',
    stateProvisionallyActive: 'You can take work while our team reviews your documents.',
    stateActive: 'You are live on Warsha.',
    stateSuspended: 'Your worker account is on hold.',
    stateNoTimePromise: 'We will tell you as soon as there is an update.',

    // Correction, rejection, appeal
    correctionTitle: 'Please fix this',
    correctionResubmit: 'Send again',
    rejectionTitle: 'Application decision',
    appealTitle: 'Appeal this decision',
    appealIntro: 'Tell us what you think we got wrong. A different reviewer will look.',
    appealStatement: 'Your explanation',
    appealSubmit: 'Send my appeal',
    appealTooShort: 'Please write a little more so a reviewer can understand.',
    appealSubmitted: 'Your appeal was received.',

    // Worker home
    workerHomeTitle: 'Your work',
    workerHomeOpportunities: 'Available jobs',
    workerHomeQuotes: 'Your quotes',
    workerHomeActiveJobs: 'Active jobs',
    workerHomeUpcoming: 'Upcoming',
    workerHomeEarnings: 'Earnings',
    workerHomeAvailability: 'Availability',
    workerHomeProfile: 'Your profile',
    workerHomeSupport: 'Help',
    workerHomeBookAsCustomer: 'Book a service',
    workerHomeCustomerModeHint: 'Need something done at home? Book it like any customer.',
    workerHomePendingNotice: 'You cannot take jobs until your application is approved.',

    // Errors and blocked states
    accountBanned: 'This account cannot be used. Contact support if you think this is wrong.',
    accountDeactivated: 'Your account is deactivated. Sign in again to reactivate it.',
    deletionPending: 'This account is scheduled for deletion.',
    genericError: 'Something went wrong. Please try again.',
    sessionExpired: 'Your session ended. Please sign in again.',
    offlineNotice: 'You are offline. Your progress is saved on this device.',
    unavailableWhilePending: 'This becomes available once your application is approved.',

    // Accessibility
    a11yRoleSelected: 'Selected',
    a11yRoleNotSelected: 'Not selected',
    a11yStepDone: 'Step complete',
    a11yStepTodo: 'Step not complete',
    a11yProgress: 'Application progress',
    a11yFrontCaptured: 'Front of your National ID has been captured',
    a11yBackCaptured: 'Back of your National ID has been captured',
    a11yPinConfirmed: 'Service location confirmed',
  },
  ar: {
    gatewayWelcome: 'أهلاً بيك في ورشة',
    gatewayIntro: 'ادخل على حسابك علشان تحجز خدمة، أو اعمل حساب جديد.',
    signIn: 'تسجيل الدخول',
    createAccount: 'إنشاء حساب',
    gatewayHelp: 'المساعدة',
    gatewayPrivacy: 'الخصوصية',
    gatewayTerms: 'الشروط',
    gatewayLoading: 'بنحمّل ورشة',

    roleQuestion: 'هتستخدم ورشة إزاي؟',
    roleCustomer: 'عميل',
    roleCustomerHint: 'احجز سباك أو كهربائي أو نجار وغيرهم.',
    roleWorker: 'صنايعي',
    roleWorkerHint: 'قدّم شغلك. محتاج تتحقق من هويتك الأول.',
    roleContinue: 'كمّل',
    roleBothNote: 'أي حساب يقدر يحجز خدمات. لو اخترت صنايعي هيبدأ طلبك كمان.',
    roleLocked: 'مش هينفع تغيّر نوع الحساب وطلبك تحت المراجعة.',
    accountSetupIncomplete: 'الحساب اللي داخل بيه ما كمّلش إعداد حساب ورشة.',
    accountSetupResume: 'كمّل التسجيل اللي بدأته قبل كده.',
    accountSetupCustomerRecovery:
      'الحساب ده عنده ملف عميل بالفعل. كمّل إعداد حساب العميل.',
    accountSetupCustomerRecoveryAction: 'كمّل إعداد العميل',
    accountSetupUnavailable:
      'مش قادرين نحدد بأمان الحساب ده اتسجل إزاي. حاول تحمّله تاني، أو اخرج وتواصل مع الدعم.',
    accountStateUnavailable:
      'مقدرناش نحمّل إعداد الحساب ده. حاول تاني، أو اخرج واستخدم حساب تاني.',

    addressTitle: 'الشغل هيتعمل فين؟',
    addressIntro: 'الصنايعي مش هيشوف العنوان غير بعد ما تحجز، وبس اللي يوصله ليك.',
    addressUseLocation: 'استخدم موقعي الحالي',
    addressSearch: 'دوّر على العنوان',
    addressChooseMap: 'اختار الموقع على الخريطة',
    addressSearchPlaceholder: 'اكتب شارع أو مكان',
    addressLocationSaved: 'الموقع اتحفظ',
    addressLocationFailed: 'معرفناش نجيب الموقع ده. جرّب طريقة تانية.',
    addressLocationPermissionDenied: 'إذن الموقع متوافقش عليه. اختار طريقة تانية أو اسمح به من الإعدادات.',
    addressLocationServicesDisabled: 'خدمات الموقع مقفولة. افتحها وحاول تاني.',
    addressLocationDeviceUnavailable: 'الجهاز لسه محددش موقع. لو بتستخدم محاكي، حدد له موقع تجريبي وحاول تاني.',
    addressNoSearchResults: 'ملقيناش مكان مطابق. جرّب بحث أبسط.',
    addressLocationLoading: 'بندور على الموقع',
    addressMapDragHint: 'اضغط على الخريطة أو حرّك العلامة لمكان الشغل بالظبط.',
    addressManual: 'هكتب العنوان بنفسي',
    addressPlaceOnMap: 'هحدد الدبوس بنفسي',
    addressUnavailable: 'لسه مش متاح',
    addressLocationUnavailableNote:
      'الخريطة والبحث عن العنوان مش متاحين في البيئة دي. استخدم موقعك الحالي، وبعدها كمّل العنوان المنظّم تحت.',
    addressGovernorate: 'المحافظة',
    addressCity: 'المدينة أو الحي',
    addressSelectGovernorate: 'اختار المحافظة',
    addressSelectDistrict: 'اختار المدينة أو الحي',
    addressSearchAdministrativeArea: 'دوّر في المحافظات والمناطق',
    close: 'إغلاق',
    addressStreet: 'الشارع',
    addressBuilding: 'العمارة',
    addressFloor: 'الدور',
    addressApartment: 'الشقة',
    addressLandmark: 'علامة مميزة قريبة',
    addressNotes: 'ملاحظات للصنايعي',
    addressLatitude: 'خط العرض',
    addressLongitude: 'خط الطول',
    addressPinRequired: 'لازم تأكد الدبوس قبل ما تحجز.',
    addressPinInvalid: 'الإحداثيات دي برّه النطاق الممكن.',
    addressConfirm: 'أكّد المكان ده',
    addressConfirmed: 'المكان اتأكد',
    addressCorrect: 'غيّر الدبوس',
    addressPermissionOptional: 'إذن الموقع اختياري. مش مضطر توافق عليه أبداً.',

    workerTitle: 'طلبك كصنايعي',
    workerIntro: 'كمّل الخطوات دي وحد من الفريق هيراجع طلبك.',
    workerStepsRemaining: 'خطوات فاضلة',
    workerAllStepsDone: 'كل الخطوات خلصت. طلبك عند الفريق.',
    workerAgreementTitle: 'شروط الصنايعي',
    workerAgreementBody: 'بتوافق على شروط الصنايعي وعلى طريقة تعامل ورشة مع مستنداتك.',
    workerAgreementAccept: 'موافق',
    workerAgreementAccepted: 'تمت الموافقة',
    workerDocumentConsent: 'موافق إن ورشة تعالج إثبات شخصيتي والشهادة بتاعتي.',

    identityTitle: 'الرقم القومي',
    identityIntro: 'محتاجين صور واضحة للوش والضهر. فريق التحقق بس اللي يقدر يفتحها.',
    identityFront: 'وش البطاقة',
    identityBack: 'ضهر البطاقة',
    identityCapture: 'صوّر',
    identityChoose: 'اختار ملف',
    identityRetake: 'صوّر تاني',
    identityPreview: 'الصورة اتاخدت',
    identityUploading: 'بنرفع الصورة',
    identityUploadFailed: 'الرفع ما كملش. الصورة لسه موجودة — جرب تاني.',
    identityCameraPermission:
      'ورشة محتاجة الكاميرا علشان تصوّر البطاقة. تقدر تختار ملف محفوظ بدل كده.',
    identityFrameGuide: 'حط البطاقة كلها جوه الإطار على سطح مستوي.',
    identityWarnBlurry: 'الصورة مش واضحة. ثبّت إيدك وجرب تاني.',
    identityWarnGlare: 'في لمعة على البطاقة. بعّدها عن النور شوية.',
    identityWarnResolution: 'دقة الصورة قليلة. قرّب وصوّر تاني.',
    identityWarnEdges: 'في حواف من البطاقة مقصوصة.',
    identityFieldsTitle: 'راجع بياناتك',
    identityFieldsIntro: 'صحّح أي حاجة غلط. اللي هتأكده هو اللي هنراجعه.',
    identityLegalName: 'الاسم زي ما هو مكتوب',
    identityNumber: 'الرقم القومي',
    identityNumberHelp: 'أربعتاشر رقم. إحنا بنحتفظ بآخر أربعة بس وببصمة مشفّرة.',
    identityNumberInvalid: 'الرقم القومي أربعتاشر رقم.',
    identityDateOfBirth: 'تاريخ الميلاد',
    identityExpiry: 'تاريخ الانتهاء',
    identityManualEntry: 'اكتب ده بنفسك',
    identityConfirmFields: 'أكّد بياناتي',
    identitySubmit: 'ابعت للمراجعة',
    identitySubmitted: 'مستنداتك عند الفريق.',
    identityNoExtraction: 'القراءة التلقائية مقفولة، فاكتب بياناتك من البطاقة من فضلك.',

    certificateTitle: 'الفيش والتشبيه',
    certificateWhat: 'شهادة الفيش والتشبيه الرسمية.',
    certificateHowIntro:
      'انت اللي بتستخرج الفيش بنفسك من الجهات المختصة وترفعه هنا. ورشة مش بتطلبه نيابة عنك ومالهاش أي دخول على أنظمة حكومية.',
    certificateIssueDate: 'تاريخ الاستخراج',
    certificateReference: 'رقم المستند (لو مكتوب)',
    certificateDeclaredName: 'الاسم اللي على الشهادة',
    certificateUpload: 'ارفع الشهادة',
    certificateFormats: 'صورة أو ملف PDF لحد ٨ ميجا.',
    certificateSubmitted: 'الشهادة بتاعتك عند فريق التحقق.',
    certificateAcknowledge: 'بأكد إن دي شهادتي أنا والبيانات اللي فيها بياناتي.',
    certificateWrongFormat: 'نوع الملف ده مش مقبول. استخدم صورة أو PDF.',
    certificateTooLarge: 'الملف أكبر من ٨ ميجا.',
    certificateFutureDate: 'تاريخ الاستخراج مينفعش يكون في المستقبل.',
    certificatePrivacy:
      'فريق التحقق بس اللي يقدر يفتح المستند ده، وكل مرة بيتفتح بتتسجل، والعملاء عمرهم ما يشوفوه.',

    stateAccountCreated: 'حسابك جاهز. ابدأ طلبك.',
    stateOnboardingIncomplete: 'لسه في خطوات ناقصة.',
    stateIdentityRequired: 'ضيف وش وضهر البطاقة.',
    stateIdentitySubmitted: 'مستندات هويتك مستنية المراجعة.',
    stateIdentityUnderReview: 'في حد بيراجع مستندات هويتك.',
    stateCertificateRequired: 'ارفع الفيش والتشبيه.',
    stateCertificateSubmitted: 'الشهادة مستنية المراجعة.',
    stateCertificateUnderReview: 'في حد بيراجع الشهادة.',
    stateCorrectionRequired: 'في حاجة محتاجة انتباهك.',
    stateManualReview: 'في مراجع بيبص على طلبك.',
    stateRejected: 'مقدرناش نوافق على طلبك.',
    stateAppealPending: 'تظلمك عند مراجع تاني.',
    stateApproved: 'اتوافق عليه. بنكمّل تجهيز حسابك.',
    stateProvisionallyActive: 'تقدر تستقبل شغل وفريقنا بيراجع مستنداتك.',
    stateActive: 'حسابك شغال على ورشة.',
    stateSuspended: 'حسابك كصنايعي موقوف مؤقتاً.',
    stateNoTimePromise: 'هنقولك أول ما يبقى في جديد.',

    correctionTitle: 'من فضلك صحّح ده',
    correctionResubmit: 'ابعت تاني',
    rejectionTitle: 'قرار الطلب',
    appealTitle: 'تظلّم على القرار',
    appealIntro: 'قولنا إيه اللي شايفه غلط. مراجع تاني هيبص عليه.',
    appealStatement: 'شرحك',
    appealSubmit: 'ابعت التظلم',
    appealTooShort: 'اكتب شوية كمان علشان المراجع يفهم.',
    appealSubmitted: 'التظلم وصلنا.',

    workerHomeTitle: 'شغلك',
    workerHomeOpportunities: 'شغل متاح',
    workerHomeQuotes: 'عروضك',
    workerHomeActiveJobs: 'شغل شغال',
    workerHomeUpcoming: 'جاي قريب',
    workerHomeEarnings: 'أرباحك',
    workerHomeAvailability: 'مواعيدك',
    workerHomeProfile: 'ملفك',
    workerHomeSupport: 'المساعدة',
    workerHomeBookAsCustomer: 'احجز خدمة',
    workerHomeCustomerModeHint: 'محتاج حاجة تتعمل في بيتك؟ احجزها زي أي عميل.',
    workerHomePendingNotice: 'مش هتقدر تاخد شغل غير لما طلبك يتوافق عليه.',

    accountBanned: 'الحساب ده مش هينفع يتستخدم. كلّم الدعم لو شايف إن ده غلط.',
    accountDeactivated: 'حسابك متوقف. ادخل تاني علشان تفعّله.',
    deletionPending: 'الحساب ده متجدول للحذف.',
    genericError: 'في حاجة غلط حصلت. جرب تاني.',
    sessionExpired: 'الجلسة خلصت. ادخل تاني من فضلك.',
    offlineNotice: 'انت مش متصل بالنت. تقدمك محفوظ على الجهاز ده.',
    unavailableWhilePending: 'ده هيبقى متاح بعد ما طلبك يتوافق عليه.',

    a11yRoleSelected: 'مختار',
    a11yRoleNotSelected: 'مش مختار',
    a11yStepDone: 'الخطوة خلصت',
    a11yStepTodo: 'الخطوة لسه',
    a11yProgress: 'تقدم الطلب',
    a11yFrontCaptured: 'وش البطاقة اتصور',
    a11yBackCaptured: 'ضهر البطاقة اتصور',
    a11yPinConfirmed: 'مكان الخدمة اتأكد',
  },
} as const;

export type OnboardingCopyKey = keyof typeof onboardingCopy.en;
