import { router } from 'expo-router';
import { FlatList, Pressable, ScrollView, StyleSheet, useWindowDimensions, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AddressSelector } from '@/components/warsha/AddressSelector'; import { CategoryCard } from '@/components/warsha/CategoryCard'; import { Header } from '@/components/warsha/Header'; import { OfferBanner } from '@/components/warsha/OfferBanner'; import { ProviderCard } from '@/components/warsha/ProviderCard'; import { RecentBookingCard } from '@/components/warsha/RecentBookingCard'; import { SearchBar } from '@/components/warsha/SearchBar'; import { AppText } from '@/components/warsha/Typography';
import { colors,spacing,typography } from '@/constants/theme'; import { useMarketplaceData } from '@/src/data/marketplace-context'; import { useLocalization } from '@/src/i18n/localization';
function SectionHeader({title,action,onAction}:{title:string;action?:string;onAction?:()=>void}){const{isRTL}=useLocalization();return <View style={[styles.sectionHeader,isRTL&&styles.reverse]}><AppText style={styles.sectionTitle}>{title}</AppText>{action&&onAction?<Pressable accessibilityRole="button" accessibilityLabel={`${action} ${title}`} hitSlop={10} onPress={onAction}><AppText style={styles.action}>{action}</AppText></Pressable>:null}</View>}
export default function HomeScreen(){const{t,isRTL}=useLocalization();const{categories,providers}=useMarketplaceData();const{width}=useWindowDimensions();const pageWidth=Math.min(width,720);const cardWidth=Math.min(278,Math.max(238,pageWidth*.7));return <SafeAreaView edges={['top']} style={styles.safe}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={[styles.content,{maxWidth:720}]}><Header/><View style={styles.controls}><AddressSelector/><SearchBar/></View><SectionHeader title={t('categories')}/><FlatList horizontal inverted={isRTL} showsHorizontalScrollIndicator={false} data={categories} keyExtractor={item=>item.id} renderItem={({item})=><CategoryCard item={item}/>} ItemSeparatorComponent={()=><View style={{width:9}}/>} contentContainerStyle={styles.horizontalContent}/><SectionHeader title={t('featuredProviders')} action={t('viewAll')} onAction={()=>router.push({pathname:'/search',params:{preset:'recommended'}})}/><FlatList horizontal inverted={isRTL} showsHorizontalScrollIndicator={false} data={providers} keyExtractor={item=>item.id} renderItem={({item})=><ProviderCard item={item} width={cardWidth}/>} ItemSeparatorComponent={()=><View style={{width:11}}/>} contentContainerStyle={styles.horizontalContent}/><SectionHeader title={t('specialOffers')} action={t('viewAll')} onAction={()=>router.push({pathname:'/categories/[id]',params:{id:'cleaning'}})}/><OfferBanner/><SectionHeader title={t('recentBookings')} action={t('viewAll')} onAction={()=>router.push('/(tabs)/orders')}/><RecentBookingCard/><View style={{height:spacing.sm}}/></ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{width:'100%',alignSelf:'center',paddingHorizontal:spacing.lg,paddingTop:spacing.md,gap:spacing.lg},controls:{gap:spacing.md},horizontalContent:{paddingVertical:1},sectionHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:spacing.sm},reverse:{flexDirection:'row-reverse'},sectionTitle:{fontSize:19,fontWeight:typography.semibold},action:{fontSize:13,color:colors.textSecondary}});


