import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { Image } from 'expo-image';
import { router } from 'expo-router';
import { useState } from 'react';
import { FlatList, Pressable, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppText } from '@/components/warsha/Typography'; import { colors,radii,spacing,typography } from '@/constants/theme'; import { useBookings,type Booking } from '@/src/bookings/booking-context'; import { useMarketplaceData } from '@/src/data/marketplace-context'; import { useLocalization } from '@/src/i18n/localization';
export default function Orders(){const{bookings}=useBookings();const{t,isRTL}=useLocalization();const[tab,setTab]=useState<'active'|'past'>('active');const visible=bookings.filter((booking)=>tab==='active'?booking.status!=='cancelled':booking.status==='cancelled');return <SafeAreaView edges={['top']} style={styles.safe}><View style={styles.header}><AppText style={styles.title}>{t('orders')}</AppText><AppText style={styles.subtitle}>{t('localDataNotice')}</AppText><View style={[styles.tabs,isRTL&&styles.reverse]}><Tab label={t('activeOrders')} active={tab==='active'} onPress={()=>setTab('active')}/><Tab label={t('pastOrders')} active={tab==='past'} onPress={()=>setTab('past')}/></View></View><FlatList data={visible} keyExtractor={(item)=>item.id} renderItem={({item})=><OrderCard booking={item}/>} ItemSeparatorComponent={()=><View style={{height:spacing.md}}/>} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><View style={styles.emptyIcon}><MaterialIcons name="receipt-long" size={30} color={colors.textSecondary}/></View><AppText style={styles.emptyText}>{tab==='active'?t('noActiveOrders'):t('ordersEmpty')}</AppText></View>}/></SafeAreaView>}
function Tab({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.tab,active&&styles.tabActive]}><AppText style={[styles.tabText,active&&styles.tabTextActive]}>{label}</AppText></Pressable>}
function OrderCard({booking}:{booking:Booking}){const{getProvider}=useMarketplaceData();const provider=getProvider(booking.providerId);const{t,isRTL}=useLocalization();if(!provider)return null;return <Pressable onPress={()=>router.push({pathname:'/booking/[id]',params:{id:booking.id}})} style={styles.card}><View style={[styles.cardTop,isRTL&&styles.reverse]}><Image source={{uri:provider.image}} style={styles.avatar}/><View style={styles.copy}><View style={[styles.nameRow,isRTL&&styles.reverse]}><AppText style={styles.name}>{provider.name}</AppText><View style={[styles.badge,booking.status==='cancelled'&&styles.cancelledBadge]}><AppText style={[styles.badgeText,booking.status==='cancelled'&&styles.cancelledText]}>{t(booking.status)}</AppText></View></View><AppText style={styles.service}>{booking.serviceName}</AppText><AppText style={styles.meta}>{booking.date} Â· {booking.time}</AppText></View></View><View style={[styles.cardBottom,isRTL&&styles.reverse]}><AppText style={styles.price}>{booking.price} EGP</AppText><View style={[styles.details,isRTL&&styles.reverse]}><AppText style={styles.detailsText}>{t('viewDetails')}</AppText><MaterialIcons name={isRTL?'arrow-back':'arrow-forward'} size={16} color={colors.textPrimary}/></View></View></Pressable>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{padding:spacing.lg,gap:spacing.sm},title:{fontSize:28,fontWeight:typography.bold},subtitle:{fontSize:11,color:colors.textMuted},tabs:{flexDirection:'row',padding:4,borderRadius:radii.lg,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,marginTop:spacing.md},reverse:{flexDirection:'row-reverse'},tab:{flex:1,height:40,borderRadius:radii.md,alignItems:'center',justifyContent:'center'},tabActive:{backgroundColor:colors.white},tabText:{fontSize:13,color:colors.textSecondary,fontWeight:typography.semibold},tabTextActive:{color:colors.background},list:{paddingHorizontal:spacing.lg,paddingBottom:spacing.xxxl,flexGrow:1},card:{padding:spacing.md,borderRadius:radii.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,gap:spacing.md},cardTop:{flexDirection:'row',gap:spacing.md},avatar:{width:68,height:78,borderRadius:radii.md},copy:{flex:1,gap:4},nameRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.sm},name:{fontSize:16,fontWeight:typography.semibold,flexShrink:1},badge:{paddingHorizontal:8,paddingVertical:4,borderRadius:radii.pill,backgroundColor:'rgba(127,200,154,.12)'},badgeText:{fontSize:10,color:colors.success,fontWeight:typography.semibold},cancelledBadge:{backgroundColor:'rgba(217,121,121,.12)'},cancelledText:{color:colors.error},service:{fontSize:13,color:colors.textSecondary},meta:{fontSize:11,color:colors.textMuted},cardBottom:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderTopWidth:1,borderTopColor:colors.border,paddingTop:spacing.md},price:{fontSize:15,fontWeight:typography.bold},details:{flexDirection:'row',alignItems:'center',gap:4},detailsText:{fontSize:12,fontWeight:typography.semibold},empty:{flex:1,alignItems:'center',justifyContent:'center',padding:spacing.xxxl,gap:spacing.md},emptyIcon:{width:64,height:64,borderRadius:22,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},emptyText:{fontSize:14,color:colors.textMuted,textAlign:'center'}});


