import MaterialIcons from '@expo/vector-icons/MaterialIcons'; import { Image } from 'expo-image'; import { router } from 'expo-router'; import { useState } from 'react'; import { ActivityIndicator,FlatList,Pressable,StyleSheet,View } from 'react-native'; import { SafeAreaView } from 'react-native-safe-area-context'; import { AppText } from '@/components/warsha/Typography'; import { colors,radii,spacing,typography } from '@/constants/theme'; import { terminalStatuses,bookingStatusTranslationKeys,type Booking } from '@/src/bookings/booking-types'; import { useBookings } from '@/src/bookings/booking-context'; import { useMarketplaceData } from '@/src/data/marketplace-context'; import { formatBookingDateTime,formatNumber,localeFor } from '@/src/utils/date-format'; import { useLocalization } from '@/src/i18n/localization';
type Tab='upcoming'|'past'|'cancelled';export default function Orders(){const{bookings,loading,error,reload}=useBookings();const{t}=useLocalization();const[tab,setTab]=useState<Tab>('upcoming');const visible=bookings.filter((booking)=>tab==='cancelled'?booking.status==='cancelled':tab==='past'?terminalStatuses.includes(booking.status)&&booking.status!=='cancelled':!terminalStatuses.includes(booking.status));return <SafeAreaView style={styles.safe}><View style={styles.header}><AppText style={styles.title}>{t('orders')}</AppText><View style={styles.tabs}>{(['upcoming','past','cancelled'] as Tab[]).map((item)=><Pressable key={item} onPress={()=>setTab(item)} style={[styles.tab,tab===item&&styles.active]}><AppText style={[styles.tabText,tab===item&&styles.activeText]}>{t(item==='cancelled'?'cancelledTab':item)}</AppText></Pressable>)}</View></View>{loading?<View style={styles.center}><ActivityIndicator color={colors.white}/></View>:error?<View style={styles.center}><AppText style={styles.empty}>{t('genericTryAgain')}</AppText><Pressable onPress={()=>void reload()} style={styles.retry}><AppText style={styles.activeText}>{t('tryAgain')}</AppText></Pressable></View>:<FlatList data={visible} keyExtractor={(item)=>item.id} renderItem={({item})=><OrderCard booking={item}/>} ItemSeparatorComponent={()=><View style={{height:spacing.md}}/>} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.center}><MaterialIcons name="receipt-long" size={38} color={colors.textMuted}/><AppText style={styles.empty}>{t('noBookings')}</AppText></View>}/>}</SafeAreaView>}
function OrderCard({booking}:{booking:Booking}){const{t,isRTL,language}=useLocalization();const{getProvider}=useMarketplaceData();const provider=getProvider(booking.providerId);if(!provider)return null;return <Pressable onPress={()=>router.push({pathname:'/booking/[id]',params:{id:booking.id}})} style={[styles.card,isRTL&&{direction:'rtl'}]}><View style={styles.top}><Image source={{uri:provider.image}} style={styles.avatar}/><View style={styles.grow}><View style={styles.between}><AppText style={styles.name}>{provider.name}</AppText><View style={[styles.badge,booking.status==='cancelled'&&styles.cancelBadge]}><AppText style={[styles.badgeText,booking.status==='cancelled'&&styles.cancelText]}>{t(bookingStatusTranslationKeys[booking.status])}</AppText></View></View><AppText style={styles.service}>{booking.serviceName}</AppText><AppText style={styles.meta}>{formatBookingDateTime(booking.date,booking.time,localeFor(language))}</AppText></View></View><View style={styles.bottom}><AppText style={styles.price}>{formatNumber(booking.priceBreakdown?.estimatedTotal??booking.price,language)} {t('currency')}</AppText><View style={styles.detailLink}><AppText style={styles.details}>{t('viewDetails')}</AppText><MaterialIcons name={isRTL?'arrow-back':'arrow-forward'} size={15} color={colors.white}/></View></View></Pressable>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{padding:spacing.lg,paddingBottom:spacing.xl,gap:spacing.xl},title:{fontSize:28,fontWeight:typography.bold},tabs:{flexDirection:'row',padding:4,borderRadius:radii.lg,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},tab:{flex:1,height:40,borderRadius:radii.md,alignItems:'center',justifyContent:'center'},active:{backgroundColor:colors.white},tabText:{fontSize:12,color:colors.textSecondary,fontWeight:typography.semibold},activeText:{color:colors.background,fontWeight:typography.bold},list:{paddingHorizontal:spacing.lg,paddingBottom:spacing.xxxl,flexGrow:1},center:{flex:1,alignItems:'center',justifyContent:'center',gap:spacing.md,padding:spacing.xxxl},empty:{fontSize:14,color:colors.textMuted,textAlign:'center'},retry:{backgroundColor:colors.white,padding:spacing.md,borderRadius:radii.md},card:{padding:spacing.lg,borderRadius:radii.lg,borderWidth:1,borderColor:colors.borderSoft,backgroundColor:colors.surface,gap:spacing.md},top:{flexDirection:'row',gap:spacing.md},avatar:{width:68,height:78,borderRadius:radii.md},grow:{flex:1,gap:4},between:{flexDirection:'row',justifyContent:'space-between',gap:spacing.sm},name:{fontSize:16,fontWeight:typography.semibold,flexShrink:1},badge:{maxWidth:120,paddingHorizontal:7,paddingVertical:4,borderRadius:radii.pill,backgroundColor:'rgba(127,200,154,.12)'},badgeText:{fontSize:9,color:colors.success,textAlign:'center'},cancelBadge:{backgroundColor:'rgba(217,121,121,.12)'},cancelText:{color:colors.error},service:{fontSize:13,color:colors.textSecondary},meta:{fontSize:11,color:colors.textMuted},bottom:{flexDirection:'row',justifyContent:'space-between',borderTopWidth:1,borderTopColor:colors.border,paddingTop:spacing.md},price:{fontSize:15,fontWeight:typography.bold},detailLink:{flexDirection:'row',alignItems:'center',gap:4},details:{fontSize:12,fontWeight:typography.semibold}});







