import { useLocalization } from '@/src/i18n/localization';

const copy={
  en:{
    requestQuote:'Request a Quote',getQuotes:'Get Quotes',quotes:'Quotes',newRequest:'New work request',describe:'Describe what you need',descriptionPlaceholder:'Tell workers what needs to be fixed or done',schedule:'When do you need it?',asap:'ASAP',today:'Today',scheduled:'Scheduled',flexible:'Flexible',payment:'Payment preference',either:'Cash or online',cash:'Cash',online:'Online',sendRequest:'Send request',requestSent:'Request sent',matching:'Finding eligible workers',collecting_quotes:'Collecting quotes',customer_reviewing:'Compare your quotes',selection_pending_confirmation:'Waiting for worker confirmation',worker_confirmed:'Worker confirmed',converted_to_booking:'Booking created',rescue_matching:'Finding a replacement',cancelled:'Request cancelled',expired:'Request expired',closed:'Closed',best_value:'Best Value',lowest_price:'Lowest Price',highest_rated:'Highest Rated',closest:'Closest',fastest_arrival:'Fastest Arrival',most_experienced:'Most Experienced',selectQuote:'Select quote',selectionWindow:'Quote selection opens after the two-minute collection window.',price:'Price',arrival:'Arrival',duration:'Duration',laborIncluded:'Labor included',materials:'Materials',warranty:'Warranty',noQuotes:'No quotes yet. Matching continues while the request is active.',cancelRequest:'Cancel request',retry:'Retry now',workerQuotes:'Quote invitations',noInvitations:'No quote invitations right now.',sendQuote:'Send quote',reviseQuote:'Revise quote',confirmSelection:'Confirm selected quote',decline:'Decline',emergencyAccept:'Accept emergency request',emergencySurcharge:'Emergency surcharge',approveSurcharge:'Approve surcharge and create request',unavailable:'Marketplace Intelligence is not activated on this environment.',minutes:'min',days:'days',requestUpdated:'Request updated',editClarification:'Clarify request',saveClarification:'Save clarification',back:'Back',loading:'Loading…',error:'Something went wrong. Try again.',cashOrOnline:'Cash / online',quoteHistory:'Quote history'},
  ar:{
    requestQuote:'اطلب عرض سعر',getQuotes:'هات عروض أسعار',quotes:'عروض الأسعار',newRequest:'طلب شغل جديد',describe:'اوصف الشغل اللي محتاجه',descriptionPlaceholder:'قول للصنايعية إيه اللي محتاج يتصلح أو يتعمل',schedule:'محتاج الخدمة إمتى؟',asap:'في أسرع وقت',today:'النهارده',scheduled:'ميعاد محدد',flexible:'ميعاد مرن',payment:'طريقة الدفع المناسبة',either:'كاش أو أونلاين',cash:'كاش',online:'أونلاين',sendRequest:'ابعت الطلب',requestSent:'الطلب اتبعت',matching:'بندور على صنايعية مناسبين',collecting_quotes:'بنجمع عروض أسعار',customer_reviewing:'قارن عروض الأسعار',selection_pending_confirmation:'مستنيين تأكيد الصنايعي',worker_confirmed:'الصنايعي أكد',converted_to_booking:'الحجز اتعمل',rescue_matching:'بندور على بديل',cancelled:'الطلب اتلغى',expired:'وقت الطلب انتهى',closed:'مقفول',best_value:'أفضل قيمة',lowest_price:'أقل سعر',highest_rated:'أعلى تقييم',closest:'الأقرب',fastest_arrival:'أسرع وصول',most_experienced:'الأكثر خبرة',selectQuote:'اختار العرض',selectionWindow:'تقدر تختار بعد فترة التجميع العادلة ومدتها دقيقتين.',price:'السعر',arrival:'الوصول',duration:'المدة',laborIncluded:'المصنعية شاملة',materials:'الخامات',warranty:'الضمان',noQuotes:'لسه مفيش عروض. البحث شغال طول ما الطلب متاح.',cancelRequest:'إلغاء الطلب',retry:'حاول تاني',workerQuotes:'طلبات عروض الأسعار',noInvitations:'مفيش طلبات عروض أسعار دلوقتي.',sendQuote:'ابعت عرض السعر',reviseQuote:'عدّل عرض السعر',confirmSelection:'أكد العرض المختار',decline:'اعتذر',emergencyAccept:'اقبل طلب الطوارئ',emergencySurcharge:'رسوم الطوارئ',approveSurcharge:'وافق على الرسوم وأنشئ الطلب',unavailable:'الخدمة دي لسه مش مفعّلة على البيئة الحالية.',minutes:'دقيقة',days:'يوم',requestUpdated:'الطلب اتحدّث',editClarification:'وضّح الطلب',saveClarification:'احفظ التوضيح',back:'رجوع',loading:'جاري التحميل…',error:'حصلت مشكلة. حاول تاني.',cashOrOnline:'كاش / أونلاين',quoteHistory:'سجل تعديلات العرض'}
} as const;

export type MarketplaceCopyKey=keyof typeof copy.en;
export function useMarketplaceText(){const{language}=useLocalization();return(key:MarketplaceCopyKey)=>copy[language][key]}

