import { useLocalization } from '@/src/i18n/localization';
import {
  isMarketplaceRequestStatus,
  marketplaceRequestStatusText,
} from '@/src/lifecycle/lifecycle-presentation';
import type { MarketplaceRequestStatus } from './marketplace-types';

export { requestWorkLabel } from './request-work-label';

const copy={
  en:{
    requestQuote:'Request a Quote',getQuotes:'Get Quotes',quotes:'Quotes',newRequest:'New work request',describe:'Describe what you need',descriptionPlaceholder:'Tell workers what needs to be fixed or done',schedule:'When do you need it?',asap:'ASAP',today:'Today',scheduled:'Scheduled',flexible:'Flexible',payment:'Payment preference',either:'Cash or online',cash:'Cash',online:'Online',sendRequest:'Send request',requestSent:'Request sent',matching:'Finding eligible workers',collecting_quotes:'Collecting quotes',customer_reviewing:'Compare your quotes',selection_pending_confirmation:'Waiting for worker confirmation',worker_confirmed:'Worker confirmed',converted_to_booking:'Booking created',rescue_matching:'Finding a replacement',cancelled:'Request cancelled',expired:'Request expired',closed:'Closed',best_value:'Best Value',lowest_price:'Lowest Price',highest_rated:'Highest Rated',closest:'Closest',fastest_arrival:'Fastest Arrival',most_experienced:'Most Experienced',selectQuote:'Select quote',selectionWindow:'Quote selection opens after the two-minute collection window.',price:'Price',arrival:'Arrival',duration:'Duration',laborIncluded:'Labor included',materials:'Materials',warranty:'Warranty',noQuotes:'No quotes yet. Matching continues while the request is active.',closedNoQuotes:'No quotes were received before this request closed.',cancelRequest:'Cancel request',retry:'Retry now',workerQuotes:'Quote invitations',activeInvitations:'Active invitations',invitationHistory:'Invitation history',noInvitations:'No quote invitations right now.',sendQuote:'Send quote',reviseQuote:'Revise quote',confirmSelection:'Confirm selected quote',decline:'Decline',emergencyAccept:'Accept emergency request',emergencySurcharge:'Emergency surcharge',approveSurcharge:'Approve surcharge and create request',unavailable:'Marketplace Intelligence is not activated on this environment.',minutes:'min',days:'days',requestUpdated:'Request updated',editClarification:'Clarify request',saveClarification:'Save clarification',back:'Back',loading:'Loading…',error:'Something went wrong. Try again.',cashOrOnline:'Cash / online',quoteHistory:'Quote history'},
  ar:{
    requestQuote:'اطلب عرض سعر',getQuotes:'هات عروض أسعار',quotes:'عروض الأسعار',newRequest:'طلب شغل جديد',describe:'اوصف الشغل اللي محتاجه',descriptionPlaceholder:'قول للصنايعية إيه اللي محتاج يتصلح أو يتعمل',schedule:'محتاج الخدمة إمتى؟',asap:'في أسرع وقت',today:'النهارده',scheduled:'ميعاد محدد',flexible:'ميعاد مرن',payment:'طريقة الدفع المناسبة',either:'كاش أو أونلاين',cash:'كاش',online:'أونلاين',sendRequest:'ابعت الطلب',requestSent:'الطلب اتبعت',matching:'بندور على صنايعية مناسبين',collecting_quotes:'بنجمع عروض أسعار',customer_reviewing:'قارن عروض الأسعار',selection_pending_confirmation:'مستنيين تأكيد الصنايعي',worker_confirmed:'الصنايعي أكد',converted_to_booking:'الحجز اتعمل',rescue_matching:'بندور على بديل',cancelled:'الطلب اتلغى',expired:'وقت الطلب انتهى',closed:'مقفول',best_value:'أفضل قيمة',lowest_price:'أقل سعر',highest_rated:'أعلى تقييم',closest:'الأقرب',fastest_arrival:'أسرع وصول',most_experienced:'الأكثر خبرة',selectQuote:'اختار العرض',selectionWindow:'تقدر تختار بعد فترة التجميع العادلة ومدتها دقيقتين.',price:'السعر',arrival:'الوصول',duration:'المدة',laborIncluded:'المصنعية شاملة',materials:'الخامات',warranty:'الضمان',noQuotes:'لسه مفيش عروض. البحث شغال طول ما الطلب متاح.',closedNoQuotes:'مفيش عروض وصلت قبل ما الطلب يتقفل.',cancelRequest:'إلغاء الطلب',retry:'حاول تاني',workerQuotes:'طلبات عروض الأسعار',activeInvitations:'الدعوات المتاحة',invitationHistory:'سجل الدعوات',noInvitations:'مفيش طلبات عروض أسعار دلوقتي.',sendQuote:'ابعت عرض السعر',reviseQuote:'عدّل عرض السعر',confirmSelection:'أكد العرض المختار',decline:'اعتذر',emergencyAccept:'اقبل طلب الطوارئ',emergencySurcharge:'رسوم الطوارئ',approveSurcharge:'وافق على الرسوم وأنشئ الطلب',unavailable:'الخدمة دي لسه مش مفعّلة على البيئة الحالية.',minutes:'دقيقة',days:'يوم',requestUpdated:'الطلب اتحدّث',editClarification:'وضّح الطلب',saveClarification:'احفظ التوضيح',back:'رجوع',loading:'جاري التحميل…',error:'حصلت مشكلة. حاول تاني.',cashOrOnline:'كاش / أونلاين',quoteHistory:'سجل تعديلات العرض'}
} as const;

type MarketplaceBaseCopyKey=keyof typeof copy.en;
export type MarketplaceCopyKey=MarketplaceBaseCopyKey | MarketplaceRequestStatus;
const fr:Record<MarketplaceBaseCopyKey,string>={
  requestQuote:'Demander un devis',getQuotes:'Recevoir des devis',quotes:'Devis',newRequest:'Nouvelle demande',describe:'Décrivez votre besoin',descriptionPlaceholder:'Expliquez ce qui doit être réparé ou réalisé',schedule:'Quand avez-vous besoin du service ?',asap:'Dès que possible',today:'Aujourd’hui',scheduled:'Date précise',flexible:'Date flexible',payment:'Préférence de paiement',either:'Espèces ou en ligne',cash:'Espèces',online:'En ligne',sendRequest:'Envoyer la demande',requestSent:'Demande envoyée',matching:'Recherche de professionnels admissibles',collecting_quotes:'Collecte des devis',customer_reviewing:'Comparez vos devis',selection_pending_confirmation:'En attente de confirmation du professionnel',worker_confirmed:'Professionnel confirmé',converted_to_booking:'Travail créé',rescue_matching:'Recherche d’un remplaçant',cancelled:'Demande annulée',expired:'Demande expirée',closed:'Clôturée',best_value:'Meilleur rapport qualité-prix',lowest_price:'Prix le plus bas',highest_rated:'Mieux noté',closest:'Le plus proche',fastest_arrival:'Arrivée la plus rapide',most_experienced:'Le plus expérimenté',selectQuote:'Choisir ce devis',selectionWindow:'Le choix sera disponible après la période équitable de collecte de deux minutes.',price:'Prix',arrival:'Arrivée',duration:'Durée',laborIncluded:'Main-d’œuvre incluse',materials:'Matériaux',warranty:'Garantie',noQuotes:'Aucun devis pour le moment. La recherche continue tant que la demande est active.',closedNoQuotes:'Aucun devis n’a été reçu avant la clôture de cette demande.',cancelRequest:'Annuler la demande',retry:'Réessayer',workerQuotes:'Invitations à proposer un devis',activeInvitations:'Invitations actives',invitationHistory:'Historique des invitations',noInvitations:'Aucune invitation pour le moment.',sendQuote:'Envoyer le devis',reviseQuote:'Modifier le devis',confirmSelection:'Confirmer le devis choisi',decline:'Refuser',emergencyAccept:'Accepter la demande urgente',emergencySurcharge:'Supplément d’urgence',approveSurcharge:'Accepter le supplément et créer la demande',unavailable:'Cette fonctionnalité n’est pas activée dans cet environnement.',minutes:'min',days:'jours',requestUpdated:'Demande mise à jour',editClarification:'Préciser la demande',saveClarification:'Enregistrer la précision',back:'Retour',loading:'Chargement…',error:'Un problème est survenu. Réessayez.',cashOrOnline:'Espèces / en ligne',quoteHistory:'Historique du devis'
};
export function useMarketplaceText(){const{language}=useLocalization();const localized=language==='fr'?fr:copy[language];return(key:MarketplaceCopyKey)=>isMarketplaceRequestStatus(key)?marketplaceRequestStatusText(language,key):(localized as Record<string,string>)[key]}

const invitationStatuses = {
  en: { invited: 'New invitation', viewed: 'Viewed', quoted: 'Quote sent', declined: 'Declined', withdrawn: 'Withdrawn', expired: 'Expired', request_closed: 'Request closed', worker_ineligible: 'Not eligible', accepted: 'Accepted' },
  ar: { invited: 'دعوة جديدة', viewed: 'تمت المشاهدة', quoted: 'تم إرسال العرض', declined: 'تم الاعتذار', withdrawn: 'تم السحب', expired: 'انتهت الصلاحية', request_closed: 'الطلب اتقفل', worker_ineligible: 'غير مؤهل', accepted: 'تم القبول' },
  fr: { invited: 'Nouvelle invitation', viewed: 'Consultée', quoted: 'Devis envoyé', declined: 'Refusée', withdrawn: 'Retirée', expired: 'Expirée', request_closed: 'Demande clôturée', worker_ineligible: 'Non admissible', accepted: 'Acceptée' },
} as const;
const schedules = { en: { asap: 'As soon as possible', today: 'Today', scheduled: 'Scheduled', flexible: 'Flexible' }, ar: { asap: 'في أسرع وقت', today: 'النهارده', scheduled: 'ميعاد محدد', flexible: 'ميعاد مرن' }, fr: { asap: 'Dès que possible', today: 'Aujourd’hui', scheduled: 'Planifié', flexible: 'Flexible' } } as const;
const paymentMethods = { en: { cash: 'Cash', online: 'Online', either: 'Cash or online' }, ar: { cash: 'كاش', online: 'أونلاين', either: 'كاش أو أونلاين' }, fr: { cash: 'Espèces', online: 'En ligne', either: 'Espèces ou en ligne' } } as const;
export function invitationStatusText(language:keyof typeof invitationStatuses,status:keyof typeof invitationStatuses.en){return invitationStatuses[language][status]}
export function marketplaceScheduleText(language:keyof typeof schedules,value:keyof typeof schedules.en){return schedules[language][value]}
export function marketplacePaymentText(language:keyof typeof paymentMethods,value:keyof typeof paymentMethods.en){return paymentMethods[language][value]}
