import Storage from 'expo-sqlite/kv-store';
import { providers } from '@/src/data/mock-data';
import { createMockNotification } from '@/src/notifications/notification-repository';
import type { MarketplaceCapabilities,MarketplaceIntelligenceRepository,MarketplaceRequest,MarketplaceRequestInput,QuoteInvitation,WorkerQuote } from './marketplace-types';
import { sortMarketplaceQuotes } from './marketplace-types';

type State={requests:MarketplaceRequest[];quotes:WorkerQuote[];invitations:QuoteInvitation[];keys:Record<string,string>};
const KEY='warsha:marketplace-intelligence:v1:mock-customer';
const capabilities:MarketplaceCapabilities={enabled:true,flows:['browse_worker','get_quotes','emergency'],quoteRevisionsEnabled:true,requestLifetimeSeconds:600,initialCollectionSeconds:120,editWindowSeconds:300,workerNoShowSeconds:900,usefulQuoteTarget:5,currency:'EGP',warrantyCategories:[]};
const empty=():State=>({requests:[],quotes:[],invitations:[],keys:{}});
async function read(){const raw=await Storage.getItem(KEY);let state:State;try{state=raw?JSON.parse(raw) as State:empty()}catch{state=empty()}const now=Date.now();let changed=false;state.requests=state.requests.map(request=>{if(!['cancelled','expired','converted_to_booking','closed'].includes(request.status)&&Date.parse(request.expiresAt)<=now){changed=true;return{...request,status:'expired',updatedAt:new Date(now).toISOString(),recoveryActions:['retry','expand','schedule','browse_workers']}}return request});if(changed)await write(state);return state}
async function write(state:State){await Storage.setItem(KEY,JSON.stringify(state))}
function id(prefix:string){return`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`}
function generateQuotes(request:MarketplaceRequest,input:MarketplaceRequestInput){const matches=providers.filter(provider=>provider.verified&&provider.available&&provider.categoryId===input.categoryId&&(input.targetedProviderId?provider.id===input.targetedProviderId:true)).slice(0,input.targetedProviderId?1:5);return matches.map((provider,index):WorkerQuote=>({id:id('QUOTE'),requestId:request.id,providerId:provider.id,workerName:provider.name,workerRating:provider.rating,workerReviewCount:provider.reviewCount,completedJobs:provider.completedJobs,status:'submitted',revision:1,priceMinor:Math.max(10000,Math.round((provider.price+index*35)*100)),currency:'EGP',etaMinutes:20+index*12,estimatedDurationMinutes:90+index*15,message:index?'I can handle this job and will confirm the scope on arrival.':'I am nearby and ready to help.',laborIncluded:true,materialsInclusion:'excluded',materialsExplanation:'Materials are agreed separately if needed.',supportedPaymentMethods:['cash','online'],submittedAt:new Date().toISOString()}))}

export const mockMarketplaceRepository:MarketplaceIntelligenceRepository={
  async capabilities(){return capabilities},
  async previewEmergency(input){return{approvalToken:`mock-approval-${input.categoryId}-${Date.now()}`,approvalVersion:1,surchargeMinor:25000,currency:'EGP',expiresAt:new Date(Date.now()+300000).toISOString()}},
  async createRequest(input,key){const state=await read();if(state.keys[key])return state.keys[key];const now=Date.now();const request:MarketplaceRequest={id:id('REQ'),flowKind:input.flowKind,status:input.flowKind==='emergency'?'matching':'collecting_quotes',categoryId:input.categoryId,serviceId:input.serviceId,targetedProviderId:input.targetedProviderId,issueDescription:input.issueDescription,notes:input.notes??'',scheduleKind:input.scheduleKind,requestedStartAt:input.requestedStartAt,requestedEndAt:input.requestedEndAt,paymentCompatibility:input.paymentCompatibility,area:{governorate:'Cairo',district:'Mock area'},revision:1,selectionVersion:0,editDeadlineAt:new Date(now+300000).toISOString(),collectionNotBefore:new Date(now+120000).toISOString(),expiresAt:new Date(now+600000).toISOString(),quoteCount:0,recoveryActions:[],createdAt:new Date(now).toISOString(),updatedAt:new Date(now).toISOString()};state.requests.unshift(request);const generated=input.flowKind==='emergency'?[]:generateQuotes(request,input);state.quotes.push(...generated);request.quoteCount=generated.length;const inviteProviders=input.flowKind==='emergency'?providers.filter(p=>p.verified&&p.available&&p.emergencyAvailable&&p.categoryId===input.categoryId).slice(0,3):providers.filter(p=>generated.some(q=>q.providerId===p.id));const invitations=inviteProviders.map((provider,index)=>({id:id('INV'),requestId:request.id,status:input.flowKind==='emergency'?'invited':'quoted',flowKind:input.flowKind,categoryId:input.categoryId,serviceId:input.serviceId,issueDescription:input.issueDescription,scheduleKind:input.scheduleKind,requestedStartAt:input.requestedStartAt,requestedEndAt:input.requestedEndAt,area:request.area,paymentCompatibility:input.paymentCompatibility,expiresAt:request.expiresAt,invitedAt:new Date(now+index).toISOString(),quoteId:generated.find(q=>q.providerId===provider.id)?.id} as QuoteInvitation));state.invitations.push(...invitations);state.keys[key]=request.id;await write(state);if(generated.length){for(const quote of generated)await createMockNotification('quote_received',undefined,undefined,`quote-received:${quote.id}`,'mock-customer',request.id)}else if(input.flowKind!=='emergency')await createMockNotification('marketplace_no_providers',undefined,undefined,`no-providers:${request.id}`,'mock-customer',request.id);if(invitations[0])await createMockNotification(input.flowKind==='emergency'?'emergency_request':'quote_invitation',undefined,undefined,`invitation:${invitations[0].id}`,'mock-user',invitations[0].id);return request.id},
  async getRequest(requestId){const state=await read();return state.requests.find(r=>r.id===requestId)},
  async getQuotes(requestId,sort){const state=await read();return sortMarketplaceQuotes(state.quotes.filter(q=>q.requestId===requestId&&['submitted','revised','selected'].includes(q.status)),sort)},
  async editRequest(requestId,revision,patch,key){const state=await read();if(state.keys[key])return state.keys[key];const request=state.requests.find(r=>r.id===requestId);if(!request||request.revision!==revision||request.selectedQuoteId||Date.parse(request.editDeadlineAt)<=Date.now())throw new Error('Request can no longer be edited');const allowed=['descriptionClarification','notes','requestedStartAt','requestedEndAt','addressClarification','attachmentIds'];const major=Object.keys(patch).some(item=>!allowed.includes(item));if(major){request.status='cancelled';const input:MarketplaceRequestInput={flowKind:request.flowKind==='browse_worker'?'browse_worker':'get_quotes',categoryId:String(patch.categoryId??request.categoryId),serviceId:String(patch.serviceId??request.serviceId??'')||undefined,targetedProviderId:request.targetedProviderId,addressId:String(patch.addressId??'home-zamalek'),issueDescription:String(patch.issueDescription??request.issueDescription),notes:String(patch.notes??request.notes),scheduleKind:(patch.scheduleKind??request.scheduleKind) as MarketplaceRequestInput['scheduleKind'],requestedStartAt:String(patch.requestedStartAt??request.requestedStartAt??'')||undefined,requestedEndAt:String(patch.requestedEndAt??request.requestedEndAt??'')||undefined,paymentCompatibility:request.paymentCompatibility};await write(state);return this.createRequest(input,`${key}:replacement`)}request.revision+=1;request.issueDescription=String(patch.descriptionClarification??request.issueDescription);request.notes=String(patch.notes??request.notes);request.requestedStartAt=String(patch.requestedStartAt??request.requestedStartAt??'')||undefined;request.requestedEndAt=String(patch.requestedEndAt??request.requestedEndAt??'')||undefined;request.updatedAt=new Date().toISOString();state.keys[key]=requestId;await write(state);return requestId},
  async cancelRequest(requestId,_reason,key){const state=await read();const request=state.requests.find(r=>r.id===requestId);if(request&&!state.keys[key]){request.status='cancelled';request.updatedAt=new Date().toISOString();state.invitations.filter(i=>i.requestId===requestId).forEach(i=>i.status='request_closed');state.keys[key]=requestId;await write(state);await createMockNotification('request_cancelled',undefined,undefined,`request-cancelled:${requestId}`,'mock-user',requestId)}},
  async selectQuote(requestId,quoteId,version,key){const state=await read();const request=state.requests.find(r=>r.id===requestId);const quote=state.quotes.find(q=>q.id===quoteId&&q.requestId===requestId);if(!request||!quote||request.selectionVersion!==version||Date.now()<Date.parse(request.collectionNotBefore))throw new Error('Quote cannot be selected yet');request.status='selection_pending_confirmation';request.selectedQuoteId=quoteId;request.selectionVersion+=1;request.confirmationDeadlineAt=new Date(Date.now()+120000).toISOString();quote.status='selected';state.keys[key]=quoteId;await write(state);const invitation=state.invitations.find(item=>item.quoteId===quoteId);await createMockNotification('quote_selected',undefined,undefined,`quote-selected:${quoteId}`,'mock-user',invitation?.id??requestId);return quoteId},
  async retryRequest(requestId,_strategy,key){const state=await read();const request=state.requests.find(r=>r.id===requestId);if(!request||request.status!=='expired')throw new Error('Retry unavailable');return this.createRequest({flowKind:request.flowKind==='browse_worker'?'browse_worker':'get_quotes',categoryId:request.categoryId,serviceId:request.serviceId,targetedProviderId:request.targetedProviderId,addressId:'home-zamalek',issueDescription:request.issueDescription,notes:request.notes,scheduleKind:request.scheduleKind,requestedStartAt:request.requestedStartAt,requestedEndAt:request.requestedEndAt,paymentCompatibility:request.paymentCompatibility},`${key}:retry`)},
  async listInvitations(cursor,limit=20){const state=await read();return state.invitations.filter(i=>!cursor||Date.parse(i.invitedAt)<Date.parse(cursor)).sort((a,b)=>Date.parse(b.invitedAt)-Date.parse(a.invitedAt)).slice(0,limit)},
  async viewInvitation(invitationId){const state=await read();const invitation=state.invitations.find(i=>i.id===invitationId);if(invitation?.status==='invited')invitation.status='viewed';await write(state)},
  async submitQuote(invitationId,terms,key){const state=await read();if(state.keys[key])return state.keys[key];const invitation=state.invitations.find(i=>i.id===invitationId);if(!invitation||!['invited','viewed'].includes(invitation.status))throw new Error('Invitation unavailable');const quoteId=id('QUOTE');state.quotes.push({...terms,id:quoteId,requestId:invitation.requestId,providerId:'mock-worker',workerName:'You',workerRating:4.8,workerReviewCount:24,completedJobs:63,status:'submitted',revision:1,currency:'EGP',submittedAt:new Date().toISOString()});invitation.status='quoted';invitation.quoteId=quoteId;state.keys[key]=quoteId;await write(state);await createMockNotification('quote_received',undefined,undefined,`quote-received:${quoteId}`,'mock-customer',invitation.requestId);return quoteId},
  async reviseQuote(quoteId,terms,key){const state=await read();const quote=state.quotes.find(q=>q.id===quoteId);if(!quote||!['submitted','revised'].includes(quote.status))throw new Error('Quote unavailable');Object.assign(quote,terms,{status:'revised',revision:quote.revision+1});state.keys[key]=String(quote.revision);await write(state);return quote.revision},
  async declineInvitation(invitationId,_reason,key){const state=await read();const invitation=state.invitations.find(i=>i.id===invitationId);if(invitation)invitation.status='declined';state.keys[key]=invitationId;await write(state)},
  async withdrawQuote(quoteId,_reason,key){const state=await read();const quote=state.quotes.find(q=>q.id===quoteId);if(quote)quote.status='withdrawn';state.keys[key]=quoteId;await write(state)},
  async confirmQuote(requestId,quoteId,key){const state=await read();const request=state.requests.find(r=>r.id===requestId);const quote=state.quotes.find(q=>q.id===quoteId);if(!request||!quote||request.selectedQuoteId!==quoteId)throw new Error('Selection unavailable');request.status='converted_to_booking';request.convertedBookingId=id('BOOKING');state.keys[key]=request.convertedBookingId;const invitation=state.invitations.find(item=>item.quoteId===quoteId);await write(state);await createMockNotification('marketplace_booking_confirmed',request.convertedBookingId,undefined,`booking-confirmed:${requestId}`,'mock-customer',request.convertedBookingId,invitation?.id);return request.convertedBookingId},
  async acceptEmergency(invitationId,key){const state=await read();const invitation=state.invitations.find(i=>i.id===invitationId);const request=state.requests.find(r=>r.id===invitation?.requestId);if(!invitation||!request||request.status!=='matching')throw new Error('Emergency request unavailable');request.status='converted_to_booking';request.convertedBookingId=id('BOOKING');invitation.status='accepted';state.invitations.filter(i=>i.requestId===request.id&&i.id!==invitationId).forEach(i=>i.status='request_closed');state.keys[key]=request.convertedBookingId;await write(state);return request.convertedBookingId},
  async getWorkerQuote(quoteId){const state=await read();const quote=state.quotes.find(q=>q.id===quoteId);return quote?{...quote,revisions:[{revision:quote.revision,terms:quote,reason:quote.revision>1?'Updated terms':'Initial quote',createdAt:quote.submittedAt}]}:undefined},
  async reportRunningLate(_bookingId,delayMinutes){return new Date(Date.now()+delayMinutes*60000).toISOString()},
  async reportWorkerNoShow(){return id('NO-SHOW')},
  async reportCustomerNoShow(){return id('NO-SHOW')},
  async createComeback(){throw new Error('Warranty configuration is disabled in Mock mode')},
};
