#!/usr/bin/env node
/**
 * Live synthetic OCR verification against hosted Development.
 *
 * This is the only test in Warsha that actually spends money at an OCR
 * provider, so it is written to spend as little as possible and to say exactly
 * how much it spent. Every image it sends is a synthetic card generated by
 * `scripts/generate-synthetic-id-cards.ps1`: invented numbers, no government
 * layout, and the words SYNTHETIC TEST CARD printed on the face. No real
 * worker's document is touched, and the harness has no code path that could
 * read one — it uploads its own bytes under its own account and asks about
 * those.
 *
 * It behaves exactly as the app does: register a worker through `worker-auth`,
 * sign in, upload to `verification-documents` under the account's own path,
 * register the document, then call `vision-extract` with the worker's own JWT.
 * Nothing here holds a service role, and nothing here is privileged. That is
 * deliberate — a harness that used elevated access would prove the provider
 * works for somebody nobody is.
 *
 * The five cases, and what each is actually asking:
 *
 *   A  Arabic card          Can Arabic and a 14-digit number be read at all?
 *   B  Mixed card           Does a bilingual card still yield useful fields?
 *   C  Unreadable card      Does failure stay a failure to READ, never a failed
 *                           verification, with manual entry still open?
 *   D  Repeat of A          Does the same bytes twice cost one call, not two?
 *   E  Second worker        Can anybody reach a document that is not theirs?
 */

import { createHash, randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

// The exact manifest the app sends. Building one by hand here would test a
// registration nobody performs, and Postgres compares it against its own
// published register anyway.
import { signupLegalManifest } from '../src/legal/signup-legal.ts';

const PROJECT = 'lrhipbcapzfxuwixfoog';
const BASE = `https://${PROJECT}.supabase.co`;

const ANON = process.env.SYNTHETIC_OCR_ANON_KEY
  ?? readFileSync('.env', 'utf8').split('\n')
    .find((l) => l.startsWith('EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY='))
    ?.split('=')[1]?.trim();
if (!ANON) throw new Error('No publishable key available.');

const CARDS = process.env.SYNTHETIC_ID_DIR ?? 'artifacts/synthetic-id';

type ApiResult = { status: number; ok: boolean; body: any };
type ApiOptions = {
  method?: string;
  token?: string;
  body?: unknown;
  headers?: Record<string, string>;
};
type Worker = {
  label: string; phone: string; token: string; userId: string; providerId: string;
};
type DocumentType = 'national_id_front' | 'national_id_back';

let paidCalls = 0;
const results: Record<string, unknown>[] = [];
const record = (name: string, detail: Record<string, unknown>) => {
  results.push({ name, ...detail });
  console.log(`\n--- ${name} ---`);
  console.log(JSON.stringify(detail, null, 2));
};

/** A Warsha worker phone that is unmistakably a test number. */
const testPhone = () =>
  `+2010${String(Math.floor(Math.random() * 90000000) + 10000000)}`;

async function api(
  path: string,
  { method = 'POST', token, body, headers = {} }: ApiOptions = {},
): Promise<ApiResult> {
  const response = await fetch(`${BASE}${path}`, {
    method,
    headers: {
      apikey: ANON,
      authorization: `Bearer ${token ?? ANON}`,
      'content-type': 'application/json',
      ...headers,
    },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown;
  try { parsed = text ? JSON.parse(text) : null; } catch { parsed = text; }
  return { status: response.status, ok: response.ok, body: parsed };
}

/**
 * Register and sign in a synthetic worker, exactly as the app does.
 *
 * `worker-auth` owns worker registration because a worker signs in by phone.
 * Going around it — creating an auth user directly — would test a path no
 * worker uses.
 */
async function makeWorker(label: string): Promise<Worker> {
  const phone = testPhone();
  const password = `Synthetic-${randomUUID().slice(0, 12)}!aA1`;
  const registered = await api('/functions/v1/worker-auth', {
    body: {
      action: 'register',
      phone,
      password,
      fullName: `Synthetic OCR ${label}`,
      language: 'en',
      legalAcceptances: signupLegalManifest('worker', 'en'),
    },
  });
  if (!registered.ok) {
    throw new Error(`Could not register ${label}: ${JSON.stringify(registered.body)}`);
  }
  const signedIn = await api('/functions/v1/worker-auth', {
    body: { action: 'sign_in', phone, password },
  });
  if (!signedIn.ok) {
    throw new Error(`Could not sign in ${label}: ${JSON.stringify(signedIn.body)}`);
  }
  const session = signedIn.body?.session ?? signedIn.body;
  const token = session?.access_token ?? session?.accessToken;
  if (!token) throw new Error(`No access token for ${label}: ${JSON.stringify(signedIn.body)}`);
  const user = await api('/auth/v1/user', { method: 'GET', token });
  // The storage policy checks the SECOND path segment against
  // `private.owns_provider`, so the real provider profile id is part of a valid
  // path. Reading it with the worker's own token, as the app does.
  const profile = await api(
    `/rest/v1/provider_profiles?select=id&user_id=eq.${user.body?.id}`,
    { method: 'GET', token });
  const providerId = Array.isArray(profile.body) ? profile.body[0]?.id : null;
  if (!providerId) {
    throw new Error(`No provider profile for ${label}: ${JSON.stringify(profile.body)}`);
  }
  return { label, phone, token, userId: user.body?.id, providerId };
}

async function uploadCard(worker: Worker, file: string, documentType: DocumentType) {
  const bytes = readFileSync(join(CARDS, file));
  const path = `${worker.userId}/${worker.providerId}/${documentType}/${Date.now()}-${randomUUID().slice(0, 8)}.png`;
  const upload = await fetch(`${BASE}/storage/v1/object/verification-documents/${path}`, {
    method: 'POST',
    headers: {
      apikey: ANON,
      authorization: `Bearer ${worker.token}`,
      'content-type': 'image/png',
    },
    body: bytes,
  });
  if (!upload.ok) {
    throw new Error(`Upload failed: ${upload.status} ${await upload.text()}`);
  }
  const registered = await api('/rest/v1/rpc/register_provider_verification_document', {
    token: worker.token,
    body: {
      p_document_type: documentType,
      p_storage_path: path,
      p_mime_type: 'image/png',
      p_file_size_bytes: bytes.byteLength,
    },
  });
  return {
    path,
    registered: registered.ok,
    registerError: registered.ok ? null : registered.body,
    sha256: createHash('sha256').update(bytes).digest('hex').slice(0, 16),
  };
}

async function extract(worker: Worker, storagePath: string, documentType: DocumentType) {
  const started = Date.now();
  const response = await api('/functions/v1/vision-extract', {
    token: worker.token,
    body: { storagePath, documentType },
  });
  return { ...response, latencyMs: Date.now() - started };
}

const main = async () => {
  console.log('Synthetic OCR verification against hosted Development.');
  console.log('Every image is a generated test card. No real document is used.\n');

  const workerA = await makeWorker('A');
  console.log(`worker A: ${workerA.userId}`);

  // The capability probe first: it is free, it makes no provider call, and if
  // the credential or the flag is not right there is no reason to spend money
  // finding that out.
  const capability = await api('/functions/v1/vision-extract', {
    token: workerA.token,
    body: { operation: 'capability' },
  });
  record('capability probe (no provider call, not billed)', capability.body);
  if (capability.body?.enabled !== true) {
    console.error('\nExtraction is not enabled for this environment. Stopping before any paid call.');
    process.exit(1);
  }
  const seed = await uploadCard(workerA, 'arabic-national-id.png', 'national_id_front');
  // --- E. Authorization, run before anything paid ----------------------------
  // It needs no successful extraction: a worker reaching another worker's
  // document must be refused whether or not OCR works at all. Running it here
  // means the result survives a credential fault, and a security property is
  // the last thing that should go unmeasured because something else broke.
  const workerB = await makeWorker('B');
  console.log(`\nworker B: ${workerB.userId}`);
  const crossExtract = await extract(workerB, seed.path, 'national_id_front');
  const crossRead = await fetch(
    `${BASE}/storage/v1/object/verification-documents/${seed.path}`,
    { headers: { apikey: ANON, authorization: `Bearer ${workerB.token}` } },
  );
  const crossSign = await api(
    `/storage/v1/object/sign/verification-documents/${seed.path}`,
    { token: workerB.token, body: { expiresIn: 60 } },
  );
  record("E. another worker reaching A's document", {
    extractStatus: crossExtract.status,
    extractResponse: crossExtract.body,
    directReadStatus: crossRead.status,
    signedUrlStatus: crossSign.status,
    signedUrlResponse: crossSign.body,
  });

  console.log('\n============================================================');

  // A credential the provider will not accept cannot produce a reading, so
  // there is nothing to learn from sending it four documents. Stopping here
  // costs nothing and says exactly what is wrong.
  if (capability.body?.credentialUsable === false) {
    console.error('\nThe provider will not accept the configured credential:');
    console.error(JSON.stringify(capability.body.credentialFailure, null, 2));
    console.error('\nNothing was sent to the provider. Fix the credential with:');
    console.error('  npm run automation:govern -- set-vision-credential <service-account.json>');
    process.exit(1);
  }

  // --- A. Arabic -------------------------------------------------------------
  // The card already uploaded for the ownership check. Uploading a second copy
  // would be a second document as far as the throttle is concerned, and would
  // make test D measure the wrong thing.
  const arabic = seed;
  const a = await extract(workerA, arabic.path, 'national_id_front');
  if (a.body?.outcome === 'succeeded' || a.body?.outcome === 'unreadable'
    || a.body?.outcome === 'no_text_found') paidCalls += 1;
  record('A. synthetic Arabic Egyptian ID', {
    upload: arabic, status: a.status, latencyMs: a.latencyMs, response: a.body,
  });

  // --- D. Idempotency: the same bytes again ---------------------------------
  // Uploaded to a NEW path deliberately. The throttle keys on the content hash,
  // so a worker who re-uploads the same photograph must not be billed twice —
  // and a test that reused the path would prove only that a path was cached.
  const repeat = await uploadCard(workerA, 'arabic-national-id.png', 'national_id_front');
  const d = await extract(workerA, repeat.path, 'national_id_front');
  const dWasBilled = d.body?.reusedStoredCandidates !== true
    && d.body?.outcome === 'succeeded'
    && d.body?.fromCache !== true;
  record('D. same document again (idempotency)', {
    sameBytes: repeat.sha256 === arabic.sha256,
    differentPath: repeat.path !== arabic.path,
    status: d.status, latencyMs: d.latencyMs, response: d.body,
    firstLatencyMs: a.latencyMs,
  });

  // --- B. Mixed --------------------------------------------------------------
  const mixed = await uploadCard(workerA, 'mixed-national-id.png', 'national_id_back');
  const b = await extract(workerA, mixed.path, 'national_id_back');
  if (b.body?.outcome === 'succeeded' || b.body?.outcome === 'unreadable'
    || b.body?.outcome === 'no_text_found') paidCalls += 1;
  record('B. synthetic mixed Arabic/English ID', {
    upload: mixed, status: b.status, latencyMs: b.latencyMs, response: b.body,
  });

  // --- C. Unreadable ---------------------------------------------------------
  const unreadable = await uploadCard(workerA, 'unreadable-national-id.png', 'national_id_front');
  const c = await extract(workerA, unreadable.path, 'national_id_front');
  if (c.body?.outcome === 'succeeded' || c.body?.outcome === 'unreadable'
    || c.body?.outcome === 'no_text_found') paidCalls += 1;
  record('C. deliberately unreadable card', {
    upload: unreadable, status: c.status, latencyMs: c.latencyMs, response: c.body,
  });

  console.log(`PAID GOOGLE VISION CALLS THIS RUN: ${paidCalls}`);
  console.log('============================================================');
  return results;
};

main().catch((error) => {
  console.error(`\nHarness failed: ${error.message}`);
  console.log(`\nPAID GOOGLE VISION CALLS BEFORE FAILURE: ${paidCalls}`);
  process.exit(1);
});
