/**
 * Generated from OCHA/HDX Egypt COD-AB v01 (CAPMAS source).
 * Dataset review date: 2024-12-19. Admin 1: 27; Admin 2: 365.
 * Source: https://data.humdata.org/dataset/cod-ab-egy
 * Do not edit by hand; run scripts/generate-egypt-admin-data.ps1.
 */
export const egyptAdministrativeAreas = [
  { id: "EG02", en: "Alexandria", ar: "الاسكندرية", areas: [
    { id: "EG0209", en: "A L Labban", ar: "قسم اللبان" },
    { id: "EG0213", en: "Al Amreia", ar: "قسم العامرية" },
    { id: "EG0206", en: "Al Attarin", ar: "قسم العطارين" },
    { id: "EG0212", en: "Al Dikhila", ar: "قسم الدخيلة" },
    { id: "EG0210", en: "Al Gumruk", ar: "قسم الجمرك" },
    { id: "EG0207", en: "Al Manshiyya", ar: "قسم المنشية" },
    { id: "EG0202", en: "Al Raml", ar: "قسم أول الرمل" },
    { id: "EG0204", en: "Bab Sharqi", ar: "قسم باب شرقى" },
    { id: "EG0214", en: "Burg al-Arab", ar: "قسم برج العرب" },
    { id: "EG0216", en: "Burg Al-Arab City", ar: "مدينه برج العرب الجديده" },
    { id: "EG0208", en: "Karmuz", ar: "قسم كرموز" },
    { id: "EG0217", en: "Kesm than Al Raml", ar: "قسم ثان الرمل" },
    { id: "EG0211", en: "Mina Al-Basal", ar: "قسم مينا البصل" },
    { id: "EG0205", en: "Muharam Bik", ar: "قسم محرم بك" },
    { id: "EG0201", en: "Muntazah", ar: "قسم المنتزة" },
    { id: "EG0218", en: "North Coast", ar: "الساحل الشمالى" },
    { id: "EG0215", en: "Port Alexandria Police Department", ar: "اداره شرطه ميناء الأسكندريه" },
    { id: "EG0203", en: "Sidi Gabir", ar: "قسم سيدى جابر" },
    { id: "EG0200", en: "Zemam Out", ar: "خارج الزمام" },
  ] },
  { id: "EG25", en: "Assiut", ar: "أسيوط", areas: [
    { id: "EG2504", en: "Abnub", ar: "مركز أبنوب" },
    { id: "EG2505", en: "Abu Tig", ar: "مركز أبوتيج" },
    { id: "EG2506", en: "Al- Badari", ar: "مركز البدارى" },
    { id: "EG2513", en: "Alfath", ar: "مركز الفتح" },
    { id: "EG2508", en: "Al-Ghanayem", ar: "مركز الغنايم" },
    { id: "EG2509", en: "Al-Qusia", ar: "مركز القوصية" },
    { id: "EG2503", en: "Assuit", ar: "مركز أسيوط" },
    { id: "EG2514", en: "Assuit City", ar: "مدينة اسيوط الجديدة" },
    { id: "EG2510", en: "Dayrut", ar: "مركز ديروط" },
    { id: "EG2501", en: "Kesm Awal Assuit", ar: "قسم أول أسيوط" },
    { id: "EG2502", en: "Kesm Than Assuit", ar: "قسم ثان أسيوط" },
    { id: "EG2512", en: "Manfalut", ar: "مركز منفلوط" },
    { id: "EG2507", en: "Sahil Silim", ar: "مركز ساحل سليم" },
    { id: "EG2511", en: "Sidfa", ar: "مركز صدفا" },
    { id: "EG2500", en: "Zemam Out", ar: "صحراء أسيوط" },
  ] },
  { id: "EG28", en: "Aswan", ar: "أسوان", areas: [
    { id: "EG2807", en: "Abu Simbel", ar: "مركز أبوسنبل" },
    { id: "EG2803", en: "Adfu", ar: "مركز أدفو" },
    { id: "EG2802", en: "Aswan", ar: "مركز أسوان" },
    { id: "EG2801", en: "Aswan", ar: "قسم أسوان" },
    { id: "EG2808", en: "Aswan City", ar: "مدينة أسوان الجديدة" },
    { id: "EG2806", en: "Daraw", ar: "مركز دراو" },
    { id: "EG2804", en: "Kum Umbu", ar: "مركز كوم امبو" },
    { id: "EG2805", en: "Nasr", ar: "مركز نصر" },
    { id: "EG2809", en: "Tushaka", ar: "مدينة توشكى الجديدة" },
    { id: "EG2800", en: "Zemam Out", ar: "خارج الزمام" },
  ] },
  { id: "EG18", en: "Behera", ar: "البحيرة", areas: [
    { id: "EG1804", en: "Abu Hummus", ar: "مركز ابوحمص" },
    { id: "EG1803", en: "Abu-l-Matamir", ar: "مركز ابوالمطامير" },
    { id: "EG1805", en: "Al-Dilingat", ar: "مركز الدلنجات" },
    { id: "EG1806", en: "Al-Mahmudiyya", ar: "مركز المحمودية" },
    { id: "EG1815", en: "Al-Rahmaniyya", ar: "مركز الرحمانية" },
    { id: "EG1818", en: "Badr", ar: "مركز بدر" },
    { id: "EG1802", en: "Damanhur", ar: "مركز دمنهور" },
    { id: "EG1801", en: "Damanhur", ar: "قسم دمنهور" },
    { id: "EG1808", en: "Hush Isa", ar: "مركز حوش عيسى" },
    { id: "EG1816", en: "Idku", ar: "مركز إدكو" },
    { id: "EG1807", en: "Itay Al-Barud", ar: "مركز إيتاى البارود" },
    { id: "EG1812", en: "Kafr Al-Dawwar", ar: "مركز كفر الدوار" },
    { id: "EG1811", en: "Kafr Al-Dawwar", ar: "قسم كفرالدوار" },
    { id: "EG1813", en: "Kum Hamada", ar: "مركز كوم حمادة" },
    { id: "EG1817", en: "Nubariyya West", ar: "قسم غرب النوبارية" },
    { id: "EG1809", en: "Rashid", ar: "مركز رشيد" },
    { id: "EG1810", en: "Shubra Khit", ar: "مركز شبراخيت" },
    { id: "EG1814", en: "Wadi Al-NatrUn", ar: "مركز وادى النطرون" },
    { id: "EG1800", en: "Zemam Out", ar: "خارج الزمام" },
  ] },
  { id: "EG22", en: "Beni Suef", ar: "بنى سويف", areas: [
    { id: "EG2206", en: "Ahnasya", ar: "مركز أهناسيا" },
    { id: "EG2204", en: "Al Fashn", ar: "مركز الفشن" },
    { id: "EG2205", en: "Al Wasta", ar: "مركز الواسطى" },
    { id: "EG2202", en: "Bani Swayf", ar: "مركز بنى سويف" },
    { id: "EG2201", en: "Bani Swayf", ar: "قسم بنى سويف" },
    { id: "EG2203", en: "Bani Swayf City", ar: "قسم مدينة بنى سويف الجديدة" },
    { id: "EG2207", en: "Biba", ar: "مركز ببا" },
    { id: "EG2209", en: "Nasir", ar: "مركز ناصر" },
    { id: "EG2208", en: "Sumusta", ar: "مركز سمسطا" },
    { id: "EG2200", en: "Zemam Out", ar: "خارج الزمام" },
  ] },
  { id: "EG01", en: "Cairo", ar: "القاهرة", areas: [
    { id: "EG0103", en: "15 Mayu", ar: "قسم 15 مايو" },
    { id: "EG0109", en: "Abdin", ar: "قسم عابدين" },
    { id: "EG0130", en: "Ain Shams", ar: "قسم عينشمس" },
    { id: "EG0113", en: "Al Azbakiyya", ar: "قسم الأزبكية" },
    { id: "EG0114", en: "Al Darb al-Ahmar", ar: "قسم الدرب الأحمر" },
    { id: "EG0108", en: "Al Khalifa", ar: "قسم الخليفة" },
    { id: "EG0125", en: "Al Matariyya", ar: "قسم المطرية" },
    { id: "EG0121", en: "Al Sahil", ar: "قسم الساحل" },
    { id: "EG0132", en: "Al Salam", ar: "قسم السلام" },
    { id: "EG0118", en: "Al Sharabiyya", ar: "قسم الشرابية" },
    { id: "EG0101", en: "Al Tibbin", ar: "قسم التبين" },
    { id: "EG0122", en: "Al Wayli", ar: "قسم الوايلي" },
    { id: "EG0117", en: "Al Zahir", ar: "قسم الظاهر" },
    { id: "EG0124", en: "Al Zaytun", ar: "قسم الزيتون" },
    { id: "EG0116", en: "Bab Al-Shariyya", ar: "قسم باب الشعرية" },
    { id: "EG0141", en: "Badr", ar: "قسم بدر" },
    { id: "EG0135", en: "Basatin", ar: "قسم البساتين" },
    { id: "EG0112", en: "Bulaq", ar: "قسم بولاق" },
    { id: "EG0115", en: "Gamaliyya", ar: "قسم الجمالية" },
    { id: "EG0123", en: "Hadaiq Al-Qubba", ar: "قسم حدائقالقبة" },
    { id: "EG0102", en: "Hilwan", ar: "قسم حلوان" },
    { id: "EG0104", en: "Maadi", ar: "قسم المعادي" },
    { id: "EG0127", en: "Madinat Nasr-2", ar: "قسم ثانمدينةنصر" },
    { id: "EG0136", en: "Marg", ar: "قسم المرج" },
    { id: "EG0134", en: "Minshat Nasir", ar: "منشأةناصر" },
    { id: "EG0128", en: "Misr al-Gadida", ar: "قسم مصرالجديدة" },
    { id: "EG0106", en: "Misr Al-Qadima", ar: "مصرالقديمة" },
    { id: "EG0110", en: "Muski", ar: "قسم الموسكي" },
    { id: "EG0126", en: "Nasr City", ar: "قسم أول مدينة نصر" },
    { id: "EG0137", en: "New Cairo-1", ar: "قسم أول القاهرة الجديدة" },
    { id: "EG0138", en: "New Cairo-2", ar: "قسم ثان القاهرة الجديدة" },
    { id: "EG0139", en: "New Cairo-3", ar: "قسم ثالث القاهرة الجديدة" },
    { id: "EG0129", en: "Nuzha", ar: "قسم النزهة" },
    { id: "EG0111", en: "Qasr Al-Nile", ar: "قسم قصر النيل" },
    { id: "EG0120", en: "Rud Al-Farag", ar: "قسم روضالفرج" },
    { id: "EG0107", en: "Sayyida Zainab", ar: "قسم السيدة زينب" },
    { id: "EG0140", en: "Shroq", ar: "قسم الشروق" },
    { id: "EG0119", en: "Shubra", ar: "قسم شبرا" },
    { id: "EG0105", en: "Tura", ar: "قسم طره" },
    { id: "EG0133", en: "Zamalik", ar: "قسم الزمالك" },
    { id: "EG0131", en: "Zawiyya Al-Hamra", ar: "قسم الزاويةالحمراء" },
    { id: "EG0100", en: "Zemam Out", ar: "خارج الزمام" },
  ] },
  { id: "EG12", en: "Dakahlia", ar: "الدقهلية", areas: [
    { id: "EG1204", en: "Aga", ar: "مركز أجا" },
    { id: "EG1218", en: "Bany Abeed", ar: "مركز بنى عبيد" },
    { id: "EG1208", en: "Bilqas", ar: "مركز بلقاس" },
    { id: "EG1209", en: "Dikirnis", ar: "مركز دكرنس" },
    { id: "EG1202", en: "E Mansora 2", ar: "قسم ثان المنصورة" },
    { id: "EG1203", en: "El Mansora", ar: "مركز المنصورة" },
    { id: "EG1201", en: "El Mansora 1", ar: "قسم اول المنصورة" },
    { id: "EG1215", en: "Gamaliyya", ar: "مركز الجمالية" },
    { id: "EG1220", en: "Gamsa", ar: "قسم جمصة" },
    { id: "EG1219", en: "Mahalet Demna", ar: "مركز محلة دمنة" },
    { id: "EG1207", en: "Manzala", ar: "مركز المنزلة" },
    { id: "EG1206", en: "Matariyya", ar: "مركز المطرية" },
    { id: "EG1214", en: "Minya Al-Nasr", ar: "مركز منية النصر" },
    { id: "EG1213", en: "Mit Ghamr", ar: "مركز ميت غمر" },
    { id: "EG1212", en: "Mit Ghamr", ar: "قسم ميت غمر" },
    { id: "EG1217", en: "MIt Salsil", ar: "مركز ميت سلسيل" },
    { id: "EG1221", en: "Nebro", ar: "مركز نبروة" },
    { id: "EG1210", en: "Shirbin", ar: "مركز شربين" },
    { id: "EG1205", en: "Sinbillawin", ar: "مركز السنبلاوين" },
    { id: "EG1211", en: "Talkha", ar: "مركز طلخا" },
    { id: "EG1216", en: "Tamy Al-Amdid", ar: "مركز تمى الأمديد" },
  ] },
  { id: "EG11", en: "Damietta", ar: "دمياط", areas: [
    { id: "EG1102", en: "Dumyat", ar: "مركز دمياط" },
    { id: "EG1101", en: "Dumyat 1", ar: "قسم أول دمياط" },
    { id: "EG1109", en: "Dumyat 2", ar: "قسم ثان دمياط" },
    { id: "EG1105", en: "Dumyat Al-Gadida", ar: "قسم مدينه دمياط الجديده" },
    { id: "EG1103", en: "Fariskur", ar: "مركز فارسكور" },
    { id: "EG1104", en: "Kafr Sad", ar: "مركز كفر سعد" },
    { id: "EG1108", en: "Police Department Port of Damietta", ar: "إداره شرطه ميناء دمياط الجديد" },
    { id: "EG1106", en: "Ras al-Bar", ar: "قسم رأس البر" },
    { id: "EG1107", en: "Zarqa", ar: "مركز الزرقا" },
  ] },
  { id: "EG23", en: "Fayoum", ar: "الفيوم", areas: [
    { id: "EG2303", en: "Abshaway", ar: "مركز أبشواى" },
    { id: "EG2304", en: "Atsa", ar: "مركز أطسا" },
    { id: "EG2302", en: "Fayyum", ar: "مركز الفيوم" },
    { id: "EG2301", en: "Fayyum", ar: "قسم الفيوم" },
    { id: "EG2308", en: "Fayyum City", ar: "مدينة الفيوم الجديدة" },
    { id: "EG2305", en: "Sinuras", ar: "مركز سنورس" },
    { id: "EG2306", en: "Tamya", ar: "مركز طامية" },
    { id: "EG2307", en: "Yousef El sadeq", ar: "مركز يوسف الصديق" },
    { id: "EG2300", en: "Zemam Out", ar: "خارج الزمام" },
  ] },
  { id: "EG16", en: "Gharbia", ar: "الغربية", areas: [
    { id: "EG1608", en: "Basyun", ar: "مركز بسيون" },
    { id: "EG1607", en: "El Mahalla El Kobra", ar: "مركز المحله الكبرى" },
    { id: "EG1605", en: "El Mahalla El Kobra 1", ar: "قسم أول المحلة الكبرى" },
    { id: "EG1606", en: "El Mahalla El Kobra 2", ar: "قسم ثان المحلة الكبرى" },
    { id: "EG1612", en: "Kafr Al-Zayyat", ar: "مركز كفر الزيات" },
    { id: "EG1611", en: "Qutur", ar: "مركز قطور" },
    { id: "EG1610", en: "Samannud", ar: "مركز سمنود" },
    { id: "EG1604", en: "Santa", ar: "مركز السنطة" },
    { id: "EG1603", en: "Tanta", ar: "مركز طنطا" },
    { id: "EG1601", en: "Tanta 1", ar: "قسم أول طنطا" },
    { id: "EG1602", en: "Tanta 2", ar: "قسم ثان طنطا" },
    { id: "EG1609", en: "Zifta", ar: "مركز زفتى" },
  ] },
  { id: "EG21", en: "Giza", ar: "الجيزة", areas: [
    { id: "EG2107", en: "6 October-1", ar: "قسم أول 6 أكتوبر" },
    { id: "EG2121", en: "6 October-2", ar: "قسم ثان 6 أكتوبر" },
    { id: "EG2102", en: "Al-Aguza", ar: "قسم العجوزة" },
    { id: "EG2106", en: "Al-Ahram", ar: "قسم الأهرام" },
    { id: "EG2115", en: "Atfeh", ar: "مركز أطفيح" },
    { id: "EG2116", en: "Auseem", ar: "مركز أوسيم" },
    { id: "EG2112", en: "Ayat", ar: "مركز العياط" },
    { id: "EG2110", en: "Badrashain", ar: "مركز البدرشين" },
    { id: "EG2114", en: "Bahariya Oasis", ar: "قسم الواحاتالبحرية" },
    { id: "EG2105", en: "Bulaq Al-DakrUr", ar: "قسم بولاق الدكرور" },
    { id: "EG2103", en: "DuqqI", ar: "قسم الدقي" },
    { id: "EG2109", en: "Giza", ar: "مركز الجيزة" },
    { id: "EG2104", en: "Giza", ar: "قسم الجيزة" },
    { id: "EG2108", en: "Hwamdeia", ar: "قسم الحوامدية" },
    { id: "EG2113", en: "Imbaba", ar: "مركز إمبابة" },
    { id: "EG2101", en: "Imbaba", ar: "قسم امبابه" },
    { id: "EG2120", en: "Kardasa", ar: "مركز كرداسة" },
    { id: "EG2111", en: "Saf", ar: "مركز الصف" },
    { id: "EG2119", en: "Shaykh Zayed", ar: "قسم الشيخ زايد" },
    { id: "EG2118", en: "Umraniyya", ar: "قسم العمرانية" },
    { id: "EG2117", en: "Waraq", ar: "قسم الوراق" },
    { id: "EG2100", en: "Zemam Out", ar: "خارج الزمام" },
  ] },
  { id: "EG19", en: "Ismailia", ar: "الإسماعيلية", areas: [
    { id: "EG1907", en: "Fayid", ar: "مركز فايد" },
    { id: "EG1904", en: "Ismailiyya", ar: "مركز الاسماعيلية" },
    { id: "EG1901", en: "Ismailiyya 1", ar: "قسم أول الاسماعيلية" },
    { id: "EG1902", en: "Ismailiyya 2", ar: "قسم ثان الاسماعيلية" },
    { id: "EG1903", en: "Ismailiyya 3", ar: "قسم ثالث الاسماعيلية" },
    { id: "EG1906", en: "Qantara Gharb, al-", ar: "مركز القنطرة" },
    { id: "EG1908", en: "Qantara Sharq, al-", ar: "قسم القنطرة شرق" },
    { id: "EG1905", en: "Tal al-Kabir, al-", ar: "مركز التل الكبير" },
  ] },
  { id: "EG15", en: "Kafr El-Shikh", ar: "كفر الشيخ", areas: [
    { id: "EG1511", en: "Al Hamul", ar: "مركز الحامول" },
    { id: "EG1504", en: "Biyalu", ar: "مركز بيلا" },
    { id: "EG1503", en: "Burullus", ar: "مركز البرلس" },
    { id: "EG1506", en: "Disuq", ar: "مركز دسوق" },
    { id: "EG1505", en: "Disuq", ar: "قسم دسوق" },
    { id: "EG1508", en: "Fuwwa", ar: "مركز فوه" },
    { id: "EG1502", en: "Kafr Al-Shaykh", ar: "مركز كفر الشيخ" },
    { id: "EG1501", en: "Kafr Al-Shaykh", ar: "قسم كفر الشيخ" },
    { id: "EG1510", en: "Mitubas", ar: "مركز مطوبس" },
    { id: "EG1509", en: "Qillin", ar: "مركز قلين" },
    { id: "EG1512", en: "Riyad", ar: "مركز الرياض" },
    { id: "EG1507", en: "Sidi Salim", ar: "مركز سيدى سالم" },
  ] },
  { id: "EG14", en: "Kalyoubia", ar: "القليوبية", areas: [
    { id: "EG1413", en: "Abour", ar: "قسم العبور" },
    { id: "EG1403", en: "Al Khanka", ar: "مركز الخانكة" },
    { id: "EG1402", en: "Banha", ar: "مركز بنها" },
    { id: "EG1401", en: "Banha", ar: "قسم بنها" },
    { id: "EG1411", en: "Kafr Shukr", ar: "مركز كفر شكر" },
    { id: "EG1412", en: "Khsos", ar: "قسم الخصوص" },
    { id: "EG1414", en: "Qaha", ar: "قسم قها" },
    { id: "EG1410", en: "Qalyub", ar: "مركز قليوب" },
    { id: "EG1409", en: "Qalyub", ar: "قسم قليوب" },
    { id: "EG1404", en: "Qanatir Al-Khayriyya", ar: "مركز القناطر الخيرية" },
    { id: "EG1405", en: "Shibin al-Qanatir", ar: "مركز شبين القناطر" },
    { id: "EG1406", en: "Shubra Al-Khayma 1", ar: "قسم أول شبرا الخيمة" },
    { id: "EG1407", en: "Shubra Al-Khayma 2", ar: "قسم ثان شبرا الخيمة" },
    { id: "EG1408", en: "Tukh", ar: "مركز طوخ" },
    { id: "EG1400", en: "Zemam Out", ar: "خارج الزمام" },
  ] },
  { id: "EG29", en: "Luxor", ar: "مدينة الأقصر", areas: [
    { id: "EG2902", en: "Luxor", ar: "مركز الأقصر" },
    { id: "EG2901", en: "Luxor", ar: "قسم الأقصر" },
    { id: "EG2903", en: "Tiba police station", ar: "مركز شرطة طيبة" },
    { id: "EG2900", en: "Zemam Out", ar: "خارج الزمام" },
  ] },
  { id: "EG33", en: "Matrouh", ar: "مطروح", areas: [
    { id: "EG3307", en: "Alamn", ar: "قسم مارينا العلمين السياحية" },
    { id: "EG3302", en: "Al-Hammam", ar: "قسم الحمام" },
    { id: "EG3304", en: "Daba", ar: "مركز الضبعة" },
    { id: "EG3301", en: "Marsa Matruh", ar: "قسم مرسى مطروح" },
    { id: "EG3308", en: "North Coast", ar: "قسم الساحل الشمالى-جزء" },
    { id: "EG3303", en: "Salloum", ar: "قسم السلوم" },
    { id: "EG3305", en: "Sidi Barani", ar: "قسم سيدى برانى" },
    { id: "EG3306", en: "Siwa", ar: "مركز سيوة" },
  ] },
  { id: "EG24", en: "Menia", ar: "المنيا", areas: [
    { id: "EG2401", en: "Kesm Al-minya", ar: "قسم المنيا" },
    { id: "EG2411", en: "Kesm Mallawi", ar: "قسم ملوى" },
    { id: "EG2404", en: "Markz Abu Qurqas", ar: "مركز ابو قرقاص" },
    { id: "EG2405", en: "Markz Al Idwa", ar: "مركز العدوة" },
    { id: "EG2402", en: "Markz Al Minya", ar: "مركز المنيا" },
    { id: "EG2406", en: "Markz Bani Mazar", ar: "مركز بنى مزار" },
    { id: "EG2407", en: "Markz Dir Mawas", ar: "مركز دير مواس" },
    { id: "EG2410", en: "Markz Maghagha", ar: "مركز مغاغة" },
    { id: "EG2412", en: "Markz Mallawi", ar: "مركز ملوى" },
    { id: "EG2409", en: "Markz Matay", ar: "مركز مطاى" },
    { id: "EG2408", en: "Markz Samalut", ar: "مركز سمالوط" },
    { id: "EG2403", en: "New Minya", ar: "مدينة المنيا الجديدة" },
    { id: "EG2400", en: "Zemam Out", ar: "خارج الزمام" },
  ] },
  { id: "EG17", en: "Menoufia", ar: "المنوفية", areas: [
    { id: "EG1704", en: "Al-Bagur", ar: "مركز الباجور" },
    { id: "EG1705", en: "Al-Shuhada", ar: "مركز الشهداء" },
    { id: "EG1703", en: "Ashmun", ar: "مركز أشمون" },
    { id: "EG1706", en: "Birkat Al-Sab", ar: "مركز بركة السبع" },
    { id: "EG1709", en: "Minuf", ar: "مركز منوف" },
    { id: "EG1712", en: "Minuf City", ar: "قسم مدينة منوف" },
    { id: "EG1708", en: "Quwisna", ar: "مركز قويسنا" },
    { id: "EG1711", en: "Sadat City", ar: "مركز السادات" },
    { id: "EG1702", en: "Shibin al-Kum", ar: "مركز شبين الكوم" },
    { id: "EG1701", en: "Shibin al-Kum", ar: "قسم شبين الكوم" },
    { id: "EG1710", en: "Sirs Al-Layyana City", ar: "قسم مدينة سرس الليانة" },
    { id: "EG1707", en: "Tala", ar: "مركز تلا" },
  ] },
  { id: "EG32", en: "New Valley", ar: "الوادى الجديد", areas: [
    { id: "EG3202", en: "A-Dakhla Oasis", ar: "مركز الوحات الداخلة" },
    { id: "EG3203", en: "Al Farafra Oasis", ar: "مركز الفرافرة" },
    { id: "EG3201", en: "Al-Kharga Oasis", ar: "مركز الواحات الخارجة" },
    { id: "EG3204", en: "Paris Paris", ar: "مركز باريس" },
  ] },
  { id: "EG34", en: "North Sinai", ar: "شمال سيناء", areas: [
    { id: "EG3406", en: "Al-Hasna", ar: "قسم الحسنة" },
    { id: "EG3405", en: "Bir Al-Abd", ar: "قسم بئر العبد" },
    { id: "EG3401", en: "El Arish 1", ar: "قسم أول العريش" },
    { id: "EG3402", en: "El Arish 2", ar: "قسم ثان العريش" },
    { id: "EG3403", en: "El Arish 3", ar: "قسم ثالث العريش" },
    { id: "EG3404", en: "El Arish 4", ar: "قسم رابع العريش" },
    { id: "EG3407", en: "Nakhl", ar: "قسم نخل" },
    { id: "EG3411", en: "Qasima", ar: "قسم القسيمة" },
    { id: "EG3409", en: "Rafah", ar: "قسم رفح" },
    { id: "EG3410", en: "Rummana", ar: "قسم رمانة" },
    { id: "EG3408", en: "Shaykh Zuwayd", ar: "قسم الشيخ زويد" },
  ] },
  { id: "EG03", en: "Port Said", ar: "بورسعيد", areas: [
    { id: "EG0302", en: "Al-Arab", ar: "قسم العرب" },
    { id: "EG0305", en: "Al-Dawahy", ar: "قسم الضواحى" },
    { id: "EG0306", en: "Al-Ganoub", ar: "قسم الجنوب" },
    { id: "EG0311", en: "Al-Ganoub 2", ar: "قسم ثان الجنوب" },
    { id: "EG0310", en: "Al-Manasra", ar: "قسم المناصرة" },
    { id: "EG0303", en: "Al-Munakh", ar: "قسم المناخ" },
    { id: "EG0301", en: "Al-Sharq", ar: "قسم الشرق" },
    { id: "EG0307", en: "Al-Zohour", ar: "قسم الزهور" },
    { id: "EG0309", en: "Mubark-Sharq Tafrea", ar: "قسم مبارك - شرق التفريعة" },
    { id: "EG0312", en: "Police Department Port Said Port", ar: "إدارة شرطة ميناء بورسعيد" },
    { id: "EG0304", en: "Port Fuad", ar: "قسم بور فؤاد" },
    { id: "EG0308", en: "Port Fuad 2", ar: "قسم ثان بور فؤاد" },
  ] },
  { id: "EG27", en: "Qena", ar: "قنا", areas: [
    { id: "EG2703", en: "Abu Tisht", ar: "مركز أبو طشت" },
    { id: "EG2712", en: "Al Waqf", ar: "مركز الوقف" },
    { id: "EG2704", en: "Armant", ar: "مركز أرمنت" },
    { id: "EG2706", en: "Dishna", ar: "مركز دشنا" },
    { id: "EG2710", en: "Farshut", ar: "مركز فرشوط" },
    { id: "EG2705", en: "Isna", ar: "مركز إسنا" },
    { id: "EG2708", en: "Nag Hammadi", ar: "مركز نجع حمادى" },
    { id: "EG2709", en: "Naqada", ar: "مركز نقادة" },
    { id: "EG2711", en: "Qift", ar: "مركز قفط" },
    { id: "EG2702", en: "Qina", ar: "مركز قنا" },
    { id: "EG2701", en: "Qina", ar: "قسم قنا" },
    { id: "EG2713", en: "Qina City", ar: "مدينة قنا الجديدة" },
    { id: "EG2707", en: "Qus", ar: "مركز قوص" },
    { id: "EG2700", en: "Zemam Out", ar: "صحراء قنا" },
  ] },
  { id: "EG31", en: "Red Sea", ar: "البحر الأحمر", areas: [
    { id: "EG3107", en: "Halayib", ar: "قسم حلايب" },
    { id: "EG3101", en: "Hurghada 1", ar: "قسم أول الغردقة" },
    { id: "EG3108", en: "Hurghada 2", ar: "قسم ثان الغردقة" },
    { id: "EG3104", en: "Marsa Alam", ar: "قسم مرسى علم" },
    { id: "EG3102", en: "Qusir", ar: "قسم القصير" },
    { id: "EG3105", en: "Ras Gharib", ar: "قسم رأس غارب" },
    { id: "EG3103", en: "Safaga", ar: "قسم سفاجا" },
    { id: "EG3106", en: "Shallatin", ar: "قسم شلاتين" },
  ] },
  { id: "EG13", en: "Sharkia", ar: "الشرقية", areas: [
    { id: "EG1309", en: "10 Ramadan 1", ar: "قسم اول مدينة العاشر من رمضان" },
    { id: "EG1321", en: "10 Ramadan 2", ar: "قسم ثان مدينه العاشر من رمضان" },
    { id: "EG1304", en: "Abu Hammad", ar: "مركز أبو حماد" },
    { id: "EG1305", en: "Abu Kabir", ar: "مركز أبوكبير" },
    { id: "EG1306", en: "Al-Husayniya", ar: "مركز الحسينية" },
    { id: "EG1318", en: "Al-Qanayat", ar: "قسم القنايات" },
    { id: "EG1307", en: "Al-Salhiyya", ar: "قسم الصالحية الجديدة" },
    { id: "EG1319", en: "Awlad Saqr", ar: "مركز أولاد صقر" },
    { id: "EG1308", en: "Bilbis", ar: "مركز بلبيس" },
    { id: "EG1310", en: "Dyarb Nigm", ar: "مركز ديرب نجم" },
    { id: "EG1317", en: "El-Ibrahimiya", ar: "مركز الأبراهيمية" },
    { id: "EG1312", en: "Faqus", ar: "مركز فاقوس" },
    { id: "EG1311", en: "Faqus", ar: "قسم فاقوس" },
    { id: "EG1315", en: "Hihya", ar: "مركز ههيا" },
    { id: "EG1313", en: "Kafr Saqr", ar: "مركز كفر صقر" },
    { id: "EG1316", en: "Mashtul Al-Suq", ar: "مركز مشتول السوق" },
    { id: "EG1314", en: "Minya al-Qamh", ar: "مركز منيا القمح" },
    { id: "EG1320", en: "Qurin", ar: "قسم القرين" },
    { id: "EG1303", en: "Zaqaziq", ar: "مركز الزقازيق" },
    { id: "EG1301", en: "Zaqaziq 1", ar: "قسم اول الزقازيق" },
    { id: "EG1302", en: "Zaqaziq 2", ar: "قسم ثان الزقازيق" },
    { id: "EG1300", en: "Zemam Out", ar: "خارج الزمام" },
  ] },
  { id: "EG35", en: "South Sinai", ar: "جنوب سيناء", areas: [
    { id: "EG3503", en: "Abu Radis", ar: "قسم أبو رديس" },
    { id: "EG3501", en: "Al-Tur", ar: "قسم الطور" },
    { id: "EG3506", en: "Dahab", ar: "قسم دهب" },
    { id: "EG3507", en: "Nuweiba", ar: "قسم نويبع" },
    { id: "EG3502", en: "Ras Sidr", ar: "قسم رأس سدر" },
    { id: "EG3504", en: "Sant Katrin", ar: "قسم سانت كاترين" },
    { id: "EG3505", en: "Sharm el-Sheikh", ar: "قسم شرم الشيخ" },
    { id: "EG3508", en: "Taba", ar: "قسم طابا" },
  ] },
  { id: "EG04", en: "Suez", ar: "السويس", areas: [
    { id: "EG0402", en: "Al-Arbiin", ar: "قسم الأربعين" },
    { id: "EG0405", en: "Al-Ganayin", ar: "قسم الجناين" },
    { id: "EG0403", en: "Ataqa", ar: "قسم عتاقة" },
    { id: "EG0404", en: "Faysal", ar: "قسم فيصل" },
    { id: "EG0406", en: "Port Suez Police Department", ar: "إدارة شرطة ميناء السويس" },
    { id: "EG0401", en: "Suez", ar: "قسم السويس" },
  ] },
  { id: "EG26", en: "Suhag", ar: "سوهاج", areas: [
    { id: "EG2604", en: "Akhmim", ar: "مركز أخميم" },
    { id: "EG2618", en: "Akhmim City", ar: "مدينة أخميم الجديدة" },
    { id: "EG2617", en: "Al Usayrat", ar: "مركز العسيرات" },
    { id: "EG2605", en: "Al-Balyana", ar: "مركز البلينا" },
    { id: "EG2606", en: "Al-Maragha", ar: "مركز المراغة" },
    { id: "EG2607", en: "Al-Minshat", ar: "مركز المنشأة" },
    { id: "EG2608", en: "Dar al-Salam", ar: "مركز دار السلام" },
    { id: "EG2610", en: "Girga", ar: "مركز جرجا" },
    { id: "EG2609", en: "Girga", ar: "قسم جرجا" },
    { id: "EG2611", en: "Guhayna Al-Gharbiyya", ar: "مركز جهينة الغربية" },
    { id: "EG2616", en: "Kawther", ar: "قسم الكوثر" },
    { id: "EG2615", en: "Kesm Tahta", ar: "قسم طهطا" },
    { id: "EG2612", en: "Saqulta", ar: "مركز ساقلته" },
    { id: "EG2603", en: "Suhag", ar: "مركز سوهاج" },
    { id: "EG2601", en: "Suhag", ar: "قسم اول سوهاج" },
    { id: "EG2619", en: "Suhag City", ar: "مدينة سوهاج الجديدة" },
    { id: "EG2602", en: "Suhag-2", ar: "قسم ثان سوهاج" },
    { id: "EG2614", en: "Tahta", ar: "مركز طهطا" },
    { id: "EG2613", en: "Tama", ar: "مركز طما" },
    { id: "EG2600", en: "Zemam Out", ar: "صحراء سوهاج" },
  ] },
] as const;
