/**
 * WPS-017 admin platform copy.
 *
 * The admin platform is a staff product, not a customer product. Warsha's
 * bilingual commitment is preserved for every workflow label a reviewer acts
 * on: English and natural Egyptian Arabic, RTL safe, with Cairo dates and EGP.
 *
 * Language rules:
 * - state the operational fact, never a customer marketing line;
 * - never repeat the motto on an operational screen;
 * - never render a private note, evidence, or contact detail the role cannot see;
 * - always name the environment before a dangerous action;
 * - always say which specification owns the decision being taken.
 *
 * Data only, so the regression suite can validate it without React or Expo.
 */
export const adminCopy = {
  en: {
    // Shell
    platformTitle: 'Warsha Operations',
    platformSubtitle: 'Internal staff workspace',
    environmentLocal: 'Local',
    environmentStaging: 'Staging',
    environmentProduction: 'PRODUCTION',
    environmentWarning: 'You are working in production. Every action here is real and audited.',
    simulatedData: 'Simulated data. Mock mode is active and nothing here is real.',
    notStaff: 'This account has no operations access.',
    notStaffDetail: 'If you need access, ask a Security Administrator. Access is never granted automatically.',
    platformUnavailable: 'The operations platform is unavailable in this environment.',
    platformUnavailableDetail: 'Production requires a verified second factor, and no provider is configured yet.',
    surfaceDisabled: 'The operations surface is switched off in this build.',
    signOut: 'Sign out of operations',
    reauthRequired: 'Re-authentication required',
    reauthDetail: 'This action is high risk. Confirm it is you before continuing.',
    reauthAction: 'Confirm it is me',
    reauthDone: 'Re-authentication recorded',
    revokeSessions: 'Revoke my operations sessions',

    // Home
    homeTitle: 'Operations home',
    homeQueues: 'Work queues',
    homeMyCases: 'Assigned to me',
    homeMyOverdue: 'Overdue',
    homeIncidents: 'Active incidents',
    homeNoQueues: 'No queues are available to your role.',
    homeNoQueuesDetail: 'Queues appear only for the capabilities you actually hold.',
    homeUpdated: 'Data as of',

    // Queues and cases
    queueOpen: 'Open',
    queueBacklog: 'Not yet opened',
    queueOverdue: 'Overdue',
    queueAssignedToMe: 'Mine',
    queueTarget: 'Target response',
    queueEmpty: 'Nothing is waiting in this queue.',
    caseTitle: 'Case',
    caseSubject: 'Subject record',
    caseStatus: 'Status',
    casePriority: 'Priority',
    caseAssignee: 'Owner',
    caseUnassigned: 'Unassigned',
    caseDue: 'Due',
    caseAge: 'Age',
    caseHistory: 'History',
    casePrivateNotes: 'Staff-private notes',
    casePrivateNoteHint: 'Only staff who can work this queue see these notes. Participants never do.',
    caseAddNote: 'Add a private note',
    caseClaim: 'Claim this case',
    caseAssign: 'Assign',
    caseStart: 'Start work',
    caseWaitParticipant: 'Waiting for the participant',
    caseWaitProvider: 'Waiting for the provider',
    caseEscalate: 'Escalate',
    caseResolve: 'Resolve',
    caseClose: 'Close',
    caseStale: 'This case changed while you were reading it. Reload before acting.',
    caseNextAction: 'Next action',
    caseOpenDomain: 'Open the authoritative record',
    caseDomainNote: 'The decision itself is recorded by the specification that owns it.',

    // Statuses
    statusUnassigned: 'Unassigned',
    statusAssigned: 'Assigned',
    statusInProgress: 'In progress',
    statusWaitingParticipant: 'Waiting for participant',
    statusWaitingProvider: 'Waiting for provider',
    statusEscalated: 'Escalated',
    statusResolved: 'Resolved',
    statusClosed: 'Closed',
    priorityUrgent: 'Urgent',
    priorityHigh: 'High',
    priorityNormal: 'Normal',
    priorityLow: 'Low',

    // Queues
    queueIdentityVerification: 'Pending identity verification',
    queueCertificateReview: 'Pending certificates',
    queueOpenDisputes: 'Open disputes',
    queueDisputeEvidenceDeadlines: 'Dispute evidence deadlines',
    queueAbuseReports: 'Abuse reports',
    queueTrustInvestigations: 'Trust investigations',
    queueAppeals: 'Appeals',
    queueReviewModeration: 'Review moderation',
    queueFailedRefunds: 'Failed refunds',
    queueFailedPayouts: 'Failed payouts',
    queueWithdrawalReviews: 'Withdrawal reviews',
    queueReconciliationExceptions: 'Reconciliation exceptions',
    queueChargebacks: 'Chargebacks',
    queuePostReleaseCases: 'Post-release financial cases',
    queueMarketplaceIncidents: 'Marketplace incidents',
    queueNotificationFailures: 'Notification delivery failures',
    queueSupportCases: 'Support cases',
    queueSecurityEvents: 'Security events',

    // Search
    searchTitle: 'Operational search',
    searchHint: 'Search an exact identifier. There is no name search and no wildcard.',
    searchPlaceholder: 'Booking, dispute, report, payment, or account ID',
    searchTooShort: 'Enter the full identifier.',
    searchWildcard: 'Wildcards are not permitted.',
    searchRateLimited: 'You have searched too often. Wait a moment and try again.',
    searchEmpty: 'Nothing matched that identifier in the areas your role can see.',
    searchAudited: 'Every search is recorded against your account.',
    searchNoNationalId: 'National ID is never searchable.',

    // Safe views
    profileTitle: 'Safe account view',
    profileContactHidden: 'Contact details are hidden for your role.',
    profileFinancialHidden: 'Earnings are hidden for your role.',
    profileTrustLevel: 'Account standing',
    profileBookings: 'Bookings',
    profileDisputes: 'Disputes',
    profileReports: 'Reports',
    profileSupport: 'Support cases',
    profileVerification: 'Verification',
    profileCertificates: 'Certificates',
    profileEarnings: 'Earnings',

    // Configuration
    configTitle: 'Configuration',
    configOwner: 'Owned by',
    configAppliedByWps017: 'Applied by the admin platform',
    configAppliedByDomain: 'Applied by the owning specification',
    configDraft: 'Draft',
    configPendingApproval: 'Awaiting approval',
    configActive: 'Active',
    configSuperseded: 'Superseded',
    configRejected: 'Rejected',
    configChangeReason: 'Why is this changing?',
    configSubmit: 'Submit for approval',
    configApprove: 'Approve and activate',
    configRollback: 'Prepare a rollback',
    configDualControl: 'A second person must approve this. You cannot approve your own change.',
    configHistoryImmutable: 'Configuration history cannot be edited. Roll back with a new version.',
    configNoSecrets: 'Secrets are never stored here.',
    configInvalidPayload: 'That value is not allowed for this configuration domain.',

    // Feature flags
    flagsTitle: 'Feature flags',
    flagsDisabledByDefault: 'Every flag is off until someone turns it on, with a reason.',
    flagEnabled: 'On',
    flagDisabled: 'Off',
    flagAudience: 'Audience',
    flagRollout: 'Rollout',
    flagReason: 'Reason',
    flagReview: 'Review by',
    flagNotSecurity: 'A security control is never a feature flag.',

    // Kill switches
    switchesTitle: 'Kill switches',
    switchesIntro: 'A switch only ever restricts. It never deletes data and never touches history.',
    switchActive: 'Active',
    switchInactive: 'Off',
    switchServerEnforced: 'Enforced by the server',
    switchAdvisory: 'Advisory only',
    switchActivate: 'Activate',
    switchClear: 'Clear',
    switchReason: 'Why is this being switched?',
    switchConfirm: 'Confirm this restriction',
    switchExistingWork: 'Existing bookings, chat, and history are unaffected.',

    // Support
    supportTitle: 'Support cases',
    supportCategory: 'Category',
    supportReply: 'Reply to the participant',
    supportPrivateNote: 'Staff-private note',
    supportEscalate: 'Escalate to the owning record',
    supportEscalateHint: 'Escalation links to the dispute or report that already exists. It never creates a second one.',

    // Incidents
    incidentsTitle: 'Incidents',
    incidentsManual: 'Incidents are opened by a person. There is no automated detection.',
    incidentOpen: 'Open an incident',
    incidentSeverity: 'Severity',
    incidentCommander: 'Commander',
    incidentAffected: 'Affected systems',
    incidentInternalSummary: 'Internal summary',
    incidentPublicSummary: 'Public summary',
    incidentTimeline: 'Timeline',
    incidentResolve: 'Resolve',
    incidentPostmortem: 'Postmortem reference',

    // Audit
    auditTitle: 'Audit explorer',
    auditReadOnly: 'Read only. Audit records can never be edited or deleted.',
    auditSource: 'Source',
    auditRange: 'Date range',
    auditActor: 'Actor',
    auditAction: 'Action',
    auditTarget: 'Target',
    auditSelfLogged: 'Opening the audit explorer is itself recorded.',

    // Analytics
    analyticsTitle: 'Analytics',
    analyticsTimezone: 'Reporting timezone',
    analyticsTimeBasis: 'Time basis',
    analyticsPartial: 'This period includes today, so the newest numbers are incomplete.',
    analyticsSuppressed: 'Hidden: too few records to report safely',
    analyticsFreshness: 'Calculated when you opened this page',
    analyticsNoPii: 'These numbers contain no personal data, no addresses, and no contact details.',
    analyticsDefinition: 'Definition',
    analyticsLimitations: 'Known limitations',
    analyticsEmpty: 'No data for this period.',

    // Exports
    exportTitle: 'Export',
    exportReason: 'Why do you need this export?',
    exportRange: 'Date range',
    exportColumns: 'Columns',
    exportRequest: 'Request export',
    exportNoFile: 'File download is not available. The bounded preview below is the approved output.',
    exportAudited: 'Every export request and download is recorded with your reason.',
    exportExpired: 'This export has expired. Request it again.',

    // Roles
    rolesTitle: 'Staff roles',
    rolesDenyByDefault: 'Access is denied by default. A role grants exactly the capabilities listed.',
    roleGrant: 'Grant a role',
    roleRevoke: 'Revoke',
    roleReason: 'Why does this person need it?',
    roleSelfDenied: 'You cannot grant a role to your own account.',
    roleBreakGlass: 'Break-glass access. Production use must be exceptional and reviewed.',
    roleSupportAgent: 'Support Agent',
    roleVerificationReviewer: 'Verification Reviewer',
    roleTrustSafetyReviewer: 'Trust & Safety Reviewer',
    roleDisputeReviewer: 'Dispute Reviewer',
    roleFinancialOperations: 'Financial Operations',
    roleMarketplaceOperations: 'Marketplace Operations',
    roleOperationsManager: 'Operations Manager',
    roleSecurityAdministrator: 'Security Administrator',
    roleSuperAdministrator: 'Super Administrator',

    // Errors and confirmations
    errorDenied: 'Your role does not allow that.',
    errorNotFound: 'That record is not available.',
    errorConflict: 'Someone else changed this. Reload and try again.',
    errorGeneric: 'That did not work. Nothing was changed.',
    confirmTitle: 'Confirm',
    confirmCancel: 'Cancel',
    confirmProceed: 'Proceed',
    required: 'Required',

    // Accessibility
    a11yEnvironment: 'Current environment',
    a11yQueueCard: 'Work queue',
    a11yCaseStatus: 'Case status',
    a11yCasePriority: 'Case priority',
    a11yOverdue: 'Overdue',
    a11ySuppressed: 'Value hidden to protect privacy',
    a11yHighRisk: 'High-risk action',
    a11yTable: 'Operational table',
    a11yMetric: 'Metric',
    a11yLoading: 'Loading operational data',
  },
  ar: {
    // Shell
    platformTitle: 'عمليات ورشة',
    platformSubtitle: 'مساحة عمل داخلية للفريق',
    environmentLocal: 'محلي',
    environmentStaging: 'تجريبي',
    environmentProduction: 'إنتاج',
    environmentWarning: 'إنت شغال على بيئة الإنتاج. كل إجراء هنا حقيقي ومسجل.',
    simulatedData: 'بيانات محاكاة. وضع المحاكاة شغال ومفيش حاجة هنا حقيقية.',
    notStaff: 'الحساب ده معندوش صلاحية دخول للعمليات.',
    notStaffDetail: 'لو محتاج صلاحية، اطلبها من مسؤول الأمان. الصلاحية مش بتتدي تلقائيًا.',
    platformUnavailable: 'منصة العمليات مش متاحة في البيئة دي.',
    platformUnavailableDetail: 'الإنتاج محتاج تحقق ثاني، ولسه مفيش مزود متظبط.',
    surfaceDisabled: 'واجهة العمليات مقفولة في النسخة دي.',
    signOut: 'خروج من العمليات',
    reauthRequired: 'محتاج تأكيد هويتك',
    reauthDetail: 'الإجراء ده خطورته عالية. أكد إن ده إنت قبل ما تكمل.',
    reauthAction: 'أكد إن ده أنا',
    reauthDone: 'تم تسجيل التأكيد',
    revokeSessions: 'إلغاء جلسات العمليات بتاعتي',

    // Home
    homeTitle: 'الصفحة الرئيسية للعمليات',
    homeQueues: 'قوائم الشغل',
    homeMyCases: 'المسند ليا',
    homeMyOverdue: 'متأخر',
    homeIncidents: 'أعطال شغالة',
    homeNoQueues: 'مفيش قوائم متاحة لدورك.',
    homeNoQueuesDetail: 'القوائم بتظهر بس للصلاحيات اللي فعلًا عندك.',
    homeUpdated: 'البيانات حتى',

    // Queues and cases
    queueOpen: 'مفتوح',
    queueBacklog: 'لسه مفتحش',
    queueOverdue: 'متأخر',
    queueAssignedToMe: 'بتاعي',
    queueTarget: 'وقت الاستجابة المستهدف',
    queueEmpty: 'مفيش حاجة مستنية في القائمة دي.',
    caseTitle: 'حالة',
    caseSubject: 'السجل الأصلي',
    caseStatus: 'الحالة',
    casePriority: 'الأولوية',
    caseAssignee: 'المسؤول',
    caseUnassigned: 'غير مسند',
    caseDue: 'الموعد',
    caseAge: 'المدة',
    caseHistory: 'السجل',
    casePrivateNotes: 'ملاحظات داخلية للفريق',
    casePrivateNoteHint: 'الملاحظات دي بيشوفها بس الفريق اللي بيشتغل على القائمة. العملاء والصنايعية مش بيشوفوها أبدًا.',
    caseAddNote: 'ضيف ملاحظة داخلية',
    caseClaim: 'استلم الحالة',
    caseAssign: 'إسناد',
    caseStart: 'ابدأ الشغل',
    caseWaitParticipant: 'مستني الطرف الآخر',
    caseWaitProvider: 'مستني المزود',
    caseEscalate: 'تصعيد',
    caseResolve: 'إنهاء',
    caseClose: 'إغلاق',
    caseStale: 'الحالة دي اتغيرت وإنت بتقرأها. حدّث الصفحة قبل ما تتصرف.',
    caseNextAction: 'الخطوة الجاية',
    caseOpenDomain: 'افتح السجل الأصلي',
    caseDomainNote: 'القرار نفسه بيتسجل في المواصفة المسؤولة عنه.',

    // Statuses
    statusUnassigned: 'غير مسند',
    statusAssigned: 'مسند',
    statusInProgress: 'جاري العمل',
    statusWaitingParticipant: 'مستني الطرف الآخر',
    statusWaitingProvider: 'مستني المزود',
    statusEscalated: 'متصعّد',
    statusResolved: 'اتحل',
    statusClosed: 'مقفول',
    priorityUrgent: 'عاجل',
    priorityHigh: 'مرتفع',
    priorityNormal: 'عادي',
    priorityLow: 'منخفض',

    // Queues
    queueIdentityVerification: 'توثيق هوية في الانتظار',
    queueCertificateReview: 'شهادات في الانتظار',
    queueOpenDisputes: 'نزاعات مفتوحة',
    queueDisputeEvidenceDeadlines: 'مواعيد أدلة النزاعات',
    queueAbuseReports: 'بلاغات إساءة',
    queueTrustInvestigations: 'تحقيقات الثقة',
    queueAppeals: 'تظلمات',
    queueReviewModeration: 'مراجعة التقييمات',
    queueFailedRefunds: 'استردادات فاشلة',
    queueFailedPayouts: 'تحويلات فاشلة',
    queueWithdrawalReviews: 'مراجعة السحب',
    queueReconciliationExceptions: 'فروقات التسوية',
    queueChargebacks: 'ردود المدفوعات',
    queuePostReleaseCases: 'حالات مالية بعد الصرف',
    queueMarketplaceIncidents: 'أعطال السوق',
    queueNotificationFailures: 'فشل إرسال الإشعارات',
    queueSupportCases: 'حالات الدعم',
    queueSecurityEvents: 'أحداث أمنية',

    // Search
    searchTitle: 'بحث تشغيلي',
    searchHint: 'ابحث برقم تعريف كامل. مفيش بحث بالاسم ولا بعلامات عامة.',
    searchPlaceholder: 'رقم حجز أو نزاع أو بلاغ أو دفعة أو حساب',
    searchTooShort: 'اكتب رقم التعريف كامل.',
    searchWildcard: 'العلامات العامة ممنوعة.',
    searchRateLimited: 'بحثت كتير في وقت قصير. استنى شوية وحاول تاني.',
    searchEmpty: 'مفيش نتيجة للرقم ده في الأماكن اللي دورك بيشوفها.',
    searchAudited: 'كل عملية بحث بتتسجل على حسابك.',
    searchNoNationalId: 'الرقم القومي مش قابل للبحث نهائيًا.',

    // Safe views
    profileTitle: 'عرض آمن للحساب',
    profileContactHidden: 'بيانات التواصل مخفية عن دورك.',
    profileFinancialHidden: 'الأرباح مخفية عن دورك.',
    profileTrustLevel: 'حالة الحساب',
    profileBookings: 'الحجوزات',
    profileDisputes: 'النزاعات',
    profileReports: 'البلاغات',
    profileSupport: 'حالات الدعم',
    profileVerification: 'التوثيق',
    profileCertificates: 'الشهادات',
    profileEarnings: 'الأرباح',

    // Configuration
    configTitle: 'الإعدادات',
    configOwner: 'المسؤول عنها',
    configAppliedByWps017: 'بتتطبق من منصة العمليات',
    configAppliedByDomain: 'بتتطبق من المواصفة المسؤولة',
    configDraft: 'مسودة',
    configPendingApproval: 'في انتظار الموافقة',
    configActive: 'مفعّلة',
    configSuperseded: 'اتستبدلت',
    configRejected: 'مرفوضة',
    configChangeReason: 'ليه بتتغير؟',
    configSubmit: 'إرسال للموافقة',
    configApprove: 'موافقة وتفعيل',
    configRollback: 'تجهيز رجوع لنسخة أقدم',
    configDualControl: 'لازم شخص تاني يوافق. مش ممكن توافق على تغييرك بنفسك.',
    configHistoryImmutable: 'سجل الإعدادات مش بيتعدل. الرجوع بيتم بنسخة جديدة.',
    configNoSecrets: 'الأسرار مش بتتخزن هنا أبدًا.',
    configInvalidPayload: 'القيمة دي مش مسموحة في المجال ده.',

    // Feature flags
    flagsTitle: 'مفاتيح المزايا',
    flagsDisabledByDefault: 'كل مفتاح مقفول لحد ما حد يفتحه بسبب مكتوب.',
    flagEnabled: 'مفتوح',
    flagDisabled: 'مقفول',
    flagAudience: 'الجمهور',
    flagRollout: 'نسبة الطرح',
    flagReason: 'السبب',
    flagReview: 'مراجعة قبل',
    flagNotSecurity: 'ضوابط الأمان مش بتتعمل كمفتاح مزايا.',

    // Kill switches
    switchesTitle: 'مفاتيح الإيقاف',
    switchesIntro: 'المفتاح بيقيّد بس. مش بيمسح بيانات ولا بيلمس السجل.',
    switchActive: 'مفعّل',
    switchInactive: 'مقفول',
    switchServerEnforced: 'مطبّق من الخادم',
    switchAdvisory: 'إرشادي فقط',
    switchActivate: 'تفعيل',
    switchClear: 'إلغاء',
    switchReason: 'ليه بتقفل ده؟',
    switchConfirm: 'أكد التقييد',
    switchExistingWork: 'الحجوزات والمحادثات والسجل الحالي مش هيتأثروا.',

    // Support
    supportTitle: 'حالات الدعم',
    supportCategory: 'التصنيف',
    supportReply: 'رد على صاحب الطلب',
    supportPrivateNote: 'ملاحظة داخلية',
    supportEscalate: 'تصعيد للسجل المسؤول',
    supportEscalateHint: 'التصعيد بيربط بالنزاع أو البلاغ الموجود بالفعل. مش بيعمل واحد تاني.',

    // Incidents
    incidentsTitle: 'الأعطال',
    incidentsManual: 'الأعطال بيفتحها شخص. مفيش رصد تلقائي.',
    incidentOpen: 'افتح عطل',
    incidentSeverity: 'الخطورة',
    incidentCommander: 'المسؤول',
    incidentAffected: 'الأنظمة المتأثرة',
    incidentInternalSummary: 'ملخص داخلي',
    incidentPublicSummary: 'ملخص عام',
    incidentTimeline: 'الخط الزمني',
    incidentResolve: 'إنهاء',
    incidentPostmortem: 'مرجع التحليل',

    // Audit
    auditTitle: 'مستكشف السجل',
    auditReadOnly: 'قراءة فقط. سجلات المراجعة مش بتتعدل ولا بتتمسح.',
    auditSource: 'المصدر',
    auditRange: 'المدة',
    auditActor: 'المنفذ',
    auditAction: 'الإجراء',
    auditTarget: 'الهدف',
    auditSelfLogged: 'فتح المستكشف نفسه بيتسجل.',

    // Analytics
    analyticsTitle: 'التحليلات',
    analyticsTimezone: 'المنطقة الزمنية للتقرير',
    analyticsTimeBasis: 'أساس الوقت',
    analyticsPartial: 'المدة دي شاملة النهارده، يبقى آخر أرقام لسه ناقصة.',
    analyticsSuppressed: 'مخفي: عدد السجلات أقل من إن نعرضه بأمان',
    analyticsFreshness: 'اتحسبت وقت ما فتحت الصفحة',
    analyticsNoPii: 'الأرقام دي مفيهاش بيانات شخصية ولا عناوين ولا وسائل تواصل.',
    analyticsDefinition: 'التعريف',
    analyticsLimitations: 'حدود معروفة',
    analyticsEmpty: 'مفيش بيانات للمدة دي.',

    // Exports
    exportTitle: 'تصدير',
    exportReason: 'محتاج التصدير ده ليه؟',
    exportRange: 'المدة',
    exportColumns: 'الأعمدة',
    exportRequest: 'اطلب التصدير',
    exportNoFile: 'تنزيل الملف مش متاح. المعاينة المحدودة تحت هي المخرج المعتمد.',
    exportAudited: 'كل طلب وتنزيل بيتسجل مع السبب اللي كتبته.',
    exportExpired: 'التصدير ده انتهت صلاحيته. اطلبه تاني.',

    // Roles
    rolesTitle: 'أدوار الفريق',
    rolesDenyByDefault: 'الصلاحية مرفوضة افتراضيًا. الدور بيدي بالظبط الصلاحيات المكتوبة.',
    roleGrant: 'منح دور',
    roleRevoke: 'سحب',
    roleReason: 'ليه الشخص ده محتاجه؟',
    roleSelfDenied: 'مش ممكن تدي دور لحسابك إنت.',
    roleBreakGlass: 'صلاحية الطوارئ. استخدامها في الإنتاج لازم يكون استثنائي ومراجَع.',
    roleSupportAgent: 'موظف دعم',
    roleVerificationReviewer: 'مراجع توثيق',
    roleTrustSafetyReviewer: 'مراجع ثقة وأمان',
    roleDisputeReviewer: 'مراجع نزاعات',
    roleFinancialOperations: 'العمليات المالية',
    roleMarketplaceOperations: 'عمليات السوق',
    roleOperationsManager: 'مدير العمليات',
    roleSecurityAdministrator: 'مسؤول الأمان',
    roleSuperAdministrator: 'مسؤول عام',

    // Errors and confirmations
    errorDenied: 'دورك مش مسموح له بده.',
    errorNotFound: 'السجل ده مش متاح.',
    errorConflict: 'حد تاني غيّر ده. حدّث الصفحة وحاول تاني.',
    errorGeneric: 'ده مانفعش. مفيش حاجة اتغيرت.',
    confirmTitle: 'تأكيد',
    confirmCancel: 'إلغاء',
    confirmProceed: 'تمام، كمّل',
    required: 'مطلوب',

    // Accessibility
    a11yEnvironment: 'البيئة الحالية',
    a11yQueueCard: 'قائمة شغل',
    a11yCaseStatus: 'حالة الملف',
    a11yCasePriority: 'أولوية الملف',
    a11yOverdue: 'متأخر',
    a11ySuppressed: 'القيمة مخفية لحماية الخصوصية',
    a11yHighRisk: 'إجراء عالي الخطورة',
    a11yTable: 'جدول تشغيلي',
    a11yMetric: 'مؤشر',
    a11yLoading: 'بيتم تحميل بيانات العمليات',
  },
} as const;

export type AdminCopyKey = keyof typeof adminCopy.en;
export type AdminLanguage = keyof typeof adminCopy;

export function adminText(language: AdminLanguage, key: AdminCopyKey): string {
  return adminCopy[language][key];
}
