/**
 * WPS-017 metric catalog.
 *
 * Dashboard code may not invent a business metric. Every key returned by
 * `get_staff_analytics` must appear here with its business question, sources,
 * numerator, denominator, inclusion and exclusion rules, time basis, refresh
 * cadence, privacy classification, and known limitations.
 *
 * `docs/analytics/WARSHA-METRIC-CATALOG.md` is the human-readable mirror of
 * this file; the regression suite asserts the two never drift apart.
 */

import type { StaffDashboard } from './admin-types';

export type MetricPrivacy =
  /** Aggregate counts with no cohort small enough to identify a person. */
  | 'aggregate'
  /** Aggregate over people; suppressed below the configured minimum cell. */
  | 'aggregate_suppressed'
  /** Money totals; visible only to a role holding the ledger capability. */
  | 'financial_restricted'
  /** Operational configuration state; no personal data at all. */
  | 'operational_state';

export type MetricTimeBasis =
  | 'record_creation'
  | 'submission_time'
  | 'request_time'
  | 'event_time'
  | 'current_state';

export type MetricDefinition = {
  key: string;
  dashboard: StaffDashboard;
  name: string;
  businessQuestion: string;
  sources: string[];
  numerator: string;
  denominator: string | null;
  inclusion: string;
  exclusion: string;
  timeBasis: MetricTimeBasis;
  updateFrequency: string;
  privacy: MetricPrivacy;
  limitations: string;
};

const onRead = 'On read. There is no materialized view and no refresh job.';
const cairo = 'Bucketed by the Africa/Cairo reporting day; authoritative timestamps stay UTC.';

export const metricCatalog: readonly MetricDefinition[] = [
  // -- Executive -----------------------------------------------------------
  {
    key: 'requestsCreated', dashboard: 'executive', name: 'Requests created',
    businessQuestion: 'How much demand entered the marketplace in the period?',
    sources: ['public.marketplace_requests'],
    numerator: 'Count of marketplace requests created in the period.', denominator: null,
    inclusion: 'Every request row regardless of flow kind or outcome.',
    exclusion: 'Nothing is excluded; drafts are counted because they represent attempted demand.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: `Includes abandoned drafts, so it overstates completed intent. ${cairo}`,
  },
  {
    key: 'bookingsCreated', dashboard: 'executive', name: 'Bookings created',
    businessQuestion: 'How many agreements were formed in the period?',
    sources: ['public.bookings'],
    numerator: 'Count of bookings created in the period.', denominator: null,
    inclusion: 'All bookings including direct bookings and marketplace conversions.',
    exclusion: 'Soft-deleted bookings are still counted; deletion does not undo history.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: `Creation is not confirmation. ${cairo}`,
  },
  {
    key: 'bookingsCompleted', dashboard: 'executive', name: 'Bookings completed',
    businessQuestion: 'How much work actually finished?',
    sources: ['public.bookings'],
    numerator: 'Bookings created in the period whose current status is completed.',
    denominator: 'Bookings created in the period.',
    inclusion: 'Status is evaluated now, not at period end.',
    exclusion: 'Cancelled, rejected, and refunded bookings.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: `A cohort measured on creation date under-reports recent periods because work is still in flight. ${cairo}`,
  },
  {
    key: 'publishedWorkers', dashboard: 'executive', name: 'Publicly discoverable workers',
    businessQuestion: 'How much supply is visible to customers right now?',
    sources: ['public.provider_profiles'],
    numerator: 'Workers with is_published true and no deletion timestamp.', denominator: null,
    inclusion: 'Current state only.',
    exclusion: 'Deleted profiles.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Published is not the same as eligible; WPS-008 eligibility applies additional hard gates.',
  },
  {
    key: 'openDisputes', dashboard: 'executive', name: 'Open disputes',
    businessQuestion: 'How much unresolved conflict is on the platform now?',
    sources: ['public.disputes'],
    numerator: 'Disputes in submitted, waiting, or under-review states.', denominator: null,
    inclusion: 'Current state only, ignoring the reporting period.',
    exclusion: 'Resolved, closed, rejected, and cancelled disputes.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'A point-in-time backlog, not a rate.',
  },
  {
    key: 'openReports', dashboard: 'executive', name: 'Open abuse reports',
    businessQuestion: 'How much trust work is waiting?',
    sources: ['public.trust_reports'],
    numerator: 'Reports in submitted, triage, or investigating status.', denominator: null,
    inclusion: 'Current state only.',
    exclusion: 'Actioned, dismissed, and duplicate reports.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Reporter identity is never exposed here or anywhere in analytics.',
  },
  {
    key: 'activeIncidents', dashboard: 'executive', name: 'Active incidents',
    businessQuestion: 'Is anything broken right now?',
    sources: ['public.operational_incidents'],
    numerator: 'Incidents in open, mitigating, or monitoring status.', denominator: null,
    inclusion: 'Current state only.',
    exclusion: 'Resolved and closed incidents.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'operational_state',
    limitations: 'Incidents are created by a human. There is no automated detection.',
  },
  {
    key: 'onlinePaymentsEnabled', dashboard: 'executive', name: 'Online payments enabled',
    businessQuestion: 'Is the payment gateway surface live?',
    sources: ['private.payment_configuration'],
    numerator: 'Gateway mode is not disabled.', denominator: null,
    inclusion: 'Current configuration only.', exclusion: 'None.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'operational_state',
    limitations: 'Mock mode reports as enabled; the payment dashboard distinguishes the environment.',
  },
  {
    key: 'marketplaceEnabled', dashboard: 'executive', name: 'Marketplace enabled',
    businessQuestion: 'Is marketplace matching active?',
    sources: ['private.marketplace_configuration'],
    numerator: 'Marketplace configuration enabled flag.', denominator: null,
    inclusion: 'Current configuration only.', exclusion: 'None.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'operational_state',
    limitations: 'WPS-008 remains the authority; this reads its flag and never writes it.',
  },

  // -- Marketplace ---------------------------------------------------------
  {
    key: 'requestsCreated', dashboard: 'marketplace', name: 'Requests created',
    businessQuestion: 'How much demand entered the marketplace in the period?',
    sources: ['public.marketplace_requests'],
    numerator: 'Count of marketplace requests created in the period.',
    denominator: 'Used as the denominator for every other marketplace rate on this dashboard.',
    inclusion: 'Every request row regardless of flow kind or outcome.',
    exclusion: 'Nothing is excluded; drafts are counted because they represent attempted demand.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: `The denominator for this whole dashboard, so read every rate against it. ${cairo}`,
  },
  {
    key: 'requestsWithQuotes', dashboard: 'marketplace', name: 'Requests receiving quotes',
    businessQuestion: 'How often does a customer get a real choice?',
    sources: ['public.marketplace_requests', 'public.worker_quotes'],
    numerator: 'Requests created in the period with at least one quote.',
    denominator: 'Requests created in the period.',
    inclusion: 'Any quote, including later withdrawn or expired ones.',
    exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: `A quote is not a useful quote; use the median quote count alongside it. ${cairo}`,
  },
  {
    key: 'requestsExpired', dashboard: 'marketplace', name: 'Requests expired',
    businessQuestion: 'How often does demand time out unserved?',
    sources: ['public.marketplace_requests'],
    numerator: 'Requests created in the period whose current status is expired.',
    denominator: 'Requests created in the period.',
    inclusion: 'Current status.', exclusion: 'Cancelled requests are counted separately.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: `Recent periods under-report because requests are still open. ${cairo}`,
  },
  {
    key: 'requestsCancelled', dashboard: 'marketplace', name: 'Requests cancelled',
    businessQuestion: 'How often does a customer withdraw demand?',
    sources: ['public.marketplace_requests'],
    numerator: 'Requests created in the period with current status cancelled.',
    denominator: 'Requests created in the period.',
    inclusion: 'Customer and system cancellations alike.', exclusion: 'Expired requests.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Cancellation reason is not modelled here.',
  },
  {
    key: 'requestsConverted', dashboard: 'marketplace', name: 'Requests converted to bookings',
    businessQuestion: 'How much demand becomes an agreement?',
    sources: ['public.marketplace_requests'],
    numerator: 'Requests created in the period now in converted_to_booking status.',
    denominator: 'Requests created in the period.',
    inclusion: 'Current status.', exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: `Conversion lags creation, so the newest days always look worse. ${cairo}`,
  },
  {
    key: 'noProviderOutcomes', dashboard: 'marketplace', name: 'No-provider outcomes',
    businessQuestion: 'How often does matching find nobody to invite?',
    sources: ['public.marketplace_requests', 'public.quote_invitations'],
    numerator: 'Requests created in the period with zero invitations.',
    denominator: 'Requests created in the period.',
    inclusion: 'All flow kinds.',
    exclusion: 'Requests that were invited but received no quote — that is a different failure.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Counts a coverage gap, not a ranking failure.',
  },
  {
    key: 'emergencyRequests', dashboard: 'marketplace', name: 'Emergency requests',
    businessQuestion: 'How often is the Emergency flow used?',
    sources: ['public.marketplace_requests'],
    numerator: 'Requests created in the period with flow kind emergency.', denominator: null,
    inclusion: 'All emergency requests.', exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Misuse detection is a WPS-016 concern and is not inferred here.',
  },
  {
    key: 'rescueRequests', dashboard: 'marketplace', name: 'Rescue Mode requests',
    businessQuestion: 'How often does a booking need rescuing?',
    sources: ['public.marketplace_requests'],
    numerator: 'Requests created in the period with flow kind rescue.', denominator: null,
    inclusion: 'All rescue requests.', exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'A rescue can itself be rescued; the chain is not collapsed.',
  },
  {
    key: 'medianQuotesPerRequest', dashboard: 'marketplace', name: 'Median quotes per request',
    businessQuestion: 'Does a typical customer get enough choice?',
    sources: ['public.marketplace_requests', 'public.worker_quotes'],
    numerator: 'Median of the per-request quote count.',
    denominator: 'Requests created in the period.',
    inclusion: 'Requests with zero quotes are included as zero.',
    exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Median hides the tail; pair with the no-provider rate.',
  },
  {
    key: 'medianSecondsToFirstQuote', dashboard: 'marketplace', name: 'Median time to first quote',
    businessQuestion: 'How fast does a customer see a first price?',
    sources: ['public.marketplace_requests', 'public.worker_quotes'],
    numerator: 'Median seconds between request creation and the earliest quote submission.',
    denominator: 'Requests created in the period that received at least one quote.',
    inclusion: 'Only requests with a quote.',
    exclusion: 'Requests with no quote are excluded rather than counted as infinite.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Survivorship bias: slow requests that never received a quote are absent.',
  },

  // -- Bookings ------------------------------------------------------------
  {
    key: 'bookingsCreated', dashboard: 'bookings', name: 'Bookings created',
    businessQuestion: 'How many agreements were formed in the period?',
    sources: ['public.bookings'],
    numerator: 'Count of bookings created in the period.',
    denominator: 'Used as the denominator for every other booking rate on this dashboard.',
    inclusion: 'All bookings including direct bookings and marketplace conversions.',
    exclusion: 'Soft-deleted bookings are still counted; deletion does not undo history.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: `The denominator for this whole dashboard. Creation is not confirmation. ${cairo}`,
  },
  {
    key: 'confirmed', dashboard: 'bookings', name: 'Confirmed bookings',
    businessQuestion: 'How many bookings moved past the draft or refused stage?',
    sources: ['public.bookings'],
    numerator: 'Bookings created in the period not in draft, cancelled, or rejected status.',
    denominator: 'Bookings created in the period.',
    inclusion: 'Current status.', exclusion: 'Draft, cancelled, rejected.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Confirmation is inferred from the current status, not from a confirmation event.',
  },
  {
    key: 'completed', dashboard: 'bookings', name: 'Completed bookings',
    businessQuestion: 'How much work finished?',
    sources: ['public.bookings'],
    numerator: 'Bookings created in the period with completed status.',
    denominator: 'Bookings created in the period.',
    inclusion: 'Current status.', exclusion: 'Everything else.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: `Lags creation. ${cairo}`,
  },
  {
    key: 'cancelled', dashboard: 'bookings', name: 'Cancelled bookings',
    businessQuestion: 'How often does an agreement fall through?',
    sources: ['public.bookings'],
    numerator: 'Bookings created in the period with cancelled status.',
    denominator: 'Bookings created in the period.',
    inclusion: 'Customer, worker, and system cancellations alike.',
    exclusion: 'No-shows, which are counted separately.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Blame is not attributed here; WPS-008 holds cancellation events with actor detail.',
  },
  {
    key: 'noShow', dashboard: 'bookings', name: 'No-show bookings',
    businessQuestion: 'How often does someone not turn up?',
    sources: ['public.bookings'],
    numerator: 'Bookings created in the period with no_show status.',
    denominator: 'Bookings created in the period.',
    inclusion: 'Both customer and worker no-shows.',
    exclusion: 'Cancellations before the appointment.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'The booking status does not say who failed to arrive.',
  },
  {
    key: 'disputed', dashboard: 'bookings', name: 'Disputed bookings',
    businessQuestion: 'How often does a booking end in conflict?',
    sources: ['public.bookings'],
    numerator: 'Bookings created in the period with disputed status.',
    denominator: 'Bookings created in the period.',
    inclusion: 'Current status.', exclusion: 'Disputes that were withdrawn before submission.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'A booking may leave disputed status after resolution, so this understates history.',
  },
  {
    key: 'cancellationRate', dashboard: 'bookings', name: 'Cancellation rate',
    businessQuestion: 'What share of bookings is cancelled?',
    sources: ['public.bookings'],
    numerator: 'Cancelled bookings created in the period.',
    denominator: 'Bookings created in the period.',
    inclusion: 'As for the two component metrics.',
    exclusion: 'Returns null when the denominator is zero rather than reporting 0%.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'A rate over a short window is noisy; read it with the absolute counts.',
  },
  {
    key: 'returnVisits', dashboard: 'bookings', name: 'Return visits',
    businessQuestion: 'How often does a worker have to come back?',
    sources: ['public.booking_return_visits'],
    numerator: 'Return visits requested in the period.', denominator: null,
    inclusion: 'All requested return visits including declined ones.',
    exclusion: 'None.',
    timeBasis: 'request_time', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'A return visit can be a warranty comeback or an agreed second section; the two are not split here.',
  },
  {
    key: 'additionalWorkRequests', dashboard: 'bookings', name: 'Additional-work requests',
    businessQuestion: 'How often does scope grow after work starts?',
    sources: ['public.booking_additional_work_requests'],
    numerator: 'Additional-work requests created in the period.', denominator: null,
    inclusion: 'Approved, rejected, and pending requests.',
    exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Frequency alone does not indicate abuse; WPS-007 holds approval outcomes.',
  },

  // -- Workers -------------------------------------------------------------
  {
    key: 'totalWorkers', dashboard: 'workers', name: 'Total workers',
    businessQuestion: 'How large is the worker base?',
    sources: ['public.provider_profiles'],
    numerator: 'Worker profiles with no deletion timestamp.', denominator: null,
    inclusion: 'Every non-deleted profile at any onboarding stage.',
    exclusion: 'Deleted profiles.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Includes profiles that never completed onboarding.',
  },
  {
    key: 'verifiedWorkers', dashboard: 'workers', name: 'Verified workers',
    businessQuestion: 'How much of the base passed identity verification?',
    sources: ['public.provider_profiles'],
    numerator: 'Worker profiles with is_verified true.',
    denominator: 'Worker profiles with no deletion timestamp.',
    inclusion: 'Current state.', exclusion: 'Deleted profiles.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Verification can expire; the flag reflects the last decision, not the expiry.',
  },
  {
    key: 'publishedWorkers', dashboard: 'workers', name: 'Published workers',
    businessQuestion: 'How many worker profiles are publicly visible?',
    sources: ['public.provider_profiles'],
    numerator: 'Worker profiles with is_published true.',
    denominator: 'Worker profiles with no deletion timestamp.',
    inclusion: 'Current state.', exclusion: 'Deleted profiles.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Published is a profile flag; WPS-008 discoverability applies further hard gates.',
  },
  {
    key: 'availableWorkers', dashboard: 'workers', name: 'Available workers',
    businessQuestion: 'How much supply is switched on right now?',
    sources: ['public.provider_profiles'],
    numerator: 'Worker profiles with is_available true.',
    denominator: 'Worker profiles with no deletion timestamp.',
    inclusion: 'Current state.', exclusion: 'Deleted profiles.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Availability is the single worker control; it says nothing about capacity.',
  },
  {
    key: 'approvedOnboarding', dashboard: 'workers', name: 'Approved onboarding',
    businessQuestion: 'How many workers completed onboarding?',
    sources: ['public.provider_profiles'],
    numerator: 'Worker profiles with onboarding_status approved.',
    denominator: 'Worker profiles with no deletion timestamp.',
    inclusion: 'Current state.', exclusion: 'Deleted profiles.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'The funnel stages before approval are not broken out here.',
  },
  {
    key: 'averageRating', dashboard: 'workers', name: 'Average worker rating',
    businessQuestion: 'What is the typical quality signal across reviewed workers?',
    sources: ['public.provider_profiles'],
    numerator: 'Mean rating average across workers with at least one review.',
    denominator: 'Workers with at least one review.',
    inclusion: 'Only reviewed workers.',
    exclusion: 'Unreviewed workers, which would otherwise drag the mean to zero.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'An unweighted mean of means; a worker with one review counts as much as one with fifty.',
  },
  {
    key: 'categoryCoverage', dashboard: 'workers', name: 'Category coverage',
    businessQuestion: 'How many service categories have visible supply?',
    sources: ['public.provider_profiles'],
    numerator: 'Distinct primary categories among published, non-deleted workers.', denominator: null,
    inclusion: 'Published workers only.',
    exclusion: 'Suppressed when the distinct count falls below the configured minimum cell.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'aggregate_suppressed',
    limitations: 'Primary category only; secondary categories are not counted.',
  },

  // -- Customers -----------------------------------------------------------
  {
    key: 'activeCustomers', dashboard: 'customers', name: 'Active customers',
    businessQuestion: 'How many distinct customers booked in the period?',
    sources: ['public.bookings'],
    numerator: 'Distinct customer ids on bookings created in the period.', denominator: null,
    inclusion: 'All booking statuses.',
    exclusion: 'Suppressed below the configured minimum cell so a tiny cohort cannot identify a person.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate_suppressed',
    limitations: 'A suppressed value renders as hidden, never as zero.',
  },
  {
    key: 'requestingCustomers', dashboard: 'customers', name: 'Requesting customers',
    businessQuestion: 'How many distinct customers asked for quotes?',
    sources: ['public.marketplace_requests'],
    numerator: 'Distinct customer ids on requests created in the period.', denominator: null,
    inclusion: 'All flow kinds.', exclusion: 'Suppressed below the minimum cell.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate_suppressed',
    limitations: 'Overlaps with active customers; the two are not mutually exclusive.',
  },
  {
    key: 'repeatCustomers', dashboard: 'customers', name: 'Repeat customers',
    businessQuestion: 'How many customers booked more than once in the period?',
    sources: ['public.bookings'],
    numerator: 'Customers with more than one booking created in the period.', denominator: null,
    inclusion: 'All booking statuses.', exclusion: 'Suppressed below the minimum cell.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate_suppressed',
    limitations: 'Window-bounded: a customer who returns after the window is not counted.',
  },
  {
    key: 'cashSelections', dashboard: 'customers', name: 'Cash selections',
    businessQuestion: 'How often is cash chosen?',
    sources: ['public.financial_booking_payments'],
    numerator: 'Payment records created in the period with method cash.', denominator: null,
    inclusion: 'All payment statuses.', exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Reflects the selected method, not a settled payment.',
  },
  {
    key: 'onlineSelections', dashboard: 'customers', name: 'Online selections',
    businessQuestion: 'How often is an online method chosen?',
    sources: ['public.financial_booking_payments'],
    numerator: 'Payment records created in the period with method online.', denominator: null,
    inclusion: 'All payment statuses.', exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Online payments remain disabled outside mock mode, so this is near zero by design.',
  },

  // -- Financial (ledger capability required) ------------------------------
  {
    key: 'grossBookingValueMinor', dashboard: 'financial', name: 'Gross booking value',
    businessQuestion: 'How much value passed through the platform?',
    sources: ['public.provider_earnings_ledger'],
    numerator: 'Sum of gross minor units on earnings rows created in the period.', denominator: null,
    inclusion: 'All earning statuses.', exclusion: 'Nothing; reversals appear as their own rows.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'financial_restricted',
    limitations: 'Derived from the WPS-007 ledger projection, never recomputed here.',
  },
  {
    key: 'commissionMinor', dashboard: 'financial', name: 'Warsha commission',
    businessQuestion: 'What did Warsha earn?',
    sources: ['public.provider_earnings_ledger'],
    numerator: 'Sum of commission minor units on earnings rows created in the period.', denominator: null,
    inclusion: 'All earning statuses.', exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'financial_restricted',
    limitations: 'Commission recorded at posting time; later reversals are separate rows.',
  },
  {
    key: 'pendingEarningsMinor', dashboard: 'financial', name: 'Pending earnings',
    businessQuestion: 'How much worker money is not yet releasable?',
    sources: ['public.provider_earnings_ledger'],
    numerator: 'Sum of net minor units in pending_job_completion or pending_release status.',
    denominator: null,
    inclusion: 'Current state, ignoring the reporting period.', exclusion: 'None.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'financial_restricted',
    limitations: 'A balance, not a flow. Do not add it to period totals.',
  },
  {
    key: 'availableEarningsMinor', dashboard: 'financial', name: 'Available earnings',
    businessQuestion: 'How much worker money can be withdrawn now?',
    sources: ['public.provider_earnings_ledger'],
    numerator: 'Sum of net minor units in available status.', denominator: null,
    inclusion: 'Current state.', exclusion: 'None.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'financial_restricted',
    limitations: 'A balance, not a flow.',
  },
  {
    key: 'paidEarningsMinor', dashboard: 'financial', name: 'Paid earnings',
    businessQuestion: 'How much has actually left the platform to workers?',
    sources: ['public.provider_earnings_ledger'],
    numerator: 'Sum of net minor units in paid_out status.', denominator: null,
    inclusion: 'Current state.', exclusion: 'None.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'financial_restricted',
    limitations: 'Payouts are disabled, so this stays zero until a payout provider is authorized.',
  },
  {
    key: 'withdrawalsRequested', dashboard: 'financial', name: 'Withdrawals requested',
    businessQuestion: 'How much withdrawal demand is there?',
    sources: ['public.provider_withdrawal_requests'],
    numerator: 'Withdrawal requests created in the period.', denominator: null,
    inclusion: 'All statuses.', exclusion: 'None.',
    timeBasis: 'request_time', updateFrequency: onRead, privacy: 'financial_restricted',
    limitations: 'Counts requests, not amounts.',
  },
  {
    key: 'refunds', dashboard: 'financial', name: 'Refunds',
    businessQuestion: 'How often is money returned?',
    sources: ['public.financial_refunds'],
    numerator: 'Refund records created in the period.', denominator: null,
    inclusion: 'All statuses.', exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'financial_restricted',
    limitations: 'Counts refund records, not net refunded value.',
  },
  {
    key: 'refundsFailed', dashboard: 'financial', name: 'Failed refunds',
    businessQuestion: 'How much refund work is stuck?',
    sources: ['public.financial_refunds'],
    numerator: 'Refund records created in the period with failed status.',
    denominator: 'Refund records created in the period.',
    inclusion: 'Current status.', exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'financial_restricted',
    limitations: 'A failed refund is an operational queue, not an accounting balance.',
  },
  {
    key: 'chargebacks', dashboard: 'financial', name: 'Chargebacks',
    businessQuestion: 'How much provider-side dispute pressure is there?',
    sources: ['private.payment_chargebacks'],
    numerator: 'Chargebacks opened in the period.', denominator: null,
    inclusion: 'All statuses.', exclusion: 'None.',
    timeBasis: 'event_time', updateFrequency: onRead, privacy: 'financial_restricted',
    limitations: 'A chargeback is a payment-provider dispute, never a WPS-013 service dispute.',
  },
  {
    key: 'reconciliationExceptions', dashboard: 'financial', name: 'Reconciliation exceptions',
    businessQuestion: 'How much money does not reconcile?',
    sources: ['private.reconciliation_exceptions'],
    numerator: 'Exceptions created in the period.', denominator: null,
    inclusion: 'All severities and statuses.', exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'financial_restricted',
    limitations: 'Reconciliation only runs when a provider is configured; this is zero while disabled.',
  },
  {
    key: 'openCashCommissionDebtRecords', dashboard: 'financial', name: 'Cash commission debt records',
    businessQuestion: 'How much cash commission was recorded in the period?',
    sources: ['public.provider_cash_commission_records'],
    numerator: 'Cash commission records created in the period.', denominator: null,
    inclusion: 'All records.', exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'financial_restricted',
    limitations: 'A record count, not an outstanding balance.',
  },

  // -- Trust and quality ---------------------------------------------------
  {
    key: 'reportsSubmitted', dashboard: 'trust', name: 'Reports submitted',
    businessQuestion: 'How much abuse is being reported?',
    sources: ['public.trust_reports'],
    numerator: 'Reports created in the period.', denominator: null,
    inclusion: 'All categories and surfaces.', exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Reporter identity is never exposed. Report volume reflects reporting culture as much as abuse.',
  },
  {
    key: 'reportsActioned', dashboard: 'trust', name: 'Reports actioned',
    businessQuestion: 'How often does a report lead to action?',
    sources: ['public.trust_reports'],
    numerator: 'Reports created in the period with actioned status.',
    denominator: 'Reports created in the period.',
    inclusion: 'Current status.', exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Lags creation; recent periods look lower.',
  },
  {
    key: 'reportsDismissed', dashboard: 'trust', name: 'Reports dismissed',
    businessQuestion: 'How often is a report closed with no action?',
    sources: ['public.trust_reports'],
    numerator: 'Reports created in the period with dismissed status.',
    denominator: 'Reports created in the period.',
    inclusion: 'Current status.', exclusion: 'Duplicates, counted separately by WPS-016.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Dismissal is not proof the report was false.',
  },
  {
    key: 'enforcementActions', dashboard: 'trust', name: 'Enforcement actions',
    businessQuestion: 'How much enforcement is happening?',
    sources: ['public.trust_enforcement_actions'],
    numerator: 'Enforcement actions created in the period.', denominator: null,
    inclusion: 'All eleven measures plus restoration.', exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Includes non-punitive investigations and restorations.',
  },
  {
    key: 'permanentBans', dashboard: 'trust', name: 'Permanent bans',
    businessQuestion: 'How often is the terminal measure used?',
    sources: ['public.trust_enforcement_actions'],
    numerator: 'Permanent bans created in the period.',
    denominator: 'Enforcement actions created in the period.',
    inclusion: 'All permanent bans.', exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'WPS-016 forbids automatic bans; every one of these had a human actor and an investigated report.',
  },
  {
    key: 'appealsSubmitted', dashboard: 'trust', name: 'Appeals submitted',
    businessQuestion: 'How often do people contest enforcement?',
    sources: ['public.trust_appeals'],
    numerator: 'Appeals created in the period.', denominator: null,
    inclusion: 'All appeal statuses.', exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Appeal content is private to the appellant and staff and never appears in analytics.',
  },
  {
    key: 'appealsOverturned', dashboard: 'trust', name: 'Appeals overturned',
    businessQuestion: 'How often was an enforcement decision wrong?',
    sources: ['public.trust_appeals'],
    numerator: 'Appeals created in the period with overturned or partially overturned status.',
    denominator: 'Appeals created in the period.',
    inclusion: 'Full and partial overturns.', exclusion: 'Withdrawn appeals.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'The single most important quality signal for the trust team; read it as a rate, not a count.',
  },
  {
    key: 'disputesOpened', dashboard: 'trust', name: 'Disputes opened',
    businessQuestion: 'How much service conflict entered the system?',
    sources: ['public.disputes'],
    numerator: 'Disputes created in the period.', denominator: null,
    inclusion: 'All reasons.', exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Includes drafts that were never submitted.',
  },
  {
    key: 'disputesResolved', dashboard: 'trust', name: 'Disputes resolved',
    businessQuestion: 'How much conflict was closed out?',
    sources: ['public.disputes'],
    numerator: 'Disputes created in the period now resolved or closed.',
    denominator: 'Disputes created in the period.',
    inclusion: 'Current status.', exclusion: 'Rejected and cancelled disputes.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: `Lags creation. ${cairo}`,
  },
  {
    key: 'reviewReports', dashboard: 'trust', name: 'Review reports',
    businessQuestion: 'How often is review content reported?',
    sources: ['public.review_reports'],
    numerator: 'Review reports created in the period.', denominator: null,
    inclusion: 'All four reasons.', exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'WPS-011 remains the review moderation authority; this only counts.',
  },
  {
    key: 'reviewModerationActions', dashboard: 'trust', name: 'Review moderation actions',
    businessQuestion: 'How much review content was acted on?',
    sources: ['public.review_moderation_events'],
    numerator: 'Moderation events created in the period.', denominator: null,
    inclusion: 'Hides and restores alike.', exclusion: 'None.',
    timeBasis: 'event_time', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Moderation is a soft hide; evidence is never destroyed.',
  },
  {
    key: 'reviewsPublished', dashboard: 'trust', name: 'Reviews published',
    businessQuestion: 'How much feedback is customers giving?',
    sources: ['public.reviews'],
    numerator: 'Reviews created in the period that are not soft-hidden.', denominator: null,
    inclusion: 'All ratings.', exclusion: 'Soft-hidden reviews.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'A review held by a dispute is still counted as published if it is not hidden.',
  },

  // -- Verification --------------------------------------------------------
  {
    key: 'submitted', dashboard: 'verification', name: 'Verifications submitted',
    businessQuestion: 'How much verification work arrived?',
    sources: ['public.provider_verifications'],
    numerator: 'Verifications whose submission timestamp falls in the period.', denominator: null,
    inclusion: 'Only submitted records.', exclusion: 'Drafts and not-started records.',
    timeBasis: 'submission_time', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'One row per worker: a resubmission overwrites the submission timestamp.',
  },
  {
    key: 'approved', dashboard: 'verification', name: 'Verifications approved',
    businessQuestion: 'How many workers are currently approved?',
    sources: ['public.provider_verifications'],
    numerator: 'Verifications currently in approved status.',
    denominator: 'All verification records.',
    inclusion: 'Current state, not period-bounded.', exclusion: 'None.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'A current-state count sitting next to period counts; do not compute a rate across the two.',
  },
  {
    key: 'rejected', dashboard: 'verification', name: 'Verifications rejected',
    businessQuestion: 'How many workers are currently rejected?',
    sources: ['public.provider_verifications'],
    numerator: 'Verifications currently in rejected status.',
    denominator: 'All verification records.',
    inclusion: 'Current state.', exclusion: 'None.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Rejection reasons are private to the worker and the reviewer.',
  },
  {
    key: 'awaitingReview', dashboard: 'verification', name: 'Awaiting review',
    businessQuestion: 'How big is the verification backlog?',
    sources: ['public.provider_verifications'],
    numerator: 'Verifications in submitted or under_review status.', denominator: null,
    inclusion: 'Current state.', exclusion: 'None.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Matches the identity verification queue exactly.',
  },
  {
    key: 'requiresResubmission', dashboard: 'verification', name: 'Correction requested',
    businessQuestion: 'How many workers were asked to fix something?',
    sources: ['public.provider_verifications'],
    numerator: 'Verifications in requires_resubmission status.', denominator: null,
    inclusion: 'Current state.', exclusion: 'None.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'A high value can indicate unclear guidance rather than poor submissions.',
  },
  {
    key: 'expired', dashboard: 'verification', name: 'Verifications expired',
    businessQuestion: 'How many verifications lapsed?',
    sources: ['public.provider_verifications'],
    numerator: 'Verifications in expired status.', denominator: null,
    inclusion: 'Current state.', exclusion: 'None.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Expiry is a WPS-006 concern; WPS-017 only reports it.',
  },
  {
    key: 'certificatesSubmitted', dashboard: 'verification', name: 'Certificates submitted',
    businessQuestion: 'How much certificate review work arrived?',
    sources: ['public.provider_certifications'],
    numerator: 'Certificates whose submission timestamp falls in the period.', denominator: null,
    inclusion: 'All certificate types.', exclusion: 'Drafts.',
    timeBasis: 'submission_time', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'The criminal-record certificate is not part of Warsha and never appears here.',
  },
  {
    key: 'certificatesApproved', dashboard: 'verification', name: 'Certificates approved',
    businessQuestion: 'How many certificates are currently approved?',
    sources: ['public.provider_certifications'],
    numerator: 'Certificates in approved status with no deletion timestamp.', denominator: null,
    inclusion: 'Current state.', exclusion: 'Deleted certificates.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Approval does not imply the certificate is publicly shown.',
  },

  // -- Notification health -------------------------------------------------
  {
    key: 'notificationsCreated', dashboard: 'notifications', name: 'Notifications created',
    businessQuestion: 'How much is Warsha telling people?',
    sources: ['public.notifications'],
    numerator: 'Notifications created in the period.', denominator: null,
    inclusion: 'Every audience including staff.', exclusion: 'Deduplicated and grouped events, which never become rows.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Grouping means one row can represent several events.',
  },
  {
    key: 'unread', dashboard: 'notifications', name: 'Unread notifications',
    businessQuestion: 'Is the inbox being read?',
    sources: ['public.notifications'],
    numerator: 'Notifications created in the period with no read timestamp.',
    denominator: 'Notifications created in the period.',
    inclusion: 'All audiences.', exclusion: 'None.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Recent periods always look unread; read it as a trend.',
  },
  {
    key: 'requiredActionOpen', dashboard: 'notifications', name: 'Open required actions',
    businessQuestion: 'How much action is outstanding?',
    sources: ['public.notifications'],
    numerator: 'Notifications requiring action with no resolution timestamp.', denominator: null,
    inclusion: 'Period-bounded by creation.', exclusion: 'Resolved actions.',
    timeBasis: 'record_creation', updateFrequency: onRead, privacy: 'aggregate',
    limitations: 'Resolution is inferred from the underlying record, not from the user tapping.',
  },
  {
    key: 'deliveryFailures', dashboard: 'notifications', name: 'Delivery failures',
    businessQuestion: 'Is external delivery working?',
    sources: ['private.notification_delivery_attempts'],
    numerator: 'Delivery attempts in the period with failed status.', denominator: null,
    inclusion: 'Push attempts only.', exclusion: 'None.',
    timeBasis: 'event_time', updateFrequency: onRead, privacy: 'operational_state',
    limitations: 'Push is disabled, so this is zero by design until a provider is authorized.',
  },
  {
    key: 'pushDeliveryEnabled', dashboard: 'notifications', name: 'Push delivery enabled',
    businessQuestion: 'Is push turned on?',
    sources: ['private.notification_configuration'],
    numerator: 'The WPS-014 push delivery flag.', denominator: null,
    inclusion: 'Current configuration.', exclusion: 'None.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'operational_state',
    limitations: 'WPS-014 constrains this flag to false; WPS-017 reads it and never writes it.',
  },
  {
    key: 'schedulerEnabled', dashboard: 'notifications', name: 'Reminder scheduler enabled',
    businessQuestion: 'Are reminders being processed?',
    sources: ['private.notification_configuration'],
    numerator: 'The WPS-014 scheduler flag.', denominator: null,
    inclusion: 'Current configuration.', exclusion: 'None.',
    timeBasis: 'current_state', updateFrequency: onRead, privacy: 'operational_state',
    limitations: 'Constrained to false by WPS-014.',
  },
] as const;

const catalogIndex = new Map(metricCatalog.map(metric => [`${metric.dashboard}:${metric.key}`, metric]));

export function findMetric(dashboard: StaffDashboard, key: string): MetricDefinition | undefined {
  return catalogIndex.get(`${dashboard}:${key}`);
}

export function metricsForDashboard(dashboard: StaffDashboard): MetricDefinition[] {
  return metricCatalog.filter(metric => metric.dashboard === dashboard);
}

/**
 * Guard used by the dashboards and by the regression suite: a metric key that
 * is not catalogued must never be rendered as a business number.
 */
export function isDocumentedMetric(dashboard: StaffDashboard, key: string): boolean {
  return catalogIndex.has(`${dashboard}:${key}`);
}
