/**
 * WPS-021 bilingual copy.
 *
 * Import-free so the regression suite can execute it under Node and assert that
 * every key exists in both languages.
 *
 * Two rules shape every reward string below.
 *
 *   1. A reward is EARNED and READY. Nothing here says "pending approval",
 *      "waiting for a campaign", or "eligible for a future offer" — because
 *      none of those is true. Staff approved the programme in advance; the
 *      reward is granted automatically and is usable immediately.
 *   2. A reward is not money. It is a discount on a future eligible booking,
 *      and the copy says so plainly rather than implying a balance.
 */

export type GrowthLanguage = 'en' | 'ar';

export const growthCopy = {
  en: {
    referralTitle: 'Invite to Warsha',
    referralSubtitle: 'Share your code. Your reward arrives when the work is done.',
    referralCodeLabel: 'Your invite code',
    referralCodeHint: 'Read this code out or share the link.',
    shareInvite: 'Share invite',
    shareMessage: 'Get your work done safely on Warsha. Use my invite code:',
    howItWorksTitle: 'How it works',
    howItWorksOne: 'Share your code with someone who needs work done.',
    howItWorksTwo: 'They join Warsha and book a worker.',
    howItWorksThree: 'Your reward arrives automatically once their first job is finished.',
    noRewardForSignup: 'Signing up alone does not earn a reward.',
    automaticNotice: 'Rewards are automatic. Nobody has to approve them.',
    statusTitle: 'Your invites',
    statusPending: 'Waiting on first job',
    statusQualified: 'Confirmed',
    statusExpired: 'Expired',
    rewardsTitle: 'Your rewards',
    rewardAvailable: 'Ready to use',
    rewardConsumed: 'Used',
    rewardExpired: 'Expired',
    rewardRevoked: 'Not valid',
    rewardsEmpty: 'No rewards yet.',
    rewardExplainer: 'A reward is a discount Warsha pays for on your next eligible booking.',
    rewardExpiresIn: 'Expires in',
    rewardExpiresToday: 'Expires today',
    rewardDays: 'days',
    rewardWorth: 'Worth up to',
    rewardConditions: 'Use it on your next eligible booking.',
    rewardMinimum: 'Minimum booking',
    enterCodeTitle: 'Have an invite code?',
    enterCodePlaceholder: 'Enter invite code',
    enterCodeAction: 'Apply invite code',
    claimAccepted: 'Invite code applied.',
    claimInvalid: 'That invite code is not valid.',
    claimSelf: 'You cannot use your own invite code.',
    claimAlready: 'An invite code was already applied to this account.',
    claimUnavailable: 'Invites are not available right now.',
    unavailableTitle: 'Invites are not available yet',
    unavailableBody: 'This will open soon. Nothing is needed from you now.',
    benefitRewardTitle: 'Your referral reward',
    benefitCampaignTitle: 'Warsha offer',
    benefitApplied: 'Applied',
    benefitApply: 'Use it',
    benefitSaves: 'You save',
    benefitEnds: 'Ends',
    benefitFunded: 'Paid by Warsha. Your worker is paid in full.',
    benefitUnavailable: 'This is no longer available.',
    benefitOnePerBooking: 'One reward or offer per booking.',
    currency: 'EGP',
    campaignsTitle: 'Promotion campaigns',
    programsTitle: 'Referral programmes',
    programsSubtitle: 'Approve the programme once. Rewards are then automatic.',
    statusDraft: 'Draft',
    statusScheduled: 'Scheduled',
    statusActive: 'Active',
    statusPaused: 'Paused',
    statusExpiredLifecycle: 'Expired',
    statusCancelled: 'Cancelled',
    budgetUsed: 'Budget used',
    redemptions: 'Redemptions',
    rewardsGranted: 'Rewards granted',
    activate: 'Activate',
    pause: 'Pause',
    resume: 'Resume',
    cancel: 'Cancel',
    campaignsEmpty: 'No campaigns exist.',
    programsEmpty: 'No referral programmes exist.',
    needsApproval: 'Needs a second approver',
    immutableNotice: 'Once approved this cannot be edited. Create a new version.',
  },
  ar: {
    referralTitle: 'ادعُ أصحابك لورشة',
    referralSubtitle: 'شارك كودك. مكافأتك بتوصل لما الشغل يخلص.',
    referralCodeLabel: 'كود الدعوة بتاعك',
    referralCodeHint: 'اقرا الكود ده أو شارك اللينك.',
    shareInvite: 'شارك الدعوة',
    shareMessage: 'خلّص شغلك بأمان على ورشة. استخدم كود الدعوة بتاعي:',
    howItWorksTitle: 'بيشتغل إزاي',
    howItWorksOne: 'شارك كودك مع حد محتاج يخلص شغل.',
    howItWorksTwo: 'يسجل في ورشة ويحجز صنايعي.',
    howItWorksThree: 'مكافأتك بتوصل أوتوماتيك أول ما أول شغلانة ليه تخلص.',
    noRewardForSignup: 'التسجيل لوحده مش بيكسّب مكافأة.',
    automaticNotice: 'المكافآت أوتوماتيك. محدش محتاج يوافق عليها.',
    statusTitle: 'دعواتك',
    statusPending: 'مستني أول شغلانة',
    statusQualified: 'مأكدة',
    statusExpired: 'انتهت',
    rewardsTitle: 'مكافآتك',
    rewardAvailable: 'جاهزة للاستخدام',
    rewardConsumed: 'اتستخدمت',
    rewardExpired: 'انتهت',
    rewardRevoked: 'مش صالحة',
    rewardsEmpty: 'لسه مفيش مكافآت.',
    rewardExplainer: 'المكافأة خصم ورشة دافعاه على حجزك الجاي المؤهل.',
    rewardExpiresIn: 'تنتهي خلال',
    rewardExpiresToday: 'تنتهي النهارده',
    rewardDays: 'يوم',
    rewardWorth: 'قيمتها لحد',
    rewardConditions: 'استخدمها في حجزك الجاي المؤهل.',
    rewardMinimum: 'أقل قيمة حجز',
    enterCodeTitle: 'عندك كود دعوة؟',
    enterCodePlaceholder: 'اكتب كود الدعوة',
    enterCodeAction: 'فعّل كود الدعوة',
    claimAccepted: 'تم تفعيل كود الدعوة.',
    claimInvalid: 'كود الدعوة ده مش صحيح.',
    claimSelf: 'مينفعش تستخدم كود الدعوة بتاعك.',
    claimAlready: 'فيه كود دعوة اتفعل على الحساب ده قبل كده.',
    claimUnavailable: 'الدعوات مش متاحة دلوقتي.',
    unavailableTitle: 'الدعوات لسه مش متاحة',
    unavailableBody: 'هتفتح قريب. مش مطلوب منك حاجة دلوقتي.',
    benefitRewardTitle: 'مكافأة الدعوة بتاعتك',
    benefitCampaignTitle: 'عرض ورشة',
    benefitApplied: 'اتطبق',
    benefitApply: 'استخدمها',
    benefitSaves: 'هتوفر',
    benefitEnds: 'ينتهي',
    benefitFunded: 'ورشة هي اللي دافعة. الصنايعي بياخد حقه كامل.',
    benefitUnavailable: 'ده مبقاش متاح.',
    benefitOnePerBooking: 'مكافأة أو عرض واحد بس لكل حجز.',
    currency: 'جنيه',
    campaignsTitle: 'حملات العروض',
    programsTitle: 'برامج الدعوات',
    programsSubtitle: 'وافق على البرنامج مرة واحدة. بعد كده المكافآت أوتوماتيك.',
    statusDraft: 'مسودة',
    statusScheduled: 'مجدولة',
    statusActive: 'شغالة',
    statusPaused: 'متوقفة مؤقتًا',
    statusExpiredLifecycle: 'منتهية',
    statusCancelled: 'ملغية',
    budgetUsed: 'الميزانية المستخدمة',
    redemptions: 'مرات الاستخدام',
    rewardsGranted: 'المكافآت الممنوحة',
    activate: 'تفعيل',
    pause: 'إيقاف مؤقت',
    resume: 'استئناف',
    cancel: 'إلغاء',
    campaignsEmpty: 'مفيش حملات.',
    programsEmpty: 'مفيش برامج دعوات.',
    needsApproval: 'محتاجة موافقة تانية',
    immutableNotice: 'بعد الموافقة مينفعش التعديل. اعمل نسخة جديدة.',
  },
} as const;

export type GrowthCopyKey = keyof (typeof growthCopy)['en'];

export function growthText(language: GrowthLanguage, key: GrowthCopyKey): string {
  return growthCopy[language][key];
}
