/**
 * WPS-021 bilingual copy.
 *
 * Import-free so the regression suite can execute it under Node and assert that
 * every key exists in both languages. The Arabic is Egyptian, matching the rest
 * of Warsha, and no string promises money: an entitlement is described as
 * earned, never as a balance, because Warsha owes nothing it has not approved.
 */

export type GrowthLanguage = 'en' | 'ar';

export const growthCopy = {
  en: {
    referralTitle: 'Invite to Warsha',
    referralSubtitle: 'Share your code. You earn when the work is done.',
    referralCodeLabel: 'Your invite code',
    referralCodeHint: 'Read this code out or share the link.',
    shareInvite: 'Share invite',
    shareMessage: 'Get your work done safely on Warsha. Use my invite code:',
    howItWorksTitle: 'How it works',
    howItWorksOne: 'Share your code with someone who needs work done.',
    howItWorksTwo: 'They join Warsha and book a worker.',
    howItWorksThree: 'You earn once their first job is finished.',
    noRewardForSignup: 'Signing up alone does not earn a reward.',
    statusTitle: 'Your invites',
    statusPending: 'Waiting on first job',
    statusQualified: 'Confirmed',
    statusExpired: 'Expired',
    rewardsTitle: 'What you have earned',
    rewardRecorded: 'Earned',
    rewardFulfilled: 'Applied',
    rewardVoid: 'Not valid',
    rewardsEmpty: 'Nothing earned yet.',
    rewardExplainer: 'An earned reward is applied to a future booking when it is available.',
    enterCodeTitle: 'Have an invite code?',
    enterCodePlaceholder: 'Enter invite code',
    enterCodeAction: 'Apply invite code',
    claimAccepted: 'Invite code applied.',
    claimInvalid: 'That invite code is not valid.',
    claimSelf: 'You cannot use your own invite code.',
    claimAlready: 'An invite code was already applied to this account.',
    claimUnavailable: 'Invites are not available right now.',
    unavailableTitle: 'Invites are not available yet',
    unavailableBody: 'This will open soon. Nothing is needed from you now.',
    promotionTitle: 'Warsha offer',
    promotionApplied: 'Offer applied',
    promotionApply: 'Apply offer',
    promotionSaves: 'You save',
    promotionEnds: 'Ends',
    promotionFunded: 'Paid by Warsha. Your worker is paid in full.',
    promotionUnavailable: 'This offer is no longer available.',
    currency: 'EGP',
    campaignsTitle: 'Growth campaigns',
    campaignStatusDraft: 'Draft',
    campaignStatusScheduled: 'Scheduled',
    campaignStatusActive: 'Active',
    campaignStatusPaused: 'Paused',
    campaignStatusExpired: 'Expired',
    campaignStatusCancelled: 'Cancelled',
    campaignBudget: 'Budget used',
    campaignRedemptions: 'Redemptions',
    campaignActivate: 'Activate',
    campaignPause: 'Pause',
    campaignResume: 'Resume',
    campaignCancel: 'Cancel',
    campaignsEmpty: 'No campaigns exist.',
    campaignNeedsApproval: 'Needs a second approver',
    campaignImmutable: 'An activated campaign cannot be edited. Create a new version.',
  },
  ar: {
    referralTitle: 'ادعُ أصحابك لورشة',
    referralSubtitle: 'شارك كودك. هتكسب لما الشغل يخلص.',
    referralCodeLabel: 'كود الدعوة بتاعك',
    referralCodeHint: 'اقرا الكود ده أو شارك اللينك.',
    shareInvite: 'شارك الدعوة',
    shareMessage: 'خلّص شغلك بأمان على ورشة. استخدم كود الدعوة بتاعي:',
    howItWorksTitle: 'بيشتغل إزاي',
    howItWorksOne: 'شارك كودك مع حد محتاج يخلص شغل.',
    howItWorksTwo: 'يسجل في ورشة ويحجز صنايعي.',
    howItWorksThree: 'هتكسب أول ما أول شغلانة ليه تخلص.',
    noRewardForSignup: 'التسجيل لوحده مش بيكسّب مكافأة.',
    statusTitle: 'دعواتك',
    statusPending: 'مستني أول شغلانة',
    statusQualified: 'مأكدة',
    statusExpired: 'انتهت',
    rewardsTitle: 'اللي كسبته',
    rewardRecorded: 'مكسوبة',
    rewardFulfilled: 'اتطبقت',
    rewardVoid: 'مش صالحة',
    rewardsEmpty: 'لسه مفيش حاجة مكسوبة.',
    rewardExplainer: 'المكافأة المكسوبة بتتطبق على حجز جاي لما تبقى متاحة.',
    enterCodeTitle: 'عندك كود دعوة؟',
    enterCodePlaceholder: 'اكتب كود الدعوة',
    enterCodeAction: 'فعّل كود الدعوة',
    claimAccepted: 'تم تفعيل كود الدعوة.',
    claimInvalid: 'كود الدعوة ده مش صحيح.',
    claimSelf: 'مينفعش تستخدم كود الدعوة بتاعك.',
    claimAlready: 'فيه كود دعوة اتفعل على الحساب ده قبل كده.',
    claimUnavailable: 'الدعوات مش متاحة دلوقتي.',
    unavailableTitle: 'الدعوات لسه مش متاحة',
    unavailableBody: 'هتفتح قريب. مش مطلوب منك حاجة دلوقتي.',
    promotionTitle: 'عرض ورشة',
    promotionApplied: 'العرض اتطبق',
    promotionApply: 'فعّل العرض',
    promotionSaves: 'هتوفر',
    promotionEnds: 'ينتهي',
    promotionFunded: 'ورشة هي اللي دافعة. الصنايعي بياخد حقه كامل.',
    promotionUnavailable: 'العرض ده مبقاش متاح.',
    currency: 'جنيه',
    campaignsTitle: 'حملات النمو',
    campaignStatusDraft: 'مسودة',
    campaignStatusScheduled: 'مجدولة',
    campaignStatusActive: 'شغالة',
    campaignStatusPaused: 'متوقفة مؤقتًا',
    campaignStatusExpired: 'منتهية',
    campaignStatusCancelled: 'ملغية',
    campaignBudget: 'الميزانية المستخدمة',
    campaignRedemptions: 'مرات الاستخدام',
    campaignActivate: 'تفعيل',
    campaignPause: 'إيقاف مؤقت',
    campaignResume: 'استئناف',
    campaignCancel: 'إلغاء',
    campaignsEmpty: 'مفيش حملات.',
    campaignNeedsApproval: 'محتاجة موافقة تانية',
    campaignImmutable: 'الحملة المفعلة مينفعش تتعدل. اعمل نسخة جديدة.',
  },
} as const;

export type GrowthCopyKey = keyof (typeof growthCopy)['en'];

export function growthText(language: GrowthLanguage, key: GrowthCopyKey): string {
  return growthCopy[language][key];
}
