/**
 * The approved Warsha icon family, as data.
 *
 * GENERATED by `scripts/generate-warsha-icon-geometry.mjs` from the SVG files in
 * `assets/icons/warsha/`. Do not edit by hand — `warsha-icons.test.mts` recompiles
 * the assets and fails if this file disagrees with them.
 *
 * The geometry lives here, once, because native cannot import an SVG file and
 * web can. Keeping a copy on each side is how two platforms end up drawing
 * subtly different marks; `WarshaIcon` on native and `WarshaIcon` on web both
 * render these same elements.
 */

/** One drawn element. `fill: currentColor` marks the single solid accent. */
export type WarshaIconElement = {
  tag: 'path' | 'rect' | 'circle' | 'ellipse';
  d?: string;
  x?: string; y?: string; width?: string; height?: string;
  rx?: string; ry?: string;
  cx?: string; cy?: string; r?: string;
  transform?: string;
  fill?: 'none' | 'currentColor';
  stroke?: 'none';
};

/** Every icon draws on a 24x24 grid with a 1.75 stroke. One family, no variants. */
export const WARSHA_ICON_VIEWBOX = '0 0 24 24' as const;
export const WARSHA_ICON_STROKE_WIDTH = 1.75 as const;

export const warshaIconGeometry = {
  'legacy-general-maintenance': [
    { tag: 'rect', x: '3', y: '8.6', width: '18', height: '11.4', rx: '2.2' },
    { tag: 'path', d: 'M8.6 8.6V6.4a1.8 1.8 0 0 1 1.8-1.8h3.2a1.8 1.8 0 0 1 1.8 1.8v2.2' },
    { tag: 'path', d: 'M3 13.4h18' },
  ],
  'profession-construction-worker': [
    { tag: 'path', d: 'M5 15.2a7 7 0 0 1 14 0' },
    { tag: 'path', d: 'M2.8 15.2h18.4a1.3 1.3 0 0 1 0 2.6H2.8a1.3 1.3 0 0 1 0-2.6z' },
    { tag: 'path', d: 'M12 8.4v6.8' },
  ],
  'profession-flooring-specialist': [
    { tag: 'rect', x: '2.6', y: '5', width: '18.8', height: '4.2', rx: '1.2' },
    { tag: 'rect', x: '2.6', y: '9.9', width: '18.8', height: '4.2', rx: '1.2' },
    { tag: 'rect', x: '2.6', y: '14.8', width: '18.8', height: '4.2', rx: '1.2' },
    { tag: 'path', d: 'M9 9.9v4.2M15.4 14.8v4.2' },
  ],
  'profession-furniture-maker': [
    { tag: 'path', d: 'M3 12.8h18v3.4a2.4 2.4 0 0 1-2.4 2.4H5.4A2.4 2.4 0 0 1 3 16.2z' },
    { tag: 'path', d: 'M9.2 12.8 11.8 8.8' },
    { tag: 'circle', cx: '6.4', cy: '10.2', r: '1.9' },
  ],
  'profession-furniture-repairer': [
    { tag: 'path', d: 'M16.5 4H8.4A4.4 4.4 0 0 0 4 8.4v7.2A4.4 4.4 0 0 0 8.4 20h8.1' },
    { tag: 'path', d: 'M12.4 4v4.2' },
    { tag: 'path', d: 'M10.4 8.2h4' },
    { tag: 'path', d: 'M9.8 2.6h5.2' },
  ],
  'profession-glass-worker': [
    { tag: 'rect', x: '3.5', y: '3.5', width: '12.5', height: '17', rx: '1.2' },
    { tag: 'path', d: 'M6.5 17 12.5 8.5' },
    { tag: 'path', d: 'M9.5 18.5 13 13.5' },
    { tag: 'circle', cx: '17.8', cy: '11.5', r: '2.6' },
    { tag: 'circle', cx: '17.8', cy: '11.5', r: '0.9', fill: 'currentColor', stroke: 'none' },
  ],
  'profession-gypsum-worker': [
    { tag: 'path', d: 'M2.6 4.6h18.8' },
    { tag: 'path', d: 'M2.6 8.4h4.6v3.6h9.6V8.4h4.6' },
    { tag: 'path', d: 'M2.6 4.6v3.8M21.4 4.6v3.8' },
    { tag: 'circle', cx: '12', cy: '14.8', r: '1.05', fill: 'currentColor', stroke: 'none' },
  ],
  'profession-home-electronics': [
    { tag: 'rect', x: '2.8', y: '4.5', width: '18.4', height: '12.5', rx: '2.2' },
    { tag: 'path', d: 'M9 20.5h6M12 17v3.5' },
    { tag: 'path', d: 'M7.5 11h2l1.4-2.6 1.6 5 1.4-2.4h2.6' },
  ],
  'profession-interior-decorator': [
    { tag: 'rect', x: '9.6', y: '3.4', width: '4.8', height: '15', rx: '1.4', transform: 'rotate(-20 12 20)' },
    { tag: 'rect', x: '9.6', y: '3.4', width: '4.8', height: '15', rx: '1.4', transform: 'rotate(20 12 20)' },
    { tag: 'rect', x: '9.6', y: '3.4', width: '4.8', height: '15', rx: '1.4' },
    { tag: 'circle', cx: '12', cy: '8.4', r: '1.1', fill: 'currentColor', stroke: 'none' },
  ],
  'profession-landscaper': [
    { tag: 'circle', cx: '7.8', cy: '8.4', r: '4.6' },
    { tag: 'path', d: 'M7.8 13v6.6' },
    { tag: 'rect', x: '13.6', y: '11.8', width: '7.4', height: '7.8', rx: '2.6' },
    { tag: 'path', d: 'M2.6 19.6h18.8' },
  ],
  'profession-mason': [
    { tag: 'path', d: 'M3.6 9 13 4.4v9.2z' },
    { tag: 'path', d: 'M13 9h4.4' },
    { tag: 'rect', x: '17.4', y: '7.4', width: '3.6', height: '3.2', rx: '1.4' },
    { tag: 'rect', x: '4', y: '16.4', width: '16', height: '4.4', rx: '1.2' },
    { tag: 'path', d: 'M12 16.4v4.4' },
  ],
  'profession-pool-technician': [
    { tag: 'path', d: 'M13 5.6v10M17.4 5.6v10' },
    { tag: 'path', d: 'M13 5.6a2.2 2.2 0 0 1 4.4 0' },
    { tag: 'path', d: 'M13 9h4.4M13 12.4h4.4' },
    { tag: 'path', d: 'M2.6 17c1.5-1.6 3-1.6 4.5 0s3 1.6 4.5 0 3-1.6 4.5 0 3 1.6 4.5 0' },
    { tag: 'path', d: 'M2.6 20.6c1.5-1.6 3-1.6 4.5 0s3 1.6 4.5 0 3-1.6 4.5 0 3 1.6 4.5 0' },
  ],
  'profession-security-system': [
    { tag: 'rect', x: '3.4', y: '7', width: '11.6', height: '6.4', rx: '2.2' },
    { tag: 'path', d: 'M15 8.6 20.6 6.2v8l-5.6-2.4z' },
    { tag: 'path', d: 'M9.2 7V3.4M6.2 3.4h6' },
    { tag: 'circle', cx: '6.6', cy: '10.2', r: '0.9', fill: 'currentColor', stroke: 'none' },
  ],
  'profession-smart-home': [
    { tag: 'path', d: 'M3.6 11.8 12 5.2l8.4 6.6v7.8a1.4 1.4 0 0 1-1.4 1.4H5a1.4 1.4 0 0 1-1.4-1.4z' },
    { tag: 'circle', cx: '12', cy: '17.8', r: '0.95', fill: 'currentColor', stroke: 'none' },
    { tag: 'path', d: 'M9.8 15.6a3.1 3.1 0 0 1 4.4 0' },
    { tag: 'path', d: 'M8.2 13.4a5.4 5.4 0 0 1 7.6 0' },
  ],
  'profession-tiler': [
    { tag: 'rect', x: '6', y: '4', width: '13', height: '6', rx: '1.2' },
    { tag: 'path', d: 'M9.6 4V2.4h5.8V4' },
    { tag: 'path', d: 'M8 10v1.8M11 10v1.8M14 10v1.8M17 10v1.8' },
    { tag: 'rect', x: '4.4', y: '15', width: '15.2', height: '5.4', rx: '1.2' },
  ],
  'profession-upholsterer': [
    { tag: 'rect', x: '5', y: '4', width: '14', height: '9.2', rx: '3' },
    { tag: 'rect', x: '3.4', y: '12.6', width: '17.2', height: '5', rx: '2' },
    { tag: 'path', d: 'M6.2 17.6v2.6M17.8 17.6v2.6' },
    { tag: 'path', d: 'M9.4 6.2v4.8M14.6 6.2v4.8' },
  ],
  'profession-welder': [
    { tag: 'path', d: 'M5.5 4.2h13v8.6a6.5 6.5 0 0 1-13 0z' },
    { tag: 'rect', x: '8', y: '7.4', width: '8', height: '2.6', rx: '1.3', fill: 'currentColor', stroke: 'none' },
    { tag: 'path', d: 'M12 20.6v1.4M8.6 19.8l-.9 1.2M15.4 19.8l.9 1.2' },
  ],
  'service-ac': [
    { tag: 'rect', x: '3', y: '4.5', width: '18', height: '7.5', rx: '2.5' },
    { tag: 'path', d: 'M5.5 9.8h13' },
    { tag: 'path', d: 'M6.2 16.2c1.5-1.8 3-1.8 4.5 0s3 1.8 4.5 0' },
    { tag: 'path', d: 'M9.2 20c1.2-1.4 2.4-1.4 3.6 0' },
  ],
  'service-alumetal': [
    { tag: 'rect', x: '3', y: '4', width: '18', height: '16', rx: '1.6' },
    { tag: 'path', d: 'M12 4v16' },
    { tag: 'rect', x: '13.6', y: '5.8', width: '5.6', height: '12.4', rx: '0.9' },
    { tag: 'rect', x: '10.9', y: '10.4', width: '2.2', height: '3.2', rx: '1.1', fill: 'currentColor', stroke: 'none' },
  ],
  'service-appliance-repair': [
    { tag: 'rect', x: '4.5', y: '3', width: '15', height: '18', rx: '3' },
    { tag: 'path', d: 'M4.5 8h15' },
    { tag: 'circle', cx: '12', cy: '14.5', r: '4' },
    { tag: 'circle', cx: '16.2', cy: '5.5', r: '1', fill: 'currentColor', stroke: 'none' },
  ],
  'service-barber': [
    { tag: 'rect', x: '8.5', y: '2.8', width: '7', height: '18.4', rx: '3.5' },
    { tag: 'path', d: 'M9 8.4 15 5M9 13.4 15 10M9 18.4 15 15' },
  ],
  'service-carpentry': [
    { tag: 'rect', x: '6', y: '8.6', width: '14', height: '4', rx: '1' },
    { tag: 'path', d: 'M6 8.6H4a2 2 0 0 0-2 2v.4a2 2 0 0 0 2 2h2' },
    { tag: 'path', d: 'M7.2 12.6l1.7 2.6 1.7-2.6 1.7 2.6 1.7-2.6 1.7 2.6 1.7-2.6' },
  ],
  'service-cleaning': [
    { tag: 'rect', x: '8', y: '9', width: '8.5', height: '11.5', rx: '2' },
    { tag: 'path', d: 'M10.5 9V6.2h4' },
    { tag: 'path', d: 'M14.5 6.2h3.2' },
    { tag: 'path', d: 'M18.8 6.2h2.2M18.3 4.3l1.9-1.1M18.3 8.1l1.9 1.1' },
  ],
  'service-electrical': [
    { tag: 'path', d: 'M9 3.5v3.5' },
    { tag: 'path', d: 'M15 3.5v3.5' },
    { tag: 'rect', x: '6', y: '7', width: '12', height: '7.5', rx: '2.5' },
    { tag: 'path', d: 'M12 14.5v6' },
  ],
  'service-flooring-tiling': [
    { tag: 'rect', x: '3.2', y: '3.2', width: '8', height: '8', rx: '1.2' },
    { tag: 'rect', x: '12.8', y: '3.2', width: '8', height: '8', rx: '1.2' },
    { tag: 'rect', x: '3.2', y: '12.8', width: '8', height: '8', rx: '1.2' },
    { tag: 'rect', x: '12.8', y: '12.8', width: '8', height: '8', rx: '1.2', transform: 'rotate(-14 16.8 16.8)' },
  ],
  'service-gardening': [
    { tag: 'path', d: 'M12 20.5V9.5' },
    { tag: 'path', d: 'M12 13.5C8.6 13.5 6.5 11.4 6.5 8 9.9 8 12 10.1 12 13.5z' },
    { tag: 'path', d: 'M12 11C15.4 11 17.5 8.9 17.5 5.5 14.1 5.5 12 7.6 12 11z' },
    { tag: 'path', d: 'M6 20.5h12' },
  ],
  'service-hairdressing': [
    { tag: 'path', d: 'M6.6 3.2 15.4 16.4' },
    { tag: 'path', d: 'M17.4 3.2 8.6 16.4' },
    { tag: 'circle', cx: '7.2', cy: '18.6', r: '2.4' },
    { tag: 'circle', cx: '16.8', cy: '18.6', r: '2.4' },
    { tag: 'circle', cx: '12', cy: '11.8', r: '0.9', fill: 'currentColor', stroke: 'none' },
  ],
  'service-locksmithing': [
    { tag: 'circle', cx: '7', cy: '12', r: '4' },
    { tag: 'path', d: 'M11 12h9' },
    { tag: 'path', d: 'M16 12v3.4M19 12v2.6' },
  ],
  'service-moving-help': [
    { tag: 'rect', x: '2.5', y: '8.5', width: '12.5', height: '11.5', rx: '1.6' },
    { tag: 'path', d: 'M8.75 8.5V20' },
    { tag: 'rect', x: '16', y: '4.5', width: '5.5', height: '5.5', rx: '1.3' },
    { tag: 'path', d: 'M18.75 4.5v5.5' },
  ],
  'service-painting': [
    { tag: 'rect', x: '3.5', y: '4', width: '12', height: '5.5', rx: '1.8' },
    { tag: 'path', d: 'M15.5 6.75h3.2v5.75H12.5v2' },
    { tag: 'rect', x: '10', y: '14.5', width: '5', height: '6.5', rx: '2.2' },
  ],
  'service-personal-styling': [
    { tag: 'path', d: 'M12 7.6V6.4a2.2 2.2 0 1 1 2.2-2.2' },
    { tag: 'path', d: 'M12 7.6 3.6 15.2a1.2 1.2 0 0 0 .8 2.1h15.2a1.2 1.2 0 0 0 .8-2.1z' },
  ],
  'service-pest-control': [
    { tag: 'ellipse', cx: '12', cy: '13.5', rx: '3.4', ry: '5', fill: 'currentColor', stroke: 'none' },
    { tag: 'circle', cx: '12', cy: '7', r: '2.2', fill: 'currentColor', stroke: 'none' },
    { tag: 'path', d: 'M10.6 5.3 9.2 3.2M13.4 5.3 14.8 3.2' },
    { tag: 'path', d: 'M8.6 10.5 5.2 8.8M8.6 13.8H5M8.6 17 5.4 18.8M15.4 10.5 18.8 8.8M15.4 13.8H19M15.4 17 18.6 18.8' },
  ],
  'service-plumbing': [
    { tag: 'path', d: 'M8 5.5V13' },
    { tag: 'path', d: 'M5.2 5.5h5.6' },
    { tag: 'path', d: 'M8 9.5h5.5a3.5 3.5 0 0 1 3.5 3.5v1.2' },
    { tag: 'path', d: 'M17 17.2c1.3 1.5 2 2.4 2 3.2a2 2 0 0 1-4 0c0-.8.7-1.7 2-3.2z', fill: 'currentColor', stroke: 'none' },
  ],
  'service-renovation-finishing': [
    { tag: 'rect', x: '3', y: '15', width: '18', height: '3.6', rx: '1.6' },
    { tag: 'path', d: 'M7.5 15v-1.8c0-2 1.7-3.2 4.5-3.2s4.5 1.2 4.5 3.2V15' },
    { tag: 'path', d: 'M5 6.2h14' },
  ],
  'service-satellite-tv-installation': [
    { tag: 'path', d: 'M3 12.6A9.6 9.6 0 0 1 12.6 3A9.6 9.6 0 0 1 3 12.6z' },
    { tag: 'path', d: 'M7.6 7.6 14.6 14.6' },
    { tag: 'circle', cx: '15.6', cy: '15.6', r: '1.6', fill: 'currentColor', stroke: 'none' },
    { tag: 'path', d: 'M8 12.6V20.5' },
    { tag: 'path', d: 'M5.2 20.5h5.6' },
  ],
  'service-water-heater-repair': [
    { tag: 'rect', x: '6', y: '3', width: '12', height: '13', rx: '3.5' },
    { tag: 'path', d: 'M9.5 3V2M14.5 3V2' },
    { tag: 'path', d: 'M8.6 10.6c1.1-1 2.2-1 3.4 0s2.3 1 3.4 0' },
    { tag: 'path', d: 'M12 22.2c-1.5 0-2.7-1-2.7-2.4 0-1.4 1.4-2 2.7-3.6 1.3 1.6 2.7 2.2 2.7 3.6 0 1.4-1.2 2.4-2.7 2.4z', fill: 'currentColor', stroke: 'none' },
  ],
} as const satisfies Record<string, readonly WarshaIconElement[]>;

export type WarshaIconName = keyof typeof warshaIconGeometry;

export function warshaIconElements(name: string): readonly WarshaIconElement[] | null {
  return (warshaIconGeometry as Record<string, readonly WarshaIconElement[]>)[name] ?? null;
}
