create or replace function private.is_staff() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.user_roles where user_id=(select auth.uid()) and role in ('support','admin')) $$;
create or replace function private.is_admin() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.user_roles where user_id=(select auth.uid()) and role='admin') $$;
create or replace function private.is_conversation_member(target_conversation_id uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.conversation_members where conversation_id=target_conversation_id and user_id=(select auth.uid())) $$;
revoke all on schema private from public; grant usage on schema private to authenticated;
grant execute on function private.is_staff() to authenticated; grant execute on function private.is_admin() to authenticated;
grant execute on function private.is_conversation_member(uuid) to authenticated;

do $$ declare t text; begin foreach t in array array[
'profiles','user_roles','customer_profiles','provider_profiles','provider_verification_documents','service_categories','services','provider_services','provider_availability','provider_service_areas','addresses','bookings','booking_status_history','booking_attachments','booking_quotes','quote_items','change_orders','change_order_items','payments','payment_transactions','refunds','provider_earnings','provider_payouts','conversations','conversation_members','messages','message_attachments','reviews','review_responses','favourites','notifications','notification_preferences','promo_codes','promo_code_uses','wallets','wallet_transactions','disputes','dispute_evidence','support_tickets','support_messages','provider_portfolio','provider_certifications','user_reports','admin_roles','admin_permissions','admin_role_assignments','audit_logs','app_settings'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;

create policy profiles_own_select on public.profiles for select to authenticated using(id=(select auth.uid()));
create policy profiles_public_provider_select on public.profiles for select to anon,authenticated using(exists(select 1 from public.provider_profiles p where p.id=profiles.id and p.is_published and p.deleted_at is null));
create policy profiles_own_update on public.profiles for update to authenticated using(id=(select auth.uid())) with check(id=(select auth.uid()));
create policy roles_own_select on public.user_roles for select to authenticated using(user_id=(select auth.uid()));
create policy customer_own_all on public.customer_profiles for all to authenticated using(id=(select auth.uid())) with check(id=(select auth.uid()));
create policy categories_public_read on public.service_categories for select to anon,authenticated using(is_active and deleted_at is null);
create policy services_public_read on public.services for select to anon,authenticated using(is_active and deleted_at is null);
create policy providers_public_read on public.provider_profiles for select to anon,authenticated using(is_published and deleted_at is null);
create policy providers_own_update on public.provider_profiles for update to authenticated using(id=(select auth.uid())) with check(id=(select auth.uid()));
create policy provider_services_public_read on public.provider_services for select to anon,authenticated using(is_active and exists(select 1 from public.provider_profiles p where p.id=provider_id and p.is_published));
create policy provider_services_own_write on public.provider_services for all to authenticated using(provider_id=(select auth.uid())) with check(provider_id=(select auth.uid()));
create policy provider_availability_public_read on public.provider_availability for select to anon,authenticated using(exists(select 1 from public.provider_profiles p where p.id=provider_id and p.is_published));
create policy provider_availability_own_write on public.provider_availability for all to authenticated using(provider_id=(select auth.uid())) with check(provider_id=(select auth.uid()));
create policy provider_areas_public_read on public.provider_service_areas for select to anon,authenticated using(exists(select 1 from public.provider_profiles p where p.id=provider_id and p.is_published));
create policy provider_areas_own_write on public.provider_service_areas for all to authenticated using(provider_id=(select auth.uid())) with check(provider_id=(select auth.uid()));
create policy addresses_own_all on public.addresses for all to authenticated using(customer_id=(select auth.uid())) with check(customer_id=(select auth.uid()));
create policy portfolio_public_read on public.provider_portfolio for select to anon,authenticated using(exists(select 1 from public.provider_profiles p where p.id=provider_id and p.is_published));
create policy portfolio_own_write on public.provider_portfolio for all to authenticated using(provider_id=(select auth.uid())) with check(provider_id=(select auth.uid()));
create policy certifications_public_read on public.provider_certifications for select to anon,authenticated using(is_public and exists(select 1 from public.provider_profiles p where p.id=provider_id and p.is_published));
create policy certifications_own_read on public.provider_certifications for select to authenticated using(provider_id=(select auth.uid()));
create policy verification_owner_read on public.provider_verification_documents for select to authenticated using(provider_id=(select auth.uid()) or private.is_staff());
create policy verification_owner_insert on public.provider_verification_documents for insert to authenticated with check(provider_id=(select auth.uid()));
create policy bookings_participant_read on public.bookings for select to authenticated using(customer_id=(select auth.uid()) or provider_id=(select auth.uid()) or private.is_staff());
create policy bookings_customer_insert on public.bookings for insert to authenticated with check(customer_id=(select auth.uid()));
create policy booking_history_participant_read on public.booking_status_history for select to authenticated using(exists(select 1 from public.bookings b where b.id=booking_id and (b.customer_id=(select auth.uid()) or b.provider_id=(select auth.uid()))) or private.is_staff());
create policy booking_attachments_participant on public.booking_attachments for select to authenticated using(exists(select 1 from public.bookings b where b.id=booking_id and (b.customer_id=(select auth.uid()) or b.provider_id=(select auth.uid()))) or private.is_staff());
create policy booking_attachments_insert on public.booking_attachments for insert to authenticated with check(uploader_id=(select auth.uid()) and exists(select 1 from public.bookings b where b.id=booking_id and (b.customer_id=(select auth.uid()) or b.provider_id=(select auth.uid()))));
create policy conversations_member_read on public.conversations for select to authenticated using(private.is_conversation_member(id) or private.is_staff());
create policy conversation_members_member_read on public.conversation_members for select to authenticated using(private.is_conversation_member(conversation_id) or private.is_staff());
create policy messages_member_read on public.messages for select to authenticated using(private.is_conversation_member(conversation_id) or private.is_staff());
create policy messages_member_insert on public.messages for insert to authenticated with check(sender_id=(select auth.uid()) and private.is_conversation_member(conversation_id));
create policy reviews_public_read on public.reviews for select to anon,authenticated using(deleted_at is null);
create policy reviews_completed_booking_insert on public.reviews for insert to authenticated with check(customer_id=(select auth.uid()) and exists(select 1 from public.bookings b where b.id=booking_id and b.customer_id=(select auth.uid()) and b.provider_id=provider_id and b.status='completed'));
create policy review_responses_public_read on public.review_responses for select to anon,authenticated using(true);
create policy favourites_own_all on public.favourites for all to authenticated using(customer_id=(select auth.uid())) with check(customer_id=(select auth.uid()));
create policy notifications_own_read on public.notifications for select to authenticated using(user_id=(select auth.uid()));
create policy notification_preferences_own_all on public.notification_preferences for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy disputes_participant_read on public.disputes for select to authenticated using(opened_by=(select auth.uid()) or private.is_staff());
create policy disputes_owner_insert on public.disputes for insert to authenticated with check(opened_by=(select auth.uid()));
create policy support_ticket_owner_read on public.support_tickets for select to authenticated using(requester_id=(select auth.uid()) or private.is_staff());
create policy support_ticket_owner_insert on public.support_tickets for insert to authenticated with check(requester_id=(select auth.uid()));
create policy admin_only_roles on public.admin_roles for all to authenticated using(private.is_admin()) with check(private.is_admin());
create policy admin_only_permissions on public.admin_permissions for all to authenticated using(private.is_admin()) with check(private.is_admin());
create policy admin_only_assignments on public.admin_role_assignments for all to authenticated using(private.is_admin()) with check(private.is_admin());
create policy admin_only_audit on public.audit_logs for select to authenticated using(private.is_admin());
create policy public_active_promos on public.promo_codes for select to authenticated using(is_active and (starts_at is null or starts_at<=now()) and (ends_at is null or ends_at>now()));
create policy admin_settings_read on public.app_settings for select to authenticated using(private.is_staff());

insert into storage.buckets(id,name,public) values('avatars','avatars',true),('provider-portfolios','provider-portfolios',true),('booking-attachments','booking-attachments',false),('verification-documents','verification-documents',false),('dispute-evidence','dispute-evidence',false) on conflict(id) do nothing;
create policy public_media_read on storage.objects for select to anon,authenticated using(bucket_id in ('avatars','provider-portfolios'));
create policy own_avatar_write on storage.objects for insert to authenticated with check(bucket_id='avatars' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy provider_portfolio_write on storage.objects for insert to authenticated with check(bucket_id='provider-portfolios' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy private_user_uploads on storage.objects for insert to authenticated with check(bucket_id in ('booking-attachments','verification-documents','dispute-evidence') and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy private_user_reads on storage.objects for select to authenticated using(bucket_id in ('booking-attachments','verification-documents','dispute-evidence') and ((storage.foldername(name))[1]=(select auth.uid())::text or private.is_staff()));
