import { File } from 'expo-file-system';
import Storage from 'expo-sqlite/kv-store';

import { removePersistedAttachment } from '@/src/bookings/attachment-storage';
import { canTransition, normalizeHistory, type Booking, type BookingAttachment, type BookingStatus } from '@/src/bookings/booking-types';
import { environment } from '@/src/config/environment';
import { getSupabaseClient } from '@/src/lib/supabase';
import { createMockNotification } from '@/src/notifications/notification-repository';
import { emitMockRealtime } from '@/src/realtime/realtime-service';
import { rollbackBookingAttachmentUpload, withSignedAttachments } from '@/src/repositories/supabase-user-repositories';

const KEY='warsha:provider-jobs:v1';
let localQueue:Promise<unknown>=Promise.resolve();
export interface ProviderJobRepository { list(providerId:string):Promise<Booking[]>;accept(id:string):Promise<void>;reject(id:string,reason:string):Promise<void>;propose(id:string,date:string,time:string,note:string):Promise<void>;advance(id:string,status:BookingStatus,note?:string):Promise<void>;noShow(id:string,reason:string):Promise<void>;complete(id:string,notes:string,attachments:BookingAttachment[]):Promise<void> }

function today(offset:number){const date=new Date();date.setDate(date.getDate()+offset);return date.toISOString().slice(0,10)}
function mockSeed(providerId:string):Booking[]{const now=Date.now();const make=(id:string,status:BookingStatus,customerName:string,serviceName:string,offset:number,hoursAgo:number,price:number):Booking=>{const history:Booking['history']=[{status:'pending_provider_approval',at:new Date(now-hoursAgo*3600000).toISOString()}];if(status!=='pending_provider_approval')history.push({status,at:new Date(now-Math.max(0,hoursAgo-1)*3600000).toISOString()});return{id,providerId,serviceId:`service-${id}`,serviceName,customerName,issueDescription:'The customer described a clear household repair problem that needs professional attention.',notes:'Please call from the building entrance.',attachments:[],address:'Building 12, Tahrir Street, Dokki, Giza',date:today(offset),time:offset===0?'14:30':'10:00',bookingType:id.endsWith('1')?'emergency':'scheduled',priceBreakdown:{servicePrice:price-75,inspectionFee:0,transportationFee:75,emergencySurcharge:0,discount:0,estimatedTotal:price,pricingType:'starting'},price,pricingType:'starting',status,history,createdAt:new Date(now-hoursAgo*3600000).toISOString(),updatedAt:new Date(now-Math.max(0,hoursAgo-1)*3600000).toISOString()}};return[make('MOCK-JOB-1','pending_provider_approval','Mariam Adel','Emergency plumbing repair',0,2,650),make('MOCK-JOB-2','confirmed','Omar Hassan','Air conditioner maintenance',1,20,900),make('MOCK-JOB-3','provider_arrived','Nour Ahmed','Electrical inspection',0,6,450),make('MOCK-JOB-4','work_in_progress','Karim Ali','Carpentry repair',0,8,1200),make('MOCK-JOB-5','completed','Salma Mostafa','Apartment cleaning',-3,72,800),make('MOCK-JOB-6','rejected','Youssef Samir','Wall painting',-1,30,1500),make('MOCK-JOB-7','cancelled','Dina Wael','Water heater repair',-2,48,700)]}
async function read(providerId:string){const raw=await Storage.getItem(KEY);if(!raw){const seed=mockSeed(providerId);await Storage.setItem(KEY,JSON.stringify(seed));return seed}try{return(JSON.parse(raw) as Booking[]).map(job=>({...job,history:normalizeHistory(job.history)}))}catch{const seed=mockSeed(providerId);await Storage.setItem(KEY,JSON.stringify(seed));return seed}}
function atomic<T>(operation:()=>Promise<T>){const result=localQueue.then(operation,operation);localQueue=result.then(()=>undefined,()=>undefined);return result}
async function mutate(id:string,operation:(job:Booking,now:string)=>Booking){return atomic(async()=>{const jobs=await read('mock-provider');const index=jobs.findIndex(job=>job.id===id);if(index<0)throw new Error('Job unavailable');const now=new Date().toISOString();jobs[index]=operation(jobs[index],now);await Storage.setItem(KEY,JSON.stringify(jobs));emitMockRealtime({table:'bookings',event:'UPDATE',id});await createMockNotification(`booking_${jobs[index].status}`,id)})}
function transition(job:Booking,status:BookingStatus,now:string,note?:string){if(!canTransition(job.status,status))throw new Error('Job action unavailable');return{...job,status,updatedAt:now,history:normalizeHistory([...job.history,{status,at:now,note}])}}
const mockRepository:ProviderJobRepository={async list(providerId){return read(providerId)},accept:id=>mutate(id,(job,now)=>transition(job,'accepted',now)),reject:(id,reason)=>mutate(id,(job,now)=>({...transition(job,'rejected',now,reason),rejectionReason:reason})),propose:(id,date,time,note)=>mutate(id,(job,now)=>({...transition(job,'rescheduling_requested',now,note),proposedDate:date,proposedTime:time,providerRescheduleNote:note})),advance:(id,status,note)=>mutate(id,(job,now)=>transition(job,status,now,note)),noShow:(id,reason)=>mutate(id,(job,now)=>transition(job,'no_show',now,reason)),complete:(id,notes,attachments)=>mutate(id,(job,now)=>({...transition(job,'completed',now,notes),completionNotes:notes,attachments:[...job.attachments,...attachments.map(item=>({...item,kind:'completion_evidence' as const}))]}))};

async function rpc(name:string,parameters:Record<string,unknown>){const{error}=await getSupabaseClient().rpc(name,parameters);if(error)throw error}
async function uploadCompletionEvidence(bookingId:string,attachments:BookingAttachment[]){if(!attachments.length)return{paths:[],uploaderId:''};const client=getSupabaseClient();const{data:{user},error:userError}=await client.auth.getUser();if(userError||!user)throw userError??new Error('Authentication required');const paths:string[]=[];try{for(const attachment of attachments){const file=new File(attachment.uri);if(!file.exists||file.size>8*1024*1024)throw new Error('Invalid completion image');const path=`${user.id}/${bookingId}/completion/${attachment.id}${file.extension||'.jpg'}`;const{error}=await client.storage.from('booking-attachments').upload(path,await file.arrayBuffer(),{contentType:attachment.mimeType||file.type||'image/jpeg',upsert:false});if(error)throw error;paths.push(path);const{error:metadataError}=await client.from('booking_attachments').insert({booking_id:bookingId,uploader_id:user.id,storage_path:path,mime_type:attachment.mimeType||file.type||'image/jpeg',attachment_kind:'completion_evidence'});if(metadataError)throw metadataError}return{paths,uploaderId:user.id}}catch(error){await rollbackBookingAttachmentUpload(bookingId,user.id,paths);throw error}}
async function cleanupCompletionEvidence(attachments:BookingAttachment[]){for(const attachment of attachments)removePersistedAttachment(attachment)}
const supabaseRepository:ProviderJobRepository={async list(providerId){const{data,error}=await getSupabaseClient().from('bookings').select('*,booking_status_history(*),booking_attachments(*)').eq('provider_id',providerId).is('deleted_at',null).order('created_at',{ascending:false});if(error)throw error;return withSignedAttachments(data as Record<string,unknown>[])},accept:id=>rpc('accept_provider_booking',{p_booking_id:id}),reject:(id,reason)=>rpc('reject_provider_booking',{p_booking_id:id,p_reason:reason}),propose:(id,date,time,note)=>rpc('propose_provider_reschedule',{p_booking_id:id,p_date:date,p_time:time,p_note:note}),advance:(id,status,note)=>rpc('advance_provider_booking_status',{p_booking_id:id,p_status:status,p_note:note??null}),noShow:(id,reason)=>rpc('report_provider_no_show',{p_booking_id:id,p_reason:reason}),async complete(id,notes,attachments){const{paths,uploaderId}=await uploadCompletionEvidence(id,attachments);try{await rpc('advance_provider_booking_status',{p_booking_id:id,p_status:'completed',p_note:notes||null});await cleanupCompletionEvidence(attachments)}catch(error){await rollbackBookingAttachmentUpload(id,uploaderId,paths);throw error}}};
export const providerJobRepository=environment.dataMode==='supabase'?supabaseRepository:mockRepository;
