import type { SupportedLanguage } from '../i18n/language-preference.ts';

/**
 * Shared customer-facing language for authentication outcomes.
 *
 * These states are rendered by the Next app and by the Expo app. Keeping the
 * words here prevents a provider error from acquiring a different meaning on
 * web, Android, or iOS. It is intentionally import-free at runtime so the web
 * bundle does not need to load React Native's localization context.
 */
export const authOutcomeCopy = {
  en: {
    existingAccountTitle: 'Looks like you already have a Warsha account',
    existingEmailBody: 'This email address is already linked to an account. Sign in instead, or reset your password if you can’t access it.',
    existingPhoneBody: 'This phone number is already linked to an account. Sign in instead, or reset your password if you can’t access it.',
    existingIdentityBody: 'This email address or phone number is already linked to an account. Sign in instead, or reset your password if you can’t access it.',
    confirmationPendingTitle: 'Check your email',
    confirmationPendingBody: 'If this address can be registered, a confirmation link will arrive. If you already have a Warsha account, sign in instead or reset your password. Warsha cannot confirm account existence, sending, or delivery from this screen.',
    confirmationProcessingTitle: 'Confirming your email address',
    confirmationProcessingBody: 'Warsha is securely checking this confirmation link.',
    confirmationCompleteTitle: 'Email address confirmed',
    confirmationCompleteBody: 'Your account is ready. Continue to the next step.',
    continueAction: 'Continue',
    confirmationExpiredTitle: 'This confirmation link has expired',
    confirmationExpiredBody: 'Request a new confirmation email, then use only the newest link.',
    confirmationUsedTitle: 'This confirmation link has already been used',
    confirmationUsedBody: 'Your email may already be confirmed. Sign in, or reset your password if you can’t access the account.',
    confirmationExpiredOrUsedTitle: 'This link has expired or was already used',
    confirmationExpiredOrUsedBody: 'Sign in if you already confirmed your email. Otherwise, request a new confirmation email and use only the newest link.',
    confirmationInvalidTitle: 'This confirmation link is invalid',
    confirmationInvalidBody: 'The link is incomplete or malformed. Return to sign in, or start registration if you do not have an account.',
    confirmationSessionMismatchTitle: 'Open the link where you requested it',
    confirmationSessionMismatchBody: 'This secure link must be completed in the same browser or device that requested it. You can also request a new confirmation email.',
    confirmationServiceTitle: 'Warsha could not check this link',
    confirmationServiceBody: 'Check your connection and try again. If the problem continues, request a new confirmation email.',
    recoveryExpiredTitle: 'This password-reset link has expired',
    recoveryExpiredBody: 'Request a new password-reset link and use only the newest one.',
    recoveryUsedTitle: 'This password-reset link has already been used',
    recoveryUsedBody: 'Sign in with your new password, or request another reset link if you still can’t access the account.',
    recoveryExpiredOrUsedTitle: 'This reset link has expired or was already used',
    recoveryExpiredOrUsedBody: 'Sign in if you already changed your password. Otherwise, request a new reset link.',
    recoveryInvalidTitle: 'This password-reset link is invalid',
    recoveryInvalidBody: 'The link is incomplete or malformed. Request a new password-reset link from Warsha.',
    recoverySessionMismatchTitle: 'Open the reset link where you requested it',
    recoverySessionMismatchBody: 'This secure link must be completed in the same browser or device that requested it. You can also request a new reset link.',
    recoveryServiceTitle: 'Warsha could not check this reset link',
    recoveryServiceBody: 'Check your connection, then request a new password-reset link if the problem continues.',
    resendTitle: 'Send a new confirmation email',
    resendBody: 'Enter the email address you registered with. If it is still awaiting confirmation, Warsha will send a new link.',
    resendSentTitle: 'Check your email',
    resendSentBody: 'If this address is awaiting confirmation, a new link is on its way. Use only the newest link and check your spam folder.',
    forgotTitle: 'Reset your password',
    forgotBody: 'Enter the email address on your account. If it has one, Warsha will send a password-reset link.',
    forgotSentTitle: 'Check your email',
    forgotSentBody: 'If that address has a Warsha account, a password-reset link is on its way.',
    emailLabel: 'Email address',
    signInAction: 'Sign in',
    forgotPasswordAction: 'Forgot password?',
    resendConfirmationAction: 'Send a new confirmation email',
    createAccountAction: 'Create account',
    retryAction: 'Try again',
    sendAction: 'Send email',
    backToSignInAction: 'Back to sign in',
    loading: 'Sending…',
    invalidEmailError: 'Enter a valid email address.',
    rateLimitedError: 'Too many attempts. Try again later.',
    sendFailedError: 'The email could not be sent. Try again.',
  },
  ar: {
    existingAccountTitle: 'واضح إن عندك حساب على ورشة بالفعل',
    existingEmailBody: 'البريد الإلكتروني ده مرتبط بحساب بالفعل. سجّل دخول بدل ما تعمل حساب جديد، أو غيّر كلمة السر لو مش قادر تدخل.',
    existingPhoneBody: 'رقم الموبايل ده مرتبط بحساب بالفعل. سجّل دخول بدل ما تعمل حساب جديد، أو غيّر كلمة السر لو مش قادر تدخل.',
    existingIdentityBody: 'البريد الإلكتروني أو رقم الموبايل ده مرتبط بحساب بالفعل. سجّل دخول بدل ما تعمل حساب جديد، أو غيّر كلمة السر لو مش قادر تدخل.',
    confirmationPendingTitle: 'راجع بريدك الإلكتروني',
    confirmationPendingBody: 'لو العنوان ده ينفع يتسجّل، هيوصلك لينك تأكيد. ولو عندك حساب على ورشة بالفعل، سجّل دخول أو غيّر كلمة السر. الشاشة دي ما تقدرش تأكد وجود الحساب أو إرسال الرسالة أو وصولها.',
    confirmationProcessingTitle: 'بنأكّد بريدك الإلكتروني',
    confirmationProcessingBody: 'ورشة بتتحقق من لينك التأكيد بأمان.',
    confirmationCompleteTitle: 'اتأكّد بريدك الإلكتروني',
    confirmationCompleteBody: 'حسابك جاهز. كمّل للخطوة الجاية.',
    continueAction: 'كمّل',
    confirmationExpiredTitle: 'صلاحية لينك التأكيد انتهت',
    confirmationExpiredBody: 'اطلب رسالة تأكيد جديدة، واستخدم أحدث لينك بس.',
    confirmationUsedTitle: 'لينك التأكيد ده اتستخدم قبل كده',
    confirmationUsedBody: 'ممكن يكون بريدك اتأكّد بالفعل. سجّل دخول، أو غيّر كلمة السر لو مش قادر تدخل الحساب.',
    confirmationExpiredOrUsedTitle: 'صلاحية اللينك انتهت أو اتستخدم قبل كده',
    confirmationExpiredOrUsedBody: 'سجّل دخول لو كنت أكّدت بريدك بالفعل. غير كده، اطلب رسالة تأكيد جديدة واستخدم أحدث لينك بس.',
    confirmationInvalidTitle: 'لينك التأكيد غير صحيح',
    confirmationInvalidBody: 'اللينك ناقص أو مكتوب بشكل غير صحيح. ارجع لتسجيل الدخول، أو ابدأ التسجيل لو ما عندكش حساب.',
    confirmationSessionMismatchTitle: 'افتح اللينك من المكان اللي طلبته منه',
    confirmationSessionMismatchBody: 'لازم تكمّل اللينك الآمن ده من نفس المتصفح أو الجهاز اللي طلبته منه. وتقدر كمان تطلب رسالة تأكيد جديدة.',
    confirmationServiceTitle: 'ورشة ما قدرتش تتحقق من اللينك',
    confirmationServiceBody: 'راجع اتصالك بالإنترنت وحاول تاني. لو المشكلة مستمرة، اطلب رسالة تأكيد جديدة.',
    recoveryExpiredTitle: 'صلاحية لينك تغيير كلمة السر انتهت',
    recoveryExpiredBody: 'اطلب لينك جديد لتغيير كلمة السر، واستخدم أحدث لينك بس.',
    recoveryUsedTitle: 'لينك تغيير كلمة السر ده اتستخدم قبل كده',
    recoveryUsedBody: 'سجّل دخول بكلمة السر الجديدة، أو اطلب لينك تاني لو لسه مش قادر تدخل الحساب.',
    recoveryExpiredOrUsedTitle: 'صلاحية لينك تغيير كلمة السر انتهت أو اتستخدم قبل كده',
    recoveryExpiredOrUsedBody: 'سجّل دخول لو كنت غيّرت كلمة السر. غير كده، اطلب لينك جديد.',
    recoveryInvalidTitle: 'لينك تغيير كلمة السر غير صحيح',
    recoveryInvalidBody: 'اللينك ناقص أو مكتوب بشكل غير صحيح. اطلب لينك جديد من ورشة.',
    recoverySessionMismatchTitle: 'افتح لينك تغيير كلمة السر من المكان اللي طلبته منه',
    recoverySessionMismatchBody: 'لازم تكمّل اللينك الآمن ده من نفس المتصفح أو الجهاز اللي طلبته منه. وتقدر كمان تطلب لينك جديد.',
    recoveryServiceTitle: 'ورشة ما قدرتش تتحقق من لينك تغيير كلمة السر',
    recoveryServiceBody: 'راجع اتصالك بالإنترنت، ولو المشكلة مستمرة اطلب لينك جديد لتغيير كلمة السر.',
    resendTitle: 'ابعت رسالة تأكيد جديدة',
    resendBody: 'اكتب البريد الإلكتروني اللي سجّلت بيه. لو لسه مستني التأكيد، ورشة هتبعت لينك جديد.',
    resendSentTitle: 'راجع بريدك الإلكتروني',
    resendSentBody: 'لو العنوان ده لسه مستني التأكيد، لينك جديد في طريقه ليك. استخدم أحدث لينك بس وراجع الرسائل غير المرغوبة.',
    forgotTitle: 'غيّر كلمة السر',
    forgotBody: 'اكتب البريد الإلكتروني بتاع حسابك. لو عليه حساب، ورشة هتبعت لينك لتغيير كلمة السر.',
    forgotSentTitle: 'راجع بريدك الإلكتروني',
    forgotSentBody: 'لو العنوان ده عليه حساب في ورشة، لينك تغيير كلمة السر في طريقه ليك.',
    emailLabel: 'البريد الإلكتروني',
    signInAction: 'تسجيل الدخول',
    forgotPasswordAction: 'نسيت كلمة السر؟',
    resendConfirmationAction: 'ابعت رسالة تأكيد جديدة',
    createAccountAction: 'إنشاء حساب',
    retryAction: 'حاول تاني',
    sendAction: 'إرسال الرسالة',
    backToSignInAction: 'الرجوع لتسجيل الدخول',
    loading: 'جاري الإرسال…',
    invalidEmailError: 'اكتب بريد إلكتروني صحيح.',
    rateLimitedError: 'محاولات كثيرة. حاول مرة أخرى لاحقًا.',
    sendFailedError: 'تعذر إرسال الرسالة الآن. حاول مرة أخرى.',
  },
  fr: {
    existingAccountTitle: 'Il semble que vous ayez déjà un compte Warsha',
    existingEmailBody: 'Cette adresse e-mail est déjà associée à un compte. Connectez-vous ou réinitialisez votre mot de passe si vous ne pouvez pas y accéder.',
    existingPhoneBody: 'Ce numéro de téléphone est déjà associé à un compte. Connectez-vous ou réinitialisez votre mot de passe si vous ne pouvez pas y accéder.',
    existingIdentityBody: 'Cette adresse e-mail ou ce numéro de téléphone est déjà associé à un compte. Connectez-vous ou réinitialisez votre mot de passe si vous ne pouvez pas y accéder.',
    confirmationPendingTitle: 'Consultez votre e-mail',
    confirmationPendingBody: 'Si cette adresse peut être inscrite, vous recevrez un lien de confirmation. Si vous avez déjà un compte Warsha, connectez-vous ou réinitialisez votre mot de passe. Cet écran ne peut confirmer ni l’existence du compte, ni l’envoi, ni la réception du message.',
    confirmationProcessingTitle: 'Confirmation de votre adresse e-mail',
    confirmationProcessingBody: 'Warsha vérifie ce lien de confirmation de manière sécurisée.',
    confirmationCompleteTitle: 'Adresse e-mail confirmée',
    confirmationCompleteBody: 'Votre compte est prêt. Passez à l’étape suivante.',
    continueAction: 'Continuer',
    confirmationExpiredTitle: 'Ce lien de confirmation a expiré',
    confirmationExpiredBody: 'Demandez un nouvel e-mail de confirmation, puis utilisez uniquement le lien le plus récent.',
    confirmationUsedTitle: 'Ce lien de confirmation a déjà été utilisé',
    confirmationUsedBody: 'Votre adresse e-mail est peut-être déjà confirmée. Connectez-vous ou réinitialisez votre mot de passe si vous ne pouvez pas accéder au compte.',
    confirmationExpiredOrUsedTitle: 'Ce lien a expiré ou a déjà été utilisé',
    confirmationExpiredOrUsedBody: 'Connectez-vous si votre adresse est déjà confirmée. Sinon, demandez un nouvel e-mail de confirmation et utilisez uniquement le lien le plus récent.',
    confirmationInvalidTitle: 'Ce lien de confirmation est incorrect',
    confirmationInvalidBody: 'Le lien est incomplet ou mal formé. Revenez à la connexion ou inscrivez-vous si vous n’avez pas de compte.',
    confirmationSessionMismatchTitle: 'Ouvrez le lien là où vous l’avez demandé',
    confirmationSessionMismatchBody: 'Ce lien sécurisé doit être utilisé dans le navigateur ou sur l’appareil qui l’a demandé. Vous pouvez aussi demander un nouvel e-mail de confirmation.',
    confirmationServiceTitle: 'Warsha n’a pas pu vérifier ce lien',
    confirmationServiceBody: 'Vérifiez votre connexion et réessayez. Si le problème persiste, demandez un nouvel e-mail de confirmation.',
    recoveryExpiredTitle: 'Ce lien de réinitialisation a expiré',
    recoveryExpiredBody: 'Demandez un nouveau lien de réinitialisation et utilisez uniquement le plus récent.',
    recoveryUsedTitle: 'Ce lien de réinitialisation a déjà été utilisé',
    recoveryUsedBody: 'Connectez-vous avec votre nouveau mot de passe ou demandez un autre lien si vous ne pouvez toujours pas accéder au compte.',
    recoveryExpiredOrUsedTitle: 'Ce lien de réinitialisation a expiré ou a déjà été utilisé',
    recoveryExpiredOrUsedBody: 'Connectez-vous si vous avez déjà changé votre mot de passe. Sinon, demandez un nouveau lien.',
    recoveryInvalidTitle: 'Ce lien de réinitialisation est incorrect',
    recoveryInvalidBody: 'Le lien est incomplet ou mal formé. Demandez un nouveau lien de réinitialisation à Warsha.',
    recoverySessionMismatchTitle: 'Ouvrez le lien de réinitialisation là où vous l’avez demandé',
    recoverySessionMismatchBody: 'Ce lien sécurisé doit être utilisé dans le navigateur ou sur l’appareil qui l’a demandé. Vous pouvez aussi demander un nouveau lien.',
    recoveryServiceTitle: 'Warsha n’a pas pu vérifier ce lien de réinitialisation',
    recoveryServiceBody: 'Vérifiez votre connexion, puis demandez un nouveau lien si le problème persiste.',
    resendTitle: 'Envoyer un nouvel e-mail de confirmation',
    resendBody: 'Saisissez l’adresse e-mail utilisée lors de votre inscription. Si elle attend encore une confirmation, Warsha enverra un nouveau lien.',
    resendSentTitle: 'Consultez votre e-mail',
    resendSentBody: 'Si cette adresse attend encore une confirmation, un nouveau lien est en route. Utilisez uniquement le lien le plus récent et vérifiez les courriers indésirables.',
    forgotTitle: 'Réinitialiser votre mot de passe',
    forgotBody: 'Saisissez l’adresse e-mail de votre compte. Si elle est associée à un compte, Warsha enverra un lien de réinitialisation.',
    forgotSentTitle: 'Consultez votre e-mail',
    forgotSentBody: 'Si cette adresse correspond à un compte Warsha, un lien de réinitialisation est en route.',
    emailLabel: 'Adresse e-mail',
    signInAction: 'Se connecter',
    forgotPasswordAction: 'Mot de passe oublié ?',
    resendConfirmationAction: 'Envoyer un nouvel e-mail de confirmation',
    createAccountAction: 'Créer un compte',
    retryAction: 'Réessayer',
    sendAction: 'Envoyer l’e-mail',
    backToSignInAction: 'Retour à la connexion',
    loading: 'Envoi…',
    invalidEmailError: 'Saisissez une adresse e-mail valide.',
    rateLimitedError: 'Trop de tentatives. Réessayez plus tard.',
    sendFailedError: 'L’e-mail n’a pas pu être envoyé. Réessayez.',
  },
} as const;

export type AuthOutcomeCopyKey = keyof typeof authOutcomeCopy.en;

export function authOutcomeText(language: SupportedLanguage, key: AuthOutcomeCopyKey): string {
  return authOutcomeCopy[language][key];
}
