import type { Session,User } from '@supabase/supabase-js';
import { createContext,PropsWithChildren,useContext,useEffect,useMemo,useState } from 'react';
import { environment } from '@/src/config/environment';
import { getSupabaseClient } from '@/src/lib/supabase';
import { sanitizeAuthError } from './auth-errors';
export type AccountRole='customer'|'provider';
type Value={mode:'mock'|'supabase';session:Session|null;user:User|null;loading:boolean;signIn:(email:string,password:string)=>Promise<void>;signUp:(name:string,email:string,password:string,role?:AccountRole,language?:'en'|'ar')=>Promise<{needsEmailConfirmation:boolean}>;requestPasswordReset:(email:string)=>Promise<void>;signOut:()=>Promise<void>};
const Context=createContext<Value|null>(null);
export function AuthProvider({children}:PropsWithChildren){const[session,setSession]=useState<Session|null>(null);const[loading,setLoading]=useState(environment.dataMode==='supabase');useEffect(()=>{let active=true;if(environment.dataMode==='mock'){setLoading(false);return()=>{active=false}}const client=getSupabaseClient();void client.auth.getSession().then(({data})=>{if(active){setSession(data.session);setLoading(false)}}).catch((error)=>{if(__DEV__)console.warn('[Warsha auth session]',error instanceof Error?error.message:'Unknown session error');if(active)setLoading(false)});const{data}=client.auth.onAuthStateChange((_event,next)=>{if(active)setSession(next)});return()=>{active=false;data.subscription.unsubscribe()}},[]);const value=useMemo<Value>(()=>({mode:environment.dataMode,session,user:session?.user??null,loading,signIn:async(email,password)=>{if(environment.dataMode==='mock')return;try{const{error}=await getSupabaseClient().auth.signInWithPassword({email,password});if(error)throw error}catch(error){throw sanitizeAuthError(error)}},signUp:async(name,email,password,role='customer',language='en')=>{if(environment.dataMode==='mock')return{needsEmailConfirmation:false};try{const acceptedAt=new Date().toISOString();const{data,error}=await getSupabaseClient().auth.signUp({email,password,options:{data:{display_name:name,preferred_language:language,account_role:role,terms_accepted_at:acceptedAt,privacy_accepted_at:acceptedAt}}});if(error)throw error;return{needsEmailConfirmation:!data.session}}catch(error){throw sanitizeAuthError(error)}},requestPasswordReset:async(email)=>{if(environment.dataMode==='mock')return;try{const{error}=await getSupabaseClient().auth.resetPasswordForEmail(email,{redirectTo:'warsha://reset-password'});if(error)throw error}catch(error){throw sanitizeAuthError(error)}},signOut:async()=>{if(environment.dataMode==='mock')return;try{const{error}=await getSupabaseClient().auth.signOut();if(error)throw error}catch(error){throw sanitizeAuthError(error)}}}),[loading,session]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useAuth(){const context=useContext(Context);if(!context)throw new Error('useAuth must be used inside AuthProvider');return context}
